### ISSUE TITLE
release: create a relui workflow for the vscode-go release process

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#3500] opened 2024-08-21 11:47 UTC
This issue tracks the relui workflow to further automate the vscode-go release process.
The new relui-based release process includes

* Sanity check on the version

* Stable release: the initial version will simply migrate the existing release process.
   But the final version will handle:
   - Create an issue to track the release
   - Create a new release branch (for v0.M.0) from the chosen prerelease version.
   - Create CLs for cherry-pick (for v0.M.N where N > 0).
   - Create a CL to update the version in `package.json` and `package-lock.json`. 
   - Create a CL to add/update `extension/LICENSE` file. (not the top-level LICENSE file).
   - Tag the release candidate.
   - Wait for the operator's manual testing with RC.
   - Trigger the next prerelease for `v0.(M+1).0`.
   - Tag the final release.

* Prerelease (to be added with [golang/vscode-go#1935](https://github.com/golang/vscode-go/issues/1935))
   - Work with the master branch (no new branch creation)
   - Create a CL to update the version in `package.json` and `package-lock.json`. 
   - Skip processes like issue/milestone creation.

cc @h9jiang

**Comment by h9jiang** [comment] 2024-08-21 20:53
As the first CL, we will create a new workflow which is responsible of creating a release candidate for the stable version of vscode-go extension. 

The input version should be the next version of some existing versions. The input version has to be a stable version. The input version's pre-release label should be empty. (The flow will figure out which `rc` it will pick)
![image](https://github.com/user-attachments/assets/bd6edfbd-6bb9-4881-92c8-e523535682e1)
![image](https://github.com/user-attachments/assets/f630b6f9-9875-437f-9866-3bd824ddcc54)
![image](https://github.com/user-attachments/assets/19d36591-9473-4f35-9133-f910a57c0dab)

**Comment by h9jiang** [comment] 2024-08-23 15:33
Some offline sync with Hana and Dmitri, we want to adopt the approve functionality same as gopls release automation. And also use the cool drop down menu.

The input of the release will be simplifies as below, the coordinator only need to provide what kind of version he/she want to release. Right now, it can only be next minor or next patch. 

![image](https://github.com/user-attachments/assets/5401e464-0817-4921-9c06-f4460a7fba69)

The flow will figure out the version based on the user input, the local relui below, I choose next minor. The relui return `v0.44.0-rc.1` WAI. 

Some more explanation, right now, the latest release is vscode-go is `v0.42.0. The next stable version should be `v0.44.0` because `0.43` will be a insider version.

![image](https://github.com/user-attachments/assets/71a41467-2f55-4e7c-a5bb-d90cae64e6c3)

The local relui below, I choose next patch., the relui return `v0.42.1-rc.1`. The next patch version is `v0.42.1` and the pre-release version start with `rc.1`. (because there is no other rc available)

![image](https://github.com/user-attachments/assets/a6d09a3e-a8aa-4216-9d04-8c639d122b3d)

**Comment by h9jiang** [comment] 2024-08-26 20:59
The next CL, we will add a step in gopls release process. Every gopls release will trigger a gopls version update in vscode-go repo.

![image](https://github.com/user-attachments/assets/852cf854-3951-4463-bd06-7271b886b759)
![image](https://github.com/user-attachments/assets/4b20a59a-6b3e-4368-8149-d89f4b92d9fb)

The update will happen at the last step of gopls release & gopls pre-release.

**Comment by h9jiang** [comment] 2024-08-27 17:58
Next CL, the flow will create the release milestone and release issue. (only if there isn't one already created and open)

The first run of the flow create this release issue below and add it to the release milestone.

![image](https://github.com/user-attachments/assets/88fa5db6-35b5-4d37-898c-2675e6624621)

![image](https://github.com/user-attachments/assets/95d29d04-574a-47c9-ace8-8173c54ca226)

The second time, it realize there is an existing & open issue, so it will not create this issue again. 

![image](https://github.com/user-attachments/assets/5ce16871-f251-4eac-9cb4-06d7f0107e9a)

**Comment by h9jiang** [comment] 2024-08-27 21:27
Next CL, the vscode go release flow will try to create a release branch if not already exist.

The current logic is, only create a branch if the input version is minor version and it's the first candidate of that minor release. in form of `vX.Y.0-rc.1` 

The local relui failed for next minor release to create the branch because of permission issue. (the input to this step is `v0.44.0-rc.1`) WAI
![image](https://github.com/user-attachments/assets/3cf38290-8a0a-4aad-ab8f-6ba4837dd05a)

The local relui failed for next patch release. The flow try to release `v0.42.1-rc.1` but this branch `release-v0.42` does not exist. Based on the implementation it's working as intended. But we will need to figure out how to do `v0.42.1+` release because this is in a transit period. Between single release branch model and multi release branch model.
![image](https://github.com/user-attachments/assets/69dde7a4-fe86-4f4b-9519-8912effa1fd4)


@hyangah  a quick work around is, we cut a branch `release-v0.42` manually from the current head of `release` branch. Or we can embed some hard coded logic in release flow, ask the flow to refer to `release` branch when the input version is smaller than or equals to `v0.42`

Regardless of the final solution, we can move forward with the CL review while working on this back-ward compatibility issue.

**Comment by hyangah** [comment] 2024-08-28 17:22
@h9jiang Now there is `release-v0.42` cut from the current `release` branch. So you can work/experiment with it.

**Comment by h9jiang** [comment] 2024-09-04 18:16
Next CL, we will add a step in gopls release flow to update gopls version in vscode-go project. 

After a gopls release is done, both master branch and release branch will be updated. 

SCREENSHOT: the local relui want to update the gopls version in both master and release branch. Because the gopls 0.16.2 is not yet released, the master branch have nothing to update (already up-to-date), the release branch have a CL ongoing. 

![image](https://github.com/user-attachments/assets/8bb35d89-c934-48bd-a254-0a6fe4451277)
![image](https://github.com/user-attachments/assets/9680ebcf-9416-4227-ac81-4fe75b1b002e)


When running this in production, what we will be expecting is, both master and release branch will be updated at the same time because production flow will release `0.16.2`. So the master branch will then out-dated.

**Comment by h9jiang** [comment] 2024-09-09 19:53
Next Change, we will add a new flow for vscode-go insider version release

When choosing this flow, this flow will figure out which insider version you should release. In the local relui run, the relui analyze the current tags in `vscode-go` repo and figure out the next insider version is `v0.43.2`

![image](https://github.com/user-attachments/assets/7bfd1a30-72df-47e6-b61c-ef5908f107ec)

**Comment by h9jiang** [comment] 2024-09-09 20:09
Next Change, we will add two steps in insider version release

1. Read the head commit from master branch
2. Wait for coordinator approval.

Personally speaking, releasing from master branch is a kind of a risky move because there could be commit merged anytime. So I explicit the commit upon approval. 

![image](https://github.com/user-attachments/assets/7780cb89-08ab-4d23-89ca-80a2931830e7)

**Comment by h9jiang** [comment] 2024-09-10 18:45
The next CL, we will refactor the x/build so it can run cloud build using docker based image. This docker based cloud build will be used to trigger vscode-go test. This test is our final signal indicating whether the commit is healthy or not.

<img width="1325" alt="image" src="https://github.com/user-attachments/assets/ae353766-039d-4645-8788-068719dfc85f">

**Comment by h9jiang** [comment] 2024-09-12 22:00
Next Change, with the extended functionality from relui, we will add a step to generate the vscode extension package

This step will use `npx vsce .....` to create artifacts for this vscode-go version. The generated package will be copied to a gcs bucket for further usage. 

Only the `npm ci & npx vsce` command's log will be printed to terminal for reference. 

![image](https://github.com/user-attachments/assets/3f1c5d6c-6f73-46a0-b47a-d23821421638)

**Comment by h9jiang** [comment] 2024-09-16 19:25
Next change, we will use relui to create release note as draft for vscode-go release coordinator for review. 

![image](https://github.com/user-attachments/assets/1e021849-2c12-4461-92e3-519005d6263b)

From the relui, the relui will print the url to the draft release note so the coordinator can review and publish. 

![image](https://github.com/user-attachments/assets/dd853944-79bf-48df-95b0-f7f389474905)

In my local test, I did change the order of the step execution so I can test it locally.


After preparing the release note as draft, should we prepare a `approve` button where the coordinator can approve and the release ui will publish the draft release and make it official release candidate? 

Or you think it's ok to release the rc release note without coordinator approval? 

@hyangah

**Comment by h9jiang** [comment] 2024-09-17 03:19
Next change, we will upload the previously generated package extension to the github release as a release asset. 

by default, when we are creating a release using tag, it have two asset automatically (`source code zip & source code tar.gz`). The relui will upload one more asset `go-X.Y.Z-Pre.vsix` resulting in 3 assets in the release. 

<img width="1224" alt="image" src="https://github.com/user-attachments/assets/ea4e5fef-0742-474c-90a0-a5e2186e2549">

The updated release looks like this:

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/bd9cbf90-23d2-40e3-a5fe-e16d71438ec9">


NOTE: in order to test this locally, I will have to create a github release for a tagged version (I picked `v0.42.0-rc.1`) because my personal credential do not have permission to create a new tag (which is WAI). In addition, I have to hardcoded some logic by telling the steps to create package extension using a pre-defined commit (pretending we are building the package for `v0.42.0-rc.1` but the commit is head of the master branch). But I believe the logic will be very similar in production so we should not worry too much. :D

**Comment by h9jiang** [comment] 2024-09-17 20:04
E2E local test for prerelease flow.

I have to make some change to the flow to make sure it can success finish. The change is available in 

https://go-review.git.corp.google.com/c/build/+/613162

![image](https://github.com/user-attachments/assets/7f17b2d8-d9bb-4f9e-9359-f0cb1592fc0d)

![image](https://github.com/user-attachments/assets/f9d36539-c862-4cf0-a32c-dabbb50c666c)

@hyangah

**Comment by h9jiang** [comment] 2024-09-18 19:47
Next change: a few more steps will be added to vscode-go insider flow. 

Including: 

- Verify the commit in the master branch.
- Generate package extension based on the commit.
- Add the insider tag to the commit.
- Create GitHub release with the tag, diff and body.

A local test, after the local run finished, a new github release (draft) is created. This draft is meant for insider version `v0.43.2` because we already released `v0.43.1`.

Things to mention: 
- The diff is between v0.42.0-rc.1 and v0.43.2 because v0.42.0-rc.1 is the last time we did the branch cut. 
- The diff link does not work because I do not have permission to tag v0.43.2 (this tag will be skipped)
- The milestone of this insider release is v0.44.0 because the insider release do not have milestone and what is available in insider is what will be available in next release.
- The content of github release is empty because [CHANGELOG.md](https://github.com/golang/vscode-go/blob/master/CHANGELOG.md)'s `## Unreleased` is empty. 
 
![image](https://github.com/user-attachments/assets/f9a25db1-82d2-47b6-aa90-f04f1338f209)


The relui execution:

![image](https://github.com/user-attachments/assets/d0ba7d04-52f5-4f4f-8c63-7b7c7f54a608)

**Comment by h9jiang** [comment] 2024-09-19 17:45
Next change, we add a new step to vscode-go to publish the packaged extension to vscode market place.

In my local relui test, I create a fake secret called `FAKE_TOKEN` and export the token as env `VSCE_PAT` in the publish step. (vsce is going to read this env and use that as credential to publish the extension)

Because my credential is fake, so the publish did not go through and failed because `not authorized to access this resource`

![image](https://github.com/user-attachments/assets/4e35f4c3-5b55-4011-84be-ba6c2ff1f6b0)

**Comment by h9jiang** [comment] 2024-09-20 20:00
Next CL, we will add the last flow vscode-go stable version release flow. The goal of this flow is to release a release candidate as final release. (release v0.44.2-rc.3 as v0.44.2)

The flow will take the same input parameter, a version bump strategy which will be used to determine which version you are trying to release (`next patch` resulting in `v0.42.2`). Then the flow will find the latest rc of that release. (for example, the flow will find `v0.42.2-rc.3` based on the input of `v0.42.2`)

However, in my local run, there is no ongoing release, so they all failed because there is no release candidate available.

![image](https://github.com/user-attachments/assets/54f4da4b-9c95-46fc-a67e-0f797b03c793)

![image](https://github.com/user-attachments/assets/7aa01d93-aa7f-4573-95a9-52f5b7a7c9a3)

**Comment by h9jiang** [comment] 2024-09-24 18:47
Next CL, some improvement on error surfacing

Context: we execute the following  cloudbuild steps in insider release flow: 

```
1. download repo
2. checkout branch
3. build the package from the commit
4. copy the log from the build process to gcs
```

After that, in x/build, we read the log from gcs and show them. 

Pain point: there is a dependency in this execution chain. If the package build is successful, we will copy the log from local to gcs and eventually surfaced to relui. But if the package build failed, the cloud build exited without continue to the log copying step. 

So in the next CL, a few changes will be made to correctly surface both the success log and failure log to relui. 


1. CloudBuild will allow failure for step `build the package from commit`. But to detect the failure, the return code of this step will be written to a local file called `return_code.txt`
2. CloudBuild will allow failure for step `copy the log from build process to gcs`. This step will be best effort trying to copy all the wanted log from local to gcs. 
3. After the cloud build finished, x/build will read the logs and the `return_code.txt` from the gcs and see if the return code is 0 or not. 

By this, we can also show log when script failed with error. (the failure error is normally more useful compare to success)

Local test: the following test failed because it need `jq` in the env but the cloud build image does not have `jq`. The step failed but we are able to surface the error log and the flow step will fail correctly. 

![image](https://github.com/user-attachments/assets/e53023d2-0fdd-4e87-b8f2-09ece28256da)

The CloudBuild will fail at the last step because it's trying to copy the built package extension from local to gcs (it does not exist because the build failed). But this is not blocking the CloudBuild to finish. 

![image](https://github.com/user-attachments/assets/0d38e6bb-0065-4786-b454-11310ef37c4f)

**Comment by h9jiang** [comment] 2024-09-24 21:35
Next CL, we add a few missing steps in vscode go stable release to create GitHub release as draft, and create a tag. 

A small change on the process. Previously, the flow use tag to build the package extension but instead, it will start using commit. (It's the same thing). 

![image](https://github.com/user-attachments/assets/7d80f56d-e67e-4ce7-aead-7d41ef005e26)

**Comment by h9jiang** [comment] 2024-09-25 21:18
Next CL, we will update the package.json and package-lock.json in the master branch so it will point to the next stable version. 

The local test below did not execute anything because the master branch has been updated. 

![image](https://github.com/user-attachments/assets/33e9ac09-7cdb-478d-8705-4e6df04e03f2)

When I provide a hard-coded version, the local test create the following CL to update the version to v0.48.0-dev. 

![image](https://github.com/user-attachments/assets/8e6a2ef2-f3f1-4586-86ff-e574541c2862)

![image](https://github.com/user-attachments/assets/8a7f1699-29f8-4aec-bcde-5ba5d85bb295)

**Comment by h9jiang** [comment] 2024-09-26 18:54
Next CL, we will add a input parameter to both vscode-go and gopls release so the github issue will be correctly assigned to the coordinator. 

![image](https://github.com/user-attachments/assets/27e66468-e421-4f6b-a63a-6b9d915512ff)

**Comment by h9jiang** [comment] 2024-10-01 17:59
Next CL, we will update the package.json and package-lock.json in release branch. This step will be triggered for every prerelease flow. 

If the package.json in release branch is already pointing to the correct version, no CL will be created. 
If the package.json in release branch is pointing to the wrong version, an auto-submit CL will be created and waiting to be merged. 

Once the CL merged, the flow will read the head of the release branch again. Pick that commit as release commit.

![image](https://github.com/user-attachments/assets/42e81e83-c8c5-43d6-a62d-ef97604fe970)

**Comment by h9jiang** [comment] 2024-10-01 20:23
Next CL, we will update the CHANGELOG.md in master branch after a stable minor version release. 

When we are releasing v0.44.0, we should create a new heading "##  v0.44.0" and move all the content under "## Unreleased" to "## v0.44.0". 

![image](https://github.com/user-attachments/assets/c39dd548-3807-4175-a5bc-6cadd094f777)

**Closed** 2024-10-23 17:16 UTC
Labels: chore/automation
