### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by delivey** [golang/vscode-go#3292] opened 2024-03-29 21:03 UTC
gopls version: v0.15.2/go1.20.5
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Cursor darwin
initialization error: undefined
issue timestamp: Fri, 29 Mar 2024 21:03:07 GMT
restart history:
Fri, 29 Mar 2024 13:07:09 GMT: activation (enabled: true)
Fri, 29 Mar 2024 13:39:53 GMT: manual (enabled: true)
Fri, 29 Mar 2024 20:59:20 GMT: manual (enabled: true)
Fri, 29 Mar 2024 20:59:53 GMT: manual (enabled: true)
Fri, 29 Mar 2024 21:02:17 GMT: manual (enabled: true)
Fri, 29 Mar 2024 21:02:55 GMT: manual (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.1" (should be something like "go1.12")

goroutine 5216 [running]:
go/types.NewChecker(0x0%3F, 0xc00355b180, 0xc00725ac30, 0x0%3F)
	  check.go:237  0x24e
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc00177e210, {0xc007c97d28, 0x1, 0x1})
	  analysis.go:1028  0x73d
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc00177e210, {0x1e50778%3F, 0xc004066270})
	  analysis.go:810  0x218
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc00177e210, {0x1e50778%3F, 0xc004066270})
	  analysis.go:672  0x145
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xda
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 1922,
    "TestdataFiles": 0,
    "GoFiles": 146,
    "ModFiles": 1,
    "Dirs": 340
  },
  "GOARCH": "amd64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.20.5",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "1.34662825s",
  "MemStats": {
    "HeapAlloc": 52476784,
    "HeapInUse": 83173376,
    "TotalAlloc": 814050808
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2759,
      "Largest": 935931,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.1",
        "AllPackages": {
          "Packages": 468,
          "LargestPackage": 155,
          "CompiledGoFiles": 2787,
          "Modules": 78
        },
        "WorkspacePackages": {
          "Packages": 52,
          "LargestPackage": 12,
          "CompiledGoFiles": 178,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-04-01 15:34
Duplicate of golang/go#66636, which we will fix for gopls@v0.15.3.

**Closed by findleyr** 2024-04-01 15:34 UTC
