### ISSUE TITLE
Lost added Go Environment path after switching Go Environment Version

### ISSUE THREAD

**Issue by ansidev** [golang/vscode-go#2198] opened 2022-04-20 06:18 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- 1.18.1 and 1.17
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <Paste gopls version here>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.66.2
    - dfd34e8260c270da74b5c2d86d61aee4b6d56977
    - x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.32.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
</details>

### Share the Go related settings you have added/edited

No setting.

### Describe the bug
Installed Go 1.18.1 via brew command.
Installed Go 1.17 via VSCode Go.

### Steps to reproduce the behavior:
1. Open project with Go Environment is Go 1.18.1 (brew)
2. Switch Go Environment to Go 1.17
3. Reload VS Code

Expected: The Go Environment list should contain Go 1.18.1 (brew).
Actual: The Go Environment list does not contain Go 1.18.1 (brew).

### Screenshots or recordings

https://user-images.githubusercontent.com/6688235/164162937-f689194a-5f8d-46d7-9357-857f2a05f73c.mov

**Comment by hyangah** [comment] 2022-04-20 12:00
As explained in the response in https://github.com/golang/vscode-go/issues/2199#issuecomment-1103846073
this is also working as intended.

When switching to 1.17 installed in $HOME/sdk/go1.17, the currently chosen Go is 1.17 and the extension doesn't keep track of the Go installed in other package managers (i.e. 1.18.1 installed by brew in your case).

Closing since this is working as intended.

**Closed by hyangah** 2022-04-20 12:00 UTC

**Comment by ansidev** [comment] 2022-04-20 12:55
@hyangah

Firstly, this issue is not related to #2199 and can be reproduced independently.

Secondly, IMO, this is probably an issue or even a bug.

As a user, losing the Go Environment path I added before and then I must add it again is unexpected behaviour.

So please consider this a bug and fix it asap. Thanks!

**Comment by hyangah** [comment] 2022-04-20 13:06
My comment for #2199 explains how the internal logic works. 

At the beginning, 1.18.1 was included because of (1).
After you switch to 1.17, 1.18.1 is no longer the currently selected version nor a version from $HOME/sdk, so it's not included.

If you want to switch back and pick up 1.18.1, use "Clear selection".

This is not a bug.
