### ISSUE TITLE
The result of `find all implementations` is incomplete

### ISSUE THREAD

**Issue by zzzzer91** [golang/vscode-go#2626] opened 2023-01-26 06:54 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.19.5 darwin/arm64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.11.0
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.74.3
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.37.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- gotests:	/Users/zzzzer/go/bin/gotests	(version: v1.6.0 built with go: go1.19.5)
	gomodifytags:	/Users/zzzzer/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.19.5)
	impl:	/Users/zzzzer/go/bin/impl	(version: v1.1.0 built with go: go1.19.5)
	goplay:	/Users/zzzzer/go/bin/goplay	(version: v1.0.0 built with go: go1.19.5)
	dlv:	/Users/zzzzer/go/bin/dlv	(version: v1.20.1 built with go: go1.19.5)
	staticcheck:	/Users/zzzzer/go/bin/staticcheck	(version: v0.3.3 built with go: go1.19.5)
	gopls:	/Users/zzzzer/go/bin/gopls	(version: v0.11.0 built with go: go1.19.5)
</details>

### Describe the bug

When i use `find all implementations` for `context.Context`, vscode shows:

![image](https://user-images.githubusercontent.com/24646819/214772752-9c07c323-6368-49d3-b502-2a2ebf33e00e.png)

I found the result is incomplete.

Goland's output:
![image](https://user-images.githubusercontent.com/24646819/214772543-17dce9e6-e097-4360-a9c2-9ba18a1d31cd.png)

why？

**Comment by findleyr** [comment] 2023-01-26 15:29
@zzzzer91 this is most likely caused by opening a different directory as your workspace folder. Which directory did you open?

We understand this is not ideal. https://go.dev/issue/57979 is our active project to fix this problem.

**Comment by zzzzer91** [comment] 2023-01-27 03:13
> @zzzzer91 this is most likely caused by opening a different directory as your workspace folder. Which directory did you open?
> 
> We understand this is not ideal. https://go.dev/issue/57979 is our active project to fix this problem.

Sincerely thank you for your work. This is the most likely reason. My Go project is in the ~/go/src directory, and I go to the Go source files in this project. Then, I use 'Find all implementations' for 'context.Context'.

**Comment by findleyr** [comment] 2023-01-27 15:58
@zzzzer91 thanks. I'm going to close this as it is covered by golang/go#57979.

**Closed by findleyr** 2023-01-27 15:58 UTC
Labels: WaitingForInfo
