### ISSUE TITLE
release: Nightly release is blocked for a week

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#363] opened 2020-07-16 17:20 UTC
Nightly release was blocked for a week due to test failures.

https://github.com/golang/vscode-go/runs/878171883?check_suite_focus=true

```
  1) Go Extension Tests With Gopls
       Completion middleware:
     AssertionError [ERR_ASSERTION]: gopls should provide an incomplete list by default
  	at Suite.<anonymous> (out/test/gopls/extension.test.js:126:24)
  	at Generator.next (<anonymous>)
  	at fulfilled (out/test/gopls/extension.test.js:5:58)
  	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

Long tests and CI tests (on Linux and on Mac) were reliably successful at head

https://github.com/golang/vscode-go/actions/runs/170560221

So, I think this is caused by the differences in the testing. In Nightly,
- We are running tests marked with `VSCODEGO_BEFORE_RELEASE_TESTS`. (install.test.ts)
- We are running tests with the `insiders` version of VS Code.

/cc @stamblerre

**Comment by hyangah** [comment] 2020-07-17 15:53
I think this is a race - @stamblerre can you please take a look at the following trace?
It seems like `gopls` returns an empty result for the `textDocument/completion` request sometimes.
`Result: {"isIncomplete":false,"items":[]}`

Does `gopls` return an empty result when internal state is not ready?

```
[Trace - 11:45:48.572 AM] Sending request 'initialize - (0)'.
Params: {"processId":51670,"clientInfo":{"name":"vscode","version":"1.48.0-insider"},"rootPath":"/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace","rootUri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"versionSupport":false,"tagSupport":{"valueSet":[1,2]}},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}},"contextSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"isPreferredSupport":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"selectionRange":{"dynamicRegistration":true}},"window":{"workDoneProgress":true}},"initializationOptions":{},"trace":"off","workspaceFolders":[{"uri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace","name":"workspace"}]}


[Trace - 11:45:48.599 AM] Received response 'initialize - (0)' in 27ms.
Result: {"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"completionProvider":{"triggerCharacters":["."]},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor.extract","refactor.rewrite","source.fixAll","source.organizeImports"]},"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"renameProvider":{"prepareProvider":true},"foldingRangeProvider":true,"executeCommandProvider":{"commands":["generate","regenerate_cgo","test","tidy","upgrade_dependency","vendor"]},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}}},"serverInfo":{"name":"gopls","version":"Build info\n----------\ngolang.org/x/tools/gopls master\n    golang.org/x/tools/gopls@(devel)\n    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=\n    github.com/google/go-cmp@v0.5.0 h1:/QaMHBdZ26BB3SSst0Iwl10Epc+xhTquomWX0oZEB6w=\n    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\n    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=\n    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=\n    golang.org/x/tools@v0.0.0-20200626171337-aa94e735be7f =\u003e ../\n    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=\n    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=\n    mvdan.cc/gofumpt@v0.0.0-20200709182408-4fd085cb6d5f h1:gi7cb8HTDZ6q8VqsUpkdoFi3vxwHMneQ6+Q5Ap5hjPE=\n    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=\n\nGo info\n-------\ngo version go1.14.3 darwin/amd64\n\n"}}


[Trace - 11:45:48.634 AM] Sending notification 'initialized'.
Params: {}


[Trace - 11:45:48.650 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/07/17 11:45:48 Build info\n----------\ngolang.org/x/tools/gopls master\n    golang.org/x/tools/gopls@(devel)\n    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=\n    github.com/google/go-cmp@v0.5.0 h1:/QaMHBdZ26BB3SSst0Iwl10Epc+xhTquomWX0oZEB6w=\n    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\n    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=\n    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=\n    golang.org/x/tools@v0.0.0-20200626171337-aa94e735be7f =\u003e ../\n    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=\n    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=\n    mvdan.cc/gofumpt@v0.0.0-20200709182408-4fd085cb6d5f h1:gi7cb8HTDZ6q8VqsUpkdoFi3vxwHMneQ6+Q5Ap5hjPE=\n    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=\n\nGo info\n-------\ngo version go1.14.3 darwin/amd64\n\n\n"}


[Trace - 11:45:48.650 AM] Received request 'workspace/configuration - (1)'.
Params: {"items":[{"scopeUri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace","section":"gopls"},{"scopeUri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace","section":"gopls-workspace"}]}


[Info  - 11:45:48 AM] 2020/07/17 11:45:48 Build info
----------
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@(devel)
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.0 h1:/QaMHBdZ26BB3SSst0Iwl10Epc+xhTquomWX0oZEB6w=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=
    golang.org/x/tools@v0.0.0-20200626171337-aa94e735be7f => ../
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
    mvdan.cc/gofumpt@v0.0.0-20200709182408-4fd085cb6d5f h1:gi7cb8HTDZ6q8VqsUpkdoFi3vxwHMneQ6+Q5Ap5hjPE=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

Go info
-------
go version go1.14.3 darwin/amd64



[Trace - 11:45:48.655 AM] Sending response 'workspace/configuration - (1)' in 5ms.
Result: [null,null]


[Trace - 11:45:48.727 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/07/17 11:45:48 go/packages.Load\n\tsnapshot=0\n\tdirectory=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace\n\tquery=[./ builtin]\n\tpackages=2\n"}


[Info  - 11:45:48 AM] 2020/07/17 11:45:48 go/packages.Load
	snapshot=0
	directory=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace
	query=[./ builtin]
	packages=2

[Trace - 11:45:48.848 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/07/17 11:45:48 go env for /Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace\n(valid build configuration = false)\n(build flags: [])\nGO111MODULE=\"\"\nGOARCH=\"amd64\"\nGOBIN=\"\"\nGOCACHE=\"/Users/hakim/Library/Caches/go-build\"\nGOENV=\"/Users/hakim/Library/Application Support/go/env\"\nGOEXE=\"\"\nGOFLAGS=\"\"\nGOHOSTARCH=\"amd64\"\nGOHOSTOS=\"darwin\"\nGOINSECURE=\"\"\nGONOPROXY=\"\"\nGONOSUMDB=\"\"\nGOOS=\"darwin\"\nGOPATH=\"/Users/hakim/go\"\nGOPRIVATE=\"\"\nGOPROXY=\"https://proxy.golang.org,direct\"\nGOROOT=\"/usr/local/go\"\nGOSUMDB=\"sum.golang.org\"\nGOTMPDIR=\"\"\nGOTOOLDIR=\"/usr/local/go/pkg/tool/darwin_amd64\"\nGCCGO=\"gccgo\"\nAR=\"ar\"\nCC=\"clang\"\nCXX=\"clang++\"\nCGO_ENABLED=\"1\"\nGOMOD=\"\"\nCGO_CFLAGS=\"-g -O2\"\nCGO_CPPFLAGS=\"\"\nCGO_CXXFLAGS=\"-g -O2\"\nCGO_FFLAGS=\"-g -O2\"\nCGO_LDFLAGS=\"-g -O2\"\nPKG_CONFIG=\"pkg-config\"\nGOGCCFLAGS=\"-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bw/6r6k9d113sv1_vvzk_1kfxbm001py5/T/go-build417706092=/tmp/go-build -gno-record-gcc-switches -fno-common\"\n\n"}


[Trace - 11:45:48.848 AM] Received request 'client/registerCapability - (2)'.
Params: {"registrations":[{"id":"workspace/didChangeConfiguration","method":"workspace/didChangeConfiguration"},{"id":"workspace/didChangeWorkspaceFolders","method":"workspace/didChangeWorkspaceFolders"},{"id":"workspace/didChangeWatchedFiles","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/**.{go,mod,sum}","kind":7}]}}]}


[Info  - 11:45:48 AM] 2020/07/17 11:45:48 go env for /Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace
(valid build configuration = false)
(build flags: [])
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hakim/Library/Caches/go-build"
GOENV="/Users/hakim/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hakim/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bw/6r6k9d113sv1_vvzk_1kfxbm001py5/T/go-build417706092=/tmp/go-build -gno-record-gcc-switches -fno-common"


[Trace - 11:45:48.863 AM] Sending response 'client/registerCapability - (2)' in 14ms.
Result: 


[Trace - 11:45:48.865 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/07/17 11:45:48 go/packages.Load\n\tsnapshot=0\n\tdirectory=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace\n\tquery=[./]\n\tpackages=1\n"}


[Info  - 11:45:48 AM] 2020/07/17 11:45:48 go/packages.Load
	snapshot=0
	directory=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace
	query=[./]
	packages=1

[Trace - 11:45:56.410 AM] Sending notification 'textDocument/didOpen'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go","languageId":"go","version":1,"text":"package abc\n\nimport (\n\t\"fmt\"\n\t\"math\"\n\t\"net\"\n)\n\n// ABC is a struct, you coudn't use Goto Definition or Hover info on this before\n// Now you can due to gogetdoc and go doc\ntype ABC struct {\n\ta int\n\tb int\n\tc int\n}\n\n// This is an unexported function so couldn't get this comment on hover :(\n// Not anymore!!\nfunc print(txt string) {\n\tfmt.Println(txt)\n}\n\nfunc main() {\n\tprint(\"Hello\")\n}\n\n// Hello is a method on the struct ABC. Will signature help understand this correctly\nfunc (abcd *ABC) Hello(s string, exclaim bool) string {\n\tnet.IPv4Mask(0, 0, 0, 0)\n\tif exclaim {\n\t\ts = s + \"!\"\n\t}\n\tif abcd.a+abcd.b+abcd.c > 3 {\n\t\treturn \"Hello \" + s\n\t}\n\treturn \"GoodBye \" + s\n}\n\n// Greetings is an exported function. So all is good.\nfunc Greetings() string {\n\txyz := ABC{1, 2, int(math.Abs(-1))}\n\treturn xyz.Hello(\"World\", false) + EmptyLine(\"Why\")\n}\n\n// EmptyLine has docs\n//\n// with a blank line in the middle\nfunc EmptyLine(s string) string {\n\treturn s + \"this is not an empty line\"\n}\n"}}


[Trace - 11:45:56.422 AM] Sending request 'textDocument/hover - (1)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go"},"position":{"line":0,"character":3}}


[Trace - 11:45:56.422 AM] Sending request 'textDocument/hover - (2)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go"},"position":{"line":23,"character":14}}


[Trace - 11:45:56.422 AM] Sending request 'textDocument/hover - (3)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go"},"position":{"line":20,"character":0}}


[Trace - 11:45:56.424 AM] Sending request 'textDocument/hover - (4)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go"},"position":{"line":28,"character":16}}


[Trace - 11:45:56.425 AM] Sending request 'textDocument/hover - (5)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go"},"position":{"line":22,"character":5}}


[Trace - 11:45:56.425 AM] Sending request 'textDocument/hover - (6)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go"},"position":{"line":40,"character":23}}


[Trace - 11:45:56.426 AM] Sending request 'textDocument/hover - (7)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go"},"position":{"line":19,"character":6}}


[Trace - 11:45:56.426 AM] Sending request 'textDocument/hover - (8)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go"},"position":{"line":23,"character":4}}


[Trace - 11:45:56.772 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/07/17 11:45:56 go/packages.Load\n\tsnapshot=1\n\tdirectory=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace\n\tquery=[file=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go]\n\tpackages=1\n"}


[Trace - 11:45:56.772 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/07/17 11:45:56 go/packages.Load\n\tsnapshot=1\n\tpackage_path=\"github.com/microsoft/vscode-go/gofixtures/gogetdoctestdata\"\n\tfiles=[/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go]\n"}


[Trace - 11:45:56.772 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/07/17 11:45:56 go/packages.Load\n\tsnapshot=1\n\tdirectory=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace\n\tquery=[./]\n\tpackages=1\n"}


[Info  - 11:45:56 AM] 2020/07/17 11:45:56 go/packages.Load
	snapshot=1
	directory=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace
	query=[file=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go]
	packages=1

[Info  - 11:45:56 AM] 2020/07/17 11:45:56 go/packages.Load
	snapshot=1
	package_path="github.com/microsoft/vscode-go/gofixtures/gogetdoctestdata"
	files=[/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go]

[Info  - 11:45:56 AM] 2020/07/17 11:45:56 go/packages.Load
	snapshot=1
	directory=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace
	query=[./]
	packages=1

[Trace - 11:45:56.815 AM] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {"changes":[{"uri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go","type":1},{"uri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/go.mod","type":1}]}


[Trace - 11:45:56.982 AM] Received response 'textDocument/hover - (1)' in 560ms.
Result: null


[Trace - 11:45:56.983 AM] Received response 'textDocument/hover - (2)' in 561ms.
Result: null


[Trace - 11:45:56.983 AM] Received response 'textDocument/hover - (3)' in 561ms.
Result: null


[Trace - 11:45:56.984 AM] Received response 'textDocument/hover - (4)' in 559ms.
Result: null


[Trace - 11:45:56.984 AM] Received response 'textDocument/hover - (5)' in 558ms.
Result: {"contents":{"kind":"markdown","value":"```go\nfunc main()\n```"},"range":{"start":{"line":22,"character":5},"end":{"line":22,"character":9}}}


[Trace - 11:45:56.984 AM] Received response 'textDocument/hover - (6)' in 558ms.
Result: {"contents":{"kind":"markdown","value":"```go\npackage math\n```\n\n[`math` on pkg.go.dev](https://pkg.go.dev/math)"},"range":{"start":{"line":40,"character":22},"end":{"line":40,"character":26}}}


[Trace - 11:45:56.985 AM] Received response 'textDocument/hover - (7)' in 559ms.
Result: {"contents":{"kind":"markdown","value":"```go\nfunc fmt.Println(a ...interface{}) (n int, err error)\n```\n\n[`fmt.Println` on pkg.go.dev](https://pkg.go.dev/fmt#Println)\n\nPrintln formats using the default formats for its operands and writes to standard output\\.\nSpaces are always added between operands and a newline is appended\\.\nIt returns the number of bytes written and any write error encountered\\.\n"},"range":{"start":{"line":19,"character":5},"end":{"line":19,"character":12}}}


[Trace - 11:45:56.986 AM] Received response 'textDocument/hover - (8)' in 559ms.
Result: {"contents":{"kind":"markdown","value":"```go\nfunc print(txt string)\n```\n\nThis is an unexported function so couldn\\'t get this comment on hover \\:\\(\nNot anymore\\!\\!\n"},"range":{"start":{"line":23,"character":1},"end":{"line":23,"character":6}}}


[Trace - 11:45:57.014 AM] Sending request 'textDocument/completion - (9)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go"},"position":{"line":19,"character":5},"context":{"triggerKind":1}}


[Trace - 11:45:57.293 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/07/17 11:45:57 go/packages.Load\n\tsnapshot=2\n\tpackage_path=\"github.com/microsoft/vscode-go/gofixtures/gogetdoctestdata\"\n\tfiles=[/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go]\n"}


[Info  - 11:45:57 AM] 2020/07/17 11:45:57 go/packages.Load
	snapshot=2
	package_path="github.com/microsoft/vscode-go/gofixtures/gogetdoctestdata"
	files=[/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go]

[Trace - 11:45:57.304 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/07/17 11:45:57 go/packages.Load\n\tsnapshot=2\n\tdirectory=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace\n\tquery=[file=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go]\n\tpackages=1\n"}


[Trace - 11:45:57.304 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/07/17 11:45:57 go/packages.Load\n\tsnapshot=2\n\tdirectory=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace\n\tquery=[./... builtin]\n\tpackages=2\n"}


[Info  - 11:45:57 AM] 2020/07/17 11:45:57 go/packages.Load
	snapshot=2
	directory=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace
	query=[file=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace/test.go]
	packages=1

[Info  - 11:45:57 AM] 2020/07/17 11:45:57 go/packages.Load
	snapshot=2
	directory=/Users/hakim/projects/google/vscode-go/test/gopls/testfixtures/src/workspace
	query=[./... builtin]
	packages=2

[Trace - 11:45:57.401 AM] Received response 'textDocument/completion - (9)' in 387ms.
Result: {"isIncomplete":false,"items":[]}
```

**Comment by stamblerre** [comment] 2020-07-17 18:18
Hm, I think something else is going on here. It looks like `gopls` is doing two initial workspace loads, one at snapshot 0 and another at snapshot 2. Looks like the first IWL happens when we don't yet have a `go.mod` file in the workspace (hence `query=[./ builtin]`, and then the second IWL happens with a `go.mod` file, which means that we completely recreate the view and do an IWL with the `query=[./... builtin]`. My guess is that the completion request is a response from the view that is shutting down.

The full recreation of the view when the `go.mod` is created was a bit of a hacky work-around before we had the idea of re-initializing a view. Maybe after https://go-review.googlesource.com/c/tools/+/242159 I can add a fix for this.

**Comment by stamblerre** [comment] 2020-07-17 20:20
Ah, I bet this was caused by https://go-review.googlesource.com/c/tools/+/242160. We didn't watch `go.mod` file changes on disk before. Is there a way to hold off on initializing `gopls` until the `go.mod` file is on disk?

**Comment by hyangah** [comment] 2020-07-17 20:59
I think we found the culprit. 

In CI tests, we install gopls with `go get golang.org/x/tools/gopls` in modules mode.
In Nightly, we install gopls with many other tools in one command 
```
$ go get github.com/acroca/go-symbols \
...
   golang.org/x/tools/gopls'
```

As a result, the gopls in nightly workflow picked up a recent version of golang.org/x/tools which includes the cl/242160.
The classic, shared `go.mod` issue.

* in CI
```
$ GOBIN=/tmp/bin GO111MODULE=on go get golang.org/x/tools/gopls
go: golang.org/x/tools/gopls upgrade => v0.4.3

$ go version -m /tmp/bin/gopls
/tmp/bin/gopls: go1.14.3
	path	golang.org/x/tools/gopls
	mod	golang.org/x/tools/gopls	v0.4.3	h1:irz7Q+XdHNECamFKbNWKvMV2Ak6zBbwdwbZndG4545I=
	dep	github.com/BurntSushi/toml	v0.3.1	h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
	dep	github.com/sergi/go-diff	v1.1.0	h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
	dep	golang.org/x/mod	v0.2.0	h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
	dep	golang.org/x/sync	v0.0.0-20190911185100-cd5d95a43a6e	h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
	dep	golang.org/x/tools	v0.0.0-20200708181441-6004c8539734	h1:Vc0Vx98oU/O3+qPQ36fnTT5UduS55KLh2uSGbL7mqEo=
	dep	golang.org/x/xerrors	v0.0.0-20191204190536-9bdfabe68543	h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
	dep	honnef.co/go/tools	v0.0.1-2020.1.4	h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
	dep	mvdan.cc/xurls/v2	v2.2.0	h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```

* in Nightly
```
$ GOBIN=/tmp/bin2 GO111MODULE=on go get github.com/acroca/go-symbols                github.com/davidrjenni/reftools/cmd/fillstruct                github.com/haya14busa/goplay/cmd/goplay                github.com/mdempsky/gocode                github.com/sqs/goreturns                github.com/uudashr/gopkgs/v2/cmd/gopkgs                github.com/zmb3/gogetdoc                golang.org/x/lint/golint                golang.org/x/tools/cmd/gorename                golang.org/x/tools/gopls
go: golang.org/x/tools/gopls upgrade => v0.4.3
...
$ go version -m /tmp/bin2/gopls
/tmp/bin2/gopls: go1.14.3
	path	golang.org/x/tools/gopls
	mod	golang.org/x/tools/gopls	v0.4.3	h1:irz7Q+XdHNECamFKbNWKvMV2Ak6zBbwdwbZndG4545I=
	dep	github.com/BurntSushi/toml	v0.3.1	h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
	dep	github.com/sergi/go-diff	v1.1.0	h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
	dep	golang.org/x/mod	v0.3.0	h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
	dep	golang.org/x/sync	v0.0.0-20200625203802-6e8e738ad208	h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=
	dep	golang.org/x/tools	v0.0.0-20200717024301-6ddee64345a6	h1:nULzSsKgihxFGLnQFv2T7lE5vIhOtg8ZPpJHapEt7o0=
	dep	golang.org/x/xerrors	v0.0.0-20191204190536-9bdfabe68543	h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
	dep	honnef.co/go/tools	v0.0.1-2020.1.4	h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
	dep	mvdan.cc/xurls/v2	v2.2.0	h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```

**Closed** 2020-07-20 15:01 UTC
Labels: NeedsInvestigation, release-blocker
