### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Xynnn007** [golang/vscode-go#3327] opened 2024-04-10 02:00 UTC
gopls version: v0.15.2/go1.20.1
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Wed, 10 Apr 2024 01:59:38 GMT
restart history:
Wed, 10 Apr 2024 01:53:00 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.0" (should be something like "go1.12")

goroutine 6574 [running]:
go/types.NewChecker(0x0%3F, 0xc0057fa080, 0xc009bb7720, 0x0%3F)
	  check.go:237  0x24e
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc005d63810, {0xc003281308, 0x1, 0x1})
	  analysis.go:1028  0x73d
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc005d63810, {0x12431d8%3F, 0xc004775bf0})
	  analysis.go:810  0x218
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc005d63810, {0x12431d8%3F, 0xc004775bf0})
	  analysis.go:672  0x145
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xda
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 736,
    "TestdataFiles": 270,
    "GoFiles": 386,
    "ModFiles": 1,
    "Dirs": 179
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.20.1",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "1.760698059s",
  "MemStats": {
    "HeapAlloc": 110514880,
    "HeapInUse": 168361984,
    "TotalAlloc": 1412833360
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 5039,
      "Largest": 1842375,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.2",
        "AllPackages": {
          "Packages": 971,
          "LargestPackage": 193,
          "CompiledGoFiles": 5236,
          "Modules": 80
        },
        "WorkspacePackages": {
          "Packages": 150,
          "LargestPackage": 40,
          "CompiledGoFiles": 584,
          "Modules": 1
        },
        "Diagnostics": 4
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-04-10 13:41
Dupe of golang/go#66636, which is fixed in the current gopls prerelease.

```
go install golang.org/x/tools/gopls@v0.15.3-pre.1
```

(or just reinstall gopls@latest with a more recent go version, such as go 1.22)

**Closed by findleyr** 2024-04-10 13:41 UTC
