### ISSUE TITLE
golang-autocompleteUnimportedPackages-Do not change the location of the original extension package

### ISSUE THREAD

**Issue by hlbbt** [golang/vscode-go#1500] opened 2021-05-13 15:31 UTC
I really like use vscode. Whether i write php or golang, but now i have a problem.
My colleagues use Goland, when i write code in vscode, auto complete unimported packages causes the packages location to change. This can cause unnecessary trouble when merging code

eg.
![118106101-d3737380-b40f-11eb-9954-bca935bb47a8](https://user-images.githubusercontent.com/52640622/118148002-bad08100-b442-11eb-83be-0df4800b0282.png)
![118106300-087fc600-b410-11eb-9a6b-04cdece56ca5](https://user-images.githubusercontent.com/52640622/118148018-bd32db00-b442-11eb-819c-1592edc31073.png)

Can you provide an option to select the goland extended package arrangement.

When i save with vscode, the extension package order is automatically changed,
I want to import extension packs automatically without changing the order of the extension pack list.
Wants to add an option that can be set, otherwise I can only abandon my beloved vscode and follow the team to use Goland。

**Comment by findleyr** [comment] 2021-05-13 16:20
Hi, why do you think this is related to autocompleteUnimportedPackages? Have you tried disabling source.organizeImports?

See also https://github.com/golang/vscode-go/blob/master/docs/advanced.md#formatting-code-and-organizing-imports

**Comment by hlbbt** [comment] 2021-05-14 03:29
Yes, i have, when i set the `sourece.organizeImports = false`, expansion packs will not be imported auto completed. I had to import each extension package manually, which made it even harder to work.

The problem i now find is that vscode and Goland have different ordering rules for packages.
So I wonder if it is possible to add a sorting option that can accommodate Goland's packages sorting.

I think vscode packages ordering rules:
![vscode](https://user-images.githubusercontent.com/52640622/118216442-1718bc80-b4a6-11eb-8483-48121adbba69.png)

I think goland packages ordering rules:
![goland](https://user-images.githubusercontent.com/52640622/118217069-51368e00-b4a7-11eb-82e9-2713e0b909aa.jpg)

**Comment by findleyr** [comment] 2021-05-14 14:25
Yes, you'll need to either choose goimports style or disable goimports. Sorry. Part of the value of goimports is that (like gofmt) it enforces a common style, which makes it easier to read code in an unfamiliar codebase. This is very unlikely to change.

It does look like goland supports goimports save hooks: [reference](https://www.jetbrains.com/help/go/integration-with-go-tools.html#goimports). Have you considered standardizing on goimports style? I don't think we'll be able to solve your problem, but I _am_ curious: is there something your team prefers about having a single import block?

**Comment by hlbbt** [comment] 2021-05-14 14:52
Thanks, I don't think they value go imports style. A goland default imports is then used. 
I don't think a single import block is friendly, but i can't choose, I have to adapt to the team.
So how do I set vscode to a single import block. Very thanks.

**Comment by findleyr** [comment] 2021-05-14 15:18
> So how do I set vscode to a single import block. Very thanks.

Sorry, there's no way to do this.  `gopls` enforces goimports style, so your options are to use goimports style or disable import organization.  The same applies to formatting: you can choose to use a different formatting style from gofmt, but gopls cannot enforce that style for you.

**Comment by hlbbt** [comment] 2021-05-14 15:30
> > So how do I set vscode to a single import block. Very thanks.
> 
> Sorry, there's no way to do this. `gopls` enforces goimports style, so your options are to use goimports style or disable import organization. The same applies to formatting: you can choose to use a different formatting style from gofmt, but gopls cannot enforce that style for you.

Oh, So can i only give up using vscode, for goland, Is this so is there no solution after all manually importing extension packages can cause bigger trouble

**Comment by hlbbt** [comment] 2021-05-14 15:56
I don't know if you can add options to manually select the default formatting style, And then i can choose the `gofmt`, 
The default formatting style goland after all `gofmt`, needs to be set if used `goimports `and changes to previous projects can be significant.
Thinks.

**Comment by stamblerre** [comment] 2021-05-14 21:52
You should still be able to format your code using `gofmt` even if you have `source.organizeImports` disabled. Are you not seeing that behavior?

**Comment by hlbbt** [comment] 2021-05-15 01:30
> `gofmt`即使已`source.organizeImports`禁用，您仍应该能够使用格式化代码。您没有看到这种行为吗？

Yes, I've tried, However, after modification, the extension package is no automatically imported when the file is saved, This is actually a bigger problem. I don't know how to persuade the team to change the formatting tool to `goimports`

**Comment by hlbbt** [comment] 2021-05-15 01:58
Quite disliked goland the default formatting is automatic imports and gofmt

**Comment by stamblerre** [comment] 2021-05-17 20:19
@hlbbt: I'm not sure how to further help here. If you disable import organization, imports will not be added automatically and you will have to manually type them in, but you will preserve the style of the import block.

**Comment by hlbbt** [comment] 2021-05-18 09:50
> @hlbbt：我不确定如何在这里提供进一步的帮助。如果禁用导入组织，导入将不会自动添加，您将必须手动输入，但是您将保留导入块的样式。

I have a small request, can you provide a setting of formatting option to `gofmt` without affecting the automatic import

**Comment by stamblerre** [comment] 2021-05-18 19:32
Your request sounds like the issue filed in https://github.com/golang/go/issues/37719, so I'm going to close this as a duplicate of that issue. Please follow along there.

**Closed by stamblerre** 2021-05-18 19:32 UTC
Labels: WaitingForInfo
