### ISSUE TITLE
debug: failed to set variable - literal string can not be allocated because function calls are not allowed without using 'call'

### ISSUE THREAD

**Issue by jeffwidman** [golang/vscode-go#890] opened 2020-11-06 04:58 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
go version go1.15.3 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
1.50.1
d2e414d9e4239a252d1ab117bd7067f125afd80a
x64
- Check your installed extensions to get the version of the VS Code Go extension 
0.18.1

### Share the Go related settings you have added/edited

No customizations

### Describe the bug

1. Start the Go debugger.
2. Try to modify a string value within a function by clicking `Edit value`. 
3. String becomes visually editable, I type to enter changes.
4. I hit enter to submit changes.
5. I see the following error:
```
Failed to set variable - literal string can not be allocated because function calls are not allowed without using 'call'
```
 
Googling around, I found this nearly identical bug report on `go-delve`, where they say it should be reported to `vscode-go`: https://github.com/go-delve/delve/issues/2057

In particular, note their summary of the bug: 
> Strings can only be set by injecting a function call, this should be reported to vscode-go.

I searched the issues here, and couldn't find a previous report.

**Comment by hyangah** [comment] 2020-11-06 16:10
@jeffwidman Thanks for filing an issue. Try call the function with `call` as the error message says. See https://github.com/golang/vscode-go/blob/master/CHANGELOG.md#new-features-1. 

And note that delve's function call support is still in experimental state (technically hard), so be aware of its limitation 
https://github.com/go-delve/delve/blob/master/Documentation/cli/README.md#call

**Comment by jeffwidman** [comment] 2020-11-06 16:19
@hyangah I wasn't attempting to call a function at all... I did the following:
1. in the upper right corner of the debugger UI there's a window that says "Variables"
2. I right-clicked on a string variable... the menu includes "Edit Value"
3. I clicked "Edit Value", then the string looks modifiable, so I type an updated value and hit "enter" to save
4. I see the error

This is a string variable, not a function... how would I call it? 

And regardless, the right-click menu clearly says "Edit Value" and then makes the field editable... at least until I type "enter" to save... if the value isn't editable, then can we remove this from the right-click menu?

**Comment by jeffwidman** [comment] 2020-11-09 18:06
Nudge @hyangah can you address ☝️ ? I think this was closed prematurely.

**Comment by hyangah** [comment] 2020-11-09 18:14
@polinasok @suzmue  do you happen to know how to disable this "Edit Value" UI?

**Comment by hyangah** [comment] 2020-11-09 18:35
Delve's Set allows only numerical types and pointers. 

https://godoc.org/github.com/go-delve/delve/service/rpc2#RPCServer.Set

```
From client: setVariable({"variablesReference":1000,"name":"s","value":"\"bar\""})
SetVariableRequest
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2020-11-09T13:24:44-05:00 debug layer=rpc <- RPCServer.Set(rpc2.SetIn{\"Scope\":{\"GoroutineID\":1,\"Frame\":0,\"DeferredCall\":0},\"Symbol\":\"s\",\"Value\":\"\\\"bar\\\"\"})\n"}}
2020-11-09T13:24:44-05:00 debug layer=rpc <- RPCServer.Set(rpc2.SetIn{"Scope":{"GoroutineID":1,"Frame":0,"DeferredCall":0},"Symbol":"s","Value":"\"bar\""})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2020-11-09T13:24:44-05:00 debug layer=rpc -> *rpc2.SetOut{} error: \"literal string can not be allocated because function calls are not allowed without using 'call'\"\n"}}
2020-11-09T13:24:44-05:00 debug layer=rpc -> *rpc2.SetOut{} error: "literal string can not be allocated because function calls are not allowed without using 'call'"
Failed to set variable - literal string can not be allocated because function calls are not allowed without using 'call'
To client: {"seq":0,"type":"response","request_seq":12,"command":"setVariable","success":false,"message":"Failed to set variable: literal string can not be allocated because function calls are not allowed without using 'call'","body":{"error":{"id":2010,"format":"Failed to set variable: literal string can not be allocated because function calls are not allowed without using 'call'","showUser":true}}}
```

More complicated setting may be achievable through 'call' (which is experimental) if a setter function is available. 
Even when a setter function is available, I am afraid we can't figure out the function automatically in implementing DAP protocol.
So, I guess this is working as intended. Maybe it is something to mention in the documentation.

**Comment by jeffwidman** [comment] 2020-11-09 20:45
Given that it's not actually settable, the ideal solution would be to hide the misleading `"Edit Value"` in the UI. 

If that's not possible, docs would be nice, but at least there's now this github issue serving as an answer who hits this in the future.

**Comment by edwardotis** [comment] 2021-02-09 05:07
The UI to set a value still fails, as described in this bug, however, I was able to set String values  just now in vscode's debug console. 

From stackoverflow:
It is now possible to call a function. You can run the commands in the debug console on a paused breakpoint.  The syntax is:
`call functionToBeCalled(arg1, arg2)
`

You can also set a variable

`call myVariable = newValue
`

You can also set a property of an object.
`call myObj.myProperty="some new property value"
`

https://stackoverflow.com/a/65565376

**Comment by polinasok** [comment] 2021-02-18 08:11
Duplicate of 1173
(Choosing the later issue to leave open as it contains the summary, the workaround and the triage decision.)

**Closed** 2021-02-18 08:11 UTC
Labels: Debug, DlvDAP, Documentation
