### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by josh-tepper-clarifai** [golang/vscode-go#383] opened 2020-07-20 03:43 UTC
Describe what you observed.

I switched branches (with git), and then immediately following this I called `git merge` to fast-forward changes from upstream.  Immediately after this I got a message indicating that gopls had crashed.  This is the first time this has happened.  It should be noted that there was a size-able diff between the two branches, and then the git merge from upstream likely also involved a large diff.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x110aab9]

goroutine 98 [running]:
go/ast.Walk(0x1a94d20, 0xc0580ab580, 0x1a98f00, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/go/ast/walk.go:349 +0x25f9
go/ast.Inspect(...)
	/usr/local/Cellar/go/1.13.4/libexec/src/go/ast/walk.go:385
golang.org/x/tools/internal/lsp/cache.astCost(0x0, 0x17cb360)
	/Users/joshtepper/work/clarifai/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/cache/cache.go:238 +0x97
golang.org/x/tools/internal/lsp/cache.(*Cache).PackageStats.func1(0x17f2200, 0xc01315c390, 0x17cb1a0, 0xc01b923940)
	/Users/joshtepper/work/clarifai/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/cache/cache.go:202 +0x21b
golang.org/x/tools/internal/memoize.(*Store).DebugOnlyIterate(0xc00031c3b0, 0xc02abe85b0)
	/Users/joshtepper/work/clarifai/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/memoize/memoize.go:184 +0x176
golang.org/x/tools/internal/lsp/cache.(*Cache).PackageStats(0xc00031c390, 0xc036800a01, 0xc, 0x1a93580)
	/Users/joshtepper/work/clarifai/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/cache/cache.go:175 +0x94
golang.org/x/tools/internal/lsp/debug.(*Instance).writeMemoryDebug(0xc000328000, 0x2, 0xc02e739b01, 0x52, 0x0)
	/Users/joshtepper/work/clarifai/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/debug/serve.go:460 +0x5df
golang.org/x/tools/internal/lsp/debug.(*Instance).MonitorMemory.func1(0xc0001dc6e0, 0xc0001aeed8, 0xc000328000, 0x1aa7dc0, 0xc00031c330)
	/Users/joshtepper/work/clarifai/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/debug/serve.go:414 +0xb6
created by golang.org/x/tools/internal/lsp/debug.(*Instance).MonitorMemory
	/Users/joshtepper/work/clarifai/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/debug/serve.go:406 +0x99
[Error - 11:35:48 PM] Connection to server got closed. Server will not be restarted.
```

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment] 2020-07-20 06:31
Thanks for the report. I believe this has been fixed at master - you can try it out by running: `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`.

**Comment by stamblerre** [comment] 2020-07-20 06:31
Duplicate of https://github.com/golang/go/issues/40224

**Closed by stamblerre** 2020-07-20 06:31 UTC
