### ISSUE TITLE
Invalid paths printed in test output

### ISSUE THREAD

**Issue by dt** [golang/vscode-go#1875] opened 2021-11-04 17:53 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.17.2 darwin/arm64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.7.3
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.61.2 arm64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.29.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- n/a
</details>

### Describe the bug

When a test is run in VS Code, file names printed as a prefix of messages logged by `t.Log` calls have the test package's path prepended to them, regardless of where the file containing that `t.Log` call is actually located, generating invalid file paths in the output. 

VS Code then appears to try to link-ify these paths which apparently includes trying to open them generating error messages in the logs and error notification pop-ups.

### Steps to reproduce the behavior:

Define some helper package that has a helper function, e.g in `./helper/util.go`:
```go
package helper

import "testing"

func DoThing(t *testing.T) {
	t.Log("this is the helper")
}
```

In some file, `demo_test.go`, add a test that calls that helper in that other package, e.g.
```go
package demo

import (
	"testing"

	"github.com/dt/demo/helper"
)

func TestFoo(t *testing.T) {
	t.Log("hello from test")
	helper.DoThing(t)
	t.Log("goodbye from test")
	t.Fail()
}
```

When run on the terminal, `go test` prints the something like this:
```
> demo go test .
--- FAIL: TestFoo (0.00s)
    some_test.go:10: hello from test
    utils.go:6: this is the helper
    some_test.go:12: goodbye from test
FAIL
FAIL    github.com/dt/demo      0.092s
FAIL
```

However when run via the extension, it prints:
```
Running tool: /opt/homebrew/bin/go test -timeout 30s -run ^TestFoo$ github.com/dt/demo

--- FAIL: TestFoo (0.00s)
    /Users/david/code/demo/some_test.go:10: hello from test
    /Users/david/code/demo/utils.go:6: this is the helper
    /Users/david/code/demo/some_test.go:12: goodbye from test
FAIL
FAIL	github.com/dt/demo	0.691s
FAIL
```

Note that in extension-run version, the file names emitted by `t.Log` have had the path to the package containing the test (`/Users/david/code/demo`) prepended, even though `util.go` is not in that directory, so that produced the wrong path.

### Screenshots or recordings

In VS Code's logs (`Log (Window)` it looks like it is seeing this path printed and trying to open it for some reason, and emitting the error (taken from a real case rather than my minimal repro):

```
[2021-11-04 17:22:12.948] [renderer3] [error] Error: Unable to read file '/Users/david/code/cockroach/branches/21.1/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/test_log_scope.go' (Error: Unable to resolve nonexistent file '/Users/david/code/cockroach/branches/21.1/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/test_log_scope.go')
    at i.handleSetInputError (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2319:142772)
    at i.handleSetInputError (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2319:146563)
    at i.setInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2319:142466)
    at async h.doSetInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2319:34301)
    at async h.doOpenEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2319:32701)
    at async h.openEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2319:32349)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2521:16907
    at async b.doOpenCodeEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1297:137258)
    at async S.open (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:604:19704)
    at async open (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:604:21217)
```

**Comment by dt** [comment] 2021-11-04 18:05
Looks like might be the same underlying cause as #1847, that cmd/go doesn't qualify paths e.g. to the module root? But pending something helpful like that from upstream, I wonder if the current behavior, of unconditionally doing `expandFilePathInOutput` on any filename, is better than just leaving the ambiguous filenames alone and unprefixed, as un-prefixed seems better than wrong-prefixed?

**Comment by suzmue** [comment] 2021-11-04 19:24
@dt This indeed is caused by the same underlying cause as #1847 (which is golang/go#47399).

Thanks for filing an issue and including this use case to consider for how the extension should workaround the underlying issue.

**Comment by suzmue** [comment] 2021-11-05 18:35
Closing this issue because we do not plan to make the change to stop unconditionally doing `expandFilePathInOutput` for test output. This will be fixed when the go command can be configured to print absolute paths instead.

**Closed by suzmue** 2021-11-05 18:35 UTC
