### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Mynraw** [golang/vscode-go#3433] opened 2024-06-25 10:18 UTC
gopls version: v0.16.0/go1.22.4
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Tue, 25 Jun 2024 10:17:15 GMT
restart history:
Tue, 25 Jun 2024 09:24:35 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: slice bounds out of range [8:7]

goroutine 146 [running]:
golang.org/x/tools/gopls/internal/golang/completion.Selection.Suffix(...)
	  completion.go:367
golang.org/x/tools/gopls/internal/server.toProtocolCompletionItems({0x14000248008, 0x3, 0x140004b07e0%3F}, 0x140006a7e40, 0x14000336c88)
	  completion.go:114  0x778
golang.org/x/tools/gopls/internal/server.(*server).Completion(0x14000190600, {0x101aa2108, 0x140003c0060}, 0x14000426aa0)
	  completion.go:76  0x4cc
golang.org/x/tools/gopls/internal/protocol.serverDispatch({0x101aa2140, 0x14000347040}, {0x101abc050, 0x14000190600}, 0x14000d378c0, {0x101aa2300, 0x140006a6200})
	  tsserver.go:361  0x1f28
golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.ServerHandler.func3({0x101aa2140, 0x14000347040}, 0x14000d378c0, {0x101aa2300, 0x140006a6200})
	  protocol.go:160  0x74
golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.handshaker.func4({0x101aa2140, 0x14000347040}, 0x14000d378c0, {0x101aa2300, 0x140006a6200})
	  lsprpc.go:509  0x6e0
golang.org/x/tools/gopls/internal/protocol.Handlers.MustReplyHandler.func1({0x101aa2140, 0x14000347040}, 0x140006aaa98, {0x101aa2300, 0x140006a6200})
	  handler.go:35  0xc0
golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2.2()
	  handler.go:103  0x90
created by golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2 in goroutine 92
	  handler.go:100  0x19c
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 6,
    "TestdataFiles": 0,
    "GoFiles": 3,
    "ModFiles": 2,
    "Dirs": 2
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.4",
  "GoplsVersion": "v0.16.0",
  "InitialWorkspaceLoadDuration": "184.30225ms",
  "MemStats": {
    "HeapAlloc": 6987344,
    "HeapInUse": 12132352,
    "TotalAlloc": 78062136
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 469,
      "Largest": 210104,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.4",
        "AllPackages": {
          "Packages": 45,
          "LargestPackage": 155,
          "CompiledGoFiles": 466,
          "Modules": 1
        },
        "WorkspacePackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-06-25 16:15
Thank you for the report. This looks like a dupe of golang/go#68169.

**Closed by findleyr** 2024-06-25 16:15 UTC
