### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by qianxi0410** [golang/vscode-go#2144] opened 2022-03-28 14:38 UTC
gopls version: v0.8.1 (go1.18rc1)
gopls flags: 
update flags: proxy
extension version: 2022.3.2318
go version: 1.18rc1
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Mon, 28 Mar 2022 14:37:57 GMT
restart history:
Mon, 28 Mar 2022 14:27:04 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb75992]

goroutine 76 [running]:
golang.org/x/tools/internal/lsp/cache.parseGoWork({0x10009e8, 0xc000253290}, {0xc000330b70, 0x27}, {0xc000330ae0%3F, 0xc0003eaec0%3F}, {0xc0005a0000, 0x0, 0x200}, {0xffa1e0, ...})
	  workspace.go:508  0x232
golang.org/x/tools/internal/lsp/cache.loadExplicitWorkspaceFile({0x10009e8, 0xc000253290}, 0xc00015f680, {0xffa1e0%3F, 0xc000658000%3F})
	  workspace.go:152  0x1e6
golang.org/x/tools/internal/lsp/cache.newWorkspace({0x10009e8, 0xc000253290}, {0xc000330b70, 0x27}, {0xffa1e0, 0xc000658000}, 0xc000526c30, 0x0, 0x0)
	  workspace.go:106  0xbb
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0xc000658000, {0x10009e8, 0xc000253290}, {0xc0002849b0, 0x9}, {0xc00016c4e0, 0x27}, 0xc0003ec240, 0x0)
	  session.go:197  0x25d
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0xc000658000, {0x10009e8, 0xc000253290}, {0xc0002849b0, 0x9}, {0xc00016c4e0, 0x27}, 0xc0005d2f40%3F)
	  session.go:166  0x287
golang.org/x/tools/internal/lsp.(*Server).addView(0xc0004a2480, {0x10009e8, 0xc000253290}, {0xc0002849b0, 0x9}, {0xc00016c4e0, 0x27})
	  workspace.go:42  0x1c7
golang.org/x/tools/internal/lsp.(*Server).addFolders(0xc0004a2480, {0x10009e8%3F, 0xc000253290}, {0xc000363640, 0x1, 0x1%3F})
	  general.go:234  0x6f5
golang.org/x/tools/internal/lsp.(*Server).initialized(0xc0004a2480, {0x10009e8, 0xc000253290}, 0xc0003739e0%3F)
	  general.go:186  0x2fa
golang.org/x/tools/internal/lsp.(*Server).Initialized(0xc000641630%3F, {0x10009e8%3F, 0xc000253290%3F}, 0xc59ec0%3F)
	  server_gen.go:156  0x25
golang.org/x/tools/internal/lsp/protocol.serverDispatch({0x10009e8, 0xc000253290}, {0x100bae0, 0xc0004a2480}, 0xc000310420, {0x1000be0, 0xc0002531d0})
	  tsserver.go:140  0x6d3
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1({0x10009e8, 0xc000253290}, 0xc000310420, {0x1000be0, 0xc0002531d0})
	  protocol.go:154  0x90
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1({0x10009e8, 0xc000253290}, 0xc000310420, {0x1000be0%3F, 0xc0002531d0%3F})
	  lsprpc.go:506  0xa43
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x10009e8, 0xc000253290}, 0xc000318ba0, {0x1000be0%3F, 0xc0002531d0%3F})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20a
[Error - 下午10:37:52] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2022-03-28 18:02
Thanks for the report - Duplicate of https://github.com/golang/go/issues/51844
The fix will be released soon (gopls v0.8.2)

**Closed by hyangah** 2022-03-28 18:02 UTC
