### ISSUE TITLE
Compiler (BrokenImport) (for IntelliSense and testing)  but go build and go test works

### ISSUE THREAD

**Issue by dsm-72** [golang/vscode-go#2761] opened 2023-05-05 17:57 UTC
## Issue description

I am having trouble setting up a Golang project to work with the Golang extension in VSCode. I have followed the instructions for setting up a Golang project and have been able to build and test my project successfully using the command line (`go build` and `go test ./...`). However, the Golang extension in VSCode is giving me an error when I try to import a package (`gonum.org/v1/gonum/mat`). The error message says that the package cannot be found in either `$GOROOT` or `$GOPATH`, but I have confirmed that the package is installed under `$GOPATH/pkg/mod/gonum.org/v1/gonum@v0.13.0/mat`. Additionally, the Golang extension does not seem to recognize my project and I am unable to run tests or use other features of the extension.

## Steps to reproduce

1. Install the Golang extension v0.38.0 in VSCode.
2. Create a new Golang project with the following directory structure:

   ```
   my_project/
   ├── PackageName/
   │   ├── subpkg/
   │   │   └── subpkg.go
   │   ├── go.mod
   │   └── main.go
   ```

3. Add the following contents to the `go.mod` file:

   ```
   module github.com/USER/PackageName

   go 1.20

   require gonum.org/v1/gonum v0.13.0 // indirect
   ```

Note: `go get gonum.org/v1/gonum/mat` and `go get -u gonum.org/v1/gonum/mat` results in `require gonum.org/v1/gonum v0.13.0`

4. Add the following contents to the `main.go` file:

   ```Golang
   package main

   import (
       "fmt"
       "github.com/USER/PackageName/subpkg"
   )

   func main() {
       subpkg.Hello()
   }
   ```

5. Add the following contents to the `subpkg/subpkg.go` file:
```Golang
package subpkg

import (
	"fmt"
	"gonum.org/v1/gonum/mat"
)

func Hello() {
	mat := mat.NewDense(4, 5, nil)
	fmt.Sprintf("Hello from subpk. mat=%v", mat)
}
```

6. Open the `my_project` directory in VSCode and attempt to run tests using the VSCode test runner or use other features of the Golang extension.

## Expected behavior

The Golang extension should recognize the project and allow me to run tests and use other features of the extension. The package `gonum.org/v1/gonum/mat` should be found and able to be imported.

## Actual behavior

The Golang extension does not recognize the project and I am unable to run tests or use other features of the extension. The package `gonum.org/v1/gonum/mat` cannot be found and gives an error when trying to import.

## System information

- OS: `Ventura 13.3.1 (a)`
- VSCode: `version:1.78.0  arm64`
- Golang version: `go version go1.20.4 darwin/arm64`
- `$GOPATH` environment variable: `/Users/USER/go/`
- `$GOROOT` environment variable: `/opt/homebrew/opt/go/libexec`

## Additional information

- Output of `go version` command: `go version go1.20.4 darwin/arm64`
- Output of `go env` command: 
```shell
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/USER/Library/Caches/go-build"
GOENV="/Users/USER/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/USER/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/USER/go/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/opt/go/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/Users/USER/Projects/my_project/PackageName/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/35/0b6fp_4n3c35y2f9yxx_wkvr0000gn/T/go-build3458128548=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
- List of installed VSCode extensions: Go v0.38.0
- Log files: N/a

**Comment by findleyr** [comment] 2023-05-09 19:40
Closing as a dupe of #57979 (we have other issues open to improve error messages in this case).

Please comment if you are not able to get this working.

**Closed by findleyr** 2023-05-09 19:40 UTC
