### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by wbasabe0891201** [golang/vscode-go#1569] opened 2021-06-15 00:19 UTC
gopls version: v0.7.0
gopls flags: 
update flags: proxy
extension version: 0.25.1
go version: 1.16.5
environment: Visual Studio Code linux
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: only file URIs are supported, got "untitled" from "untitled:Untitled-1"

goroutine 19519 [running]:
golang.org/x/tools/internal/span.URI.Filename(...)
	  uri.go:32
golang.org/x/tools/internal/lsp.(*Server).definition(0xc0001ac2a0, 0xfbf318, 0xc00c7fe100, 0xc00c2f8000, 0x0, 0x0, 0x0, 0x0, 0x0)
	  definition.go:16  0x797
golang.org/x/tools/internal/lsp.(*Server).Definition(0xc0001ac2a0, 0xfbf318, 0xc00c7fe100, 0xc00c2f8000, 0xc00c2f8000, 0x0, 0x0, 0x0, 0x0)
	  server_gen.go:40  0x4d
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xfbf318, 0xc00c7fe100, 0xfd65a0, 0xc0001ac2a0, 0xc00c546060, 0xfbf580, 0xc00c7fe080, 0x1, 0x0, 0xfadae0)
	  tsserver.go:386  0x2752
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xfbf318, 0xc00c7fe100, 0xc00c546060, 0xfbf580, 0xc00c7fe080, 0x0, 0xc02a1a5f9c7434ee)
	  protocol.go:154  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xfbf318, 0xc00c7fe100, 0xc00c546060, 0xfbf580, 0xc00c7fe080, 0x0, 0x0)
	  lsprpc.go:684  0x459
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xfbf318, 0xc00c7fe100, 0xc0053bc210, 0xfbf580, 0xc00c7fe080, 0xc014a04090, 0x443e56)
	  handler.go:35  0xd7
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00847c180, 0xc00bebc930, 0xc00024dd60, 0xfbf318, 0xc00c7fe100, 0xc0053bc210, 0xfbf580, 0xc00c7fe080)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 19:19:10] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2021-06-15 01:15
Thanks for the report @wbasabe0891201 
Duplicate of #1559 
The fix (avoiding crash by ignoring `untitled` files) will be available in the next release.

**Closed by hyangah** 2021-06-15 01:15 UTC
