### ISSUE TITLE
gopls: 자동 문제 보고서(충돌)

### ISSUE THREAD

**Issue by Parasiel** [golang/vscode-go#1545] opened 2021-06-05 08:20 UTC
gopls version: v0.7.0-pre.1
gopls flags: 
update flags: proxy
extension version: 2021.5.2720
go version: 1.16.4
environment: Visual Studio Code win32
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: index out of range [-1]

goroutine 139 [running]:
golang.org/x/tools/internal/lsp/template.parseBuffer(0xc0004b1400, 0x0, 0x200, 0x200)
	  parse.go:96  0xc7d
golang.org/x/tools/internal/lsp/template.Diagnose(0x14c5148, 0xc00036f3d0, 0xc00019a380, 0xc00054b490, 0x66)
	  implementations.go:35  0x31f
golang.org/x/tools/internal/lsp.(*Server).diagnose(0xc00019a2a0, 0x14bb1d0, 0xc0002cb0c0, 0x14cf378, 0xc00019a380, 0x0)
	  diagnostics.go:215  0x88f
golang.org/x/tools/internal/lsp.(*Server).diagnoseDetached(0xc00019a2a0, 0x14cf378, 0xc00019a380)
	  diagnostics.go:90  0xb8
golang.org/x/tools/internal/lsp.(*Server).addFolders.func3(0xc00019a2a0, 0x14cf378, 0xc00019a380, 0xc0004ca060, 0xc000488960, 0xc000378360)
	  general.go:264  0x46
created by golang.org/x/tools/internal/lsp.(*Server).addFolders
	  general.go:263  0xb5c
[Error - 오후 5:19:54] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2021-06-05 12:23
Hi, this is a duplicate of #1540, and will be fixed in the next gopls release.

**Closed by findleyr** 2021-06-05 12:23 UTC
