### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by dgallion1** [golang/vscode-go#1009] opened 2020-12-07 14:43 UTC
[log.txt](https://github.com/golang/vscode-go/files/5653328/log.txt)
gopls version: v0.5.5
gopls flags: -rpc.trace

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: no snapshot assigned for files [file:///C:/work1/dev/server/goMods/webServerLib/appToWs.go]

goroutine 120 [running]:
golang.org/x/tools/internal/lsp.(*Server).didModifyFiles(0xc0001a6460, 0x19a48a0, 0xc000497d40, 0xc00c523cc0, 0x1, 0x1, 0x0, 0x0, 0x0)
	  text_synchronization.go:234  0xe8b
golang.org/x/tools/internal/lsp.(*Server).didOpen(0xc0001a6460, 0x19a48a0, 0xc000497d40, 0xc005708740, 0x0, 0xc004235a20)
	  text_synchronization.go:92  0x217
golang.org/x/tools/internal/lsp.(*Server).DidOpen(0xc0001a6460, 0x19a48a0, 0xc000497d40, 0xc005708740, 0xc005708740, 0x0)
	  server_gen.go:56  0x50
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x19a48a0, 0xc000497d40, 0x19b9160, 0xc0001a6460, 0xc007f2a120, 0x249b95ce9c0, 0xc000497ce0, 0x0, 0x1992100, 0xc003e95ef0)
	  tsserver.go:112  0x11b8
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x19a48a0, 0xc000497d40, 0xc007f2a120, 0x249b95ce9c0, 0xc000497ce0, 0x23d1f01a1, 0x1dfeca0)
	  protocol.go:63  0xc7
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x19a48a0, 0xc000497d40, 0xc007f2a120, 0x249b95ce9c0, 0xc000497ce0, 0x0, 0x0)
	  lsprpc.go:559  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x19a48a0, 0xc000497d40, 0xc00025bd40, 0x249b95ce9c0, 0xc000497ce0, 0xce300000ce2, 0xd0300000d00)
	  handler.go:35  0xda
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc000036480, 0xc000110900, 0xc0009340a0, 0x19a48a0, 0xc000497d40, 0xc00025bd40, 0x249b95ce9c0, 0xc000497ce0)
	  handler.go:103  0x8d
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x179
[Error - 9:42:03 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2020-12-07 15:03
Duplicate of #1008 
Thanks again, @dgallion1 - let's continue discussion in #1008 where you attached the full trace already.

**Closed by hyangah** 2020-12-07 15:03 UTC
