### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by ZivHuang** [golang/vscode-go#3564] opened 2024-10-13 00:32 UTC
gopls version: v0.13.2/go1.23.0
gopls flags: 
update flags: proxy
extension version: 0.42.1
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Sun, 13 Oct 2024 00:30:44 GMT
restart history:
Sun, 13 Oct 2024 00:28:31 GMT: activation (enabled: true)
Sun, 13 Oct 2024 00:28:49 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 16346 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-10-21 16:21
Dupe of #3570.

**Closed by findleyr** 2024-10-21 16:21 UTC
