### ISSUE TITLE
Couldn't attach the process 

### ISSUE THREAD

**Issue by Kellermaan** [golang/vscode-go#1662] opened 2021-08-04 03:12 UTC
Everything I used is up to date.

### Share the Go related settings you have added/edited

{
                        "name": "Attach to Process",
                        "type": "go",
                        "request": "attach",
                        "mode": "local",
                        "processId": 2299
},

### Describe the bug
I couldn't use the attach debug mode when I use the remote ssh on my server.
I run the app, and get the process id 2299, then I set up the json file.
When I clik the run button, just no reaction.

### Screenshots or recordings
![图片](https://user-images.githubusercontent.com/11674190/128116301-990eabd9-3c86-434c-8ce0-6f4c4b82f83c.png)

**Comment by hyangah** [comment] 2021-08-04 11:59
@Kellermaan was there any log message in the Debug Console? Try to [increase log verbosity](https://github.com/golang/vscode-go/blob/master/docs/debugging-legacy.md#enable-logging) to gather more details.

```
{
"name": "Attach to Process",
...
"showLog": true,
"logOutput": "rpc,debugger",
"trace": "verbose",
}
```

**Comment by hyangah** [comment] 2021-08-04 23:46
Probably a duplicate of https://github.com/golang/vscode-go/issues/1608. 
v0.27.0 will include the fix for the issue. Until then, either try to specify `cwd` or try a new adapter that doesn't have this issue - (by adding the debugAdapter property: `"debugAdapter": "dlv-dap"`)

**Comment by Kellermaan** [comment] 2021-08-09 14:53
@hyangah  sure, got it, it works now, thanks a lot!

**Comment by hyangah** [comment] 2021-08-09 17:47
Glad to hear that the problem was solved. Closing.

**Closed by hyangah** 2021-08-09 17:47 UTC
Labels: Debug, WaitingForInfo
