### ISSUE TITLE
Go to definition of the module is very annoying

### ISSUE THREAD

**Issue by axetroy** [golang/vscode-go#257] opened 2020-06-25 14:50 UTC
See the gif

![1](https://user-images.githubusercontent.com/9758711/85742428-d0a75b80-b735-11ea-96e9-900bfcc4050f.gif)

Every time I go to the module, it will show such a prompt and it is very very annoying

It should not be a link for `go doc`

It should go to the local module (`go modules` or `vendor`)

**Comment by stamblerre** [comment] 2020-06-25 19:20
This is a `gopls` issue - you can read more here: https://github.com/golang/go/issues/39065. We will aim to have a fix for this before `gopls/v0.5.0` is released. Closing as a duplicate.

**Comment by stamblerre** [comment] 2020-06-25 19:20
Duplicate of https://github.com/golang/go/issues/39065

**Closed by stamblerre** 2020-06-25 19:20 UTC
