### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by ccb1900** [golang/vscode-go#2150] opened 2022-03-30 08:13 UTC
gopls version: v0.8.1 (go1.18)
gopls flags: 
update flags: proxy
extension version: 0.32.0
go version: 1.18
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Wed, 30 Mar 2022 08:13:29 GMT
restart history:
Wed, 30 Mar 2022 08:11:04 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102ed9710]

goroutine 148 [running]:
golang.org/x/tools/internal/lsp/cache.parseGoWork({0x10335c5f0, 0x14000113a40}, {0x140001344c0, 0x34}, {0x14000134340%3F, 0x102a6b5ac%3F}, {0x14000276200, 0x0, 0x200}, {0x103355f48, ...})
	  workspace.go:508  0x1d0
golang.org/x/tools/internal/lsp/cache.loadExplicitWorkspaceFile({0x10335c5f0, 0x14000113a40}, 0x140001186c0, {0x103355f48%3F, 0x140000dc000%3F})
	  workspace.go:152  0x15c
golang.org/x/tools/internal/lsp/cache.newWorkspace({0x10335c5f0, 0x14000113a40}, {0x140001344c0, 0x34}, {0x103355f48, 0x140000dc000}, 0x14000204930, 0x0, 0x0)
	  workspace.go:106  0xb0
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0x140000dc000, {0x10335c5f0, 0x14000113a40}, {0x1400011cc00, 0x11}, {0x140007886c0, 0x34}, 0x14000146240, 0x0)
	  session.go:197  0x21c
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0x140000dc000, {0x10335c5f0, 0x14000113a40}, {0x1400011cc00, 0x11}, {0x140007886c0, 0x34}, 0x1400010a0e8%3F)
	  session.go:166  0x1b0
golang.org/x/tools/internal/lsp.(*Server).addView(0x14000500900, {0x10335c5f0, 0x14000113a40}, {0x1400011cc00, 0x11}, {0x140007886c0, 0x34})
	  workspace.go:42  0x1f0
golang.org/x/tools/internal/lsp.(*Server).addFolders(0x14000500900, {0x10335c5f0%3F, 0x14000113a40}, {0x1400010ec60, 0x1, 0x8%3F})
	  general.go:234  0x4e8
golang.org/x/tools/internal/lsp.(*Server).initialized(0x14000500900, {0x10335c5f0, 0x14000113a40}, 0x1400001a000%3F)
	  general.go:186  0x2d4
golang.org/x/tools/internal/lsp.(*Server).Initialized(0x1400064beb0%3F, {0x10335c5f0%3F, 0x14000113a40%3F}, 0x10321c160%3F)
	  server_gen.go:156  0x28
golang.org/x/tools/internal/lsp/protocol.serverDispatch({0x10335c5f0, 0x14000113a40}, {0x1033663d8, 0x14000500900}, 0x140004a8000, {0x10335c7e8, 0x14000113980})
	  tsserver.go:140  0x5c8
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1({0x10335c5f0, 0x14000113a40}, 0x140004a8000, {0x10335c7e8, 0x14000113980})
	  protocol.go:154  0x70
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1({0x10335c5f0, 0x14000113a40}, 0x140004a8000, {0x10335c7e8%3F, 0x14000113980%3F})
	  lsprpc.go:506  0x788
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x10335c5f0, 0x14000113a40}, 0x1400029bd40, {0x10335c7e8%3F, 0x14000113980%3F})
	  handler.go:35  0xf4
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0x90
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x1dc
[Error - 下午4:13:04] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2022-03-30 13:22
Duplicate of #2139

**Closed by hyangah** 2022-03-30 13:22 UTC
