### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by JimmyWang** [golang/vscode-go#1441] opened 2021-04-20 01:34 UTC
gopls version: v0.6.10
gopls flags: 
update flags: proxy
extension version: 0.24.1
go version: 1.15.6
environment: Visual Studio Code win32
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

logs pls refer to https://github.com/golang/vscode-go/issues/1436

**Comment by findleyr** [comment] 2021-04-20 01:49
Thanks for following up. I'll re-open #1436 -- we can continue discussion there.

**Comment by findleyr** [comment] 2021-04-20 12:53
(closing as a duplicate of #1436)

**Closed** 2021-04-20 12:53 UTC
