### ISSUE TITLE
Go debugger exits 

### ISSUE THREAD

**Issue by alan-marcinkowski** [golang/vscode-go#2262] opened 2022-05-25 19:35 UTC
Issue Type: <b>Bug</b>

There is a dlv remote server running headless in a pod container. I can attach and start stepping. At a certain step in my code, the debugger exits and breaks the connection to the remote debugger.

From client: variables({"variablesReference":1000})
VariablesRequest
Unhandled error in debug adapter: TypeError: Cannot read properties of undefined (reading 'addr')
    at GoDebugSession.convertDebugVariableToProtocolVariable (c:\Users\alan.marcinkowski\.vscode\extensions\golang.go-0.33.1\dist\debugAdapter.js:16651:25)
    at c:\Users\alan.marcinkowski\.vscode\extensions\golang.go-0.33.1\dist\debugAdapter.js:16219:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 3)

Extension version: 0.33.1
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (2.20GB free)|
|Process Argv|--crash-reporter-id 04bdc96b-ffd6-4090-888d-668e53f3e2dd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes516:30244333
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by hyangah** [comment] 2022-05-26 20:21
Duplicate of https://github.com/golang/vscode-go/issues/2183

@alan-marcinkowski Can you try the 'dlv-dap' mode as described in https://github.com/golang/vscode-go/issues/2183#issuecomment-1099922193?

We also plan to switch the default to the 'dlv-dap' mode for `remote`/`attach` case. Your feedback and friction reports are greatly appreciated!

**Closed** 2022-05-27 14:50 UTC
Labels: Debug, Duplicate, WillNotFix

**Comment by alan-marcinkowski** [comment] 2022-10-11 07:26
…Yes, I’ve confirmed this to be a legacy issue as well. I have fewer issues with dlv-dap … but I still have issues. The substitute path doesn’t work well when going from debugging remote linux from a windows vscode. Definitely worked better with vscode over WSL.

Thanks.

From: Hyang-Ah Hana Kim ***@***.***>
Sent: Thursday, May 26, 2022 4:21 PM
To: golang/vscode-go ***@***.***>
Cc: Marcinkowski, Alan ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [golang/vscode-go] Go debugger exits (Issue #2262)

CAUTION: This Email is from an EXTERNAL source. Ensure you trust this sender before clicking on any links or attachments.
________________________________

Duplicate of #2183<https://urldefense.com/v3/__https:/github.com/golang/vscode-go/issues/2183__;!!L7QdHkQ!hKn_cGSJXgUKV-0ZedbMA1QHClFZuX5ZOG5ESPxSBdcsJlwxnpQXUiX__vsTz0I1t5vqkzKTU2GxqCNEx4eWl3hbaK9vdw$>

@alan-marcinkowski<https://urldefense.com/v3/__https:/github.com/alan-marcinkowski__;!!L7QdHkQ!hKn_cGSJXgUKV-0ZedbMA1QHClFZuX5ZOG5ESPxSBdcsJlwxnpQXUiX__vsTz0I1t5vqkzKTU2GxqCNEx4eWl3iTSJDemQ$> Can you try the 'dlv-dap' mode as described in #2183 (comment)<https://urldefense.com/v3/__https:/github.com/golang/vscode-go/issues/2183*issuecomment-1099922193__;Iw!!L7QdHkQ!hKn_cGSJXgUKV-0ZedbMA1QHClFZuX5ZOG5ESPxSBdcsJlwxnpQXUiX__vsTz0I1t5vqkzKTU2GxqCNEx4eWl3jJd8TkZA$>?

We also plan to switch the default to the 'dlv-dap' mode for remote/attach case. Your feedback and friction reports are greatly appreciated!
