### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by sanjit91** [golang/vscode-go#2636] opened 2023-02-01 16:18 UTC
gopls version: v0.11.0 (go1.19.4)
gopls flags: 
update flags: proxy
extension version: 0.37.1
go version: 1.19.5
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Wed, 01 Feb 2023 16:18:07 GMT
restart history:
Wed, 01 Feb 2023 16:14:59 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x15d139d]

goroutine 123 [running]:
golang.org/x/tools/gopls/internal/lsp/mod.hoverOnModuleStatement({0x1b30ea0%3F, 0xc000344f60%3F}, 0xc000344f60%3F, 0x1b31108%3F, {0x1b3d298%3F, 0xc0004b86e0%3F}, {0x1b31108%3F, 0xc00042c380%3F})
	  hover.go:128  0x5d
golang.org/x/tools/gopls/internal/lsp/mod.Hover({0x1b30df8, 0xc000310c40}, {0x1b3d298, 0xc0004b86e0}, {0x1b31108, 0xc00042c380}, {0x344de0%3F, 0xc0%3F})
	  hover.go:50  0x35f
golang.org/x/tools/gopls/internal/lsp.(*Server).hover(0x17492c0%3F, {0x1b30df8, 0xc000310c40}, 0xc000344de0)
	  hover.go:25  0x152
golang.org/x/tools/gopls/internal/lsp.(*Server).Hover(0xc00026c360%3F, {0x1b30df8%3F, 0xc000310c40%3F}, 0x17492c0%3F)
	  server_gen.go:140  0x25
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch({0x1b30df8, 0xc000310c40}, {0x1b40c60, 0xc0000fa600}, 0xc000344db0, {0x1b311e8, 0xc000310b40})
	  tsserver.go:397  0xca6
golang.org/x/tools/gopls/internal/lsp/protocol.ServerHandler.func1({0x1b30df8, 0xc000310c40}, 0xc000344db0, {0x1b311e8, 0xc000310b40})
	  protocol.go:157  0x90
golang.org/x/tools/gopls/internal/lsp/lsprpc.handshaker.func1({0x1b30df8, 0xc000310c40}, 0xc000344db0, {0x1b311e8%3F, 0xc000310b40%3F})
	  lsprpc.go:519  0xa39
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x1b30df8, 0xc000310c40}, 0xc000271f68, {0x1b311e8%3F, 0xc000310b40%3F})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20a
[Error - 9:48:00 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2023-02-02 03:04
Thanks for the report @sanjit91  Does your go.mod file missing the `module` statement?

It looks like this is a duplicate of https://github.com/golang/go/issues/57625
The fix is at head, but v0.12.0 is not yet released.

**Comment by hyangah** [comment] 2023-03-01 02:57
Closing - this is a rare case crash and is already fixed at tip.

**Closed by hyangah** 2023-03-01 02:57 UTC
Labels: WaitingForInfo, Duplicate
