### ISSUE TITLE
auto duplicate comment lines on save

### ISSUE THREAD

**Issue by pelli-chen** [golang/vscode-go#992] opened 2020-12-03 03:14 UTC
Issue Type: <b>Bug</b>

1. code:

// Line 1.
type Tree struct {
	arr []string
}

2. save ok.

3. code:

// Line 1.
// aa
type Tree struct {
	arr []string
}

4. on saving, becomes to:

// Line 1.
// aa
// aa
type Tree struct {
	arr []string
}

5. Ctrl+s again, becomes to:

// Line 1.
// aa
// aa
// aa
// aa
type Tree struct {
	arr []string
}

-- Seems each time it duplicated all comment lines except line 1.

Extension version: 0.19.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (4.26GB free)|
|Process Argv|--crash-reporter-id 8c5ea524-7202-4632-9e32-51a508a1ba30|
|Screen Reader|no|
|VM|67%|
</details>

**Comment by stamblerre** [comment] 2020-12-03 04:27
Thanks for the report. This looks like a duplicate of https://github.com/golang/go/issues/42923.

**Comment by stamblerre** [comment] 2020-12-03 04:27
Duplicate of https://github.com/golang/go/issues/42923

**Comment by stamblerre** [comment] 2020-12-03 04:28
As a work-around for now, you can set your line endings to LF instead of CRLF in the bottom-right corner of the VS Code window.

**Closed by stamblerre** 2020-12-03 04:27 UTC
