### ISSUE TITLE
Enable working on multi-module project without workspace

### ISSUE THREAD

**Issue by cletter7** [golang/vscode-go#3007] opened 2023-10-12 17:16 UTC
**Is your feature request related to a problem? Please describe.**
I am working on a monorepo with a bunch of go modules:

```
root
└── plugins
    └── plugin1
        ├── main.go
        └── go.mod
    └── plugin2
        ├── main.go
        └── go.mod
    ...
```

And in VS Code I get errors in the import section of the Go files:

> could not import github.com/.../... (cannot find package "github.com/.../..." in GOROOT or GOPATH)

![image](https://github.com/golang/vscode-go/assets/1436174/1cf61987-a064-4340-b6c4-d46a70efba8b)

Also, VS Code fails to go to the definition or show type on hover when working with the go files inside modules.

And I intentionally don't want to add workspace to the repo root. That's because the modules in the monorepo depend on different versions of same packages and there is no intention to keep those dependencies in sync. But if I enable go workspace then all those modules start to use the same version of the dependecy even though `go.mod` specifies another version. According to [this comment](https://github.com/golang/go/issues/57738#issuecomment-1379509667) this is by design:

> By design, a workspace can have only one set of consistent dependencies. (If you want to work with the dependencies of each module separately, don't combine them in a workspace.)

**Describe the solution you'd like**
I'd like VS Code to be able to work with modules even though they are not located in a root of the repo and even though there is no workspace (just like it works with frontend packages).

**Describe alternatives you've considered**
- Considered adding workspace but this doesn't work in my case.
- Considered opening modules folder as separate folders in VS Code but this is not a convenient way of working with the monorepo.

**Comment by adonovan** [comment] 2023-10-12 18:03
I think this feature comes under the ["zero-config gopls"](https://github.com/golang/go/issues/57979) umbrella, on which work is underway.

@findleyr

**Comment by findleyr** [comment] 2023-10-24 14:18
@cletter7 you can add additional workspace folders manually in VS Code.

I expect zero-config gopls to land in Q4 of this year (I'm resuming work on it as soon as gopls@v0.14.0 goes out).

**Comment by findleyr** [comment] 2023-10-26 21:25
@cletter7 you can set up vs code to have a workspace folder for each module. There is some documentation for this approach here: https://github.com/golang/tools/blob/master/gopls/doc/workspace.md#multiple-workspace-folders

**Comment by findleyr** [comment] 2023-11-02 17:03
I'm going to close this as a dupe of golang/go#57979, which is one of my main priorities for the rest of the year. Please stay tuned!

**Closed by findleyr** 2023-11-02 17:03 UTC
