### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by AntelopeXia** [golang/vscode-go#1548] opened 2021-06-07 08:30 UTC
gopls version: v0.7.0-pre.1
gopls flags: 
update flags: proxy
extension version: 2021.5.2720
go version: 1.15.7
environment: Visual Studio Code win32
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2021-06-07 16:11
Closing, as the issue is empty.
Please reopen if you can share the stack trace of the gopls crash (found by navigating to View -> Output -> Tasks -> gopls (server)).

**Comment by AntelopeXia** [comment] 2021-06-08 01:48
rror: Connection got disposed.
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78880:27)
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:81031:35)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83382:42)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:87174:15)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83369:18)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78092:26)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at StreamMessageReader.fireClose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79744:27)
    at Socket.<anonymous> (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79829:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
[Error - 上午9:46:50] Request textDocument/codeLens failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78880:27)
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:81031:35)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83382:42)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:87174:15)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83369:18)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78092:26)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at StreamMessageReader.fireClose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79744:27)
    at Socket.<anonymous> (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79829:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
[Info  - 上午9:46:56] 2021/06/08 09:46:56 go env for C:\code
(root C:\code)
(go version go version go1.15.7 windows/amd64)
(valid build configuration = false)
(build flags: [])
GONOPROXY=
GOPRIVATE=
GOSUMDB=sum.golang.org
GONOSUMDB=
GOINSECURE=
GOROOT=c:\go
GOCACHE=C:\Users\Smile_xia\AppData\Local\go-build
GOMOD=NUL
GOPATH=C:\code\go
GO111MODULE=on
GOFLAGS=
GOMODCACHE=C:\code\go\pkg\mod
GOPROXY=https://goproxy.io,direct


[Error - 上午9:47:04] 2021/06/08 09:47:04 go/packages.Load: err: exit status 1: stderr: go: cannot find main module; see 'go help modules'

	snapshot=0
	directory=C:\code
	query=[./ builtin]
	packages=0

[Error - 上午9:47:04] 2021/06/08 09:47:04 initial workspace load failed: err: exit status 1: stderr: go: cannot find main module; see 'go help modules'
: packages.Load error

[Error - 上午9:47:04] 2021/06/08 09:47:04 errors loading workspace: gopls requires a module at the root of your workspace.
You can work with multiple modules by opening each one as a workspace folder.
Improvements to this workflow will be coming soon, and you can learn more here:
https://github.com/golang/tools/blob/master/gopls/doc/workspace.md.
	snapshot=0
	directory=file:///C:/code

panic: runtime error: index out of range [0] with length 0

goroutine 149 [running]:
golang.org/x/tools/internal/lsp/template.Diagnose.func1(0xc000562220, 0x1e, 0xc0005d3918, 0x2, 0x2)
	C:/code/go/pkg/mod/golang.org/x/tools@v0.1.3-0.20210603170232-c0e0604565ff/internal/lsp/template/implementations.go:41 +0x334
golang.org/x/tools/internal/lsp/template.Diagnose(0x1a41640, 0xc000227780, 0xc000272000, 0xc0003ce230, 0x62)
	C:/code/go/pkg/mod/golang.org/x/tools@v0.1.3-0.20210603170232-c0e0604565ff/internal/lsp/template/implementations.go:49 +0x7ea
golang.org/x/tools/internal/lsp.(*Server).diagnose(0xc0001382a0, 0x1a371c0, 0xc0001cc600, 0x1a4bea0, 0xc000272000, 0xc000272000)
	C:/code/go/pkg/mod/golang.org/x/tools@v0.1.3-0.20210603170232-c0e0604565ff/internal/lsp/diagnostics.go:215 +0x905
golang.org/x/tools/internal/lsp.(*Server).diagnoseDetached(0xc0001382a0, 0x1a4bea0, 0xc000272000)
	C:/code/go/pkg/mod/golang.org/x/tools@v0.1.3-0.20210603170232-c0e0604565ff/internal/lsp/diagnostics.go:90 +0xb8
golang.org/x/tools/internal/lsp.(*Server).addFolders.func3(0xc0001382a0, 0x1a4bea0, 0xc000272000, 0xc00059d650, 0xc0003642e0, 0xc000095a40)
	C:/code/go/pkg/mod/golang.org/x/tools@v0.1.3-0.20210603170232-c0e0604565ff/internal/lsp/general.go:264 +0x46
created by golang.org/x/tools/internal/lsp.(*Server).addFolders
	C:/code/go/pkg/mod/golang.org/x/tools@v0.1.3-0.20210603170232-c0e0604565ff/internal/lsp/general.go:263 +0xb1c
[Error - 上午9:47:04] Connection to server got closed. Server will not be restarted.
[Error - 上午9:47:04] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78880:27)
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:81031:35)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83382:42)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:87174:15)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83369:18)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78092:26)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at StreamMessageReader.fireClose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79744:27)
    at Socket.<anonymous> (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79829:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
[Error - 上午9:47:04] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78880:27)
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:81031:35)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83382:42)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:87174:15)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83369:18)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78092:26)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at StreamMessageReader.fireClose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79744:27)
    at Socket.<anonymous> (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79829:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
[Error - 上午9:47:04] Request textDocument/documentLink failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78880:27)
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:81031:35)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83382:42)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:87174:15)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83369:18)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78092:26)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at StreamMessageReader.fireClose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79744:27)
    at Socket.<anonymous> (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79829:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
[Error - 上午9:47:04] Request textDocument/foldingRange failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78880:27)
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:81031:35)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83382:42)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:87174:15)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83369:18)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78092:26)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at StreamMessageReader.fireClose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79744:27)
    at Socket.<anonymous> (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79829:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
[Error - 上午9:47:04] Request textDocument/codeLens failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78880:27)
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:81031:35)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83382:42)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:87174:15)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83369:18)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78092:26)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at StreamMessageReader.fireClose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79744:27)
    at Socket.<anonymous> (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79829:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
[Error - 上午9:47:04] Request textDocument/codeLens failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78880:27)
    at Object.dispose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:81031:35)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83382:42)
    at LanguageClient.handleConnectionClosed (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:87174:15)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:83369:18)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at closeHandler (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:78092:26)
    at CallbackList.invoke (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79010:39)
    at Emitter.fire (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79072:36)
    at StreamMessageReader.fireClose (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79744:27)
    at Socket.<anonymous> (c:\Users\Smile_xia\.vscode\extensions\golang.go-nightly-2021.6.715\dist\goMain.js:79829:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)

**Comment by findleyr** [comment] 2021-06-08 02:02
Thanks, we'll look into this.

**Closed** 2021-06-08 16:07 UTC
