### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by nazip** [golang/vscode-go#711] opened 2020-09-30 13:33 UTC
gopls version: v0.5.0
gopls flags: -rpc.trace serve --debug=localhost:6060

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 114 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x231
golang.org/x/tools/internal/lsp/debug.section(0xf135e0, 0xc000412ea0, 0x0, 0xd9eaa3, 0x7, 0xc000400ec8)
	  info.go:69  0x319
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xf28a60, 0xc000386640, 0xf135e0, 0xc000412ea0, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc00024c5a0, 0xf28a60, 0xc000386640, 0xc0003ee000, 0x0, 0x0, 0x0)
	  general.go:87  0x463
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc00024c5a0, 0xf28a60, 0xc000386640, 0xc0003ee000, 0xc0003ee000, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xf28a60, 0xc000386640, 0xf47f60, 0xc00024c5a0, 0xc000366ea0, 0xf28ca0, 0xc0003865c0, 0x0, 0x0, 0x0)
	  tsserver.go:235  0x7fe
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xf28a60, 0xc000386640, 0xc000366ea0, 0xf28ca0, 0xc0003865c0, 0x0, 0xbfd54022b22dab62)
	  protocol.go:63  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xf28a60, 0xc000386640, 0xc000366ea0, 0xf28ca0, 0xc0003865c0, 0x0, 0x0)
	  lsprpc.go:557  0x44c
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xf28a60, 0xc000386640, 0xc000373040, 0xf28ca0, 0xc0003865c0, 0x0, 0x0)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0001bf1a0, 0xc000381650, 0xc0002a18c0, 0xf28a60, 0xc000386640, 0xc000373040, 0xf28ca0, 0xc0003865c0)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Error - 4:32:58 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2020-09-30 13:38
@nazip thanks for the report. This is a duplicate of https://github.com/golang/vscode-go/issues/707#issuecomment-701393791 

Please follow the workaround for now.

**Closed by hyangah** 2020-09-30 13:38 UTC
