### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by novaku** [golang/vscode-go#921] opened 2020-11-14 07:49 UTC
gopls version: v0.5.3
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0xcf6b25]

goroutine 117 [running]:
golang.org/x/tools/internal/lsp/source/completion.(*completer).deepSearch(0xc000154780, 0x1092620, 0xc006894d80)
	  deep_completion.go:136  0x1125
golang.org/x/tools/internal/lsp/source/completion.Completion(0x1092620, 0xc006894d80, 0x10a4980, 0xc0048e3ad0, 0x1092860, 0xc0048fe120, 0x402a000000000000, 0x403e000000000000, 0x3ff0000000000000, 0x0, ...)
	  completion.go:552  0xcd4
golang.org/x/tools/internal/lsp.(*Server).completion(0xc00022a000, 0x10925a0, 0xc0000c07c0, 0xc005beb8c0, 0x0, 0x0, 0x0)
	  completion.go:31  0xe8c
golang.org/x/tools/internal/lsp.(*Server).Completion(0xc00022a000, 0x10925a0, 0xc0000c07c0, 0xc005beb8c0, 0xc005beb8c0, 0x0, 0x0)
	  server_gen.go:24  0x50
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x10925a0, 0xc0000c07c0, 0x10a6f20, 0xc00022a000, 0xc00631a660, 0x10927e0, 0xc0000c0580, 0x0, 0x107fd40, 0xc001574e70)
	  tsserver.go:285  0x22c2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x10925a0, 0xc0000c07c0, 0xc00631a660, 0x10927e0, 0xc0000c0580, 0x624efd9d, 0x14ecd40)
	  protocol.go:63  0xc7
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x10925a0, 0xc0000c07c0, 0xc00631a660, 0x10927e0, 0xc0000c0580, 0x0, 0x0)
	  lsprpc.go:559  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x10925a0, 0xc0000c07c0, 0xc000314ac0, 0x10927e0, 0xc0000c0580, 0x0, 0x0)
	  handler.go:35  0xda
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0000383c0, 0xc0004dec00, 0xc000818180, 0x10925a0, 0xc0000c07c0, 0xc000314ac0, 0x10927e0, 0xc0000c0580)
	  handler.go:103  0x8d
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x179
[Error - 2:48:57 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment] 2020-11-14 17:46
Duplicate of https://github.com/golang/vscode-go/issues/923

**Closed by stamblerre** 2020-11-14 17:46 UTC
