### ISSUE TITLE
Extension host terminated unexpectedly on the macOS Catalina

### ISSUE THREAD

**Issue by zhanswift** [golang/vscode-go#473] opened 2020-08-05 04:52 UTC
- Run `go version` to get version of Go
	- go1.13.5 darwin/amd64
- Check your installed extensions to get the version of the VS Code Go extension 
	- v0.16.0
- Run `go env` to get the go development environment details
	- GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/username/Library/Caches/go-build"
GOENV="/Users/username/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/username/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/12/j4y4gb956nn5nsx471vz78yh0000gn/T/go-build629689818=/tmp/go-build -gno-record-gcc-switches -fno-common"

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

> {
>     "go.lintTool": "golint",
>     "go.lintFlags": [
> 	    "--exclude=\"\bexported \\w+ (\\S*['.]*)([a-zA-Z'.*]*) should have comment or be unexported\b\""
>     ]
> }

### Describe the bug
Happens by itself

### Steps to reproduce the behavior:
1. Make change
2. Save change
3. See error

### Screenshots or recordings
<img width="672" alt="Screen Shot 2020-08-04 at 11 21 36 PM" src="https://user-images.githubusercontent.com/16617536/89373069-5ad7cd80-d6ad-11ea-8f66-f87cc231b121.png">

**Comment by jarsj** [comment] 2020-08-05 08:28
Facing the exact problem since couple of days.

**Comment by Lumexralph** [comment] 2020-08-05 09:54
I am currently facing same issue.

**Comment by hyangah** [comment] 2020-08-05 13:19
Duplicate of https://github.com/golang/vscode-go/issues/469

**Closed by hyangah** 2020-08-05 13:19 UTC
