### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by potato-panda-express** [golang/vscode-go#2718] opened 2023-04-01 07:15 UTC
gopls version: v0.11.0 (go1.20.2)
gopls flags: --cache-style=always
update flags: proxy
extension version: 0.38.0
go version: 1.20.2
environment: Visual Studio Code darwin
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Sat, 01 Apr 2023 07:15:11 GMT
restart history:
Sat, 01 Apr 2023 07:07:18 GMT: activation (enabled: true)
Sat, 01 Apr 2023 07:15:00 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2023-04-03 17:03
Dupe of #2717.

**Closed by findleyr** 2023-04-03 17:03 UTC
