### ISSUE TITLE
High memory usage for gopls

### ISSUE THREAD

**Issue by ptrinh** [golang/vscode-go#1859] opened 2021-10-27 15:07 UTC
Issue Type: <b>Performance Issue</b>

2.9 GB

Extension version: 0.28.1
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 5, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id acd1f8c1-0897-497f-ad80-02fedf666ed1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	   115	  7487	code main
    1	    49	  7514	   gpu-process
    0	    16	  7518	   utility
    0	   229	  7521	   window (paysiclient.go — grab-id)
    0	    98	  7560	     extensionHost
    0	  1720	  7607	       /Users/ptrinh/gopath/bin/gopls -mode=stdio
    0	    16	  7632	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=7560
    0	    33	  7565	     watcherService
    0	    98	  7559	   shared-process
    0	    16	  7561	     ptyHost
    0	     0	  8925	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    82	  8922	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (paysiclient.go — grab-id)
|    Folder (grab-id): 4396 files
|      File types: go(3670) sql(92) json(54) log(43) txt(20) md(10) sh(8)
|                  xml(7) html(7) gitignore(4)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by findleyr** [comment] 2021-11-18 18:34
Closing this as a dupe of golang/go#47855. We hope to improve gopls' memory usage in Q12022.

**Closed by findleyr** 2021-11-18 18:34 UTC
Labels: WaitingForInfo
