### ISSUE TITLE
gopls: automated issue report (crash): exec: "go": executable file not found in $PATH

### ISSUE THREAD

**Issue by andrewrynhard** [golang/vscode-go#716] opened 2020-09-30 18:46 UTC
gopls version: v0.5.0
gopls flags: 

Describe what you observed.

Go is definitely in my `PATH`, but I get :

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 93 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x22e
golang.org/x/tools/internal/lsp/debug.section(0xed12a0, 0xc0003fa9f0, 0x0, 0xd571db, 0x7, 0xc0003e6f18)
	  info.go:69  0x319
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xee5240, 0xc000325440, 0xed12a0, 0xc0003fa9f0, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc000226460, 0xee5240, 0xc000325440, 0xc000154c00, 0x0, 0x0, 0x0)
	  general.go:87  0x58b
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc000226460, 0xee5240, 0xc000325440, 0xc000154c00, 0xc000154c00, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xee5240, 0xc000325440, 0xf003c0, 0xc000226460, 0xc0003d2a20, 0xee5480, 0xc0003253c0, 0x0, 0x0, 0x0)
	  tsserver.go:235  0x4bb
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xee5240, 0xc000325440, 0xc0003d2a20, 0xee5480, 0xc0003253c0, 0x0, 0xbfd5526ec26afbc5)
	  protocol.go:63  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xee5240, 0xc000325440, 0xc0003d2a20, 0xee5480, 0xc0003253c0, 0x0, 0x0)
	  lsprpc.go:557  0x420
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xee5240, 0xc000325440, 0xc00032ab40, 0xee5480, 0xc0003253c0, 0x0, 0x0)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00020d0e0, 0xc000352330, 0xc00027d510, 0xee5240, 0xc000325440, 0xc00032ab40, 0xee5480, 0xc0003253c0)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Info  - 11:45:15 AM] </pre>

**Comment by hyangah** [comment] 2020-09-30 19:21
@andrewrynhard  Thanks for reporting the issue. This is a duplicate of #713.
Please try https://github.com/golang/vscode-go/releases/tag/v0.17.2-rc.1 to see if it fixes the issue.
Or try one of the workarounds described in the issue.

**Closed** 2020-09-30 19:27 UTC
