### ISSUE TITLE
slow search - when go plugin installed, the search funtionality of vs code become unusable in large projects.

### ISSUE THREAD

**Issue by EdgarLip** [golang/vscode-go#3355] opened 2024-04-22 06:44 UTC
$ go version
go version go1.22.1 windows/amd64

vs code:
Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19044

$ gopls -v version
Build info
----------
golang.org/x/tools/gopls v0.15.3
    golang.org/x/tools/gopls@v0.15.3 h1:zbdOidFrPTc8Bx0YrN5QKgJ0zCjyGi0L27sKQ/bDG5o=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.6.0 h1:ofyhxvXcZhMsU5ulbFiLKl/XBFqE1GSq7atu8tAmTRI=
    golang.org/x/exp/typeparams@v0.0.0-20221212164502-fae10dda9338 h1:2O2DON6y3XMJiQRAS1UWU+54aec2uopH3x7MAiqGW6Y=
    golang.org/x/mod@v0.15.0 h1:SernR4v+D55NyBH2QiEQrlBAnj1ECL6AGrA5+dPaMY8=
    golang.org/x/sync@v0.6.0 h1:5BMeUDZ7vkXGfEr1x9B4bRcTH4lpkTkpdh0T/J+qjbQ=
    golang.org/x/sys@v0.17.0 h1:25cE3gD+tdBA7lp7QfhuV+rJiE9YXTcS3VG1SqssI/Y=
    golang.org/x/telemetry@v0.0.0-20240209200032-7b892fcb8a78 h1:vcVnuftN4J4UKLRcgetjzfU9FjjgXUUYUc3JhFplgV4=     
    golang.org/x/text@v0.14.0 h1:ScX5w1eTa3QqT8oi6+ziP7dTV1S2+ALU0bI+0zXKWiQ=
    golang.org/x/tools@v0.18.1-0.20240412183611-d92ae0781217 h1:uH9jJYgeLCvblH0S+03kFO0qUDxRkbLRLFiKVVDl7ak=      
    golang.org/x/vuln@v1.0.1 h1:KUas02EjQK5LTuIx1OylBQdKKZ9jeugs+HiqO5HormU=
    honnef.co/go/tools@v0.4.6 h1:oFEHCKeID7to/3autwsWfnuv69j3NsfcXbvJKuIcep8=
    mvdan.cc/gofumpt@v0.6.0 h1:G3QvahNDmpD+Aek/bNOLrFR2XC6ZAdo62dZu65gmwGo=
    mvdan.cc/xurls/v2@v2.5.0 h1:lyBNOm8Wo71UknhUs4QTFUNNMyxy2JEIaKKo0RWOh+8=
go: go1.22.1

$ code -v
1.88.1
e170252f762678dec6ca2cc69aba1570769a5d39
x64

setting: 
( the only thing that it is related to go that i have found) 
1) 
	// If this setting is false, no telemetry will be sent regardless of the new setting's value. Deprecated in favor of the `telemetry.telemetryLevel` setting.
	// Enable diagnostic data to be collected. This helps us to better understand how Visual Studio Code is performing and where improvements need to be made. [Read more](https://go.microsoft.com/fwlink/?LinkId=521839) about what we collect and our privacy statement.
	"telemetry.enableTelemetry": true,

    "go.alternateTools": {
                                                          < ------ this is empty ....  C:\Users\<my name>\AppData\Roaming\Code\User\settings.json
    }

golang.go

### Describe the bug
The bug : 
1) installing the the go addon.
2) ctr + shift+f 
3) seach for some thing e.g:  "copy system clock" 
    it can take few minutes 
  
1)expect it to find it under 3 seconds ! 
   which is what happends when i remove the go plugin and restart.

![image](https://github.com/golang/vscode-go/assets/52099499/6ac2a1d3-e3f8-4211-9e9c-e6ae0c1f300d)
this seach can take more then 3 minutes - which is unacceptable, when without the plugin it take 3 seconds max.

**Comment by hyangah** [comment] 2024-04-22 14:55
@EdgarLip Since the "Search" functionality does not directly interact with this extension or its tools, we need more info for triage.

* Run  `Developer: Open Process Explorer` from Command Palette.  Do the extensionHost and gopls consume much cpu/memory?

* Enable gopls logging by adding this to your settings.json. `"go.languageServerFlags": ["-rpc.trace"]` 
   Then, open the "gopls" output channel (`Output: Show Output Channel` -> select 'gopls (server)' from the drop down). Run search. Do you see a lot of disc scanning activities or error messages?
   
* Are you running antivirus programs? If you disable the programs, or allowlist `go` and `gopls`, do you see any changes in performance?

**Comment by EdgarLip** [comment] 2024-04-23 12:31
Hi @hyangah 
thanks for taking this one ! 

• here is a snippet of the process explorer during very long search : 
![image](https://github.com/golang/vscode-go/assets/52099499/c8a86eb6-2631-453e-9c31-738621b09778)

• added the flag:
![image](https://github.com/golang/vscode-go/assets/52099499/4d22905f-1f90-4ace-b9e0-75872e32b3e1)
restarted few times "vscode" ... but i do not see the 'gopls (server)'  in the drop down list.

•added go to be allowed by the FW: 
![image](https://github.com/golang/vscode-go/assets/52099499/f02e7d1a-cbb8-4e0b-a549-1ee2edea8724)
again restart everything just in case ... no change... 
i do not know how to add gopls.

**Comment by hyangah** [comment] 2024-04-23 17:30
Thanks for sharing the screenshots. I don't see anything obvious unfortunately.
From the process explorer, I guess `extensionHost[3]` is the one corresponding to the window with go files since that's the only one with `gopls` process. That process and its children consumes 0% of CPU. Memory usage is also not too high. In fact, other VS Code processes seem also idle. 

* Have you looked into the window's process monitor?
* Is the problem present when all other extensions are disabled and only golang.go extension is activated?
* The gopls trace is in the OUTPUT tab (bottom window in the standard layout). Can you share the trace?

<img width="545" alt="Screenshot 2024-04-23 at 1 26 58 PM" src="https://github.com/golang/vscode-go/assets/4999471/0cb839f9-266b-4dc5-a9c0-18a837b91d6a">

**Comment by EdgarLip** [comment] 2024-04-24 07:36
1)i have successfully added the gopls to the FW exceptions as well : 
   which in my case located : C:\Users\<name>\go\bin\gopls.exe 
![image](https://github.com/golang/vscode-go/assets/52099499/2b9350ca-f34a-437a-a1b1-df09fc563f89)


2) i have disable and even uninstalled all plugins , and even when go is the only one installed - this is happening. 
    i will not recreate it right now to show ... since it took so much of my time. 

3) here is how the search looks like for the windows task explorer, during search is running: 
![image](https://github.com/golang/vscode-go/assets/52099499/23731b79-960d-47c2-a325-3f241ccc3474)

4) after playing long time with the searches and with the file explorer ( and after excluding the gopls - from the FW 
    as mentioned above ), it looks the issue is now not persistent as was previously, but happens only when 
     "microsoft defender antibvirus service" service is at it's peak ( don't know what it's doing )
![image](https://github.com/golang/vscode-go/assets/52099499/d1725fb9-9ca2-4be9-95dc-1e7b7b343692)
then search is slow. 

WDYT ?

**Comment by hyangah** [comment] 2024-04-30 01:01
Thanks for the detailed info and screenshot. 

>  it looks the issue is now not persistent as was previously, but happens only when
"microsoft defender antibvirus service" service is at it's peak

It looks like the issue is the Antivirus software.

Microsoft Defender Antivirus Service is the anti-virus software. I don't know exactly what it is doing, but there are many reports in the internet that talk about slowness caused by Microsoft Defender. See https://groups.google.com/g/golang-nuts/c/IR8v3B1pPCI/m/-yrCL_j0HAAJhttps://groups.google.com/g/golang-nuts/c/IR8v3B1pPCI/m/-yrCL_j0HAAJ

Try to adjust exclusion rules to skip files in the directories used by the go command and gopls:

https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26
 or
https://www.dell.com/support/kbdoc/en-us/000128249/windows-defender-resolving-high-hard-disk-drive-and-cpu-usage-during-scans

For example, configure the anti-virus scanner to skip directories reported by
  `go env GOMODCACHE GOBUILDCACHE`
and the `CacheDir` directory reported by `gopls.exe stats`. 

Since the issue is not the extension's issue but requires the antivirus software configuration, I will close the issue.

**Closed by hyangah** 2024-04-30 01:01 UTC
Labels: WaitingForInfo
