### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by romanb52** [golang/vscode-go#2904] opened 2023-08-01 08:54 UTC
gopls version: v0.13.0 (go1.20.6)
gopls flags: 
update flags: proxy
extension version: 0.39.1
go version: 1.20.6
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Tue, 01 Aug 2023 08:54:15 GMT
restart history:
Sun, 30 Jul 2023 15:32:26 GMT: activation (enabled: true)
Mon, 31 Jul 2023 15:52:22 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: index out of range [1] with length 1

goroutine 81 [running]:
go/types.(*Tuple).At(...)
	  tuple.go:31
golang.org/x/tools/gopls/internal/lsp/analysis/stubmethods.fromCallExpr(0x140007253c0, 0x1400024eaa0, 0x462, 0x1400162b800)
	  stubmethods.go:177  0x384
golang.org/x/tools/gopls/internal/lsp/analysis/stubmethods.GetStubInfo(0x14000254360%3F, 0x462%3F, {0x14000857000%3F, 0xf, 0x10}, 0x101558d00%3F)
	  stubmethods.go:141  0xb0
golang.org/x/tools/gopls/internal/lsp/analysis/stubmethods.DiagnosticForError(0x14000238cb0%3F, 0x140004feea0%3F, 0x462, 0x468, {0x14000a95700%3F, 0x3a%3F}, 0x1400163c2c0%3F)
	  stubmethods.go:85  0x88
golang.org/x/tools/gopls/internal/lsp.(*Server).codeAction(0x140001e4d20%3F, {0x101592900%3F, 0x1400029ca00%3F}, 0x140001e4d20)
	  code_action.go:206  0xee8
golang.org/x/tools/gopls/internal/lsp.(*Server).CodeAction(0x14000256000%3F, {0x101592900%3F, 0x1400029ca00%3F}, 0x1014132a0%3F)
	  server_gen.go:16  0x24
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch({0x101592900, 0x1400029ca00}, {0x1015a2428, 0x1400040eee0}, 0x14000338c90, {0x101592bd8, 0x140004fa4c0})
	  tsserver.go:239  0x18cc
golang.org/x/tools/gopls/internal/lsp/protocol.ServerHandler.func1({0x101592900, 0x1400029ca00}, 0x14000338c90, {0x101592bd8, 0x140004fa4c0})
	  protocol.go:157  0x6c
golang.org/x/tools/gopls/internal/lsp/lsprpc.handshaker.func1({0x101592900, 0x1400029ca00}, 0x14000338c90, {0x101592bd8%3F, 0x140004fa4c0%3F})
	  lsprpc.go:519  0x768
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x101592900, 0x1400029ca00}, 0x140004ad7d0, {0x101592bd8%3F, 0x140004fa4c0%3F})
	  handler.go:35  0xf0
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0x90
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x1dc
[Error - 10:54:03] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2023-08-01 12:26
Thanks very much for reporting this crash. This is a dupe of golang/go#61693. We'll fix this and hopefully release v0.13.1 later today. Sorry for the breakage.

**Closed by findleyr** 2023-08-01 12:26 UTC
