### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by vominhtri1049** [golang/vscode-go#737] opened 2020-10-02 14:42 UTC
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 99 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x233
golang.org/x/tools/internal/lsp/debug.section(0x1ac8300, 0xc0000a9fb0, 0x0, 0x199a7ab, 0x7, 0xc0000d0f28)
	  info.go:69  0x322
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0x1adc3c0, 0xc000431e80, 0x1ac8300, 0xc0000a9fb0, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc000412d20, 0x1adc3c0, 0xc000431e80, 0xc0000aa000, 0x0, 0x0, 0x0)
	  general.go:87  0x585
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc000412d20, 0x1adc3c0, 0xc000431e80, 0xc0000aa000, 0xc0000aa000, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1adc3c0, 0xc000431e80, 0x1af02c0, 0xc000412d20, 0xc0000a8000, 0x1adc600, 0xc000431e00, 0x0, 0x1ac9c40, 0xc00009e000)
	  tsserver.go:235  0x4d2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1adc3c0, 0xc000431e80, 0xc0000a8000, 0x1adc600, 0xc000431e00, 0x197801b, 0x1f34aa0)
	  protocol.go:63  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1adc3c0, 0xc000431e80, 0xc0000a8000, 0x1adc600, 0xc000431e00, 0x0, 0x0)
	  lsprpc.go:557  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1adc3c0, 0xc000431e80, 0xc00042d1e0, 0x1adc600, 0xc000431e00, 0x0, 0x0)
	  handler.go:35  0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc000183680, 0xc00043d8c0, 0xc00043a360, 0x1adc3c0, 0xc000431e80, 0xc00042d1e0, 0x1adc600, 0xc000431e00)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 9:42:19 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2020-10-02 14:50
@vominhtri1049 Do you still see the issue with the latest version of the extension (0.17.2)? 

There was a regression caused by 0.17.1 which should be fixed with the new version. (See #713)

**Closed** 2020-11-02 14:52 UTC
Labels: WaitingForInfo
