### ISSUE TITLE
 gopls client: couldn't create connection to server.   

### ISSUE THREAD

**Issue by devashishRaj** [golang/vscode-go#3039] opened 2023-11-09 14:20 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- <go version go1.21.4 darwin/arm64>
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <gopls -v version
	- [1]    54207 killed     gopls -v version>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- <1.84.1 arm64>
* Check your installed extensions to get the version of the VS Code Go extension
	- <v0.39.1>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/devashishraj/go
GOROOT: /opt/homebrew/Cellar/go/1.21.4/libexec
PATH: /opt/homebrew/opt/qt@5/bin:/opt/homebrew/opt/gnu-time/libexec/gnubin:/Users/devashishraj/go/bin:/Users/devashishraj/.cargo/bin:/opt/homebrew/opt/ruby/bin/ruby:/Users/devashishraj/bashNzshcripts/zsh_Scripts:/Users/devashishraj:/opt/homebrew/opt/llvm/bin:/Users/devashishraj/bin:/usr/local/bin:/opt/homebrew/Caskroom/mambaforge/base/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion.app/Contents/Public:/opt/homebrew/opt/fzf/bin

	go:	/opt/homebrew/bin/go: go version go1.21.4 darwin/arm64

	gotests:	not installed
	gomodifytags:	not installed
	impl:	not installed
	goplay:	not installed
	dlv:	/Users/devashishraj/go/bin/dlv	(version: v1.21.0 built with go: go1.21.0)
	golangci-lint:	/Users/devashishraj/go/bin/golangci-lint	(version: v1.54.1 built with go: go1.21.0)
	gopls:	/Users/devashishraj/go/bin/gopls	(version: v0.12.2 built with go: go1.21.4)

go env
Workspace Folder (gobyTest): /Users/devashishraj/myRepos/gobyTest
	GO111MODULE='auto'
	GOARCH='arm64'
	GOBIN=''
	GOCACHE='/Users/devashishraj/Library/Caches/go-build'
	GOENV='/Users/devashishraj/Library/Application Support/go/env'
	GOEXE=''
	GOEXPERIMENT=''
	GOFLAGS=''
	GOHOSTARCH='arm64'
	GOHOSTOS='darwin'
	GOINSECURE=''
	GOMODCACHE='/Users/devashishraj/go/pkg/mod'
	GONOPROXY=''
	GONOSUMDB=''
	GOOS='darwin'
	GOPATH='/Users/devashishraj/go'
	GOPRIVATE=''
	GOPROXY='https://proxy.golang.org,direct'
	GOROOT='/opt/homebrew/Cellar/go/1.21.4/libexec'
	GOSUMDB='sum.golang.org'
	GOTMPDIR=''
	GOTOOLCHAIN='auto'
	GOTOOLDIR='/opt/homebrew/Cellar/go/1.21.4/libexec/pkg/tool/darwin_arm64'
	GOVCS=''
	GOVERSION='go1.21.4'
	GCCGO='gccgo'
	AR='llvm-ar'
	CC='clang'
	CXX='clang++'
	CGO_ENABLED='1'
	GOMOD=''
	GOWORK=''
	CGO_CFLAGS='-O2 -g'
	CGO_CPPFLAGS=''
	CGO_CXXFLAGS='-O2 -g'
	CGO_FFLAGS='-O2 -g'
	CGO_LDFLAGS='-O2 -g'
	PKG_CONFIG='pkg-config'
	GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/g5/cd3mv8z10z950tldc1rwknb40000gn/T/go-build6886368=/tmp/go-build -gno-record-gcc-switches -fno-common'>

```
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```
"go.addTags": {
        "transform": "camelcase"
    },
    "go.vetOnSave": "workspace",
    "go.trace.server": "messages",
    "go.toolsManagement.checkForUpdates": "local",
    "go.logging.level": "info",
   "go.lintOnSave": "workspace",
    "go.toolsManagement.autoUpdate": true,
    "go.testExplorer.showDynamicSubtestsInEditor": true,
    "go.lintTool": "golangci-lint",
    "go.inlayHints.rangeVariableTypes": true,
    "go.testExplorer.alwaysRunBenchmarks": true,

```

### Describe the bug
```
[Info  - 19:32:16] 
true
[Error - 19:32:16] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 19:32:16] The gopls server failed to initialize.
[Error - 19:32:16] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error starting language server: Error: Pending response rejected since connection got disposed
```
### Steps to reproduce the behavior:
open any go workspace or go file 
<img width="1352" alt="Screenshot 2023-11-09 at 7 44 05 PM" src="https://github.com/golang/vscode-go/assets/29112354/c32802a1-c149-423d-9c21-60ae93ce3459">

run any go file using go run in terminal window within vscode or press when any linting happens. error will pop up

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by findleyr** [comment] 2023-11-09 15:16
Possibly related: golang/go#63997.

Can you try signing the binary? `codesign -f -s - $(which gopls)`

**Comment by devashishRaj** [comment] 2023-11-09 15:27
Oh , i was in a hurry so tired to delete the binary from go/bin and then installed gopls via homebrew and it solved the issue.

But I'll revert back later to see the signing it or reverting to older version works or not.

**Comment by fatpa** [comment] 2023-11-10 03:49
> codesign -f -s - $(which gopls)

This can work on go 1.21.4 with MacOS 14.2 Beta2.

**Comment by findleyr** [comment] 2023-11-10 13:26
@fatpa it should not be necessary to sign the gopls binary. I'm trying to figure out why this is happening for some people (see also https://github.com/golang/go/issues/63997).

**Comment by fatpa** [comment] 2023-11-10 13:31
> @devashishRaj @fatpa are you on arm64?

Yes, m2 chip

**Comment by johnwangzhcn** [comment] 2023-11-17 15:58
I encountered a similar issue. My computer's processor is an Apple M1, running MacOS 14.1.1 (23B81), with Go SDK version 1.21.4. I'm using VSCode version 1.84.2 with Go for Visual Studio Code plugin version v0.40.0. After updating gopls to v0.14.2, I started experiencing this issue. I can confirm that everything was normal before updating gopls. The gopls (server) displays the following information:

[Info  - 23:48:58] 
true
[Error - 23:48:58] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 23:48:58] The gopls server failed to initialize.
[Error - 23:48:58] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error starting language server: Error: Pending response rejected since connection got disposedFailed to stop client: Error: Client is not running and can't be stopped. It's current state is: startFailed
[Info  - 23:49:05] 
true
[Error - 23:49:05] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 23:49:05] The gopls server failed to initialize.
[Error - 23:49:05] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error starting language server: Error: Pending response rejected since connection got disposedFailed to stop client: Error: Client is not running and can't be stopped. It's current state is: startFailed
[Info  - 23:49:13] 
true
[Error - 23:49:13] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 23:49:13] The gopls server failed to initialize.
[Error - 23:49:13] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error starting language server: Error: Pending response rejected since connection got disposed

**Comment by findleyr** [comment] 2023-11-17 16:15
@johnwangzhcn can you please try `codesign -f -s - $(which gopls)`? If that fixes the problem, then you are also experiencing https://github.com/golang/go/issues/63997.

**Comment by johnwangzhcn** [comment] 2023-11-18 09:53
> @johnwangzhcn can you please try `codesign -f -s - $(which gopls)`? If that fixes the problem, then you are also experiencing [golang/go#63997](https://github.com/golang/go/issues/63997).你可以试试 `codesign -f -s - $(which gopls)` 吗？如果这解决了问题，那么您也遇到了 golang/go#63997。

Yes, my problem was solved after I tried to execute the command. Thank you.

**Comment by devashishRaj** [comment] 2023-11-18 16:10
> @johnwangzhcn can you please try `codesign -f -s - $(which gopls)`? If that fixes the problem, then you are also experiencing [golang/go#63997](https://github.com/golang/go/issues/63997).

yeah this one fixed on mine too .

**Comment by findleyr** [comment] 2023-11-29 17:19
Closing as a dupe of https://github.com/golang/go/issues/63997.

**Closed by findleyr** 2023-11-29 17:19 UTC
Labels: WaitingForInfo
