### ISSUE TITLE
More output when it fails to connect to debug adapter

### ISSUE THREAD

**Issue by YarikRevich** [golang/vscode-go#2017] opened 2022-01-15 07:48 UTC
**Problem**
Using legacy debug adapter I met some problem. Trying to run debug session I always met problem "connect ECONNREFUSED...", so it took me some time so solve it, because there was not explicit information about used debug adapter, or any information about executable file which was used

**Solution**
I consider, It'd be better to show information about used adapter and the executable which was run as a debug adapter for debug session

**Comment by hyangah** [comment] 2022-01-18 14:21
Have you tried to enable tracing and logging to see the details?
What was the root cause of the issue you encountered, and what more info would be useful to spot the root cause?

FYI legacy debug adapter is in maintenance mode so it's unlikely we will look into this issue any further.

**Comment by hyangah** [comment] 2022-02-15 01:00
Closing since there is no planned work to add more features to the legacy debug adapter.

**Closed by hyangah** 2022-02-15 01:00 UTC
Labels: Debug, WaitingForInfo
