### ISSUE TITLE
gopls: automated issue report (crash) [panic: slice out of bounds, v0.15.3/go1.22.2]

### ISSUE THREAD

**Issue by rusq** [golang/vscode-go#3352] opened 2024-04-20 05:02 UTC
Hey team, I tried to add as much information as I could, but please let me know if any additional diag is needed.

## Reproduce

1. Install [goyacc](https://pkg.go.dev/golang.org/x/tools/cmd/goyacc)

       go install golang.org/x/tools/cmd/goyacc@latest

2. Run the following command to generate y.go and y.output

       goyacc slacktime.y

3. Open "y.go" file in VSCode.
4. Observe the Gopls crash.

To confirm:
1. Restart the Gopls server
2. It crashes again

## Notes

`slacktime.y` is C version of the grammar file, so "y.go" will not work straight away.  I was just planning to adapt it to Goyacc, but ran into this issue.  I suspect it is similar to #3351 which was recently opened as well. 

I'm attaching an archive of the project files.  There's no sensitive information, it's just an experimental code.
-  the gopls log is in `gopls.log`.
- the reproduction steps are duplicated in REPRODUCE.md, should you need them
- `generate-y.go.sh` contains the command to generate y.go, should it be required.
- "slacktime.l" has nothing to do with this, just there for completeness.
- I have not included irrelevant slacktime.h files nor the implementation of functions handle_slacktime, which is irrelevant and would only add entropy, but can share them as well if needed.

HERE WE GO: 
[gopls-issue-project.tar.gz](https://github.com/golang/vscode-go/files/15046900/gopls-issue-project.tar.gz)

Thank you, and please let me know if anything else is required?

## Orignial Report
gopls version: v0.15.3/go1.22.2
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Sat, 20 Apr 2024 04:36:43 GMT
restart history:
Sat, 20 Apr 2024 04:35:52 GMT: activation (enabled: true)
Sat, 20 Apr 2024 04:36:42 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

> [!IMPORTANT]
> I have opened the y.go file from the attached archive.  Y.go file is the go file generated by [goyacc](https://pkg.go.dev/golang.org/x/tools/cmd/goyacc) tool.  See [Reproduce](#reproduce) above.

<pre>panic: runtime error: slice bounds out of range [3:2]

goroutine 125 [running]:
golang.org/x/tools/gopls/internal/protocol.(*Mapper).LineCol8Position(0xc0001d0f00, 0x2, 0x0)
	  mapper.go:151  0x1a5
golang.org/x/tools/gopls/internal/cache.goPackagesErrorDiagnostics.func1({{0xc000240c40, 0xd}, {0xc000800280, 0x1c}, 0x1}, 0x1c%3F, {0x676e900, 0xc0001abb00}, {0x6776d00, 0xc00060a0f0})
	  errors.go:58  0x145
golang.org/x/tools/gopls/internal/cache.goPackagesErrorDiagnostics({0x6776d00, 0xc00060a0f0}, {{0xc000240c40, 0xd}, {0xc000800280, 0x1c}, 0x1}, 0xc000346100, {0x676e900, 0xc0001abb00})
	  errors.go:69  0xf5
golang.org/x/tools/gopls/internal/cache.computeLoadDiagnostics({0x6776d00, 0xc00060a0f0}, 0xc0001abb00, 0xc000346100)
	  load.go:541  0x185
golang.org/x/tools/gopls/internal/cache.(*packageHandleBuilder).buildPackageHandle(0xc000230140, {0x6776d00, 0xc00060a0f0}, 0xc00060a0a0)
	  check.go:1129  0x2b7
golang.org/x/tools/gopls/internal/cache.(*Snapshot).getPackageHandles.func2.1()
	  check.go:932  0xce
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 179
	  errgroup.go:75  0x96
</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 136 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

**Comment by rusq** [comment] 2024-04-20 05:06
Probably this should have been opened in gopls issue, but I blame extension for opening this page when I pressed "report"!

**Comment by rusq** [comment] 2024-04-20 05:14
I have tested with the previous versions, here are my results:

| version | Works? |
| --- | --- |
| v0.14.2 | ✅ |
| v0.15.0 | ❌|
| v0.15.1 | ❌ |
| v0.15.2 | ❌ |

**Comment by findleyr** [comment] 2024-04-22 14:22
Thank you for the reproducer and detailed report. This looks like a dupe of golang/go#66875, so I'll close it in favor of that issue.

The reproducer will make this much easier to fix.

**Closed** 2024-04-22 14:23 UTC
