### ISSUE TITLE
gopls: panic with invalid Go version 

### ISSUE THREAD

**Issue by wevertonrs** [golang/vscode-go#3276] opened 2024-03-22 22:38 UTC
gopls version: v0.15.2/go1.20.4
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Fri, 22 Mar 2024 22:38:21 GMT
restart history:
Fri, 22 Mar 2024 22:37:29 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.1" (should be something like "go1.12")

goroutine 624 [running]:
go/types.NewChecker(0x0%3F, 0xc0011400c0, 0xc0017ce7d0, 0x0%3F)
	C:/Program   check.go:237  0x24e
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc000afa0b0, {0xc00000aa28, 0x1, 0x1})
	  analysis.go:1028  0x73d
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc000afa0b0, {0x1db9438%3F, 0xc00061d050})
	  analysis.go:810  0x218
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc000afa0b0, {0x1db9438%3F, 0xc00061d050})
	  analysis.go:672  0x145
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xda
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 34,
    "TestdataFiles": 0,
    "GoFiles": 5,
    "ModFiles": 1,
    "Dirs": 20
  },
  "GOARCH": "amd64",
  "GOOS": "windows",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.20.4",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "4.0224353s",
  "MemStats": {
    "HeapAlloc": 8825880,
    "HeapInUse": 16572416,
    "TotalAlloc": 98190112
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 493,
      "Largest": 210104,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.1",
        "AllPackages": {
          "Packages": 67,
          "LargestPackage": 148,
          "CompiledGoFiles": 491,
          "Modules": 1
        },
        "WorkspacePackages": {
          "Packages": 5,
          "LargestPackage": 2,
          "CompiledGoFiles": 6,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment] 2024-03-25 21:48
This was fixed in https://go.dev/cl/507975. To get this fix we recommend upgrading to go1.21 or later

**Comment by Alfahan** [comment] 2024-03-26 00:08
Okey thanks!

**Comment by tvendelin** [comment] 2024-03-26 14:21
The error message says

```
panic: invalid Go version "go1.22.1" (should be something like "go1.12")
```

but this IS the current version, according to https://go.dev/doc/install , isn't it?
I've upgraded my Go today, and hitting this error every time I launch Neovim.

**Comment by suzmue** [comment] 2024-03-28 17:39
Can you try reinstalling gopls with the latest go

**Comment by tvendelin** [comment] 2024-04-02 12:56
@suzmue : Indeed, after installing `gopls` explicitly, the issue is gone. 
A few things that were confusing to me:

- I have just upgraded to the latest Go version and falsely assumed the upgraded `gopls` comes with it
- Your bug report form allows only a single line  for `gopls` version, so I've assumed that's all you want.

**Closed** 2024-04-16 19:13 UTC
Labels: WaitingForInfo
