### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by prakasa-tkpd** [golang/vscode-go#720] opened 2020-10-01 03:29 UTC
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 63 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x22e
golang.org/x/tools/internal/lsp/debug.section(0x1ad1660, 0xc00044c1b0, 0x0, 0x1956c58, 0x7, 0xc000434f18)
	  info.go:69  0x319
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0x1ae56c0, 0xc00009de00, 0x1ad1660, 0xc00044c1b0, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc0000c6320, 0x1ae56c0, 0xc00009de00, 0xc000424000, 0x0, 0x0, 0x0)
	  general.go:87  0x58b
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc0000c6320, 0x1ae56c0, 0xc00009de00, 0xc000424000, 0xc000424000, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1ae56c0, 0xc00009de00, 0x1b00b60, 0xc0000c6320, 0xc0004101e0, 0x1ae5900, 0xc00009dd80, 0x0, 0x0, 0x0)
	  tsserver.go:235  0x4bb
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1ae56c0, 0xc00009de00, 0xc0004101e0, 0x1ae5900, 0xc00009dd80, 0x0, 0xbfd5712797aa3a40)
	  protocol.go:63  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1ae56c0, 0xc00009de00, 0xc0004101e0, 0x1ae5900, 0xc00009dd80, 0x0, 0x0)
	  lsprpc.go:557  0x420
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1ae56c0, 0xc00009de00, 0xc0000e6320, 0x1ae5900, 0xc00009dd80, 0x100785f, 0xc0002001d8)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0000a0780, 0xc0000b2f60, 0xc000095070, 0x1ae56c0, 0xc00009de00, 0xc0000e6320, 0x1ae5900, 0xc00009dd80)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Error - 10:29:34 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2020-10-01 13:10
@prakasa-tkpd  thanks for the report. This is a duplicate of https://github.com/golang/vscode-go/issues/713.

**Closed by hyangah** 2020-10-01 13:10 UTC
