### ISSUE TITLE
Support Wire ()code generation

### ISSUE THREAD

**Issue by cylof22** [golang/vscode-go#2075] opened 2022-02-21 14:45 UTC
**Is your feature request related to a problem? Please describe.**
When use google's dependent injection library "Wire", the DI definition file "wire.go" will always see an error: "No packages found for open file **/wire.go: <nil>.". If add "go.buildFlags": ["-tags=wireinject"] to the .vscode/settings.json, the "wire_gen.go" will see the similar error:  No packages found for open file **/wire_gen.go: <nil>."

**Describe the solution you'd like**
I want the language server have an option to support the two "wire.go" and "wire_gen.go" together.

**Describe alternatives you've considered**
I have follow the server prompt to add buildFlags, but it does't fix my problem.

**Additional context**
Use the https://github.com/google/wire/tree/main/_tutorial to test.

**Comment by findleyr** [comment] 2022-03-03 22:27
As far as I can tell, this is very closely related to https://github.com/golang/go/issues/49104.

In general, gopls does not have the ability to support multiple sets of build tags simultaneously. As a result, we can't encode rules for various frameworks such as Wire or mage.

I'm not saying this isn't a problem, just that it will be fundamental to fix. Gopls uses the `go` command to list packages, and requires additional support from the Go command to build arbitrary packages in this way.

**Comment by findleyr** [comment] 2022-03-18 17:59
I'm going to close this as a dupe of #49104, which has the same underlying cause.

**Closed by findleyr** 2022-03-18 17:59 UTC
Labels: FeatureRequest
