### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by davidovich** [golang/vscode-go#2145] opened 2022-03-28 15:38 UTC
gopls version: v0.8.1 (go1.18)
gopls flags: 
update flags: proxy
extension version: 0.32.0
go version: 1.18
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Mon, 28 Mar 2022 15:20:03 GMT
restart history:
Mon, 28 Mar 2022 15:13:27 GMT: activation (enabled: true)
Mon, 28 Mar 2022 15:19:00 GMT: manual (enabled: true)
Mon, 28 Mar 2022 15:19:56 GMT: manual (enabled: true)

gopls crashes on a completely commented out content of `go.work`:

```
// go 1.18

// use (
//	.
//	../../[a-valid-module]/[path]
//)
```

The crash does not happen if I uncomment the `go 1.18` directive, but gopls does not find any code location - I have to delete the `go.work` file to make it work again.

If everything is uncommented, it works.

When the go.work file has comments, I get these kind of errors in the gopls (server) output:

```
[Error - 11:34:52 AM] 2022/03/28 11:34:52 errors loading workspace: err: exit status 1: stderr: go: no modules were found in the current workspace; see 'go help work'
: packages.Load error
```

Below is the automatically generated bug report trace:

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb76292]

goroutine 121 [running]:
golang.org/x/tools/internal/lsp/cache.parseGoWork({0x1001d20, 0xc0001fe360}, {0xc0002b4b70, 0x2c}, {0xc000572d40%3F, 0xc0005deec0%3F}, {0xc000340200, 0x3f, 0x200}, {0xffb4e0, ...})
	  workspace.go:508  0x232
golang.org/x/tools/internal/lsp/cache.loadExplicitWorkspaceFile({0x1001d20, 0xc0001fe360}, 0xc0002cd7a0, {0xffb4e0%3F, 0xc00044c180%3F})
	  workspace.go:152  0x1e6
golang.org/x/tools/internal/lsp/cache.newWorkspace({0x1001d20, 0xc0001fe360}, {0xc0002b4b70, 0x2c}, {0xffb4e0, 0xc00044c180}, 0xc0004553b0, 0x0, 0x0)
	  workspace.go:106  0xbb
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0xc00044c180, {0x1001d20, 0xc0001fe360}, {0xc000549cc0, 0xa}, {0xc000132000, 0x2c}, 0xc0005cc900, 0x0)
	  session.go:197  0x25d
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0xc00044c180, {0x1001d20, 0xc0001fe360}, {0xc000549cc0, 0xa}, {0xc000132000, 0x2c}, 0xc00044e0a0%3F)
	  session.go:166  0x287
golang.org/x/tools/internal/lsp.(*Server).addView(0xc0002ac6c0, {0x1001d20, 0xc0001fe360}, {0xc000549cc0, 0xa}, {0xc000132000, 0x2c})
	  workspace.go:42  0x1c7
golang.org/x/tools/internal/lsp.(*Server).addFolders(0xc0002ac6c0, {0x1001d20%3F, 0xc0001fe360}, {0xc0000e8000, 0x5, 0x1%3F})
	  general.go:234  0x6f5
golang.org/x/tools/internal/lsp.(*Server).initialized(0xc0002ac6c0, {0x1001d20, 0xc0001fe360}, 0xc0000d8090%3F)
	  general.go:186  0x2fa
golang.org/x/tools/internal/lsp.(*Server).Initialized(0xc000430d30%3F, {0x1001d20%3F, 0xc0001fe360%3F}, 0xc5af00%3F)
	  server_gen.go:156  0x25
golang.org/x/tools/internal/lsp/protocol.serverDispatch({0x1001d20, 0xc0001fe360}, {0x100ce00, 0xc0002ac6c0}, 0xc0002e8090, {0x1001f18, 0xc0001fe2a0})
	  tsserver.go:140  0x6d3
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1({0x1001d20, 0xc0001fe360}, 0xc0002e8090, {0x1001f18, 0xc0001fe2a0})
	  protocol.go:154  0x90
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1({0x1001d20, 0xc0001fe360}, 0xc0002e8090, {0x1001f18%3F, 0xc0001fe2a0%3F})
	  lsprpc.go:506  0xa43
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x1001d20, 0xc0001fe360}, 0xc0005c83a8, {0x1001f18%3F, 0xc0001fe2a0%3F})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20a
[Error - 11:19:01 AM] </pre>

**Comment by hyangah** [comment] 2022-03-28 18:02
Thanks for the report - Duplicate of https://github.com/golang/go/issues/51844
The fix will be released soon (gopls v0.8.2)

**Closed by hyangah** 2022-03-28 18:02 UTC
