### ISSUE TITLE
gopls: could not import package and variable detection  in same package  stopped working 

### ISSUE THREAD

**Issue by TheDhejavu** [golang/vscode-go#996] opened 2020-12-03 12:45 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	-  go version go1.15.5 darwin/amd64
- Run `gopls -v version` to get version of Gopls if you are using [the language server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).
	- golang.org/x/tools/gopls v0.5.4
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.51.1
- Check your installed extensions to get the version of the VS Code Go extension
	- 0.19.0
- Run `go env` to get the go development environment details
	-     

 GO111MODULE="on"
    GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ayodeji/Library/Caches/go-build"
GOENV="/Users/ayodeji/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ayodeji/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ayodeji/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ayodeji/go/src/github.com/workspace/simple-bank/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yq/s2hqwwn519z_lgl7mqr_496c0000gn/T/go-build473978771=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

    {
       "go.autocompleteUnimportedPackages": true,
    "go.useLanguageServer": true,
    "go.formatTool": "goimports",
    "[go]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
        // Optional: Disable snippets, as they conflict with completion ranking.
        "editor.snippetSuggestions": "none",
    },
    "[go.mod]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
    },
      }

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
<img width="281" alt="Screenshot 2020-12-03 at 1 08 35 PM" src="https://user-images.githubusercontent.com/19678915/101019108-528b8400-3521-11eb-8117-a9ae5556bc6f.png">
<img width="817" alt="Screenshot 2020-12-03 at 1 09 28 PM" src="https://user-images.githubusercontent.com/19678915/101019603-13116780-3522-11eb-9397-e072d1e14198.png">

**Comment by hyangah** [comment] 2020-12-03 13:21
@TheDhejavu thanks for reporting an issue. Did you open the editor from the directory where `go.mod` file is?  Currently the language server requires to open the directory (workspace root) where the corresponding `go.mod` file is located https://github.com/golang/vscode-go/issues/275#issue-648468015  In your case, it looks like the workspace root should be `simple-bank` directory.

If opening from the directory doesn't fix the problem, please share the gopls trace.  https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#vs-code

**Comment by TheDhejavu** [comment] 2020-12-03 13:33
@hyangah i opened the project from the root. Here is the tracer for golps 


        
[Error - 2:30:22 PM] Request textDocument/codeAction failed.
  Message: no supported code action to execute for file:///Users/ayodeji/go/src/github.com/workspace/simple-bank/go.sum, wanted []
  Code: 0 
[Error - 2:30:23 PM] 2020/12/03 14:30:23 go/packages.Load: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin github.com/workspace/simple-bank/...]: exit status 1: open /Users/ayodeji/Library/Caches/go-build/76/76f1b07ead1a0346b7fa6859db4aeac3cda03a63af9b7d7a58e4c990224ccdd4-d: permission denied

	snapshot=17
	directory=/Users/ayodeji/go/src/github.com/workspace/simple-bank
	query=[builtin github.com/workspace/simple-bank/...]
	packages=0

[Error - 2:30:23 PM] 2020/12/03 14:30:23 initial workspace load failed: source error list:
	file:///Users/ayodeji/go/src/github.com/workspace/simple-bank/go.mod:0:0-0:39: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin github.com/workspace/simple-bank/...]: exit status 1: open /Users/ayodeji/Library/Caches/go-build/76/76f1b07ead1a0346b7fa6859db4aeac3cda03a63af9b7d7a58e4c990224ccdd4-d: permission denied


[Info  - 2:30:24 PM] 2020/12/03 14:30:24 go/packages.Load
	snapshot=17
	directory=/Users/ayodeji/go/src/github.com/workspace/simple-bank
	query=[file=/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go]
	packages=1

[Info  - 2:30:24 PM] 2020/12/03 14:30:24 go/packages.Load
	snapshot=17
	package_path="/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go"
	files=[/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go]

[Error - 2:30:26 PM] 2020/12/03 14:30:26 go/packages.Load: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin github.com/workspace/simple-bank/...]: exit status 1: open /Users/ayodeji/Library/Caches/go-build/76/76f1b07ead1a0346b7fa6859db4aeac3cda03a63af9b7d7a58e4c990224ccdd4-d: permission denied

	snapshot=18
	directory=/Users/ayodeji/go/src/github.com/workspace/simple-bank
	query=[builtin github.com/workspace/simple-bank/...]
	packages=0

[Error - 2:30:26 PM] 2020/12/03 14:30:26 initial workspace load failed: source error list:
	file:///Users/ayodeji/go/src/github.com/workspace/simple-bank/go.mod:0:0-0:39: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin github.com/workspace/simple-bank/...]: exit status 1: open /Users/ayodeji/Library/Caches/go-build/76/76f1b07ead1a0346b7fa6859db4aeac3cda03a63af9b7d7a58e4c990224ccdd4-d: permission denied


[Info  - 2:30:26 PM] 2020/12/03 14:30:26 go/packages.Load
	snapshot=18
	directory=/Users/ayodeji/go/src/github.com/workspace/simple-bank
	query=[file=/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go]
	packages=1

[Info  - 2:30:26 PM] 2020/12/03 14:30:26 go/packages.Load
	snapshot=18
	package_path="/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go"
	files=[/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go]

[Info  - 2:30:26 PM] 2020/12/03 14:30:26 go/packages.Load
	snapshot=18
	directory=/Users/ayodeji/go/src/github.com/workspace/simple-bank
	query=[file=/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go]
	packages=1

[Info  - 2:30:26 PM] 2020/12/03 14:30:26 go/packages.Load
	snapshot=18
	package_path="/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go"
	files=[/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go]

[Error - 2:30:26 PM] Request textDocument/codeAction failed.
  Message: no supported code action to execute for file:///Users/ayodeji/go/src/github.com/workspace/simple-bank/go.sum, wanted []
  Code: 0 
[Error - 2:30:27 PM] 2020/12/03 14:30:27 go/packages.Load: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin github.com/workspace/simple-bank/...]: exit status 1: open /Users/ayodeji/Library/Caches/go-build/76/76f1b07ead1a0346b7fa6859db4aeac3cda03a63af9b7d7a58e4c990224ccdd4-d: permission denied

	snapshot=21
	directory=/Users/ayodeji/go/src/github.com/workspace/simple-bank
	query=[builtin github.com/workspace/simple-bank/...]
	packages=0

[Error - 2:30:27 PM] 2020/12/03 14:30:27 initial workspace load failed: source error list:
	file:///Users/ayodeji/go/src/github.com/workspace/simple-bank/go.mod:0:0-0:39: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin github.com/workspace/simple-bank/...]: exit status 1: open /Users/ayodeji/Library/Caches/go-build/76/76f1b07ead1a0346b7fa6859db4aeac3cda03a63af9b7d7a58e4c990224ccdd4-d: permission denied


[Info  - 2:30:27 PM] 2020/12/03 14:30:27 go/packages.Load
	snapshot=21
	package_path="/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go"
	files=[/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go]

[Info  - 2:30:27 PM] 2020/12/03 14:30:27 go/packages.Load
	snapshot=21
	directory=/Users/ayodeji/go/src/github.com/workspace/simple-bank
	query=[file=/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go]
	packages=1

[Error - 2:31:28 PM] 2020/12/03 14:31:28 go/packages.Load: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin github.com/workspace/simple-bank/...]: exit status 1: open /Users/ayodeji/Library/Caches/go-build/76/76f1b07ead1a0346b7fa6859db4aeac3cda03a63af9b7d7a58e4c990224ccdd4-d: permission denied

	snapshot=22
	directory=/Users/ayodeji/go/src/github.com/workspace/simple-bank
	query=[builtin github.com/workspace/simple-bank/...]
	packages=0

[Error - 2:31:28 PM] 2020/12/03 14:31:28 initial workspace load failed: source error list:
	file:///Users/ayodeji/go/src/github.com/workspace/simple-bank/go.mod:0:0-0:39: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin github.com/workspace/simple-bank/...]: exit status 1: open /Users/ayodeji/Library/Caches/go-build/76/76f1b07ead1a0346b7fa6859db4aeac3cda03a63af9b7d7a58e4c990224ccdd4-d: permission denied


[Info  - 2:31:28 PM] 2020/12/03 14:31:28 go/packages.Load
	snapshot=22
	package_path="/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go"
	files=[/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go]

[Info  - 2:31:28 PM] 2020/12/03 14:31:28 go/packages.Load
	snapshot=22
	directory=/Users/ayodeji/go/src/github.com/workspace/simple-bank
	query=[file=/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go]
	packages=1

[Info  - 2:31:28 PM] 2020/12/03 14:31:28 go/packages.Load
	snapshot=22
	directory=/Users/ayodeji/go/src/github.com/workspace/simple-bank
	query=[file=/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go]
	packages=1

[Info  - 2:31:28 PM] 2020/12/03 14:31:28 go/packages.Load
	snapshot=22
	package_path="/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go"
	files=[/Users/ayodeji/go/src/github.com/workspace/simple-bank/db/sqlc/account_test.go]

[Info  - 2:31:30 PM] 2020/12/03 14:31:30 go/packages.Load
	snapshot=1
	directory=/Users/ayodeji/go/src/github.com/workspace/the-crypto-project
	query=[builtin github.com/workspace/the-crypto-project/...]
	packages=1

[Info  - 2:31:48 PM] 2020/12/03 14:31:48 background imports cache refresh starting

[Info  - 2:31:48 PM] 2020/12/03 14:31:48 background refresh finished after 18.066571ms

**Comment by hyangah** [comment] 2020-12-03 13:54
@TheDhejavu Thanks for the trace. Looks like `go` commands encountered permission issues. 

```
file:///Users/ayodeji/go/src/github.com/workspace/simple-bank/go.mod:0:0-0:39: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin github.com/workspace/simple-bank/...]: exit status 1: open /Users/ayodeji/Library/Caches/go-build/76/76f1b07ead1a0346b7fa6859db4aeac3cda03a63af9b7d7a58e4c990224ccdd4-d: permission denied
```

Can you try to clear the build cache (`go build -cache`) and see if it helps?

**Comment by TheDhejavu** [comment] 2020-12-03 14:04
@hyangah  thanks, build -cache didn't work but I tried `sudo go clean -cache -modcache -i -r` and it works.

**Comment by hyangah** [comment] 2020-12-03 14:26
@TheDhejavu Glad to hear that the problem is resolved.

@stamblerre I will leave this open for you to see. Is there any planned work to surface this type of errors in a different way from gopls side? Feel free to close this issue. 
As part of [CL/274449](https://go-review.googlesource.com/c/vscode-go/+/274449) work, the language client will be configured to reveal the gopls output channel in case of errors, and I hope this helps.

**Comment by RiccardoManfrin** [comment] 2020-12-03 14:52
I kind of had same issue.. the initial comment by @hyangah  in my case was enlightening. I was generating some OpenAPI code which among the many things also placed a `main.go` and `go.mod` file in some nested folder. This was ruining the day to VSCode.

**Comment by hyangah** [comment] 2020-12-03 16:08
@RiccardoManfrin Yeah, a typical "the-same-symptom-many-different-reasons" problem. We need a better error reporting and troubleshooting story.

**Comment by stamblerre** [comment] 2020-12-03 17:05
> @stamblerre I will leave this open for you to see. Is there any planned work to surface this type of errors in a different way from gopls side? Feel free to close this issue.

The error should've showed up in the status bar at the bottom of the screen. @TheDhejavu did you see the pop-up or was it not noticeable?

**Comment by TheDhejavu** [comment] 2020-12-03 20:10
Hi @stamblerre, I didn't notice any pop-up message.

**Comment by stamblerre** [comment] 2020-12-07 00:41
Thanks for following up, @TheDhejavu. It's unfortunate that an error message didn't appear, but it's difficult to test this exact scenario. I do think an error message will pop-up with the new logic in v0.6.0. I'm going to close this issue as a result.

**Closed by stamblerre** 2020-12-07 00:41 UTC
Labels: WaitingForInfo
