### ISSUE TITLE
gopls: use the workspace module when it's available

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#1260] opened 2021-02-28 22:14 UTC
As previously discussed, if the user has `experimentalWorkspaceModule` set, commands should run through the workspace module. `gopls` currently creates a directory based on its PID for VS Code Go to run commands in.

**Comment by hyangah** [comment] 2021-03-01 03:53
Duplicate of #1239

**Closed by hyangah** 2021-03-01 03:53 UTC
