### ISSUE TITLE
wrong code suggestion when action is following case type assert

### ISSUE THREAD

**Issue by hauntedness** [golang/vscode-go#2170] opened 2022-04-07 13:21 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- 1.18
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- v0.8.2
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.66.0  e18005f0f1b33c29e81d732535d8c0e47cafb0b5 x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.32.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	-  Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: C:\Users\huantedness\go
GOROOT: C:\Program Files\Go
PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\NetSarang\Xshell 7\;C:\Program Files (x86)\NetSarang\Xftp 7\;C:\ProgramData\protoc-3.18.0-rc-1-win64\bin;C:\Users\huantedness\go\bin;C:\ProgramData\chocolatey\bin;C:\ProgramData\sqlite;C:\TDM-GCC-64\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\tools\miniconda3\Scripts\conda.exe;C:\Program Files\Go\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\huantedness\.cargo\bin;C:\Users\huantedness\AppData\Local\Microsoft\WindowsApps;C:\ProgramData\apache-tomcat-8.5.72\bin;C:\ProgramData\apache-maven-3.8.4\\bin;C:\Users\huantedness\.jdks\corretto-11.0.12\bin;C:\tools\neovim\Neovim\bin;C:\Users\huantedness\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\huantedness\AppData\Roaming\npm;C:\Program Files\nodejs;C:\Users\huantedness\go\bin

	go:	C:\Program Files\Go\bin\go.exe: go version go1.18 windows/amd64

	go-outline:	C:\Users\huantedness\go\bin\go-outline.exe	(version: v0.0.0-20210608161538-9736a4bde949 built with go: go1.18)
	gotests:	C:\Users\huantedness\go\bin\gotests.exe	(version: v1.6.0 built with go: go1.18)
	gomodifytags:	C:\Users\huantedness\go\bin\gomodifytags.exe	(version: v1.16.0 built with go: go1.18)
	impl:	C:\Users\huantedness\go\bin\impl.exe	(version: v1.1.0 built with go: go1.18)
	goplay:	C:\Users\huantedness\go\bin\goplay.exe	(version: v1.0.0 built with go: go1.18)
	dlv:	C:\Users\huantedness\go\bin\dlv.exe	(version: v1.8.2 built with go: go1.18)
	staticcheck:	C:\Users\huantedness\go\bin\staticcheck.exe	(version: v0.3.0 built with go: go1.18)
	gopls:	C:\Users\huantedness\go\bin\gopls.exe	(version: v0.8.2 built with go: go1.18)

go env
Workspace Folder (testast): c:\Users\huantedness\NvimProjects\goprojects\testast
	set GO111MODULE=on
	set GOARCH=amd64
	set GOBIN=
	set GOCACHE=C:\Users\huantedness\AppData\Local\go-build
	set GOENV=C:\Users\huantedness\AppData\Roaming\go\env
	set GOEXE=.exe
	set GOEXPERIMENT=
	set GOFLAGS=
	set GOHOSTARCH=amd64
	set GOHOSTOS=windows
	set GOINSECURE=
	set GOMODCACHE=C:\Users\huantedness\go\pkg\mod
	set GONOPROXY=
	set GONOSUMDB=
	set GOOS=windows
	set GOPATH=C:\Users\huantedness\go
	set GOPRIVATE=
	set GOPROXY=https://goproxy.cn
	set GOROOT=C:\Program Files\Go
	set GOSUMDB=sum.golang.org
	set GOTMPDIR=
	set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
	set GOVCS=
	set GOVERSION=go1.18
	set GCCGO=gccgo
	set GOAMD64=v1
	set AR=ar
	set CC=gcc
	set CXX=g++
	set CGO_ENABLED=1
	set GOMOD=c:\Users\huantedness\NvimProjects\goprojects\testast\go.mod
	set GOWORK=
	set CGO_CFLAGS=-g -O2
	set CGO_CPPFLAGS=
	set CGO_CXXFLAGS=-g -O2
	set CGO_FFLAGS=-g -O2
	set CGO_LDFLAGS=-g -O2
	set PKG_CONFIG=pkg-config
	set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\HUANTE~1\AppData\Local\Temp\go-build207366775=/tmp/go-build -gno-record-gcc-switches
	

</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
  -- all default
### Describe the bug
 the issue is happened in switch block along with type assertion, a map assignment is needed to replicate the problem

### Steps to reproduce the behavior:
1. use below sample code segment to reproduce the issue
package main
import (
	"go/ast"
)
var Store map[*ast.StructType]string
func main() {
	var tsssssssssssss *ast.TypeSpec
	switch noisySuggest := tsssssssssssss.Type.(type) {
	case *ast.StructType:
		// here get a good t.autocompletion
		Store[noisySuggest] = ""
		// here get wrong suggest
		// tap noisySuggest + "."
	default:
		// no issue if no default statement
	}
}

![image](https://user-images.githubusercontent.com/59566708/162207809-245167dc-3926-4712-8792-a740d2974a4c.png)

**Comment by hauntedness** [comment] 2022-04-07 13:39
per further check, the issue is only in regarding to the part between case and default

**Comment by findleyr** [comment] 2022-04-08 18:50
The reason for this is poor parser error recovery: the syntax is interpreted as noisysuggest.default (which is invalid), and (I think) parses the expression as a BadExpr.

Aha, indeed, I found the issue: https://go.dev/issue/29148

**Comment by findleyr** [comment] 2022-04-08 18:53
Closing this as a dupe of golang/go#29148.

It is unfortunate that that issue has stayed open for so long. I am collecting parser recovery issues for a hopeful future where we have time to address them.

**Closed by findleyr** 2022-04-08 18:53 UTC
Labels: gopls
