### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by pjweinb** [golang/vscode-go#739] opened 2020-10-04 18:00 UTC
gopls version: (devel)
gopls flags: -rpc.trace -logfile=auto

tip, output of git log --oneline
ecd9fd27 (HEAD -> master, origin/master, origin/HEAD) internal/lsp/source: ignore empty package names for completion

Here is the gopls section from settings.json:
  "gopls": {
    "usePlaceholders": true, // add parameter placeholders when completing a function
    "completionDocumentation": true,
    "verboseOutput": false,
    "codelens": {
      "gc_details": true,
    },
    "analyses": {
      "fillstruct": true,
      "staticcheck": true,
    },
    "experimentalWorkspaceModule": true,
    "semantictokens": true,
  },

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

opened vscode in <source-distribution>/src and it crashed 5 times.

constructed query in snapshot.load was:[cmd/... std/... builtin]

[the two modules it seems to be complaining about are (map[span.URI]*cache.moduleRoot{"file:///Users/pjw/goroot/src":(*cache.moduleRoot)(0xc0003524e0), "file:///Users/pjw/goroot/src/cmd":(*cache.moduleRoot)(0xc0000cd560)})

<pre>panic: unsupported use of -modfile, expected 1 module, got 2

goroutine 132 [running]:
golang.org/x/tools/internal/lsp/cache.(*snapshot).load(0xc0001fa240, 0x1af7100, 0xc00011cf90, 0xc00036a1c0, 0x3, 0x4, 0x0, 0x0)
	  load.go:109  0x2ca5
golang.org/x/tools/internal/lsp/cache.(*snapshot).initialize.func2()
	  view.go:767  0x470
sync.(*Once).doSlow(0xc0005e1b50, 0xc000571ef8)
	  once.go:66  0xec
sync.(*Once).Do(...)
	  once.go:57
golang.org/x/tools/internal/lsp/cache.(*snapshot).initialize(0xc0001fa240, 0x1af7040, 0xc0002c08c0, 0xc000320201)
	  view.go:726  0x1d5
golang.org/x/tools/internal/lsp/cache.(*Session).createView.func3(0xc0001fa240, 0x1af7040, 0xc0002c08c0, 0xc0003204b0)
	  session.go:245  0x45
created by golang.org/x/tools/internal/lsp/cache.(*Session).createView
	  session.go:244  0xa30
[Error - 1:30:04 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

[Trace - 13:52:25.844 PM] Sending request 'initialize - (0)'.
Params: {"processId":1102,"clientInfo":{"name":"vscode","version":"1.49.3"},"rootPath":"/Users/pjw/goroot/src","rootUri":"file:///Users/pjw/goroot/src","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"versionSupport":false,"tagSupport":{"valueSet":[1,2]}},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}},"contextSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"isPreferredSupport":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"selectionRange":{"dynamicRegistration":true}},"window":{"workDoneProgress":true}},"initializationOptions":{},"trace":"off","workspaceFolders":[{"uri":"file:///Users/pjw/goroot/src","name":"src"}]}

[Trace - 13:52:25.845 PM] Received response 'initialize - (0)' in 1ms.
Result: {"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"completionProvider":{"triggerCharacters":["."]},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor.extract","refactor.rewrite","source.fixAll","source.organizeImports"]},"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"renameProvider":{"prepareProvider":true},"foldingRangeProvider":true,"executeCommandProvider":{"commands":["generate","fill_struct","regenerate_cgo","test","tidy","undeclared_name","upgrade_dependency","vendor","extract_variable","extract_function","gc_details","generate_gopls_mod"]},"callHierarchyProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}}},"serverInfo":{"name":"gopls","version":"Build info\n----------\ngolang.org/x/tools/gopls master\n    golang.org/x/tools/gopls@(devel)\n    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=\n    github.com/google/go-cmp@v0.5.1 h1:JFrFEBb2xKufg6XkJsJr+WbKb4FQlURi5RUcBveYu9k=\n    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\n    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=\n    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=\n    golang.org/x/tools@v0.0.0-20200828161849-5deb26317202 =\u003e ../\n    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=\n    honnef.co/go/tools@v0.0.1-2020.1.5 h1:nI5egYTGJakVyOryqLs1cQO5dO0ksin5XXs2pspk75k=\n    mvdan.cc/gofumpt@v0.0.0-20200802201014-ab5a8192947d h1:t8TAw9WgTLghti7RYkpPmqk4JtQ3+wcP5GgZqgWeWLQ=\n    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=\n"}}

[Trace - 13:52:25.846 PM] Sending notification 'initialized'.
Params: {}

[Trace - 13:52:25.846 PM] Received request 'window/workDoneProgress/create - (1)'.
Params: {"token":"5577006791947779410"}

[Trace - 13:52:25.847 PM] Sending response 'window/workDoneProgress/create - (1)' in 1ms.
Result: 

[Trace - 13:52:25.848 PM] Received notification '$/progress'.
Params: {"token":"5577006791947779410","value":{"kind":"begin","title":"Setting up workspace","message":"Loading packages..."}}

[Trace - 13:52:25.848 PM] Received request 'workspace/configuration - (2)'.
Params: {"items":[{"scopeUri":"file:///Users/pjw/goroot/src","section":"gopls"},{"scopeUri":"file:///Users/pjw/goroot/src","section":"gopls-src"}]}

[Trace - 13:52:25.852 PM] Sending response 'workspace/configuration - (2)' in 3ms.
Result: [{"usePlaceholders":true,"completionDocumentation":true,"verboseOutput":false,"codelens":{"gc_details":true},"analyses":{"fillstruct":true,"staticcheck":true},"experimentalWorkspaceModule":true,"semantictokens":true},null]

**Comment by findleyr** [comment] 2020-10-05 00:50
This looks like a duplicate of https://github.com/golang/go/issues/41725.

**Comment by pjweinb** [comment] 2020-10-05 12:18
Lost something above: executed command was 'code <GO-SOURCE-DISTRIBUTION>/src'

**Comment by stamblerre** [comment] 2020-10-05 16:15
> constructed query in snapshot.load was:[cmd/... std/... builtin]

[the two modules it seems to be complaining about are (map[span.URI]*cache.moduleRoot{"file:///Users/pjw/goroot/src":(*cache.moduleRoot)(0xc0003524e0), "file:///Users/pjw/goroot/src/cmd":(*cache.moduleRoot)(0xc0000cd560)})

Thank you for this info! I will close this as a duplicate, but I will try to reproduce this in the Go distribution now that we have an example case.

**Closed** 2020-10-05 16:23 UTC
