### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by edenzhang2012** [golang/vscode-go#2744] opened 2023-04-23 11:58 UTC
gopls version: v0.11.0 (go1.20.2)
gopls flags: 
update flags: proxy
extension version: 0.38.0
go version: 1.20.3
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Sun, 23 Apr 2023 11:57:42 GMT
restart history:
Sun, 23 Apr 2023 11:44:06 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xb8ab3d]

goroutine 146 [running]:
golang.org/x/tools/gopls/internal/lsp/mod.hoverOnModuleStatement({0x10d18e8%3F, 0xc0002ea690%3F}, 0xc0002ea690%3F, 0x10d1b50%3F, {0x10de430%3F, 0xc00019c9a0%3F}, {0x10d1b50%3F, 0xc0004b2310%3F})
	  hover.go:128  0x5d
golang.org/x/tools/gopls/internal/lsp/mod.Hover({0x10d1840, 0xc000494500}, {0x10de430, 0xc00019c9a0}, {0x10d1b50, 0xc0004b2310}, {0x2ea4e0%3F, 0xc0%3F})
	  hover.go:50  0x31f
golang.org/x/tools/gopls/internal/lsp.(*Server).hover(0xcfe0a0%3F, {0x10d1840, 0xc000494500}, 0xc0002ea4e0)
	  hover.go:25  0x152
golang.org/x/tools/gopls/internal/lsp.(*Server).Hover(0xc0002b81c0%3F, {0x10d1840%3F, 0xc000494500%3F}, 0xcfe0a0%3F)
	  server_gen.go:140  0x25
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch({0x10d1840, 0xc000494500}, {0x10e2300, 0xc000596000}, 0xc0002ea4b0, {0x10d1c30, 0xc00007e4c0})
	  tsserver.go:397  0xca6
golang.org/x/tools/gopls/internal/lsp/protocol.ServerHandler.func1({0x10d1840, 0xc000494500}, 0xc0002ea4b0, {0x10d1c30, 0xc00007e4c0})
	  protocol.go:157  0x90
golang.org/x/tools/gopls/internal/lsp/lsprpc.handshaker.func1({0x10d1840, 0xc000494500}, 0xc0002ea4b0, {0x10d1c30%3F, 0xc00007e4c0%3F})
	  lsprpc.go:519  0x9f9
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x10d1840, 0xc000494500}, 0xc000012a20, {0x10d1c30%3F, 0xc00007e4c0%3F})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20a
[Error - 7:57:22 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2023-04-26 13:17
Thank you for reporting.

This is a duplicate of golang/go#57625, which will be fixed in the next gopls release.

**Closed by findleyr** 2023-04-26 13:17 UTC
