### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by flyingfishzxf** [golang/vscode-go#2819] opened 2023-06-13 09:05 UTC
gopls version: v0.12.2 (go1.20.5)
gopls flags: 
update flags: proxy
extension version: 0.38.0
go version: 1.20.5
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Tue, 13 Jun 2023 09:04:49 GMT
restart history:
Tue, 13 Jun 2023 09:04:35 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: internal error: assertion failed

goroutine 883 [running]:
golang.org/x/tools/internal/gcimporter.iexportCommon.func1()
	  iexport.go:93  0x8a
panic({0xd82ea0, 0x114f950})
	  panic.go:884  0x213
golang.org/x/tools/internal/gcimporter.assert(...)
	  iexport.go:1141
golang.org/x/tools/internal/gcimporter.constantToFloat({0x11593f0%3F, 0x171aad0%3F})
	  iexport.go:967  0x147
golang.org/x/tools/internal/gcimporter.(*exportWriter).value(0xc00105ea80, {0x1155218%3F, 0xc00052f3b0}, {0x11593f0, 0x171aad0})
	  iexport.go:930  0x2dc
golang.org/x/tools/internal/gcimporter.(*iexporter).doDecl(0xc0015a21e0, {0x11619d8, 0xc00137a600})
	  iexport.go:481  0x2ed
golang.org/x/tools/internal/gcimporter.iexportCommon({0x1151240, 0xc00128c7e0}, 0xc0015a6dc0, 0x0, 0x1, 0x2, {0xc0014ffca8, 0x1, 0x0%3F})
	  iexport.go:139  0x3a5
golang.org/x/tools/internal/gcimporter.IExportShallow(0xdc6300%3F, 0xc00059f400)
	  iexport.go:43  0x75
golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).checkPackage.func1()
	  check.go:646  0x2b1
created by golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).checkPackage
	  check.go:638  0x305
[Error - 5:04:39 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2023-06-15 14:58
Thanks for the report, and sorry for the breakage. This is a dupe of https://go.dev/issue/60605, which is fixed at master.

We'll release gopls@v0.12.3 soon with the fix.

**Closed as not planned by findleyr** 2023-06-15 14:58 UTC
Labels: FrozenDueToAge
