### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by shinjikhang** [golang/vscode-go#3315] opened 2024-04-04 13:47 UTC
gopls version: v0.15.2/go1.20.5
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Thu, 04 Apr 2024 13:46:59 GMT
restart history:
Thu, 04 Apr 2024 11:33:16 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.1" (should be something like "go1.12")

goroutine 2837 [running]:
go/types.NewChecker(0x0%3F, 0xc00098d1c0, 0xc002287090, 0x0%3F)
	  check.go:237  0x24e
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc00198e6e0, {0xc0022c2578, 0x1, 0x1})
	  analysis.go:1028  0x73d
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc00198e6e0, {0x1e50778%3F, 0xc000385050})
	  analysis.go:810  0x218
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc00198e6e0, {0x1e50778%3F, 0xc000385050})
	  analysis.go:672  0x145
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xda
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 38,
    "TestdataFiles": 0,
    "GoFiles": 1,
    "ModFiles": 1,
    "Dirs": 17
  },
  "GOARCH": "amd64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.20.5",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "1.672096115s",
  "MemStats": {
    "HeapAlloc": 22007336,
    "HeapInUse": 32882688,
    "TotalAlloc": 311112960
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 1310,
      "Largest": 395026,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.2",
        "AllPackages": {
          "Packages": 209,
          "LargestPackage": 154,
          "CompiledGoFiles": 1306,
          "Modules": 17
        },
        "WorkspacePackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by timothy-king** [comment] 2024-04-04 20:55
Duplicate of https://github.com/golang/go/issues/66636. Fix is expected to be in gopls@v0.15.3. Workaround is to reinstall gopls with go1.21+.

**Closed by timothy-king** 2024-04-04 20:55 UTC
