### ISSUE TITLE
`go.test.previous` is not work single method test

### ISSUE THREAD

**Issue by Centny** [golang/vscode-go#331] opened 2020-07-12 23:45 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
 go version go1.14.4 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
1.48.0-insider
e7920dce7bfd0b707ebfc0a5379c6edd2233e475
x64
- Check your installed extensions to get the version of the VS Code Go extension 
![image](https://user-images.githubusercontent.com/4049551/87259123-7e0ec300-c4db-11ea-8cc4-dd0ab1f43f75.png)

- Run `go env` to get the go development environment details
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\cny\AppData\Local\go-build
set GOENV=C:\Users\cny\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\gopath
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\cny\AppData\Local\Temp\go-build810391794=/tmp/go-build -gno-record-gcc-switches

### Share the Go related settings you have added/edited
{
    "extensions.ignoreRecommendations": false,
    "explorer.confirmDelete": false,
    "editor.formatOnSave": true,
    "http.proxy": "http://127.0.0.1:1103",
    "go.formatTool": "goimports",
    "go.coverOnSingleTest": true,
    "go.testFlags": [
        "-v",
        "-count=1"
    ],
    "go.coverOnSingleTestFile": true,
    "go.lintOnSave": "file",
    "go.useLanguageServer": true,
}

### Describe the bug
- the `go.test.previous` is not work single method test

```.go
//testx.go
import "fmt"

func Hello() {
	fmt.Println("hello world")
}
```
```.go
//testx_test.go
package testx

import "testing"

func TestHello(t *testing.T) {
	Hello()
}

func TestHello2(t *testing.T) {
	Hello()
}

```
- first click run test to run signle method
![image](https://user-images.githubusercontent.com/4049551/87259245-73086280-c4dc-11ea-9ecb-cc7e1b89949a.png)

- ctrl+shift+p run go test previous, no run sigle method
![image](https://user-images.githubusercontent.com/4049551/87259254-83204200-c4dc-11ea-8393-aefda2c43b6f.png)

**Comment by hyangah** [comment] 2020-07-13 13:40
Looks like a duplicate of https://github.com/golang/vscode-go/issues/269

We plan to release v0.16.0 end of this month.

**Closed by hyangah** 2020-07-13 13:40 UTC
