### ISSUE TITLE
Generate Unit-Tests fails for Generics

### ISSUE THREAD

**Issue by mwat56** [golang/vscode-go#3484] opened 2024-08-09 15:17 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.22.1 linux/amd64

* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.16.1
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.92.0
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.42.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- 
	go:	/usr/lib/go-1.22/bin/go: go version go1.22.1 linux/amd64

	gopls:	/home/matthias/devel/Go/bin/gopls	(version: v0.16.1 built with go: go1.22.1)
	gotests:	/home/matthias/devel/Go/bin/gotests	(version: v1.6.0 built with go: go1.22.1)
	gomodifytags:	/home/matthias/devel/Go/bin/gomodifytags	(version: v1.16.0 built with go: go1.22.1)
	impl:	not installed
	goplay:	not installed
	dlv:	/home/matthias/devel/Go/bin/dlv	(version: v1.22.1 built with go: go1.22.1)
	staticcheck:	/home/matthias/devel/Go/bin/staticcheck	(version: v0.4.7 built with go: go1.22.1)

</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:

When I try to prepare a unit-test for a function or file that uses generics I only get the message:

> output.Process: imports.Process: /tmp/gotests_2003483964:75:23: missing type constraint (and 10 more errors)

**Comment by hyangah** [comment] 2024-09-05 18:15
Duplicate of #3425
which was closed in favor of golang/go#47479 (gopls).

What's a reasonable unit-test like for generics is still under discussion here. Please chime in. https://github.com/cweill/gotests/issues/165

**Closed** 2024-09-05 18:16 UTC
Labels: upstream-tools, Duplicate
