### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by kkkooottt** [golang/vscode-go#724] opened 2020-10-01 10:04 UTC
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 116 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x22e
golang.org/x/tools/internal/lsp/debug.section(0xed1240, 0xc0000eb290, 0x0, 0xd571db, 0x7, 0xc0000d8f18)
	  info.go:69  0x319
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xee51e0, 0xc00034b100, 0xed1240, 0xc0000eb290, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc00035c320, 0xee51e0, 0xc00034b100, 0xc0000c2000, 0x0, 0x0, 0x0)
	  general.go:87  0x58b
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc00035c320, 0xee51e0, 0xc00034b100, 0xc0000c2000, 0xc0000c2000, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xee51e0, 0xc00034b100, 0xf00360, 0xc00035c320, 0xc0000b52c0, 0xee5420, 0xc00034b080, 0x0, 0x0, 0x0)
	  tsserver.go:235  0x4bb
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xee51e0, 0xc00034b100, 0xc0000b52c0, 0xee5420, 0xc00034b080, 0x0, 0xbfd5883fe7b62cf2)
	  protocol.go:63  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xee51e0, 0xc00034b100, 0xc0000b52c0, 0xee5420, 0xc00034b080, 0x0, 0x0)
	  lsprpc.go:557  0x420
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xee51e0, 0xc00034b100, 0xc000348c80, 0xee5420, 0xc00034b080, 0x40771f, 0xc00003a5f8)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc000312960, 0xc00034d8f0, 0xc0003016e0, 0xee51e0, 0xc00034b100, 0xc000348c80, 0xee5420, 0xc00034b080)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Error - 1:03:43 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2020-10-01 13:07
@kkkooottt thanks for the report. This is a duplicate of https://github.com/golang/vscode-go/issues/713.

**Closed by hyangah** 2020-10-01 13:07 UTC
