### ISSUE TITLE
Breaks Code folding

### ISSUE THREAD

**Issue by UserJHansen** [golang/vscode-go#2498] opened 2022-10-16 09:27 UTC
Type: <b>Bug</b>

Go into an open file with region comments:
e.g. 
//#region code
fmt.Println("Hello")
//#endregion

Expected:
A folding icon allowing you to fold it closed

Result:
No folding area

Extension version: 0.35.2
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1400 Quad-Core Processor            (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.46GB (9.25GB free)|
|Process Argv|--file-uri file:///c%3A/Users/userj/Github/Computer/Computer.code-workspace --crash-reporter-id 268785cc-6a34-4924-a17a-f1a7a1fae3fa|
|Screen Reader|no|
|VM|50%|

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30573243

```

</details>

**Comment by hyangah** [comment] 2022-10-18 21:29
Duplicate of #134

**Closed by hyangah** 2022-10-18 21:29 UTC

**Comment by UserJHansen** [comment] 2022-10-19 10:29
Sorry about that
