### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by ldipenti** [golang/vscode-go#399] opened 2020-07-23 15:04 UTC
Hello! I'm having issues when loading a go project on vscode, gopls seems to be panic'ing for some reason.

Here's the stack trace that I get on vscode's window:

```
Info  - 11:53:06 AM] 2020/07/23 11:53:06 Build info
----------
golang.org/x/tools/gopls 0.4.3
    golang.org/x/tools/gopls@v0.4.3 h1:irz7Q+XdHNECamFKbNWKvMV2Ak6zBbwdwbZndG4545I=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200708181441-6004c8539734 h1:Vc0Vx98oU/O3+qPQ36fnTT5UduS55KLh2uSGbL7mqEo=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

Go info
-------
go version go1.14.5 darwin/amd64



[Info  - 11:53:07 AM] 2020/07/23 11:53:07 go env for /Users/lucas/Devel/git/arvados
(valid build configuration = true)
(build flags: [])
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/lucas/Library/Caches/go-build"
GOENV="/Users/lucas/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/lucas/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/lucas/Devel/git/arvados/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9h/rbpwljgj581g1slqyrtl6xjm0000gp/T/go-build079812446=/tmp/go-build -gno-record-gcc-switches -fno-common"


panic: only file URIs are supported, got "gitlens" from "gitlens://40e3249/Users/lucas/Devel/git/arvados?%7B%22path%22%3A%22%2FUsers%2Flucas%2FDevel%2Fgit%2Farvados%22%2C%22ref%22%3A%2240e3249b1f75ff1442adbc360885c80db436c50b%22%2C%22repoPath%22%3A%22%2FUsers%2Flucas%2FDevel%2Fgit%2Farvados%22%7D"

goroutine 76 [running]:
golang.org/x/tools/internal/span.URI.Filename(...)
	/Users/lucas/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/span/uri.go:32
golang.org/x/tools/internal/lsp/cache.(*View).setBuildInformation(0xc000372000, 0x1a686c0, 0xc0003dfa70, 0xc000442000, 0xf0, 0xc000325880, 0x31, 0x31, 0x1, 0x1950ad0, ...)
	/Users/lucas/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/cache/view.go:746 +0x4b7
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0xc000310f00, 0x1a686c0, 0xc0003dfa70, 0xc00043a200, 0x11, 0xc000442000, 0xf0, 0x4000000000000000, 0x10101, 0xc00042ca00, ...)
	/Users/lucas/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/cache/session.go:157 +0x4d5
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0xc000310f00, 0x1a686c0, 0xc0003dfa70, 0xc00043a200, 0x11, 0xc000442000, 0xf0, 0x4000000000000000, 0x10101, 0xc00042ca00, ...)
	/Users/lucas/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/cache/session.go:108 +0x12b
golang.org/x/tools/internal/lsp.(*Server).addView(0xc000394d00, 0x1a686c0, 0xc0003dfa70, 0xc00043a200, 0x11, 0xc000442000, 0xf0, 0x1a7a6a0, 0xc0000df080, 0x1a7b700, ...)
	/Users/lucas/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/workspace.go:42 +0x1e4
golang.org/x/tools/internal/lsp.(*Server).addFolders(0xc000394d00, 0x1a686c0, 0xc0003dfa70, 0xc000291700, 0x2, 0x4)
	/Users/lucas/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/general.go:191 +0x184
golang.org/x/tools/internal/lsp.(*Server).initialized(0xc000394d00, 0x1a686c0, 0xc0003dfa70, 0x1fe0598, 0x0, 0x0)
	/Users/lucas/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/general.go:179 +0x3a4
golang.org/x/tools/internal/lsp.(*Server).Initialized(0xc000394d00, 0x1a686c0, 0xc0003dfa70, 0x1fe0598, 0x1fe0598, 0x0)
	/Users/lucas/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/server_gen.go:112 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1a686c0, 0xc0003dfa70, 0x1a82a80, 0xc000394d00, 0xc0002382d0, 0x3356198, 0xc0003dfa10, 0x0, 0x0, 0xbfbe86f4ab4f5f30)
	/Users/lucas/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/protocol/tsserver.go:92 +0x647
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1a686c0, 0xc0003dfa70, 0xc0002382d0, 0x3356198, 0xc0003dfa10, 0x0, 0x0)
	/Users/lucas/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/protocol/protocol.go:62 +0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1a686c0, 0xc0003dfa70, 0xc0002382d0, 0x3356198, 0xc0003dfa10, 0x0, 0x0)
	/Users/lucas/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/lsprpc/lsprpc.go:509 +0x40e
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1a686c0, 0xc0003dfa70, 0xc0003fe200, 0x3356198, 0xc0003dfa10, 0x0, 0x0)
	/Users/lucas/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/jsonrpc2/handler.go:35 +0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00030f260, 0xc0003dfe90, 0xc0003b3b30, 0x1a686c0, 0xc0003dfa70, 0xc0003fe200, 0x3356198, 0xc0003dfa10)
	/Users/lucas/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/Users/lucas/go/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/jsonrpc2/handler.go:100 +0x171
[Info  - 11:53:07 AM] Connection to server got closed. Server will restart.
[Error - 11:53:07 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 11:53:07 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 11:53:07 AM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 11:53:07 AM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 11:53:07 AM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/Users/lucas/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
```

**Comment by stamblerre** [comment] 2020-07-23 15:46
Thanks for the report! This looks like a duplicate of https://github.com/golang/go/issues/40272, so let's continue the discussion there.

**Closed by stamblerre** 2020-07-23 15:46 UTC
