### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Sangwaniya** [golang/vscode-go#3445] opened 2024-07-10 11:11 UTC
gopls version: v0.16.1/go1.21.6
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Wed, 10 Jul 2024 11:11:10 GMT
restart history:
Wed, 10 Jul 2024 11:08:29 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: slice bounds out of range [45:44]

goroutine 1034 [running]:
golang.org/x/tools/internal/imports.(*ModuleResolver).scanDirForPackage(0xc000638790, {{0xc000c12525%3F, 0x43b2f9a4d583d9b0%3F}, 0x8%3F}, {0xc0006156b0, 0x2c})
	  mod.go:744  0x705
golang.org/x/tools/internal/imports.(*ModuleResolver).scan.func3({{0xc000c12525%3F, 0x170e4e0%3F}, 0xc000f1ad50%3F}, {0xc0006156b0%3F, 0x21b23a8%3F})
	  mod.go:618  0x50
golang.org/x/tools/internal/gopathwalk.(*walker).walk(0xc0008de870, {0xc000bbd5c0, 0x37}, 0x0, {0x1b87e58, 0xc0006c58f0})
	  walk.go:268  0x3d7
golang.org/x/tools/internal/gopathwalk.(*walker).walk(0xc0008de870, {0xc000c12525, 0x2c}, 0x0, {0x1b87e90, 0xc000f1ad30})
	  walk.go:334  0x87b
golang.org/x/tools/internal/gopathwalk.walkDir({{0xc000c12525%3F, 0xc000c29f18%3F}, 0xc000c29f18%3F}, 0xc000f1ad00, 0xc000f1acf0, {0x0%3F, 0xc0%3F, 0x4%3F})
	  walk.go:120  0x366
golang.org/x/tools/internal/gopathwalk.WalkSkip(...)
	  walk.go:77
golang.org/x/tools/internal/imports.(*ModuleResolver).scan.func4()
	  mod.go:643  0x2db
created by golang.org/x/tools/internal/imports.(*ModuleResolver).scan in goroutine 201
	  mod.go:627  0x465
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 2198,
    "TestdataFiles": 0,
    "GoFiles": 1626,
    "ModFiles": 2,
    "Dirs": 570
  },
  "GOARCH": "amd64",
  "GOOS": "windows",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.21.6",
  "GoplsVersion": "v0.16.1",
  "InitialWorkspaceLoadDuration": "1.1520102s",
  "MemStats": {
    "HeapAlloc": 1753048,
    "HeapInUse": 3899392,
    "TotalAlloc": 7153568
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 1,
      "Largest": 3429,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.21.6",
        "AllPackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "WorkspacePackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-07-10 13:43
Thank you for the report. Duplicate of golang/go#68334.

This is a regression in Go 1.22.5.

**Closed by findleyr** 2024-07-10 13:43 UTC
