### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by kevinxxq** [golang/vscode-go#2328] opened 2022-07-10 15:54 UTC
gopls version: v0.9.0 (go1.17.6)
gopls flags: 
update flags: proxy
extension version: 0.34.1
go version: 1.17.6
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Sun, 10 Jul 2022 15:53:46 GMT
restart history:
Sun, 10 Jul 2022 15:47:18 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment] 2022-07-11 19:29
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by kevinxxq** [comment] 2022-07-12 02:57
Hi @suzmue , Thank you for taking care it. the whole story is:
It started yesterday when I tried to short the project name from github.com/aaaaaa/bbb to bbb, I delete the go.mod, go.sum and then go mod init bbbb, go mod tidy.
then I run the go generate in a file.

Now it works after I reload the IDE, but I can't see the progress of go generate(there are handred lines of commands, I can see it before this crash).

Thank you.
----------------------------------------------------
I just got a output again and copied it here:
[Error - 10:48:35] Request textDocument/definition failed.
  Message: no identifier found
  Code: 0 
[Error - 10:48:46] Request textDocument/definition failed.
  Message: no identifier found
  Code: 0 
[Info  - 10:49:00] 2022/07/12 10:49:00 background imports cache refresh starting

[Info  - 10:49:01] 2022/07/12 10:49:01 background refresh finished after 1.2117727s

[Info  - 10:49:20] 2022/07/12 10:49:20 protoc --proto_path=. --dart_out=grpc:D:\flutterwork\osc_client\lib\grpc google/type/color.proto google/protobuf/timestamp.proto google/protobuf/empty.proto google/protobuf/any.proto google/protobuf/wrappers.proto

	operation="generate"

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x957578]

goroutine 60146 [running]:
golang.org/x/tools/internal/xcontext.detachedContext.Value(...)
	D:/GoWorks/pkg/mod/golang.org/x/tools@v0.1.12-0.20220630195555-6178576f8ba1/internal/xcontext/xcontext.go:23
golang.org/x/tools/internal/lsp/debug.GetInstance({0x134bc88, 0xc0722e4020})
	D:/GoWorks/pkg/mod/golang.org/x/tools@v0.1.12-0.20220630195555-6178576f8ba1/internal/lsp/debug/serve.go:361 +0x3e
golang.org/x/tools/internal/lsp/debug.makeGlobalExporter.func1({0x134bc88, 0xc0722e4020}, {{0xc0ab562c2d343eec, 0x248ec34eb801, 0x18b8940}, {{{0x1349260, 0xc000068460}, 0xa, {0xfdac00, 0x1104eee}}, ...}, ...}, ...)
	D:/GoWorks/pkg/mod/golang.org/x/tools@v0.1.12-0.20220630195555-6178576f8ba1/internal/lsp/debug/serve.go:571 +0x7e
golang.org/x/tools/internal/event/core.deliver({0x134bc88, 0xc0722e4020}, 0xc00030c7e0, {{0xc0ab562c2d343eec, 0x248ec34eb801, 0x18b8940}, {{{0x1349260, 0xc000068460}, 0xa, {0xfdac00, ...}}, ...}, ...})
	D:/GoWorks/pkg/mod/golang.org/x/tools@v0.1.12-0.20220630195555-6178576f8ba1/internal/event/core/export.go:45 +0xfd
golang.org/x/tools/internal/event/core.ExportPair({_, _}, {{0x0, 0x0, 0x0}, {{{0x1349260, 0xc000068460}, 0xa, {0xfdac00, 0x1104eee}}, ...}, ...}, ...)
	D:/GoWorks/pkg/mod/golang.org/x/tools@v0.1.12-0.20220630195555-6178576f8ba1/internal/event/core/export.go:68 +0x128
golang.org/x/tools/internal/event.Start({0x134bc88, 0xc0722e4020}, {0x1104eee, 0xc03ce28020}, {0xc04aa7a1e0, 0x0, 0x0})
	D:/GoWorks/pkg/mod/golang.org/x/tools@v0.1.12-0.20220630195555-6178576f8ba1/internal/event/event.go:91 +0x378
golang.org/x/tools/internal/jsonrpc2.(*conn).Notify(0x10, {0x134bc88, 0xc0722e4020}, {0x1104eee, 0xa}, {0xfbede0, 0xc03ce28020})
	D:/GoWorks/pkg/mod/golang.org/x/tools@v0.1.12-0.20220630195555-6178576f8ba1/internal/jsonrpc2/conn.go:85 +0x368
golang.org/x/tools/internal/lsp/protocol.clientConn.Notify(...)
	D:/GoWorks/pkg/mod/golang.org/x/tools@v0.1.12-0.20220630195555-6178576f8ba1/internal/lsp/protocol/protocol.go:60
golang.org/x/tools/internal/lsp/protocol.(*clientDispatcher).Progress(0x134bc88, {0x134bc88, 0xc0722e4020}, 0xd6)
	D:/GoWorks/pkg/mod/golang.org/x/tools@v0.1.12-0.20220630195555-6178576f8ba1/internal/lsp/protocol/tsclient.go:168 +0x42
golang.org/x/tools/internal/lsp/progress.(*WorkDone).Report(0xc023934cd0, {0x0, 0x0}, {0xc012e49960, 0xd6}, 0x0)
	D:/GoWorks/pkg/mod/golang.org/x/tools@v0.1.12-0.20220630195555-6178576f8ba1/internal/lsp/progress/progress.go:188 +0x291
golang.org/x/tools/internal/lsp/progress.(*WorkDoneWriter).Write(0xc03cdca3e0, {0xc01cc3e000, 0xd6, 0x0})
	D:/GoWorks/pkg/mod/golang.org/x/tools@v0.1.12-0.20220630195555-6178576f8ba1/internal/lsp/progress/progress.go:268 +0x5c
io.(*multiWriter).Write(0xc03abd8c80, {0xc01cc3e000, 0xd6, 0x8000})
	D:/src/Go/src/io/multi.go:60 +0x86
io.copyBuffer({0x13349e0, 0xc0091d0ff0}, {0x1334e80, 0xc03abd8c80}, {0x0, 0x0, 0x0})
	D:/src/Go/src/io/io.go:425 +0x204
io.Copy(...)
	D:/src/Go/src/io/io.go:382
os/exec.(*Cmd).writerDescriptor.func1()
	D:/src/Go/src/os/exec/exec.go:311 +0x3a
os/exec.(*Cmd).Start.func1(0xc00022a5c0)
	D:/src/Go/src/os/exec/exec.go:441 +0x25
created by os/exec.(*Cmd).Start
	D:/src/Go/src/os/exec/exec.go:440 +0x8e5
[Error - 10:49:20] Connection to server got closed. Server will not be restarted.

**Comment by findleyr** [comment] 2022-07-12 21:37
This is a dupe of golang/go#53781. Apologies for the breakage: we'll release gopls@v0.9.1 this week with a fix.

**Closed by findleyr** 2022-07-12 21:37 UTC
