### ISSUE TITLE
Testing deeper sub tests result in no test run

### ISSUE THREAD

**Issue by emilhem** [golang/vscode-go#2719] opened 2023-04-03 09:49 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.20.2 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```
Build info
----------
golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20221031165847-c99f073a8326 h1:QfTh0HpN6hlw6D3vu8DAwC8pBIwikq0AI1evdm+FksE=
    golang.org/x/exp/typeparams@v0.0.0-20221031165847-c99f073a8326 h1:fl8k2zg28yA23264d82M4dp+YlJ3ngDcpuB1bewkQi4=
    golang.org/x/mod@v0.7.0 h1:LapD9S96VoQRhi/GrNTqeBJFrUjs5UHCAtTlgwA5oZA=
    golang.org/x/sync@v0.1.0 h1:wsuoTGHzEhffawBOhz5CYhcrV4IdKZbEyZjBMuTp12o=
    golang.org/x/sys@v0.2.0 h1:ljd4t30dBnAvMZaQCevtY0xLLD0A+bRZXbgLMLU1F/A=
    golang.org/x/text@v0.4.0 h1:BrVqGRd7+k1DiOgtnFvAkoQEWQvBc25ouMJM6429SFg=
    golang.org/x/tools@v0.3.1-0.20221213193459-ca17b2c27ca8 h1:7/HkGkN/2ktghBCSRRgp31wAww4syfsW52tj7yirjWk=
    golang.org/x/vuln@v0.0.0-20221109205719-3af8368ee4fe h1:qptQiQwEpETwDiz85LKtChqif9xhVkAm8Nhxs0xnTww=
    honnef.co/go/tools@v0.3.3 h1:oDx7VAwstgpYpb3wv0oxiZlxY+foCpRAwY7Vk6XpAgA=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.20.2
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
```
1.77.0
7f329fe6c66b0f86ae1574c2911b681ad5a45d63
x64
```
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.38.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/emil.hemdal/go
GOROOT: /home/linuxbrew/.linuxbrew/Cellar/go/1.20.2/libexec
PATH: /home/emil.hemdal/.local/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/emil.hemdal/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin

	go:	/home/linuxbrew/.linuxbrew/bin/go: go version go1.20.2 linux/amd64

	gotests:	/home/emil.hemdal/go/bin/gotests	(version: v1.6.0 built with go: go1.20.1)
	gomodifytags:	/home/emil.hemdal/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.20.1)
	impl:	/home/emil.hemdal/go/bin/impl	(version: v1.1.0 built with go: go1.20.1)
	goplay:	/home/emil.hemdal/go/bin/goplay	(version: v1.0.0 built with go: go1.20.1)
	dlv:	/home/emil.hemdal/go/bin/dlv	(version: v1.20.1 built with go: go1.20.1)
	staticcheck:	/home/emil.hemdal/go/bin/staticcheck	(version: v0.4.2 built with go: go1.20.1)
	gopls:	/home/emil.hemdal/go/bin/gopls	(version: v0.11.0 built with go: go1.20.2)

go env
Workspace Folder (snip): /home/emil.hemdal/dev/snip
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/emil.hemdal/.cache/go-build"
	GOENV="/home/emil.hemdal/.config/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/emil.hemdal/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/home/emil.hemdal/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/home/linuxbrew/.linuxbrew/Cellar/go/1.20.2/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/home/linuxbrew/.linuxbrew/Cellar/go/1.20.2/libexec/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.20.2"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="gcc-11"
	CXX="g++-11"
	CGO_ENABLED="1"
	GOMOD="/home/emil.hemdal/dev/snip/go.mod"
	GOWORK=""
	CGO_CFLAGS="-O2 -g"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-O2 -g"
	CGO_FFLAGS="-O2 -g"
	CGO_LDFLAGS="-O2 -g"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3467527775=/tmp/go-build -gno-record-gcc-switches"
```
</details>

### Share the Go related settings you have added/edited

```json
    "go.formatTool": "gofmt",
```

### Describe the bug

Clicking `run test` on a sub level test in VS Code results in `testing: warning: no tests to run`.

What I expect to happen is that the test should run.

Running the tests using the terminal works (i.e. `go test -run=TestingTheTester/2/3 example.com/testingthetester/test`)

### Steps to reproduce the behavior:
1. Create an empty project and add a test directory
2. Add a test file there (like `testingthe_test.go`)
3. Add the following content
```Go
package testingthetester_test

import (
	"testing"
)

func TestTestingTheTester(t *testing.T) {
	t.Log("Level 1")
	t.Run("2", func(t *testing.T) {
		t.Log("Level 2")
		t.Run("3", func(t *testing.T) {
			t.Log("Level 3")
			t.Fatalf("Failing level 3")
		})
		t.Fatalf("Failing level 2")
	})
	t.Fatalf("Failing level 1")
}
```
4. Run the inner most test using the `run test` "middle thingy"

### Screenshots or recordings
[Screencast from 2023-04-03 11:48:22.webm](https://user-images.githubusercontent.com/1503789/229474898-3324fbd7-f8ab-41df-ac74-e848b56ff0a5.webm)

**Comment by findleyr** [comment] 2023-04-04 21:51
Thanks for the report, especially the screencast.

From that output it looks clearly like the subtest pattern is not considering the intermediate subtest name.

CC @hyangah as I didn't find any existing bugs for this.

**Comment by findleyr** [comment] 2023-04-06 16:53
I think we should fix this with https://github.com/golang/go/issues/59445, integrating test discovery with gopls.

Will leave this open to record the bug, so that we can verify it is fixed.

**Comment by hyangah** [comment] 2023-12-05 05:03
Thanks for the detailed report again.
Let's track the progress in #3022.

Duplicate of #3022

**Closed by hyangah** 2023-12-05 05:03 UTC
Labels: go-test
