### ISSUE TITLE
Debug test with specific set of environment variables

### ISSUE THREAD

**Issue by nfx** [golang/vscode-go#2370] opened 2022-07-25 12:47 UTC
**Is your feature request related to a problem? Please describe.**
This extension gives a great code lens to debug a test, though it seems not to be possible to debug test with a different set of environment variables. `.vscode/launch.json` doesn't seem to be picked up. This approach is very handy in troubleshooting regressions or experimenting with an existing code.
<img width="395" alt="image" src="https://user-images.githubusercontent.com/259697/180780111-1655223c-045c-41c8-a538-5dc373647a91.png">

**Describe the solution you'd like**
Ability to debug a GoLang test with different sets of environment variables and possibly other flags.

**Describe alternatives you've considered**
The workaround is to launch vscode process with specific set of environment variables, but this is sub optimal.

**Comment by hyangah** [comment] 2022-07-26 17:34
I think this is a duplicate of [#1293 ](https://github.com/golang/vscode-go/issues/855)

**Comment by hyangah** [comment] 2022-07-28 17:11
Closing this in favor of #1293

**Closed by hyangah** 2022-07-28 17:11 UTC
Labels: Debug, debug/config
