### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by JoseFMP** [golang/vscode-go#1107] opened 2021-01-21 10:39 UTC
The extension works fine but... just extremely slow.

Is there any way to figure out what is the reason?

**Comment by virtumonde** [comment] 2021-01-21 13:20
@JoseFMP did you rule out that it is not trivially occurring because of your large codebase?

**Comment by hyangah** [comment] 2021-01-21 15:53
@JoseFMP Please be more specific - when you observe the slowness (loading time, specific features), and how to reproduce (codebase size, settings, frequencies). Performance issue investigation requires different approaches depending on the nature of the issue.

**Comment by mrjrieke** [comment] 2021-01-23 14:51
I've seen it when a project has a large package dependency tree.  I think it's just really really inefficient with large package trees.  I've seen it completely take over a linux box -- with the only solution: press and hold the reboot button.

**Comment by JoseFMP** [comment] 2021-01-25 04:34
I found out, if I enable the language server, it is blazing fast and all works smoothly perfect.

In the past the language server did not work. Now works like a charm. In my opinion, there should not be any more an option to enable/disable language server. It should be just always on.

**Comment by stamblerre** [comment] 2021-01-25 06:14
Glad to hear that the language server is working for you @JoseFMP! We are planning to enable it by default in the next release: https://github.com/golang/vscode-go/issues/1037.

Going to close this issue, as it has been resolved.

**Closed by stamblerre** 2021-01-25 06:14 UTC

**Comment by mrjrieke** [comment] 2021-01-26 14:37
No, this is still extremely slow.

**Comment by stamblerre** [comment] 2021-01-26 14:57
@mrjrieke: If you are encountering a problem, please open your own issue with the information requested here: https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md.
