### ISSUE TITLE
Doc package links should be clickable

### ISSUE THREAD

**Issue by tylerbrandt** [golang/vscode-go#3374] opened 2024-05-02 17:53 UTC
**Is your feature request related to a problem? Please describe.**

It is a bit frustrating that when I format links in a doc comment like `[package.Symbol]`, `[github.com/fully-qualified/package]`, or `[symbol]`, which are all formats that `pkgsite` supports (https://tip.golang.org/doc/comment#doclinks), vscode-go doesn't do anything with those. If they happen to be links that _VS Code_ recognizes (like fully-qualified GitHub links) it'll open those in the browser, but this isn't what I want either (it should go to the pkg.go.dev page for that package).

**Describe the solution you'd like**
The link should act like a Go type mention (hover over shows preview of docs, command-click goes to definition). Ideally also it would change the syntax highlighting to indicate that this is a "valid" link (which is a productivity boon when authoring such comments, particularly since typos are common and sometimes there's weird gotchas with the formatting). Goland has a really nice implementation of this with both features:

<img width="779" alt="Screenshot 2024-05-02 at 10 52 01 AM" src="https://github.com/golang/vscode-go/assets/1256483/7b0374a2-51f0-46df-bafe-2b89cfdaabed">

**Describe alternatives you've considered**
I have resorted to running a live-updating `entr -r pkgsite` command in the console and using the browser. But it would be nice if I didn't have to leave my editor for that!

**Additional context**

Demo app which has these kinds of links in it: https://github.com/tylerbrandt/godoc-example

**Comment by suzmue** [comment] 2024-05-06 22:48
I believe this is the same feature request as this upstream feature request in golang/go#61677. Please feel free to add your support to that request by reacting or commenting on that issue!

I am going to close this issue as a duplicate of golang/go#61677, but if you believe this is an error, feel free to reopen.

**Closed by suzmue** 2024-05-06 22:48 UTC

**Comment by tylerbrandt** [comment] 2024-05-08 04:14
Ok, I didn’t know this was the language server responsibility but 👍🏻
