### ISSUE TITLE
Tools installation failure: failed to close gocode process

### ISSUE THREAD

**Issue by nikunj321** [golang/vscode-go#376] opened 2020-07-19 09:55 UTC
- Issue Type: `Bug`
- Extension Name: `go`
- Extension Version: `0.15.1`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.47.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by stamblerre** [comment] 2020-07-19 17:22
@nikunj321: Can you please describe the problem you experienced?

**Comment by nikunj321** [comment] 2020-07-20 03:01
while running Go:Install/Update Tools
i got following problem..

Tools environment: GOPATH=C:\Users\Shruvin\go
Installing 17 tools at C:\Users\Shruvin\go\bin in module mode.
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  gotests
  gomodifytags
  impl
  fillstruct
  goplay
  godoctor
  dlv
  gocode-gomod
  godef
  goimports
  golint

Installing github.com/uudashr/gopkgs/v2/cmd/gopkgs SUCCEEDED
Installing github.com/ramya-rao-a/go-outline SUCCEEDED
Installing github.com/acroca/go-symbols SUCCEEDED
Installing golang.org/x/tools/cmd/guru SUCCEEDED
Installing golang.org/x/tools/cmd/gorename SUCCEEDED
Installing github.com/cweill/gotests/... SUCCEEDED
Installing github.com/fatih/gomodifytags SUCCEEDED
Installing github.com/josharian/impl SUCCEEDED
Installing github.com/davidrjenni/reftools/cmd/fillstruct SUCCEEDED
Installing github.com/haya14busa/goplay/cmd/goplay SUCCEEDED
Installing github.com/godoctor/godoctor SUCCEEDED
Installing github.com/go-delve/delve/cmd/dlv SUCCEEDED
Installing github.com/stamblerre/gocode SUCCEEDED
Installing github.com/rogpeppe/godef SUCCEEDED
Installing golang.org/x/tools/cmd/goimports SUCCEEDED
Installing golang.org/x/lint/golint SUCCEEDED

1 tools failed to install.

gocode: Failed to close gocode process: Error: Command failed: C:\Users\Shruvin\go\bin\gocode.exe close
2020/07/20 08:25:55 dial tcp 127.0.0.1:37373: connectex: No connection could be made because the target machine actively refused it.
.

**Comment by hyangah** [comment] 2020-07-20 14:28
Looks like a duplicate of https://github.com/golang/vscode-go/issues/362
Let's follow up there.

**Closed by hyangah** 2020-07-20 14:28 UTC
