### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by johnnylin0828** [golang/vscode-go#3546] opened 2024-09-24 10:05 UTC
gopls version: v0.16.2/go1.22.5
gopls flags: 
update flags: proxy
extension version: 0.42.1
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Tue, 24 Sep 2024 10:04:49 GMT
restart history:
Tue, 24 Sep 2024 10:04:47 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic:   stmt.go:932: assertion failed

goroutine 3823 [running]:
go/types.(*Checker).handleBailout(0x14004d62e00, 0x14005fad878)
	  check.go:367  0x9c
panic({0x1034b3460%3F, 0x14005ee9330%3F})
	  panic.go:770  0x124
go/types.assert(0x0%3F)
	  errors.go:28  0x60
go/types.(*Checker).rangeStmt(0x14004d62e00, 0x3, 0x14001ec1bc0)
	  stmt.go:932  0xb58
go/types.(*Checker).stmt(0x14004d62e00, 0x3, {0x10363d120, 0x14001ec1bc0})
	  stmt.go:827  0x874
go/types.(*Checker).stmtList(0x14004d62e00, 0x3, {0x1400326ef00%3F, 0x1031351cf%3F, 0x5%3F})
	  stmt.go:121  0x88
go/types.(*Checker).stmt(0x14004d62e00, 0x3, {0x10363d0c0, 0x14000472e10})
	  stmt.go:562  0x1974
go/types.(*Checker).rangeStmt(0x14004d62e00, 0x3, 0x14001ec1ce0)
	  stmt.go:993  0x570
go/types.(*Checker).stmt(0x14004d62e00, 0x0, {0x10363d120, 0x14001ec1ce0})
	  stmt.go:827  0x874
go/types.(*Checker).stmtList(0x14004d62e00, 0x0, {0x14000572800%3F, 0x1031351cf%3F, 0x5%3F})
	  stmt.go:121  0x88
go/types.(*Checker).stmt(0x14004d62e00, 0x0, {0x10363d0c0, 0x14000473710})
	  stmt.go:562  0x1974
go/types.(*Checker).stmt(0x14004d62e00, 0x0, {0x10363d090, 0x1400326f940})
	  stmt.go:574  0x258c
go/types.(*Checker).stmtList(0x14004d62e00, 0x0, {0x14000570700%3F, 0x0%3F, 0x0%3F})
	  stmt.go:121  0x88
go/types.(*Checker).funcBody(0x14004d62e00, 0x103639658%3F, {0x14003240920%3F, 0x14004e5ab70%3F}, 0x1400209b740, 0x14000473890, {0x0%3F, 0x0%3F})
	  stmt.go:41  0x21c
go/types.(*Checker).funcDecl.func1()
	  decl.go:852  0x44
go/types.(*Checker).processDelayed(0x14004d62e00, 0x0)
	  check.go:467  0x12c
go/types.(*Checker).checkFiles(0x14004d62e00, {0x14004d63000, 0x36, 0x40})
	  check.go:411  0x188
go/types.(*Checker).Files(...)
	  check.go:372
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).checkPackage(0x140040312c0, {0x10363e408, 0x14003deed80}, 0x14000be46c0)
	  check.go:1543  0x788
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).handleSyntaxPackage(0x140040312c0, {0x10363e408, 0x14003deed80}, 0x0, {0x140005ec2e8, 0x12})
	  check.go:568  0x534
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackageInternal.func2()
	  check.go:418  0x34
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 3022
	  errgroup.go:75  0x98
</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 827 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-09-26 16:14
Dupe of golang/go#68334. Please upgrade to Go 1.22.6 or later.

**Closed by findleyr** 2024-09-26 16:14 UTC
