### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by KarthickRaja-Jaze** [golang/vscode-go#3535] opened 2024-09-13 07:26 UTC
gopls version: v0.16.2/go1.22.5
gopls flags: 
update flags: proxy
extension version: 0.42.1
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Fri, 13 Sep 2024 07:26:22 GMT
restart history:
Fri, 13 Sep 2024 07:26:20 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic:   stmt.go:932: assertion failed

goroutine 5130 [running]:
go/types.(*Checker).handleBailout(0xc0055ad000, 0xc006379898)
	  check.go:367  0x88
panic({0xe9d620%3F, 0xc0065c7520%3F})
	  panic.go:770  0x132
go/types.assert(0x0%3F)
	  errors.go:28  0x54
go/types.(*Checker).rangeStmt(0xc0055ad000, 0x3, 0xc00091d620)
	  stmt.go:932  0xe70
go/types.(*Checker).stmt(0xc0055ad000, 0x3, {0x131bd08, 0xc00091d620})
	  stmt.go:827  0xab9
go/types.(*Checker).stmtList(0xc0055ad000, 0x3, {0xc00287f7e0%3F, 0x101ac01%3F, 0x5%3F})
	  stmt.go:121  0x85
go/types.(*Checker).stmt(0xc0055ad000, 0x3, {0x131bca8, 0xc0028b2750})
	  stmt.go:562  0x20f2
go/types.(*Checker).stmt(0xc0055ad000, 0x3, {0x131bc78, 0xc00371f3c0})
	  stmt.go:574  0x3017
go/types.(*Checker).stmtList(0xc0055ad000, 0x3, {0xc00371f480%3F, 0x101ac01%3F, 0x5%3F})
	  stmt.go:121  0x85
go/types.(*Checker).stmt(0xc0055ad000, 0x3, {0x131bca8, 0xc0028b27b0})
	  stmt.go:562  0x20f2
go/types.(*Checker).stmt(0xc0055ad000, 0x3, {0x131bc78, 0xc00371f540})
	  stmt.go:574  0x3017
go/types.(*Checker).stmtList(0xc0055ad000, 0x3, {0xc00287f8b0%3F, 0x101ac01%3F, 0x5%3F})
	  stmt.go:121  0x85
go/types.(*Checker).stmt(0xc0055ad000, 0x3, {0x131bca8, 0xc0028b27e0})
	  stmt.go:562  0x20f2
go/types.(*Checker).stmt(0xc0055ad000, 0x3, {0x131bc78, 0xc00371f580})
	  stmt.go:574  0x3017
go/types.(*Checker).stmtList(0xc0055ad000, 0x3, {0xc0028b93c0%3F, 0x101ac01%3F, 0x5%3F})
	  stmt.go:121  0x85
go/types.(*Checker).stmt(0xc0055ad000, 0x3, {0x131bca8, 0xc0028b2810})
	  stmt.go:562  0x20f2
go/types.(*Checker).rangeStmt(0xc0055ad000, 0x3, 0xc00091d680)
	  stmt.go:993  0x74d
go/types.(*Checker).stmt(0xc0055ad000, 0x0, {0x131bd08, 0xc00091d680})
	  stmt.go:827  0xab9
go/types.(*Checker).stmtList(0xc0055ad000, 0x0, {0xc000ab1688%3F, 0x0%3F, 0x45929e%3F})
	  stmt.go:121  0x85
go/types.(*Checker).funcBody(0xc0055ad000, 0x1319388%3F, {0xc0005b6f30%3F, 0xc000144380%3F}, 0xc003ab2080, 0xc0028b2840, {0x0%3F, 0x0%3F})
	  stmt.go:41  0x331
go/types.(*Checker).funcDecl.func1()
	  decl.go:852  0x3a
go/types.(*Checker).processDelayed(0xc0055ad000, 0x0)
	  check.go:467  0x162
go/types.(*Checker).checkFiles(0xc0055ad000, {0xc000655b00, 0x15, 0x20})
	  check.go:411  0x1cc
go/types.(*Checker).Files(...)
	  check.go:372
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).checkPackage(0xc004cf4060, {0x131d0a8, 0xc00409e8a0}, 0xc003ef50e0)
	  check.go:1543  0xa25
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).handleSyntaxPackage(0xc004cf4060, {0x131d0a8, 0xc00409e8a0}, 0x0, {0xc000714360, 0x10})
	  check.go:568  0x5e5
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackageInternal.func2()
	  check.go:418  0x2b
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 3398
	  errgroup.go:75  0x96
</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 1157 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2024-09-13 12:19
Duplicate of https://github.com/golang/go/issues/68334.
Please install go 1.22.6 or newer, and reinstall gopls. Thanks!

**Closed by hyangah** 2024-09-13 12:19 UTC
