### ISSUE TITLE
Folded code unfolds on syntax error

### ISSUE THREAD

**Issue by infinitepr0** [golang/vscode-go#1224] opened 2021-02-12 11:48 UTC
### What version of Go, VS Code & VS Code Go extension are you using?

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
`go version go1.15.8 linux/amd64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```
Build info
----------
golang.org/x/tools/gopls v0.6.5
    golang.org/x/tools/gopls@v0.6.5 h1:kLt9rD/dWtVdvc8LmdcxagDFih6zxYXREpKSYYZu5KE=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.4 h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.0 h1:8pl+sMODzuvGJkmj2W4kZihvVb5mKm8pB/X44PIQHv8=
    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
    golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=
    golang.org/x/tools@v0.1.1-0.20210201201750-4d4ee958a9b7 h1:/wdPW261t381NDQd8TBo63/FyvACfLICwtH8wMRoHJQ=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.0.1-2020.1.6 h1:W18jzjh8mfPez+AwGLxmOImucz/IFjpNlrKVnaj2YVc=
    mvdan.cc/gofumpt@v0.1.0 h1:hsVv+Y9UsZ/mFZTxJZuHVI6shSQCtzZ11h1JEFPAZLw=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```

* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
```
1.53.2
622cb03f7e070a9670c94bae1a45d78d7181fbd4
x64
```

* Check your installed extensions to get the version of the VS Code Go extension
`0.22.1`
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/infinitepro/go
GOROOT: /usr/lib/go
PATH: /home/infinitepro/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

   gopkgs: /home/infinitepro/go/bin/gopkgs installed
   go-outline: /home/infinitepro/go/bin/go-outline installed
   gotests: /home/infinitepro/go/bin/gotests installed
   gomodifytags: /home/infinitepro/go/bin/gomodifytags installed
   impl: /home/infinitepro/go/bin/impl installed
   goplay: /home/infinitepro/go/bin/goplay installed
   dlv: /home/infinitepro/go/bin/dlv installed
   golint: /home/infinitepro/go/bin/golint installed
   gopls: /home/infinitepro/go/bin/gopls installed

go env
Workspace Folder (cpt-lib): /home/infinitepro/Desktop/GitHub/cp-tools/cpt-lib
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/infinitepro/.cache/go-build"
	GOENV="/home/infinitepro/.config/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/infinitepro/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/home/infinitepro/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/lib/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/home/infinitepro/Desktop/GitHub/cp-tools/cpt-lib/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build229485445=/tmp/go-build -gno-record-gcc-switches"
```

### Describe the bug
- Write some foldable code (loop, conditional statements etc).
- Fold the code blocks.
- Start writing a new line of code and stop midway (ensure there is a syntax error)
- Have the previously folded code automatically unfolded.

### Screenshots or recordings

https://user-images.githubusercontent.com/45997896/107764268-ec5b8280-6d55-11eb-9f12-e00bdf66dcee.mp4

**Comment by hyangah** [comment] 2021-02-12 14:50
@infinitepr0 Thanks for the report. 

@stamblerre This looks like a duplicate of https://github.com/golang/go/issues/41281.

I folded `F` below. As soon as I entered `if`, gopls detected the incomplete statement as an error and sent out the folding range response that doesn't include ranges below the problematic statement. (message 9)
The issue 41281 is currently classified as 'unplanned'.  Folding action is not stored and hard for users to recover the lost folding range when it is removed due to the missing foldingRange info caused by (transient) errors. 

```
package main

func main() {
	for i := 0; i < 10; i++ {
		println(F())
	}
	if
}

// F is ... folded
func F() int {
	x++
	return x
}
```

gopls trace.

```
...

[Trace - 09:31:36.893 AM] Sending request 'textDocument/foldingRange - (7)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/w/main.go"}}


[Trace - 09:31:36.893 AM] Received response 'textDocument/foldingRange - (7)' in 0ms.
Result: [{"startLine":2,"startCharacter":13,"endLine":5,"endCharacter":2},{"startLine":3,"startCharacter":26,"endLine":4,"endCharacter":14},{"startLine":10,"startCharacter":14,"endLine":12,"endCharacter":9}]

..

[Trace - 09:31:37.042 AM] Sending notification 'textDocument/didChange'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/w/main.go","version":3},"contentChanges":[{"range":{"start":{"line":6,"character":1},"end":{"line":6,"character":1}},"rangeLength":0,"text":"i"}]}


[Trace - 09:31:37.044 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///Users/hakim/projects/google/w/main.go","version":3,"diagnostics":[{"range":{"start":{"line":6,"character":1},"end":{"line":6,"character":2}},"severity":1,"source":"compiler","message":"undeclared name: i"}]}


[Trace - 09:31:37.153 AM] Sending notification 'textDocument/didChange'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/w/main.go","version":4},"contentChanges":[{"range":{"start":{"line":6,"character":2},"end":{"line":6,"character":2}},"rangeLength":0,"text":"f"}]}


[Trace - 09:31:37.156 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///Users/hakim/projects/google/w/main.go","version":4,"diagnostics":[{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":0}},"severity":1,"source":"syntax","message":"expected operand, found '}'"}]}


[Trace - 09:31:37.351 AM] Sending request 'textDocument/foldingRange - (9)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/w/main.go"}}


[Trace - 09:31:37.352 AM] Received response 'textDocument/foldingRange - (9)' in 0ms.
Result: [{"startLine":3,"startCharacter":26,"endLine":4,"endCharacter":14}]

**Comment by stamblerre** [comment] 2021-02-12 15:59
This is caused by the fundamental issue with the Go parser, which is that it doesn't recover well from syntax errors. This is the same reason that you won't get completion results for code that is below a syntax error. I believe @findleyr can speak to plans for parser improvements, but at the earliest, this could be fixed for Go 1.17.

**Comment by hyangah** [comment] 2021-02-12 16:26
Thanks for the explanation. Maybe I am too naive - what will happen if gopls returns an error when the parse error is detected?

I just tried to make FoldingRange query fail if pgf.ParseError != nil in https://github.com/golang/tools/blob/9eba6e1578c0e266628eefd47f0b750a6a63cf07/internal/lsp/source/folding_range.go#L23, and it seems like vscode preserves the folding range. But I am not sure what side-effect this would cause eventually.

```
[Trace - 11:19:57.825 AM] Sending request 'textDocument/foldingRange - (14)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/w/main.go"}}


[Error - Received] 11:19:57.826 AM #14 /Users/hakim/projects/google/w/main.go:13:1: expected operand, found '}' (and 3 more errors)


[Error - 11:19:57 AM] Request textDocument/foldingRange failed.
  Message: /Users/hakim/projects/google/w/main.go:13:1: expected operand, found '}' (and 3 more errors)
  Code: 0 
[Trace - 11:19:58.357 AM] Sending request 'textDocument/codeLens - (15)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/w/main.go"}}
```

**Comment by stamblerre** [comment] 2021-02-12 16:29
Oh that's totally fine if you want to send that CL. I tried having it return empty results, but forgot about the error 😄 . The only possibility is that other LSP clients don't handle this gracefully and constantly pop-up an error to the user.

**Comment by mattwelke** [comment] 2021-02-13 03:12
> This is caused by the fundamental issue with the Go parser, which is that it doesn't recover well from syntax errors. This is the same reason that you won't get completion results for code that is below a syntax error.

This is something I encounter *all the time*. I often make some change that makes my code invalid until I'm done, and then edit code elsewhere in my file. A recent example I remember was editing log lines. I could have really used code completion for all the variables I wanted to add to `fmt.Printf`'s arguments after the string. Having code completion work even when I have a syntax error would be great.

**Comment by hyangah** [comment] 2021-04-13 15:35
I believe the fix was released with v0.23.1 & gopls v0.6.7. 
Please reopen or update the issue if it's still not working. Thanks!

**Comment by mattwelke** [comment] 2021-04-13 17:57
Fixed for me for latest go and gopls installed into VS Code today:

![image](https://user-images.githubusercontent.com/7719209/114598695-32529b00-9c60-11eb-9f0c-875f05d4cb9e.png)

Stopping typing and saving both don't unfold code.

**Comment by thebenjhoward** [comment] 2022-02-07 00:19
It would appear that this error has returned. Currently on gopls v0.7.5, but I believe I updated a few versions last time, so I'm not sure when this was reintroduced. Please reopen issue. Here are the errors output to the console with filenames removed. The extra spaces in the first 2 are intentional

```
[Error - 4:17:36 PM] 2022/02/06 16:17:36 unable to compute positions for type errors: no parsed file for  in [redacted]
	package="[redacted]"

[Error - 4:17:37 PM] 2022/02/06 16:17:37 unable to compute positions for type errors: no parsed file for  in [redacted]
	package="[redacted]"

[Error - 4:17:37 PM] 2022/02/06 16:17:37 DocumentSymbols failed: invalid pos
	URI=file:///[redacted].go
```

**Comment by hyangah** [comment] 2022-02-12 14:53
@thebenjhoward Can you please file a new bug report with a reproducer?
The maintainers don't read closed issues regularly, and it can be a different issue (for example, I see the example in https://github.com/golang/vscode-go/issues/1224#issuecomment-778240476 works as expected, but some other cases not working as expected).

**Closed by hyangah** 2022-02-12 14:53 UTC
Labels: upstream-tools, gopls
