### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by driif** [golang/vscode-go#3199] opened 2024-02-28 09:35 UTC
gopls version: v0.15.0/go1.22.0
gopls flags: 
update flags: proxy
extension version: 0.41.1
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Wed, 28 Feb 2024 09:35:24 GMT
restart history:
Wed, 28 Feb 2024 08:59:08 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: incomplete panic trace.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 6036,
    "TestdataFiles": 4,
    "GoFiles": 362,
    "ModFiles": 2,
    "Dirs": 1237
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.0",
  "GoplsVersion": "v0.15.0",
  "InitialWorkspaceLoadDuration": "1.058668875s",
  "MemStats": {
    "HeapAlloc": 99150912,
    "HeapInUse": 154992640,
    "TotalAlloc": 1087308320
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 3505,
      "Largest": 1062398,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.21.5",
        "AllPackages": {
          "Packages": 692,
          "LargestPackage": 141,
          "CompiledGoFiles": 3512,
          "Modules": 105
        },
        "WorkspacePackages": {
          "Packages": 115,
          "LargestPackage": 36,
          "CompiledGoFiles": 374,
          "Modules": 2
        },
        "Diagnostics": 8
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-02-28 14:05
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

This seems like it may be a duplicate of #3194.

**Closed** 2024-03-13 18:08 UTC
Labels: WaitingForInfo
