### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Torwang1** [golang/vscode-go#1974] opened 2021-12-28 07:17 UTC
gopls version: v0.7.4
gopls flags: 
update flags: proxy
extension version: 0.30.0
go version: 1.16.9
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Tue, 28 Dec 2021 07:17:43 GMT
restart history:
Mon, 27 Dec 2021 07:40:38 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: index out of range [1] with length 1

goroutine 128 [running]:
golang.org/x/tools/internal/lsp/template.weakMatch(0xc00267f4f0, 0x1, 0xc0025509e6, 0x7, 0x3ff0000000000000)
	  completion.go:278  0x179
golang.org/x/tools/internal/lsp/template.(*completer).complete(0xc001b66ed8, 0x42, 0xc001a8e4b7, 0x3b)
	  completion.go:137  0xfdd
golang.org/x/tools/internal/lsp/template.Completion(0x1cd3218, 0xc00064b940, 0x1ce7518, 0xc000db9d00, 0x1cdd778, 0xc001c83380, 0xb00000093, 0x3ff0000000000000, 0x0, 0x0, ...)
	  completion.go:58  0x3c6
golang.org/x/tools/internal/lsp.(*Server).completion(0xc000631c20, 0x1cd3218, 0xc00064b940, 0xc0024de000, 0x0, 0x0, 0x0)
	  completion.go:37  0xe70
golang.org/x/tools/internal/lsp.(*Server).Completion(0xc000631c20, 0x1cd3218, 0xc00064b940, 0xc0024de000, 0xc0024de000, 0x0, 0x0)
	  server_gen.go:32  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1cd3218, 0xc00064b940, 0x1ceb0b8, 0xc000631c20, 0xc000a94660, 0x1cd3480, 0xc00064b8c0, 0x0, 0x0, 0x1cc1280)
	  tsserver.go:398  0x278a
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1cd3218, 0xc00064b940, 0xc000a94660, 0x1cd3480, 0xc00064b8c0, 0x0, 0xc06acc63966fb2b8)
	  protocol.go:154  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1cd3218, 0xc00064b940, 0xc000a94660, 0x1cd3480, 0xc00064b8c0, 0x0, 0x0)
	  lsprpc.go:506  0x459
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1cd3218, 0xc00064b940, 0xc0002138a8, 0x1cd3480, 0xc00064b8c0, 0x0, 0x0)
	  handler.go:35  0xd7
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0000b6900, 0xc0003ea960, 0xc0000a8d10, 0x1cd3218, 0xc00064b940, 0xc0002138a8, 0x1cd3480, 0xc00064b8c0)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 3:17:34 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2022-01-04 14:22
Thank you for the report. This is a duplicate of golang/go#50430.

**Closed by findleyr** 2022-01-04 14:22 UTC
