### ISSUE TITLE
Weird completion behaviour

### ISSUE THREAD

**Issue by aol-nnov** [golang/vscode-go#3004] opened 2023-10-11 12:26 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.19.6 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
----------
golang.org/x/tools/gopls v0.13.2
    golang.org/x/tools/gopls@v0.13.2 h1:Pyvx6MKvatbX3zzZmdGiFRfQZl0ohPlt2sFxO/5j6Ro=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e h1:+WEEuIdZHnUeJJmEUjyYC2gfUMj69yZXw17EnHg/otA=
    golang.org/x/exp/typeparams@v0.0.0-20221212164502-fae10dda9338 h1:2O2DON6y3XMJiQRAS1UWU+54aec2uopH3x7MAiqGW6Y=
    golang.org/x/mod@v0.12.0 h1:rmsUpXtvNzj340zd98LZ4KntptpfRHwpFOHG188oHXc=
    golang.org/x/sync@v0.3.0 h1:ftCYgMx6zT/asHUrPw8BLLscYtGznsLAnjq5RH9P66E=
    golang.org/x/sys@v0.10.0 h1:SqMFp9UcQJZa+pmYuAKjd9xq1f0j5rLcDIk0mj4qAsA=
    golang.org/x/text@v0.11.0 h1:LAntKIrcmeSKERyiOh0XMV39LXS8IE9UL2yP7+f5ij4=
    golang.org/x/tools@v0.11.2-0.20230810185051-cc6b5804b8cf h1:Oush7UwPamr2/iNeNFBuNFj89YyHn0YY69EKDdvANnk=
    golang.org/x/vuln@v0.0.0-20230110180137-6ad3e3d07815 h1:A9kONVi4+AnuOr1dopsibH6hLi1Huy54cbeJxnq4vmU=
    honnef.co/go/tools@v0.4.2 h1:6qXr+R5w+ktL5UkwEbPp+fEvfyoMPche6GkOpGHZcLc=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.19.6
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.83.0
e7e037083ff4455cf320e344325dacb480062c3c
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.39.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: /Users/aol/go/bin
toolsGopath: 
gopath: /Users/aol/go
GOROOT: /usr/local/Cellar/go/1.19.6/libexec
PATH: /Users/aol/.nvm/versions/node/v18.10.0/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/aol/go/bin:/Users/aol/bin:/tool/bin:/Users/aol/Library/Android/sdk/platform-tools:/usr/local/opt/node@16/bin:/usr/local/opt/heroku-node/bin

	go:	/usr/local/bin/go: go version go1.19.6 darwin/amd64

	gotests:	not installed
	gomodifytags:	not installed
	impl:	not installed
	goplay:	not installed
	dlv:	/Users/aol/go/bin/dlv	(version: v1.20.1 built with go: go1.19.6)
	staticcheck:	/Users/aol/go/bin/staticcheck	(version: v0.4.3 built with go: go1.19.6)
	gopls:	/Users/aol/go/bin/gopls	(version: v0.13.2 built with go: go1.19.6)

go env
Workspace Folder (ci-vars): /Users/aol/develop/<redacted>/gitlab/ci-vars
	GO111MODULE="on"
	GOARCH="amd64"
	GOBIN="/Users/aol/go/bin"
	GOCACHE="/Users/aol/Library/Caches/go-build"
	GOENV="/Users/aol/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/aol/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/aol/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/Cellar/go/1.19.6/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/Cellar/go/1.19.6/libexec/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.19.6"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/aol/develop/<redacted>/ci-vars/go.mod"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j1/kyq29sy55mnfywx0d9bf08n40000gn/T/go-build1499354943=/tmp/go-build -gno-record-gcc-switches -fno-common"
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```
    "go.toolsManagement.autoUpdate": true,
    "go.testFlags": [
        "-v"
    ],
    "go.survey.prompt": false,
    "gopls": {
        "ui.semanticTokens": true
    },
```

### Describe the bug
I start typing, say, `os.getenv`, an IntelliSense popup appears, showing a single suggestion `Getenv`. I press enter, suggestion is applied, but also function argument is filled with a word. I end up with `os.Getenv(key)` with cursor blinking after closing bracket. If I press backspace, I can erase closing bracket and the word `key` - I mean, it's all plain text in the editor. It's an empty file with no other code in it and I do not have any local variable called `key`.

Expected behaviour is as follows:

I start typing, say, `os.getenv`, an IntelliSense popup appears, showing a single suggestion `Getenv`. I press enter, suggestion is applied, I end up with `os.Getenv()` with cursor blinking between brackets.

It seems to me like a regression as I was coding in golang using this vscode profile before (few months ago). I've installed vscode and vscode-go updates since then. Today I returned to golang programming and hit such an annoying thing...

### Steps to reproduce the behavior:

1. start with empty file, say

```
package main

func main() {

}
```
2. place cursor inside main function and start typing `os.getenv`
3. press enter to apply IntelliSense suggestion 

### Screenshots or recordings
result after applying IntelliSense suggestion
```
package main

import "os"

func main() {
	os.Getenv(key)<-cursor is here, no text fragments are selected
}
```

**Comment by aol-nnov** [comment] 2023-10-11 12:32
Also, I was able to reproduce it in a clean profile with no extra plugins installed

**Comment by hyangah** [comment] 2023-10-12 17:29
Thanks for the report. Unfortunately, I cannot reproduce it yet with gopls v0.13.2 and the latest vscode-go&vscode.
Do you mind capturing the gopls trace and sharing it with us? The instruction is here: https://github.com/golang/vscode-go/wiki/troubleshooting#collect-gopls-information

Since this could be related to the settings/configuration, trace starting from the 'initialize' message to the completion suggestion is needed for triaging. Also, if you have other editor-related settings, please share it with us.

**Comment by aol-nnov** [comment] 2023-10-12 17:36
@hyangah, will do! As soon as I get to my work place. It'll take 12 hrs approximately..

> Also, if you have other editor-related settings, please share it with us.

As I mentioned earlier, I've managed to reproduce it even in clear profile.. so, gopls trace is the best bet, I'm afraid..

I'll fiddle with it tomorrow and will return back with additional info.

// glad, it's not a global bug,though )

**Comment by aol-nnov** [comment] 2023-10-13 11:19
@hyangah please find the requested trace attached. Let me know, if you need any additional info.
[gopls_trace.txt](https://github.com/golang/vscode-go/files/12892864/gopls_trace.txt)

**Comment by aol-nnov** [comment] 2023-10-13 13:20
Yay! It's fixed in v0.14.0-pre.2!

v0.14.0-pre.2 yields:

```
package main

import "os"

func main() {
	os.Getenv()
}
```

With cursor placed inside brackets and all arguments-relevant info is shown inside a popup!

Love this behaviour!

**Comment by hyangah** [comment] 2023-10-13 15:10
Thanks for sharing the trace and trying v0.14.0-pre.2. 
Looks like this is a dup of https://github.com/golang/go/issues/62676 which was fixed in v0.14.0 dev cycle.
(I think my vscode was probably still using v0.14.0-pre.2, not v0.13.2. My apologies for the misinformation)

**Comment by hyangah** [comment] 2023-10-13 15:13
Duplicate of golang/go#62676

**Closed by hyangah** 2023-10-13 15:13 UTC
Labels: gopls, gopls/completion

**Comment by vuon9** [comment] 2023-10-21 16:39
```
go install golang.org/x/tools/gopls@v0.14.0-pre.4
```
Temporary fix until the next stable release.
