### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by sainamercy** [golang/vscode-go#3274] opened 2024-03-22 07:27 UTC
gopls version: v0.15.2/go1.18.1
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Fri, 22 Mar 2024 07:26:47 GMT
restart history:
Fri, 22 Mar 2024 05:57:11 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.0" (should be something like "go1.12")

goroutine 3750 [running]:
go/types.NewChecker(0x0%3F, 0xc0008bd440, 0xc00262c370, 0x0%3F)
	  check.go:240  0x279
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc001d43340, {0xc003f5da00, 0x1, 0x1})
	  analysis.go:1028  0x6f1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc001d43340, {0x1031b58, 0xc0003fa1b0})
	  analysis.go:810  0xd9
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc001d43340, {0x1031b58%3F, 0xc0003fa1b0})
	  analysis.go:672  0x145
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xda
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 76,
    "TestdataFiles": 0,
    "GoFiles": 16,
    "ModFiles": 1,
    "Dirs": 51
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.18.1",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "557.912645ms",
  "MemStats": {
    "HeapAlloc": 30750344,
    "HeapInUse": 47120384,
    "TotalAlloc": 449050784
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 1822,
      "Largest": 395043,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.1",
        "AllPackages": {
          "Packages": 295,
          "LargestPackage": 161,
          "CompiledGoFiles": 1818,
          "Modules": 43
        },
        "WorkspacePackages": {
          "Packages": 9,
          "LargestPackage": 3,
          "CompiledGoFiles": 16,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment] 2024-03-25 21:11
Duplicate of #3276

**Closed by suzmue** 2024-03-25 21:11 UTC
