### ISSUE TITLE
x/tools/gopls: crash with unexpected composite literal type (redux)

### ISSUE THREAD

**Issue by WilburXu** [golang/vscode-go#2916] opened 2023-08-04 08:35 UTC
gopls version: v0.13.1 (go1.19.8)
gopls flags: 
update flags: proxy
extension version: 0.39.1
go version: 1.19.8
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Fri, 04 Aug 2023 08:35:25 GMT
restart history:
Fri, 04 Aug 2023 08:30:27 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: unexpected composite literal type: *gitlab.xunlei.cn/xlppc/drive/pkg/task/postshare/runner.Node

goroutine 11423 [running]:
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0xc00ca479e0, {0x100d80840%3F, 0xc004493e00%3F})
	  find.go:389  0x128c
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0xc00ca479e0, {0x100d80840%3F, 0xc004493e40%3F})
	  find.go:384  0x132b
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0xc00ca479e0, {0x100d80840%3F, 0xc004493e80%3F})
	  find.go:362  0x118e
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0xc00ca479e0, {0x100d80840%3F, 0xc004493f00%3F})
	  find.go:362  0x118e
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0xc00ca479e0, {0x100d80840%3F, 0xc0044a2e00%3F})
	  find.go:384  0x132b
golang.org/x/tools/refactor/satisfy.(*Finder).stmt(0xc00ca479e0, {0x100d80600%3F, 0xc0044a2e40%3F})
	  find.go:538  0x11fb
golang.org/x/tools/refactor/satisfy.(*Finder).stmt(0xc00ca479e0, {0x100d80720%3F, 0xc004c99ad0%3F})
	  find.go:588  0x13e5
golang.org/x/tools/refactor/satisfy.(*Finder).Find(0xc00ca479e0, 0xc00b721180%3F, {0xc00c6bf800, 0x2, 0x10001123f%3F})
	  find.go:106  0x216
golang.org/x/tools/gopls/internal/lsp/source.(*renamer).satisfy(0xc00ae59c00)
	  rename_check.go:836  0xd3
golang.org/x/tools/gopls/internal/lsp/source.(*renamer).checkMethod(0xc00ae59c00, 0xc007ba3800)
	  rename_check.go:753  0x3b9
golang.org/x/tools/gopls/internal/lsp/source.(*renamer).check(0xc00ae59c00, {0x100d8abd8, 0xc007ba3800%3F})
	  rename_check.go:105  0x1a5
golang.org/x/tools/gopls/internal/lsp/source.renameObjects({0xc00ac69200%3F, 0xc000ec9a40%3F}, {0x0%3F, 0xc002620160%3F}, {0xc00ce88cd8, 0x11}, {0x100d883c8, 0xc00bb2a3f0}, {0xc00c6bf7f0, 0x1, ...})
	  rename.go:1031  0x26d
golang.org/x/tools/gopls/internal/lsp/source.renameExported({0x100d82140, 0xc0036fc8a0}, {0x100d8ec38, 0xc002620160}, {0xc00754c900, 0x8, 0x203000%3F}, {0xc0029e0e40, 0x26}, {0xc00c575c80, ...}, ...)
	  rename.go:608  0x259
golang.org/x/tools/gopls/internal/lsp/source.renameOrdinary({0x100d82140, 0xc0036fc8a0}, {0x100d8ec38, 0xc002620160}, {0x100d830e0, 0xc00367f7a0}, {0x83849d%3F, 0x1%3F}, {0xc00ce88cd8, 0x11})
	  rename.go:448  0x927
golang.org/x/tools/gopls/internal/lsp/source.Rename({0x100d82140%3F, 0xc0036fc750%3F}, {0x100d8ec38, 0xc002620160}, {0x100d830e0, 0xc00367f7a0}, {0x0%3F, 0x0%3F}, {0xc00ce88cd8, 0x11})
	  rename.go:234  0x1d7
golang.org/x/tools/gopls/internal/lsp.(*Server).rename(0x10096f260%3F, {0x100d82098, 0xc001bafd80}, 0xc000ec9780)
	  rename.go:29  0x22b
golang.org/x/tools/gopls/internal/lsp.(*Server).Rename(0xc001a6e6e0%3F, {0x100d82098%3F, 0xc001bafd80%3F}, 0x10096f260%3F)
	  server_gen.go:216  0x25
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch({0x100d82098, 0xc001bafd80}, {0x100d922d0, 0xc0001781c0}, 0xc0036fc4e0, {0x100d82370, 0xc001bafd00})
	  tsserver.go:537  0xe05
golang.org/x/tools/gopls/internal/lsp/protocol.ServerHandler.func1({0x100d82098, 0xc001bafd80}, 0xc0036fc4e0, {0x100d82370, 0xc001bafd00})
	  protocol.go:157  0x90
golang.org/x/tools/gopls/internal/lsp/lsprpc.handshaker.func1({0x100d82098, 0xc001bafd80}, 0xc0036fc4e0, {0x100d82370%3F, 0xc001bafd00%3F})
	  lsprpc.go:519  0xa39
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x100d82098, 0xc001bafd80}, 0xc00b9ff410, {0x100d82370%3F, 0xc001bafd00%3F})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20a
[Error - 16:35:15] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2023-08-04 12:01
Looks like a duplicate of https://github.com/golang/go/issues/61640 or similar. 

cc @findleyr

**Comment by findleyr** [comment] 2023-08-07 15:33
Closing as dupe of golang/go#61813. Will fix with high priority.

**Closed by findleyr** 2023-08-07 15:33 UTC
