### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by latte-go** [golang/vscode-go#2078] opened 2022-02-22 09:01 UTC
gopls version: v0.7.5
gopls flags: 
update flags: proxy
extension version: 0.31.1
go version: 1.17
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Tue, 22 Feb 2022 09:01:31 GMT
restart history:
Tue, 22 Feb 2022 08:38:39 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2022-02-22 21:24
Closing, as the issue is empty.
Please reopen if you can share the stack trace of the gopls crash (found by navigating to View -> Output -> Tasks -> gopls (server)).

**Closed by findleyr** 2022-02-22 21:24 UTC
