### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by weiliu2-Leo** [golang/vscode-go#3369] opened 2024-04-29 08:27 UTC
gopls version: v0.15.3/go1.22.2
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Mon, 29 Apr 2024 08:27:27 GMT
restart history:
Mon, 29 Apr 2024 08:26:57 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: slice bounds out of range [:-1]

goroutine 18968 [running]:
golang.org/x/tools/gopls/internal/protocol.(*Mapper).LineCol8Position(0xc016734c60, 0x1, 0x0)
	  mapper.go:151  0x1ad
golang.org/x/tools/gopls/internal/cache.goPackagesErrorDiagnostics.func1({{0x0, 0x0}, {0xc00aa5f650, 0x6e}, 0x1}, 0x6e%3F, {0x128b8a0, 0xc0004fe360}, {0x1293d00, 0xc014f03d10})
	  errors.go:58  0x145
golang.org/x/tools/gopls/internal/cache.goPackagesErrorDiagnostics({0x1293d00, 0xc014f03d10}, {{0x0, 0x0}, {0xc00aa5f650, 0x6e}, 0x1}, 0xc00db30500, {0x128b8a0, 0xc0004fe360})
	  errors.go:69  0xf5
golang.org/x/tools/gopls/internal/cache.computeLoadDiagnostics({0x1293d00, 0xc014f03d10}, 0xc0004fe360, 0xc00db30500)
	  load.go:541  0x185
golang.org/x/tools/gopls/internal/cache.(*packageHandleBuilder).buildPackageHandle(0xc0145fe040, {0x1293d00, 0xc014f03d10}, 0xc014cccbe0)
	  check.go:1129  0x2b7
golang.org/x/tools/gopls/internal/cache.(*Snapshot).getPackageHandles.func2.1()
	  check.go:932  0xce
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 17964
	  errgroup.go:75  0x96
</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 5139 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2024-04-29 13:34
Thanks for the report! @weiliu2-Leo 

Duplicate of golang/go#66875

**Closed by hyangah** 2024-04-29 13:34 UTC
