### ISSUE TITLE
 Simplify Display of Function Names and Package Paths in Call Stack

### ISSUE THREAD

**Issue by chxia1024** [golang/vscode-go#2787] opened 2023-05-28 04:59 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the function names and package paths are quite long and include the entire package path, which can make the call stack hard to read and cluttered.

**Describe the solution you'd like**
I propose simplifying the display of function names and package paths by providing an option to truncate or abbreviate them, making the call stack more concise and readable. This could be particularly useful when working with Go codebases that have deeply nested packages.

**Describe alternatives you've considered**
gopls substitute-path or JB-goland IDE solution?

**Additional context**
![image](https://github.com/golang/vscode-go/assets/18694552/c083bdd8-51dd-49af-a792-fb2ee7653665)

**Comment by jamalc** [comment] 2023-06-01 14:26
Duplicate of #2707

**Closed by jamalc** 2023-06-01 14:26 UTC
Labels: Debug
