### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by dobau** [golang/vscode-go#1578] opened 2021-06-18 10:40 UTC
gopls version: v0.7.0
gopls flags: 
update flags: proxy
extension version: 0.25.1
go version: 1.16.2
environment: Visual Studio Code darwin
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: only file URIs are supported, got "untitled" from "untitled:Untitled-1"

goroutine 4915 [running]:
golang.org/x/tools/internal/span.URI.Filename(...)
	  uri.go:32
golang.org/x/tools/internal/lsp.(*Server).definition(0xc0002262a0, 0x1bc0b18, 0xc007f5c2c0, 0xc00889a180, 0x0, 0x0, 0x0, 0x0, 0x0)
	  definition.go:16  0x797
golang.org/x/tools/internal/lsp.(*Server).Definition(0xc0002262a0, 0x1bc0b18, 0xc007f5c2c0, 0xc00889a180, 0xc00889a180, 0x0, 0x0, 0x0, 0x0)
	  server_gen.go:40  0x4d
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1bc0b18, 0xc007f5c2c0, 0x1bd7f20, 0xc0002262a0, 0xc005dfeb10, 0x1bc0d80, 0xc007f5c100, 0x203000, 0x203000, 0x1baf080)
	  tsserver.go:386  0x2752
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1bc0b18, 0xc007f5c2c0, 0xc005dfeb10, 0x1bc0d80, 0xc007f5c100, 0x0, 0xc02b3b06d1c12698)
	  protocol.go:154  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1bc0b18, 0xc007f5c2c0, 0xc005dfeb10, 0x1bc0d80, 0xc007f5c100, 0x0, 0x0)
	  lsprpc.go:684  0x459
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1bc0b18, 0xc007f5c2c0, 0xc003fb4798, 0x1bc0d80, 0xc007f5c100, 0xc00afacd00, 0x1000000010433f6)
	  handler.go:35  0xd7
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc002600a20, 0xc0070abcb0, 0xc000318dd0, 0x1bc0b18, 0xc007f5c2c0, 0xc003fb4798, 0x1bc0d80, 0xc007f5c100)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 7:25:31 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2021-06-18 14:24
Thanks @dobau 
I think the fix is released in [v0.26.0 (released yesterday)](https://github.com/golang/vscode-go/releases/tag/v0.26.0). Can you please update the extension and tell us if it no longer crashes gopls?

**Comment by findleyr** [comment] 2021-07-08 19:23
Closing. Please re-open if the issue is still occurring.

**Closed by findleyr** 2021-07-08 19:23 UTC
Labels: WaitingForInfo
