### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by phrafa** [golang/vscode-go#3293] opened 2024-03-29 21:07 UTC
gopls version: v0.15.2/go1.20.3
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Fri, 29 Mar 2024 21:07:10 GMT
restart history:
Fri, 29 Mar 2024 18:55:16 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.1" (should be something like "go1.12")

goroutine 204 [running]:
go/types.NewChecker(0x0%3F, 0xc000383640, 0xc000094a50, 0x0%3F)
	  check.go:237  0x24e
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc0004948f0, {0xc0003942d0, 0x1, 0x1})
	  analysis.go:1028  0x73d
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc0004948f0, {0x124e118%3F, 0xc0004de210})
	  analysis.go:810  0x218
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc0004948f0, {0x124e118%3F, 0xc0004de210})
	  analysis.go:672  0x145
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xda
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 7,
    "TestdataFiles": 0,
    "GoFiles": 3,
    "ModFiles": 1,
    "Dirs": 7
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.20.3",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "392.431656ms",
  "MemStats": {
    "HeapAlloc": 2531400,
    "HeapInUse": 5111808,
    "TotalAlloc": 11238392
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 4,
      "Largest": 44,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.1",
        "AllPackages": {
          "Packages": 3,
          "LargestPackage": 1,
          "CompiledGoFiles": 3,
          "Modules": 1
        },
        "WorkspacePackages": {
          "Packages": 3,
          "LargestPackage": 1,
          "CompiledGoFiles": 3,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-04-01 15:34
Duplicate of golang/go#66636, which we will fix for gopls@v0.15.3.

**Closed by findleyr** 2024-04-01 15:34 UTC
