### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by dsxing** [golang/vscode-go#3607] opened 2024-11-19 06:11 UTC
gopls version: v0.16.2/go1.22.5
gopls flags: 
update flags: proxy
extension version: 0.42.1
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Tue, 19 Nov 2024 06:10:08 GMT
restart history:
Tue, 19 Nov 2024 06:06:22 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: C:/Program   stmt.go:932: assertion failed

goroutine 26955 [running]:
go/types.(*Checker).handleBailout(0xc025e2f600, 0xc012ca9900)
	C:/Program   check.go:367  0x88
panic({0x15ad9e0%3F, 0xc01e110850%3F})
	C:/Program   panic.go:770  0x132
go/types.assert(0x0%3F)
	C:/Program   errors.go:28  0x54
go/types.(*Checker).rangeStmt(0xc025e2f600, 0x3, 0xc01eedb3e0)
	C:/Program   stmt.go:932  0xe70
go/types.(*Checker).stmt(0xc025e2f600, 0x0, {0x1a30660, 0xc01eedb3e0})
	C:/Program   stmt.go:827  0xab9
go/types.(*Checker).stmtList(0xc025e2f600, 0x0, {0xc0260e6000%3F, 0x0%3F, 0x1d%3F})
	C:/Program   stmt.go:121  0x85
go/types.(*Checker).funcBody(0xc025e2f600, 0x1a2ca78%3F, {0xc0260dd0a8%3F, 0xc02cdaf600%3F}, 0xc011e1b880, 0xc0260cdb90, {0x0%3F, 0x0%3F})
	C:/Program   stmt.go:41  0x331
go/types.(*Checker).funcDecl.func1()
	C:/Program   decl.go:852  0x3a
go/types.(*Checker).processDelayed(0xc025e2f600, 0x0)
	C:/Program   check.go:467  0x162
go/types.(*Checker).checkFiles(0xc025e2f600, {0xc01a4e37c0, 0x25, 0x25})
	C:/Program   check.go:411  0x1cc
go/types.(*Checker).Files(...)
	C:/Program   check.go:372
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc017560d00, {0xc011cc7680, 0x25, 0x25})
	  analysis.go:1054  0x6be
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc017560d00, {0x1a31908, 0xc01965f560})
	  analysis.go:835  0x1d8
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc017560d00, {0x1a31908, 0xc01965f560})
	  analysis.go:694  0x126
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:402  0xca
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 26954
	  errgroup.go:75  0x96
</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 38938 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by h9jiang** [comment] 2024-11-20 21:21
This is a version from gopls 0.16.2.

cc @findleyr

**Comment by findleyr** [comment] 2024-11-21 01:45
Duplicate of https://github.com/golang/go/issues/68334. Please upgrade to Go 1.22.6 or later.

**Closed by findleyr** 2024-11-21 01:45 UTC
Labels: FrozenDueToAge
