### ISSUE TITLE
debug: cannot view nested maps on watch/variables panes

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#135] opened 2020-05-29 02:09 UTC
_From https://github.com/microsoft/vscode-go/issues/3198 by @lggomez_:

## Describe the bug

1- Have a nested map variable:
```go
	nestedmap := map[string]interface{}{}
	nestedmap["issuer"] = map[string]interface{}{
		"foo": "bar",
	}
```
2- Expand the variable in the variables pane up to foo, and the debug adapter request will fail with the following:

```
VariablesRequest
Failed to eval expression:  {
 "Expr": "nestedmap.data.data[\"foo\"]",
 "Scope": {
  "goroutineID": -1,
  "frame": 0
 },
 "Cfg": {
  "followPointers": true,
  "maxVariableRecurse": 1,
  "maxStringLen": 100,
  "maxArrayValues": 5,
  "maxStructFields": -1
 }
} 

Eval error: nestedmap (type map[string]interface {}) is not a struct
Failed to evaluate expression - nestedmap (type map[string]interface {}) is not a struct
```

## Screenshot
<img width="1097" alt="Screen Shot 2020-04-20 at 20 43 16" src="https://user-images.githubusercontent.com/6326271/79810520-a1e1c300-8349-11ea-95cc-183079f4f0ca.png">

The watch and variables pane expect a tree object which we create from the delve response in order to show the key and value properties of the map, and on traversal from the pane we're not converting back this object to go syntax, thus being `b.data.data["issuer"]` instead of `b["issuer"]` and/or `b["issuer"]["foo"]`

Here is the relevant code which does the variables request to delve and converts said response's variable representations from delve into DAP variables:

request:
https://github.com/microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L1189-L1209

variable mapper:
https://github.com/microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L1614-L1694

For reference, the correct expression to get the innermost property of this map:

```go
	nestedmap := map[string]interface{}{
		"issuer": map[string]interface{}{
			"foo1": map[string]interface{}{
				"foo2": "bar2",
			},
		},
	}
```

is the following:

```shell
(dlv) p nestedmap["issuer"].(data)["foo1"].(data)["foo2"]
interface {}(string) "bar2"
```

**Comment by lmatter** [comment] 2020-07-07 19:08
Sorry for the "me too", but this is a bit of a show-stopper for me.  Any suggested workaround?  Just parsing json from a text file and can't debug.

**Comment by lggomez** [comment] 2020-07-07 19:33
Sorry for the delay, I stopped working on this issue before the repo migration

Solving this is harder than I expected because of 2 reasons:
- The DAP request must match the correct delve syntax
- The current model is somewhat limited in the way it propagates variables, and more context is needed to build the correct variables call for each level of the nested map

cc @polinasok @eliben since this might be relevant for the new DAP implementation you are working on

**Comment by polinasok** [comment] 2020-10-26 17:35
@lmatter The only workaround right now is to manually use dlv-friendly expressions (not Go syntax) either from the WATCH PANE or from the DEBUG CONSOLE:
![image](https://user-images.githubusercontent.com/51177946/97207037-c1352f00-1776-11eb-8e45-a0c494f43c09.png)
These are the same expressions you would need to use if working with dlv cli:
```
(dlv) p nestedmap["issuer"]
interface {}(map[string]interface {}) [
        "foo": "bar", 
]
(dlv) p nestedmap["issuer"].(data)
map[string]interface {} [
        "foo": "bar", 
]
(dlv) p nestedmap["issuer"].(data)["foo"]
interface {}(string) "bar"
(dlv) p nestedmap["issuer"].(data)["foo"]
interface {}(string) "bar"
(dlv) p nestedmap["issuer"].(data)["foo"].(data)
"bar"
(dlv) p nestedmap["issuer"]["foo"]
Command failed: expression "nestedmap["issuer"]" (interface {}) does not support indexing
```

**Comment by polinasok** [comment] 2020-10-26 18:27
As for the bug itself, with head commit I am seeing:
```
Failed to eval expression:  {
 "Expr": "undefined.data[\"foo\"]",
 "Scope": {
  "goroutineID": -1,
  "frame": 0
 },
 "Cfg": {
  "followPointers": true,
  "maxVariableRecurse": 1,
  "maxStringLen": 64,
  "maxArrayValues": 64,
  "maxStructFields": -1
 }
} 
Eval error: could not find symbol value for undefined
```
So it appears that this now has two underlying issues, (1) one where `data` is missing the much needed `()`, and (2) `undefined`.

(1) Delve [documentation on how to load more variable](https://github.com/go-delve/delve/blob/master/Documentation/api/ClientHowto.md#loading-more-of-a-variable) is lacking the expression for interface data, but that is the special clause that we are missing here - we must special case interface data and use parenthesis in the expression.

(2) It appears that something has changed in the way we set `fullyQualifiedName`, and it is now missing.

(Also filed a separate issue to improve our error handling - #840).

**Comment by lggomez** [comment] 2020-10-26 18:45
Originally we had all the fields populated on the adapter side but the structure itself was not enough since some kind of backpropagation is still needed in order to adapt each variable node of the pane to build correct delve expression instead of having just a `data` qualifier per non-leaf variable node

**Comment by hyangah** [comment] 2020-10-26 18:53
Assigning this to @polinasok for triage further.
Ideally we want to address this from the new delve dap implementation rather than implementing it from the javascript/typescript DA.

**Comment by torlarse** [comment] 2021-01-12 08:39
Hi, just chiming in with my
```
Failed to evaluate expression - 1:25: expected ')', found json (and 1 more errors)
```
, which appears multiple times when parsing a JSON blob.

**Comment by polinasok** [comment] 2021-01-20 06:57
@torlarse There is not enough information in your description to understand what exactly is going on. How exactly are you parsing the json blob? I am assuming you have some complicated nested structure that you are trying to view, level by level, in a VARIABLES pane or maybe you are using Add to Watch for some level.  Am I right? If not, then you might need to file a separate issue and please do include, where possible, code, steps to reproduce, UI snapshots and logging copies.

If my guess is correct, when you reach a level where the data has not been loaded by default, a request will be made to delve to load more with an automatically constructed expression. Or maybe you chose to add the variable to WATCH from the UI, which also uses an automatically constructed expression. Unfortunately, in many cases these expressions are not properly constructed, so they fail. For example, see #1052 or #1086 or [other issues similar issues](https://github.com/golang/vscode-go/issues?q=is%3Aissue++evaluateName+author%3Apolinasok+).

The good news is that these errors only impacts the UI, not the rest of the debug session.

**Comment by polinasok** [comment] 2021-01-21 23:03
I want to also add is that while we are becoming increasingly aware of such shortcomings in the existing adapter, our plan is to fix them in the new native adapter that we are currently building into the delve debugger itself. You can give it a try using the version of dlv at head commit (latest release won't have all the features as this is in active development) and the [nightly version](https://github.com/golang/vscode-go/blob/master/docs/nightly.md) using `"type": "go"` (labeled as "Go Dlv Dap (Experimental)").

**Comment by torlarse** [comment] 2021-01-25 07:48
@polinasok sorry for late reply, thanks for thorough explanation. I understand there is an improved dlv version coming, great! Regarding my json blob, it is not so easy to provide simple debugging info, so I'll just "peek through the blinds" into the data structure for now. Sincerely appreciate all the effort put in to the VS Code environment 👍

**Comment by oscar-bardrick-h24** [comment] 2021-03-30 10:49
I am also suffering with this

**Comment by polinasok** [comment] 2021-04-05 06:15
This issue has been fixed in the new (still experimental, WIP) dlv dap adapter. Please [give it a try](https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md). Here is a screenshot:
![image](https://user-images.githubusercontent.com/51177946/113542987-4defde80-959a-11eb-8845-4c5d04f70a2c.png)

**Closed** 2021-04-05 06:16 UTC
Labels: Debug, DlvDAP, FixedInDlvDapOnly, WillNotFixInOrigDA
