### ISSUE TITLE
Missing strikethrough for deprecated functions

### ISSUE THREAD

**Issue by festo** [golang/vscode-go#599] opened 2020-09-02 12:46 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.13.1 darwin/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
```
1.48.2 
a0479759d6e9ea56afa657e454193f72aef85bd0 
x64
```
- Check your installed extensions to get the version of the VS Code Go extension 
	- `v0.16.1`
- Run `go env` to get the go development environment details
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/festo/Library/Caches/go-build"
GOENV="/Users/festo/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/festo/projects"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rw/8nr3dydx39xgdjs1hld1dws00000gn/T/go-build888602545=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Share the Go related settings you have added/edited

```
  "go.lintFlags": [
        "--fast"
 ],
"[go]": {
    "editor.formatOnSave": true
},
"go.lintTool": "golangci-lint",
"go.useLanguageServer": true,
"go.formatTool": "gofmt",
```

### Describe the bug
The editor doesn't mark deprecated functions with a strikethrough

### Steps to reproduce the behaviour:
1. Mark a function with `// Deprecated: ...` comment
2. Use the function somewhere
3. See error

### Screenshots or recordings
![Screenshot 2020-09-02 at 14 35 47](https://user-images.githubusercontent.com/1818211/91982769-06b31e00-ed2b-11ea-9509-c1d45dbc6334.png)

**Comment by hyangah** [comment] 2020-09-02 12:57
Language server can provide the deprecation diagnostic tag, 
and it looks like there is already a feature request in gopls side 
https://github.com/golang/go/issues/40447. 

cc @stamblerre

**Comment by stamblerre** [comment] 2020-09-02 15:28
Yep, let's close this as a duplicate.

**Comment by stamblerre** [comment] 2020-09-02 15:28
Duplicate of golang/go#40447

**Closed by stamblerre** 2020-09-02 15:28 UTC
