### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by RatchanonPhethan** [golang/vscode-go#3132] opened 2024-01-16 06:39 UTC
gopls version: v0.14.2/go1.20.11
gopls flags: 
update flags: proxy
extension version: 0.40.1
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Tue, 16 Jan 2024 06:38:57 GMT
restart history:
Tue, 16 Jan 2024 02:38:39 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after running for 158ms
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2024-01-17 21:48
Duplicate of #3133

**Closed by hyangah** 2024-01-17 21:48 UTC
