### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by pantsmann** [golang/vscode-go#1358] opened 2021-03-18 00:08 UTC
gopls version: v0.6.5
gopls flags: 
extension version: 0.23.2
environment: Visual Studio Code - Insiders linux
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Got this error when opening vscode.

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 </pre>

**Comment by hyangah** [comment] 2021-03-18 00:25
Thanks for the report. Duplicate of #1300
Please follow the instruction to update the gopls.

**Closed by hyangah** 2021-03-18 00:25 UTC
