### ISSUE TITLE
gopls: issue report (crash)

### ISSUE THREAD

**Issue by Sangwaniya** [golang/vscode-go#3377] opened 2024-05-06 08:43 UTC
gopls version: v0.15.3/go1.21.6
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Mon, 06 May 2024 08:28:39 GMT
restart history:
Mon, 06 May 2024 08:25:18 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: slice bounds out of range [45:44]

goroutine 6656 [running]:
golang.org/x/tools/internal/imports.(*ModuleResolver).scanDirForPackage(0xc000e80630, {{0xc005f33745%3F, 0xe2f2b97516f8d084%3F}, 0x8%3F}, {0xc002d90c00, 0x2c})
	  mod.go:727  0x705
golang.org/x/tools/internal/imports.(*ModuleResolver).scan.func3({{0xc005f33745%3F, 0xa35e20%3F}, 0xc007581cc0%3F}, {0xc002d90c00%3F, 0x14412a8%3F})
	  mod.go:601  0x50
golang.org/x/tools/internal/gopathwalk.(*walker).walk(0xc005a19320, {0xc008be0cc0, 0x37}, 0x0, {0xe70af8, 0xc005c931f0})
	  walk.go:268  0x3d7
golang.org/x/tools/internal/gopathwalk.(*walker).walk(0xc005a19320, {0xc005f33745, 0x2c}, 0x0, {0xe70b30, 0xc007581ca0})
	  walk.go:334  0x87b
golang.org/x/tools/internal/gopathwalk.walkDir({{0xc005f33745%3F, 0xc000107f18%3F}, 0xc000107f18%3F}, 0xc007581c70, 0xc007581c60, {0x0%3F, 0x80%3F, 0x4%3F})
	  walk.go:120  0x366
golang.org/x/tools/internal/gopathwalk.WalkSkip(...)
	  walk.go:77
golang.org/x/tools/internal/imports.(*ModuleResolver).scan.func4()
	  mod.go:626  0x2db
created by golang.org/x/tools/internal/imports.(*ModuleResolver).scan in goroutine 4798
	  mod.go:610  0x465
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 2099,
    "TestdataFiles": 0,
    "GoFiles": 1626,
    "ModFiles": 2,
    "Dirs": 577
  },
  "GOARCH": "amd64",
  "GOOS": "windows",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.21.6",
  "GoplsVersion": "v0.15.3",
  "InitialWorkspaceLoadDuration": "4.9689003s",
  "MemStats": {
    "HeapAlloc": 31132568,
    "HeapInUse": 39731200,
    "TotalAlloc": 74056808
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2207,
      "Largest": 1654271,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.21.6",
        "AllPackages": {
          "Packages": 417,
          "LargestPackage": 134,
          "CompiledGoFiles": 2217,
          "Modules": 49
        },
        "WorkspacePackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment] 2024-05-06 22:43
Closing as a duplicate of golang/go#67156

**Closed by suzmue** 2024-05-06 22:43 UTC
