### ISSUE TITLE
Problems tab does not update after clearing problems

### ISSUE THREAD

**Issue by Justin-Randall** [golang/vscode-go#512] opened 2020-08-12 08:27 UTC
### What version of Go, VS Code & VS Code Go extension are you using?

- Run `go version` to get version of Go
	- `go version go1.14.4 windows/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- `1.47.3
91899dcef7b8110878ea59626991a18c8a6a1b3e
x64`

- Check your installed extensions to get the version of the VS Code Go extension 
	- `0.16.1`
- Run `go env` to get the go development environment details
```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\User\AppData\Local\go-build
set GOENV=C:\Users\User\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\User\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\User\gitlab.com\playscale\products\stashed-2\internal\pkg\frontends\stashedclient\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\User\AppData\Local\Temp\go-build157120118=/tmp/go-build -gno-record-gcc-switches
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

No overrides. Everything is stock.

#### A clear and concise description of what the bug.
When problems are detected and displayed in the IDE, they persist even after fixing the problems. I can go to a terminal window and run all build and tests with zero problems, but the Problems pane is not updated as the problems are fixed. I have followed some advice and added folders containing go.mod files to the workspace (cluttering up my file tree with redundant entries), but other problems persist. Often after they are fixed, they refer to the incorrect line number. I must completely close VS Code and restart it. This happens every few minutes and is not an ideal workflow, no matter how fast a close and restart happens.

#### A clear and concise description of what you expected to happen.
I expect the problems tab to be consistent. As problems are fixed, they are removed from the Problems tab and no longer reported. 

### Steps to reproduce the behavior:
1. Add a new dependency (for example) creating a new problem that is caught
2. Fix the problem
3. See the problem stick around like a couch-surfing friend who will never leave your house.

This happens with a variety of detected problems, so it is difficult to narrow it down.

**Comment by hyangah** [comment] 2020-08-12 20:40
@Justin-Randall Are you not using the language server? (`"go.useLanguageServer": true`)? Please check both 1) global settings (`Preferences: Open Settings (JSON)`) and 2) workspace settings (`Preferences: Open Workspace Settings (JSON)`).

A concrete example to reproduce and screenshot might be helpful.

**Comment by Justin-Randall** [comment] 2020-08-12 22:40
I checked. The User settings do. The Workspace settings do not. The workspace was created as I had to add new folders with go.mod to pacify intellisense for "undefined" symbols showing up in the "problems" tab. 

I have toggled this for the workspace to TRUE and will let you know if that has had any effect.

I recommend that anyone capable of investigating this bug also do the same. Create a new project with internal packages and fight through the same problems.

The only work-around I have found is to kill the IDE and restart it every few minutes.

**Comment by hyangah** [comment] 2020-08-12 22:54
If language server is on in user setting and workspace setting doesn't mention it, the language server is enabled. So, there is no need to set workspace setting again. 

For language server troubleshooting, follow the instructions in https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#vs-code and share the log.

**Comment by Justin-Randall** [comment] 2020-08-12 23:05
The Workspace settings UI showed it explicitly as OFF, even if though the user settings UI showed it as ON. So, there is clearly some disconnect between the internally.

The workspace settings json only show user folders added to pacify intellisense. No other settings.

After toggling the useLanguageServer setting in the UI, apart from the "folders" section, this was added to the workspace file:

```
	"settings": {
		"go.useLanguageServer": true
	}
```

This is the content of my "settings.json" file:
```
{
}
```

If the default installed behavior reproduces this bug, and a the workaround is for each programmer to configure for some special case, that in itself is probably a bug that needs to be addressed.

**Comment by stamblerre** [comment] 2020-08-12 23:21
As @hyangah said, user settings override workspace settings, which is why you were seeing this behavior.
The language server is not on by default, but if you intend to use it, we can help troubleshoot - please provide the information requested in the [troubleshooting guide](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#vs-code).

**Comment by Justin-Randall** [comment] 2020-08-13 00:17
So the user settings, which amount to `{}` override the workspace settings that set `go.useLanguageServer: false`? That makes no sense. In the UI, the User settings show that `go.useLanguageServer: true` while the same UI, with no modifications, show `go.useLanguageServer: false` as the default, no text associated.

The problem is clearly in VS Code. My config was stock with no changes.

**Comment by Justin-Randall** [comment] 2020-08-13 00:23
![image](https://user-images.githubusercontent.com/26448370/90080667-cbca5580-dd3d-11ea-8951-492cf30d2268.png)

![image](https://user-images.githubusercontent.com/26448370/90080715-e997ba80-dd3d-11ea-96a6-80e46efbbb5b.png)

Here is an example of a critical problem referencing a string. Right after actually invoking the method 2 lines above with no problems. "Problems" inspects the enclosed String text and labels it as a project breaking issue.

This is after enabling gopls in the workspace.

**Comment by stamblerre** [comment] 2020-08-13 00:32
> So the user settings, which amount to {} override the workspace settings that set go.useLanguageServer: false? That makes no sense. In the UI, the User settings show that go.useLanguageServer: true while the same UI for the workspace, with no modifications, show go.useLanguageServer: false as the default, no text associated.

I'm sorry, I didn't realize that you had explicitly set `"go.useLanguageServer": false`. My understanding is that user settings that set `"go.useLanguageServer": true` and empty workspace settings will result in the language server being enabled. Perhaps that is a bug on our part, and I'll defer to @hyangah on whether or not this is correct. It's also possible there is a bug in the VS Code settings UI, and if you feel there is, please file it in the VS Code repository: https://github.com/microsoft/vscode.

As for the issues with the language server, it's impossible to understand the issue here without the logs, so if you're interested in further investigation, please provide them ([troubleshooting guide](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#vs-code)), as previously requested.

**Comment by hyangah** [comment] 2020-08-13 01:59
@Justin-Randall JSON (settings.json) is the truth, and UI is built on top of it. 

As far as I can tell, once the value is set by the user settings, the current UI shows that. Same for user settings. If this isn't sufficient,  please report  a UI improvement request to the vscode repository. They welcome settings UI improvement ideas.

<img width="692" alt="Screen Shot 2020-08-12 at 9 44 15 PM" src="https://user-images.githubusercontent.com/4999471/90085072-12d82c80-dce5-11ea-8911-83f093348e8c.png">

If you already have `"go.useLanguageServer": true` in your user settings, you don't need to set that in the workspace settings. The user settings will apply as long as you do not specify `"go.useLanguageServer": false` in the workspace setting JSON file. (I just verified it)

If none of the user settings or the workspace settings specifies `"go.useLanguageServer"`, the default is not using the language server. If you are using modules mode, probably many of intellisense features will not work properly without the language server.

It looks like you turned on the language server, so let's focus on the original problem. I will wait for your gopls trace. Thanks!

**Comment by stamblerre** [comment] 2020-11-10 23:29
Looks like this has had the WaitingForInfo label for a few months without any updates. Going to close this--please create a new issue if you encounter further problems with the language server.

**Closed by stamblerre** 2020-11-10 23:29 UTC
Labels: WaitingForInfo, gopls
