### ISSUE TITLE
Migrate go-outline usage to gopls

### ISSUE THREAD

**Issue by jackwootton** [golang/vscode-go#1554] opened 2021-06-09 17:18 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.16.4 linux/amd64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- `golang.org/x/tools/gopls v0.6.11`
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- `1.55.2`
	- `3c4e3df9e89829dce27b7b5c24508306b151f30d`
	- `x64`
* Check your installed extensions to get the version of the VS Code Go extension
	- `0.25.1`
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/jack/go
GOROOT: /usr/local/go
PATH: /home/jack/.local/bin:/usr/local/go/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

gopkgs: gopkgs not installed
go-outline: go-outline not installed
gotests: gotests not installed
gomodifytags: gomodifytags not installed
impl: impl not installed
goplay: goplay not installed
dlv: dlv not installed
dlv-dap: dlv-dap not installed
staticcheck: staticcheck not installed
gopls: /home/jack/go/bin/gopls installed

go env
Workspace Folder (api): /home/jack/go/src/github.com/jsonsystems/api
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jack/.cache/go-build"
GOENV="/home/jack/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jack/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jack/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jack/go/src/github.com/jsonsystems/api/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1647289639=/tmp/go-build -gno-record-gcc-switches"
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
```json
{
  "vim.easymotion": true,
  "vim.incsearch": true,
  "vim.useSystemClipboard": true,
  "vim.useCtrlKeys": true,
  "vim.hlsearch": true,
  "vim.insertModeKeyBindings": [
    {
      "before": [
        "j",
        "j"
      ],
      "after": [
        "<Esc>"
      ]
    }
  ],
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [
        "<leader>",
        "d"
      ],
      "after": [
        "d",
        "d"
      ]
    },
    {
      "before": [
        "<C-n>"
      ],
      "commands": [
        ":nohl"
      ]
    }
  ],
  "vim.leader": "<space>",
  "vim.handleKeys": {
    "<C-a>": false,
    "<C-f>": false
  },
  "vim.easymotionMarkerForegroundColorOneChar": "yellow",
  "vim.easymotionMarkerForegroundColorTwoChar": "yellow",
  "workbench.colorTheme": "Mayukai Dark",
  "editor.lineHeight": 24,
  "editor.fontSize": 13,
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": false,
  "git.enableSmartCommit": true,
  "window.menuBarVisibility": "toggle",
  "workbench.sideBar.location": "left",
  "files.exclude": {
    "**/.git": false,
    "**/node_modules/**": true
  },
  "go.useLanguageServer": true,
  "diffEditor.ignoreTrimWhitespace": true,
  "[python]": {
    "editor.defaultFormatter": "ms-python.python"
  },
  "explorer.confirmDragAndDrop": false,
  "protoc": {
    "options": [
      "--proto_path=/usr/local/include/google/"
    ]
  },
  "markdown.extension.toc.omittedFromToc": {
    "README.md": ["# Table of Contents", "# jsn"]
  
  }
}
```

### Describe the bug
Upon opening a new VSCode window with Go files present in the workspace, 3 identical notifications are displayed in the bottom right corner of VSCode. 
```
The "go-outline" command is not available.
Run "go get -v github.com/ramya-rao-a/go-outline" to install.
```
Clicking the cog/settings icon in the top right of any notification opens the Go extension for VSCode ([repository](https://github.com/golang/vscode-go)). 

- Why, when the notification recommends installing `github.com/ramya-rao-a/go-outline`, does the settings icon open the extension page for https://github.com/golang/vscode-go?
- Why do I repeatedly see this notification?
  - I do not want to install an extension from `github.com/ramya-rao-a`  

- I do not see this notification having dismissed it once
- Clicking the settings icon in the top right of the notification opens the extension for `github.com/ramya-rao-a/go-outline` and not `github.com/golang/vscode-go`

### Steps to reproduce the behavior:
1. Open a workspace with Go files

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/1623996/121399232-c2058480-c945-11eb-81f3-9212a3381d86.png)
![image](https://user-images.githubusercontent.com/1623996/121400080-aa7acb80-c946-11eb-9d04-d139e78b257d.png)

**Comment by findleyr** [comment] 2021-06-09 20:54
Thanks, we generally want to suppress pop-ups whenever possible.  Having duplicates like this is a bug.

CC @hyangah @suzmue

**Comment by jackwootton** [comment] 2021-06-09 21:08
@findleyr Thanks for responding so promptly. 

Multiple popups is annoying, but specifically, I want to highlight

- why does the settings icon open an extension with a different repository from that cited in the notification?
  - the notification cites `github.com/ramya-rao-a/go-outline` while clicking the cog opens `github.com/ramya-rao-a/go-outline`
- why after this has been dismissed, do I get notified every time I open VSCode?

**Comment by hyangah** [comment] 2021-06-09 21:15
> Why, when the notification recommends installing github.com/ramya-rao-a/go-outline, does the settings icon open the extension page for https://github.com/golang/vscode-go?
> Why do I repeatedly see this notification?
>    I do not want to install an extension from github.com/ramya-rao-a

Because vscode-go extension needs github.com/ramya-rao-a/go-outline and initiated the popup.
https://github.com/golang/vscode-go/blob/master/docs/tools.md#go-outline

The tool is used to generate the code lenses for example. This is currently a **required** tool. :-(

Multiple notification is annoying - the extension needs to keep track of the notification and suppress the duplicate notification.

**Comment by findleyr** [comment] 2021-06-11 19:40
We discussed this, and the best solution is to deprecate go-outline altogether.

The reason for the repeated prompt is that go-outline is a 'required tool'. Satisfying this requirement with gopls seems like the cleanest solution.

**Comment by hyangah** [comment] 2021-07-28 01:47
Duplicate of #1020

**Closed by hyangah** 2021-07-28 01:47 UTC
Labels: NeedsInvestigation
