### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by c100bit** [golang/vscode-go#2811] opened 2023-06-11 06:42 UTC
gopls version: v0.12.2 (go1.20.4)
gopls flags: 
update flags: proxy
extension version: 0.38.0
go version: 1.20.4
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Sun, 11 Jun 2023 06:42:33 GMT
restart history:
Sat, 10 Jun 2023 11:28:16 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: internal error: assertion failed

goroutine 870 [running]:
golang.org/x/tools/internal/gcimporter.iexportCommon.func1()
	  iexport.go:93  0x8a
panic({0x100988de0, 0x100d57260})
	  panic.go:884  0x213
golang.org/x/tools/internal/gcimporter.assert(...)
	  iexport.go:1141
golang.org/x/tools/internal/gcimporter.constantToFloat({0x100d60d30%3F, 0x101327708%3F})
	  iexport.go:967  0x147
golang.org/x/tools/internal/gcimporter.(*exportWriter).value(0xc001537140, {0x100d5cb18%3F, 0x1012d5320}, {0x100d60d30, 0x101327708})
	  iexport.go:930  0x2dc
golang.org/x/tools/internal/gcimporter.(*iexporter).doDecl(0xc001538000, {0x100d69398, 0xc001948420})
	  iexport.go:481  0x2ed
golang.org/x/tools/internal/gcimporter.iexportCommon({0x100d58ae0, 0xc000b92600}, 0xc000948cc0, 0x0, 0x1, 0x2, {0xc0015abca8, 0x1, 0x0%3F})
	  iexport.go:139  0x3a5
golang.org/x/tools/internal/gcimporter.IExportShallow(0x1009cc9a0%3F, 0xc0002ae730)
	  iexport.go:43  0x75
golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).checkPackage.func1()
	  check.go:646  0x2b1
created by golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).checkPackage
	  check.go:638  0x305
[Error - 09:42:19] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2023-06-12 17:48
Thank you for the report. This is a dupe of https://go.dev/issue/60605, which has a fix in-flight.

We should be releasing v0.12.3 containing this fix within ~a week.

**Closed by findleyr** 2023-06-12 17:48 UTC
