### ISSUE TITLE
Formatting verb highlightings are gone

### ISSUE THREAD

**Issue by lixin9311** [golang/vscode-go#2352] opened 2022-07-19 01:20 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.18.3 darwin/arm64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```text
Build info
----------
golang.org/x/tools/gopls v0.9.1
    golang.org/x/tools/gopls@v0.9.1 h1:SigsTL4Hpv3a6b/a7oPCLRv5QUeSM6PZNdta1oKY4B0=
    github.com/BurntSushi/toml@v1.0.0 h1:dtDWrepsVPfW9H/4y7dDgFc2MBUSeJhlaDtK13CxFlU=
    github.com/google/go-cmp@v0.5.7 h1:81/ik6ipDQS2aGcBfIN5dHDB36BwrStyeAQquSYCV4o=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp/typeparams@v0.0.0-20220218215828-6cf2b201936e h1:qyrTQ++p1afMkO4DPEeLGq/3oTsdlvdH4vqZUBWzUKM=
    golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20220209214540-3681064d5158 h1:rm+CHSpPEEW2IsXUib1ThaHIjuBVZjxNgSKmBLFfD4c=
    golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
    golang.org/x/tools@v0.1.12-0.20220713141851-7464a5a40219 h1:Ljlba2fVWOA1049JjsKii44g8nZN2GjpxMlzVc8AnQM=
    golang.org/x/vuln@v0.0.0-20220613164644-4eb5ba49563c h1:r5bbIROBQtRRgoutV8Q3sFY58VzHW6jMBYl48ANSyS4=
    honnef.co/go/tools@v0.3.2 h1:ytYb4rOqyp1TSa2EPvNVwtPQJctSELKaMyLfqNP4+34=
    mvdan.cc/gofumpt@v0.3.0 h1:kTojdZo9AcEYbQYhGuLf/zszYthRdhDNDUi2JKTxas4=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.18.3
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
```text
1.69.2
3b889b090b5ad5793f524b5d1d39fda662b96a2a
arm64
```
* Check your installed extensions to get the version of the VS Code Go extension
	- `v0.35.0`
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```text
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/lucus/go
GOROOT: /opt/homebrew/Cellar/go/1.18.3/libexec
PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/lucus/go/bin:/Users/lucus/.pub-cache/bin

	go:	/opt/homebrew/bin/go: go version go1.18.3 darwin/arm64

	gotests:	/Users/lucus/go/bin/gotests	(version: v1.6.0 built with go: go1.18.2)
	gomodifytags:	/Users/lucus/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.18.2)
	impl:	/Users/lucus/go/bin/impl	(version: v1.1.0 built with go: go1.18.2)
	goplay:	/Users/lucus/go/bin/goplay	(version: v1.0.0 built with go: go1.18.2)
	dlv:	/Users/lucus/go/bin/dlv	(version: v1.9.0 built with go: go1.18.3)
	staticcheck:	/Users/lucus/go/bin/staticcheck	(version: v0.3.1 built with go: go1.18.2)
	gopls:	/Users/lucus/go/bin/gopls	(version: v0.9.1 built with go: go1.18.3)

go env
Workspace Folder (****masked out ****): ****masked out ****
	GO111MODULE=""
	GOARCH="arm64"
	GOBIN=""
	GOCACHE="/Users/lucus/Library/Caches/go-build"
	GOENV="/Users/lucus/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="arm64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/lucus/go/pkg/mod"
	GONOPROXY="****masked out ****"
	GONOSUMDB="****masked out ****"
	GOOS="darwin"
	GOPATH="/Users/lucus/go"
	GOPRIVATE="****masked out ****"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/opt/homebrew/Cellar/go/1.18.3/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/opt/homebrew/Cellar/go/1.18.3/libexec/pkg/tool/darwin_arm64"
	GOVCS=""
	GOVERSION="go1.18.3"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="****masked out ****"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6_/msm1_r211ds7gwg7dv3zw8j40000gn/T/go-build3268943341=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```json
{
    "go.useLanguageServer": true,
    "go.toolsManagement.autoUpdate": true
}
```

### Describe the bug
A clear and concise description of what the bug.
After enabling Go extension:
![image](https://user-images.githubusercontent.com/371475/179643223-8668c22e-629d-41ed-847e-bff564348698.png)

With Go extension disabled & reload the window:
![image](https://user-images.githubusercontent.com/371475/179643307-ef39c2f6-eb3b-4aa6-a136-32ec4e6af460.png)

Even with vscode global inlay setting disabled, the issue is still there.

**Comment by koeichen** [comment] 2022-07-19 02:39
same in here

**Comment by ShoshinNikita** [comment] 2022-07-19 06:08
Another problem with semantic highlighting is the color of `nil` - it is indistinguishable from structure fields and local variables:

![image](https://user-images.githubusercontent.com/30220965/179675950-fb9ec4ee-cb87-4ce0-a3ca-8ef55255a6ba.png)

The solution is to disable semantic highlighting for `.go` files:

```json
"[go]": {
	"editor.semanticHighlighting.enabled": false
}
```

**Comment by hyangah** [comment] 2022-07-19 15:19
Duplicate of #2355

**Closed by hyangah** 2022-07-19 15:19 UTC
