### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by jasonliancatalyst** [golang/vscode-go#1546] opened 2021-06-05 11:51 UTC
gopls version: v0.7.0-pre.1
gopls flags: 
update flags: proxy
extension version: 2021.5.2720
go version: 1.16.4
environment: Visual Studio Code linux
initialization error: undefined
manual restart count: 0
total start count: 2

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2021-06-05 12:54
Hi, thanks for reporting. Could you share your gopls logs or any other extension output? Do you recall what you were doing when gopls crashed?
https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-extension-logs

**Comment by jasonliancatalyst** [comment] 2021-06-05 16:45
thanks for looking

go version: 
go version go1.16.4 linux/amd64

vscode version
1.56.2
x64

I've attached the error log.
[error.log](https://github.com/golang/vscode-go/files/6602890/error.log)

**Comment by findleyr** [comment] 2021-06-07 15:50
Thanks!

Here's the panicking stack:
```
golang.org/x/tools/internal/lsp/template.parseBuffer(0xc000208600, 0x0, 0x200, 0x200)
	/home/jjlemb/go/pkg/mod/golang.org/x/tools@v0.1.3-0.20210602202533-5eeea501c404/internal/lsp/template/parse.go:96 +0xc7d
golang.org/x/tools/internal/lsp/template.Diagnose(0xfc9308, 0xc0005be830, 0xc00017e380, 0xc00026a420, 0x58)
	/home/jjlemb/go/pkg/mod/golang.org/x/tools@v0.1.3-0.20210602202533-5eeea501c404/internal/lsp/template/implementations.go:35 +0x85
golang.org/x/tools/internal/lsp.(*Server).diagnose(0xc00017e2a0, 0xfbf8e8, 0xc0002044c0, 0xfd3078, 0xc00017e380, 0x1f4500001f00)
	/home/jjlemb/go/pkg/mod/golang.org/x/tools@v0.1.3-0.20210602202533-5eeea501c404/internal/lsp/diagnostics.go:215 +0x8a5
golang.org/x/tools/internal/lsp.(*Server).diagnoseDetached(0xc00017e2a0, 0xfd3078, 0xc00017e380)
	/home/jjlemb/go/pkg/mod/golang.org/x/tools@v0.1.3-0.20210602202533-5eeea501c404/internal/lsp/diagnostics.go:90 +0xb1
golang.org/x/tools/internal/lsp.(*Server).addFolders.func3(0xc00017e2a0, 0xfd3078, 0xc00017e380, 0xc000211ef0, 0xc00007aea0, 0xc000370670)
	/home/jjlemb/go/pkg/mod/golang.org/x/tools@v0.1.3-0.20210602202533-5eeea501c404/internal/lsp/general.go:264 +0x3f
created by golang.org/x/tools/internal/lsp.(*Server).addFolders
	/home/jjlemb/go/pkg/mod/golang.org/x/tools@v0.1.3-0.20210602202533-5eeea501c404/internal/lsp/general.go:263 +0xb3c
```

So this looks like a dupe of https://github.com/golang/vscode-go/issues/1540, which will be fixed in the next release. Sorry for the breakage!

**Closed by findleyr** 2021-06-07 15:50 UTC
Labels: WaitingForInfo
