### ISSUE TITLE
Language Server doesn't work for newly opened file when it's neither in module mode nor in GOPATH mode

### ISSUE THREAD

**Issue by jeffreyyjp** [golang/vscode-go#1613] opened 2021-07-09 09:39 UTC
For asking questions, see:
- [GitHub Discussions (Q&A)](https://github.com/golang/vscode-go/discussions/categories/q-a)
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Before filing an issue, please review our troubleshooting guides
* [Troubleshooting problems with debugging](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#troubleshooting)
* [Troubleshooting other problems](https://github.com/golang/vscode-go/tree/master/docs/troubleshooting.md)

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16.4 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
----------
golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@v0.7.0 h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.5 h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.2 h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20210510120138-977fb7262007 h1:gG67DSER+11cZvqIMb8S8bt0vZtiN6xWYARwirrOSfE=
    golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c h1:Pv9gNyJFYVdpUAVZYJ1BDSU4eGgXQ+0f3DIGAdolO5s=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.2.0 h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=
    mvdan.cc/gofumpt@v0.1.1 h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.58.0
2d23c42a936db1c7b3b06f918cde29561cc47cd6
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.26.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- gopath: /home/jeffrey/go
GOROOT: /usr/local/go
PATH: /usr/local/go/bin:/home/jeffrey/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/d/programs/Git/cmd:/mnt/d/programs/Minikube:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/yangjianpeng/AppData/Local/Microsoft/WindowsApps:/mnt/d/programs/Microsoft VS Code/bin

   gopkgs: /home/jeffrey/go/bin/gopkgs installed
   go-outline: /home/jeffrey/go/bin/go-outline installed
   gotests: /home/jeffrey/go/bin/gotests installed
   gomodifytags: /home/jeffrey/go/bin/gomodifytags installed
   impl: /home/jeffrey/go/bin/impl installed
   goplay: /home/jeffrey/go/bin/goplay installed
   dlv: /home/jeffrey/go/bin/dlv installed
   dlv-dap: /home/jeffrey/go/bin/dlv-dap installed
   staticcheck: /home/jeffrey/go/bin/staticcheck installed
   gopls: /home/jeffrey/go/bin/gopls installed

go env
Workspace Folder (gopl.io): /home/jeffrey/Coding/Myself/opensource/gopl.io
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/jeffrey/.cache/go-build"
	GOENV="/home/jeffrey/.config/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/jeffrey/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/home/jeffrey/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.16.4"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/dev/null"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2848456532=/tmp/go-build -gno-record-gcc-switches"

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.
In my project, each time I open a new file in the editor from Explorer, the Go Language Server doesn't work for newly opened files, I move my cursor to hover in any function, it doesn't show any linting, code navigation, IntelliSense. Only I do "Reload Window" or "Go: Restart Language Server"

Any newly opened file should be handled by this Language Server

### Steps to reproduce the behavior:
1. Open any files with .go suffix
2. hover cursor to any function, for example, "make" or "fmt.Println". Or use "go to definition"
3. Doesn't work

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by findleyr** [comment] 2021-07-09 16:42
Hi, if I'm understanding correctly your editor does not behave correctly until you do "Go: Restart Language Server"? That certainly is not expected behavior. For the record, that is not the expected behavior and does not repro for me.

There may be something misconfigured in your workspace, but in that case it would be very surprising for gopls to _start_ working once restarted.  Do you get any initial error messages?

**Comment by jeffreyyjp** [comment] 2021-07-10 02:45
@findleyr I don't get any error, I just clone the project which is gopl.io (The Go Programming Language Book repo). but I can put my gopls(server) log here

[Info  - 10:35:37 AM] 2021/07/10 10:35:35 go env for /Users/yangjianpeng/coding/go-pro/gopl.io
(root /Users/yangjianpeng/coding/go-pro/gopl.io)
(go version go version go1.16.5 darwin/amd64)
(valid build configuration = false)
(build flags: [])
GOMODCACHE=/Users/yangjianpeng/go/pkg/mod
GOCACHE=/Users/yangjianpeng/Library/Caches/go-build
GOFLAGS=
GOPRIVATE=
GOROOT=/usr/local/Cellar/go/1.16.5/libexec
GOSUMDB=sum.golang.org
GOINSECURE=
GOMOD=/dev/null
GONOSUMDB=
GOPATH=/Users/yangjianpeng/go
GO111MODULE=
GONOPROXY=
GOPROXY=https://goproxy.cn,direct


[Info  - 10:35:37 AM] 2021/07/10 10:35:36 go/packages.Load
	snapshot=0
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[./ builtin]
	packages=2

[Info  - 10:35:37 AM] 2021/07/10 10:35:36 go/packages.Load
	snapshot=0
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[./]
	packages=1

[Info  - 10:35:37 AM] 2021/07/10 10:35:36 go/packages.Load
	snapshot=0
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[./]
	packages=1

[Info  - 10:35:37 AM] 2021/07/10 10:35:36 go/packages.Load
	snapshot=0
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[./]
	packages=1

[Info  - 10:35:40 AM] 2021/07/10 10:35:39 go/packages.Load
	snapshot=1
	package="command-line-arguments"
	files=[/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/helloworld/main.go]

[Info  - 10:35:40 AM] 2021/07/10 10:35:39 go/packages.Load
	snapshot=1
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[file=/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/helloworld/main.go]
	packages=1

[Info  - 10:35:40 AM] 2021/07/10 10:35:39 go/packages.Load
	snapshot=1
	package="command-line-arguments"
	files=[/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/helloworld/main.go]

[Info  - 10:35:40 AM] 2021/07/10 10:35:39 go/packages.Load
	snapshot=1
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[file=/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/helloworld/main.go]
	packages=1

[Info  - 10:35:40 AM] 2021/07/10 10:35:40 discovered missing identifiers: map[memRecordCycle:true pageBits:true]
	package="runtime"

[Info  - 10:36:10 AM] 2021/07/10 10:36:10 background imports cache refresh starting

[Info  - 10:36:10 AM] 2021/07/10 10:36:10 background refresh finished after 152.904993ms

[Info  - 10:38:31 AM] 2021/07/10 10:38:31 go/packages.Load
	snapshot=2
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[file=/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go]
	packages=1

[Info  - 10:38:31 AM] 2021/07/10 10:38:31 go/packages.Load
	snapshot=2
	package="command-line-arguments"
	files=[/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go]

[Info  - 10:38:31 AM] 2021/07/10 10:38:31 go/packages.Load
	snapshot=2
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[file=/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go]
	packages=1

[Info  - 10:38:31 AM] 2021/07/10 10:38:31 go/packages.Load
	snapshot=2
	package="command-line-arguments"
	files=[/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go]

[Error - 10:38:31 AM] 2021/07/10 10:38:31 DocumentSymbols failed: getting file for DocumentSymbols: no parsed file for file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go in command-line-arguments
	URI=file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go

[Error - 10:38:32 AM] 2021/07/10 10:38:32 no highlight: getting file for Highlight: no parsed file for file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go in command-line-arguments
	URI=file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go

[Info  - 10:39:01 AM] 2021/07/10 10:39:01 background imports cache refresh starting

[Info  - 10:39:01 AM] 2021/07/10 10:39:01 background refresh finished after 109.390423ms

[Info  - 10:39:04 AM] 2021/07/10 10:39:04 go/packages.Load
	snapshot=3
	package="command-line-arguments"
	files=[/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup2/main.go]

[Info  - 10:39:04 AM] 2021/07/10 10:39:04 go/packages.Load
	snapshot=3
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[file=/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup2/main.go]
	packages=1

[Info  - 10:39:04 AM] 2021/07/10 10:39:04 go/packages.Load
	snapshot=3
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[file=/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup2/main.go]
	packages=1

[Info  - 10:39:04 AM] 2021/07/10 10:39:04 go/packages.Load
	snapshot=3
	package="command-line-arguments"
	files=[/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup2/main.go]

[Error - 10:39:04 AM] 2021/07/10 10:39:04 DocumentSymbols failed: getting file for DocumentSymbols: no parsed file for file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup2/main.go in command-line-arguments
	URI=file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup2/main.go

[Info  - 10:39:14 AM] 2021/07/10 10:39:14 Shutdown session
	shutdown_session=1

[Info  - 10:39:15 AM] 2021/07/10 10:39:15 go env for /Users/yangjianpeng/coding/go-pro/gopl.io
(root /Users/yangjianpeng/coding/go-pro/gopl.io)
(go version go version go1.16.5 darwin/amd64)
(valid build configuration = false)
(build flags: [])
GOPROXY=https://goproxy.cn,direct
GOMODCACHE=/Users/yangjianpeng/go/pkg/mod
GOINSECURE=
GOPATH=/Users/yangjianpeng/go
GOPRIVATE=
GOFLAGS=
GOSUMDB=sum.golang.org
GONOPROXY=
GONOSUMDB=
GOMOD=/dev/null
GOROOT=/usr/local/Cellar/go/1.16.5/libexec
GO111MODULE=
GOCACHE=/Users/yangjianpeng/Library/Caches/go-build


[Info  - 10:39:15 AM] 2021/07/10 10:39:15 go/packages.Load
	snapshot=0
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[./ builtin]
	packages=2

[Info  - 10:39:15 AM] 2021/07/10 10:39:15 go/packages.Load
	snapshot=0
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[./]
	packages=1

[Info  - 10:39:15 AM] 2021/07/10 10:39:15 go/packages.Load
	snapshot=0
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[./]
	packages=1

[Info  - 10:39:15 AM] 2021/07/10 10:39:15 go/packages.Load
	snapshot=0
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[./]
	packages=1

[Info  - 10:39:15 AM] 2021/07/10 10:39:15 go/packages.Load
	snapshot=3
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[file=/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go]
	packages=1

[Info  - 10:39:15 AM] 2021/07/10 10:39:15 go/packages.Load
	snapshot=3
	package="command-line-arguments"
	files=[/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup2/main.go]

[Info  - 10:39:15 AM] 2021/07/10 10:39:15 go/packages.Load
	snapshot=3
	package="command-line-arguments"
	files=[/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go]

[Info  - 10:39:15 AM] 2021/07/10 10:39:15 go/packages.Load
	snapshot=3
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[file=/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup2/main.go]
	packages=1

[Info  - 10:39:15 AM] 2021/07/10 10:39:15 discovered missing identifiers: map[memRecordCycle:true pageBits:true]
	package="runtime"

[Error - 10:39:15 AM] 2021/07/10 10:39:15 DocumentSymbols failed: getting file for DocumentSymbols: no parsed file for file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go in command-line-arguments
	URI=file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go

[Info  - 10:39:16 AM] 2021/07/10 10:39:16 reloadOrphanedFiles reloading
	query=[file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/helloworld/main.go]

[Info  - 10:39:16 AM] 2021/07/10 10:39:16 go/packages.Load
	snapshot=3
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[file=/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/helloworld/main.go]
	packages=1

[Info  - 10:39:16 AM] 2021/07/10 10:39:16 go/packages.Load
	snapshot=3
	package="command-line-arguments"
	files=[/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/helloworld/main.go]

[Error - 10:39:29 AM] 2021/07/10 10:39:29 DocumentSymbols failed: getting file for DocumentSymbols: no parsed file for file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/helloworld/main.go in command-line-arguments
	URI=file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/helloworld/main.go

[Info  - 10:39:47 AM] 2021/07/10 10:39:47 background imports cache refresh starting

[Info  - 10:39:47 AM] 2021/07/10 10:39:47 background refresh finished after 118.932668ms

[Info  - 10:40:59 AM] 2021/07/10 10:40:59 background imports cache refresh starting

[Info  - 10:40:59 AM] 2021/07/10 10:40:59 background refresh finished after 179.524705ms

[Error - 10:41:33 AM] 2021/07/10 10:41:33 DocumentSymbols failed: getting file for DocumentSymbols: no parsed file for file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/helloworld/main.go in command-line-arguments
	URI=file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/helloworld/main.go

[Info  - 10:41:48 AM] 2021/07/10 10:41:48 background imports cache refresh starting

[Info  - 10:41:48 AM] 2021/07/10 10:41:48 background refresh finished after 41.165509ms

[Error - 10:41:50 AM] 2021/07/10 10:41:50 no highlight: getting file for Highlight: no parsed file for file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go in command-line-arguments
	URI=file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go

[Info  - 10:42:20 AM] 2021/07/10 10:42:20 background imports cache refresh starting

[Info  - 10:42:20 AM] 2021/07/10 10:42:20 background refresh finished after 45.078949ms

[Info  - 10:42:58 AM] 2021/07/10 10:42:58 go env for /Users/yangjianpeng/coding/go-pro/gopl.io
(root /Users/yangjianpeng/coding/go-pro/gopl.io)
(go version go version go1.16.5 darwin/amd64)
(valid build configuration = false)
(build flags: [])
GONOSUMDB=
GOPATH=/Users/yangjianpeng/go
GONOPROXY=
GOROOT=/usr/local/Cellar/go/1.16.5/libexec
GOSUMDB=sum.golang.org
GOCACHE=/Users/yangjianpeng/Library/Caches/go-build
GOINSECURE=
GOMOD=/dev/null
GO111MODULE=
GOFLAGS=
GOMODCACHE=/Users/yangjianpeng/go/pkg/mod
GOPRIVATE=
GOPROXY=https://goproxy.cn,direct


[Info  - 10:42:58 AM] 2021/07/10 10:42:58 go/packages.Load
	snapshot=0
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[./ builtin]
	packages=2

[Info  - 10:42:58 AM] 2021/07/10 10:42:58 go/packages.Load
	snapshot=0
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[./]
	packages=1

[Info  - 10:42:58 AM] 2021/07/10 10:42:58 go/packages.Load
	snapshot=0
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[./]
	packages=1

[Info  - 10:42:58 AM] 2021/07/10 10:42:58 go/packages.Load
	snapshot=0
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[./]
	packages=1

[Info  - 10:42:59 AM] 2021/07/10 10:42:59 go/packages.Load
	snapshot=3
	package="command-line-arguments"
	files=[/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go]

[Info  - 10:42:59 AM] 2021/07/10 10:42:59 go/packages.Load
	snapshot=3
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[file=/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go]
	packages=1

[Info  - 10:42:59 AM] 2021/07/10 10:42:59 go/packages.Load
	snapshot=3
	package="command-line-arguments"
	files=[/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup2/main.go]

[Info  - 10:42:59 AM] 2021/07/10 10:42:59 go/packages.Load
	snapshot=3
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[file=/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup2/main.go]
	packages=1

[Info  - 10:42:59 AM] 2021/07/10 10:42:59 discovered missing identifiers: map[memRecordCycle:true pageBits:true]
	package="runtime"

[Error - 10:42:59 AM] 2021/07/10 10:42:59 DocumentSymbols failed: getting file for DocumentSymbols: no parsed file for file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go in command-line-arguments
	URI=file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go

[Info  - 10:42:59 AM] 2021/07/10 10:42:59 reloadOrphanedFiles reloading
	query=[file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/helloworld/main.go]

[Info  - 10:42:59 AM] 2021/07/10 10:42:59 go/packages.Load
	snapshot=3
	directory=/Users/yangjianpeng/coding/go-pro/gopl.io
	query=[file=/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/helloworld/main.go]
	packages=1

[Info  - 10:42:59 AM] 2021/07/10 10:42:59 go/packages.Load
	snapshot=3
	package="command-line-arguments"
	files=[/Users/yangjianpeng/coding/go-pro/gopl.io/ch1/helloworld/main.go]

[Error - 10:43:12 AM] 2021/07/10 10:43:12 no highlight: getting file for Highlight: no parsed file for file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go in command-line-arguments
	URI=file:///Users/yangjianpeng/coding/go-pro/gopl.io/ch1/dup1/main.go

[Info  - 10:43:29 AM] 2021/07/10 10:43:29 background imports cache refresh starting

[Info  - 10:43:29 AM] 2021/07/10 10:43:29 background refresh finished after 212.446042ms

**Comment by hyangah** [comment] 2021-07-12 13:54
gopl.io materials were written before go tools adopted Go Modules and does not have `go.mod`. When it is checked out outside `GOPATH/src` and gopls couldn't find the module root (the directory with `go.mod`), gopls does not know clearly where the module boundary is and applies heuristics. 
 
@jeffreyyjp There are two workarounds I can think of:
 - From the root of the gopls.io repo (`/Users/yangjianpeng/coding/go-pro/gopl.io`), run these commands and reload the window (Ctrl+Shift+P -> `Developer: Reload Window` command)
     ```
     go mod init gopl.io
     go mod tidy
     ```
     
 - Checkout this `gopl.io` directory under your `$GOPATH/src` directory (`/Users/yangjianpeng/go/src`)? In addition,  you may need to set `"go.toolsEnvVars": { "GO111MODULE": "off" }` if you need VSCode Go extensions features more than language intellisense.

**Comment by jeffreyyjp** [comment] 2021-07-13 07:43
@hyangah I tried workaround 1, and it just works for me. Thank you very much.

**Comment by hyangah** [comment] 2021-07-13 13:43
Thanks @jeffreyyjp for the update.
Closing since this is working as intended.

**Closed by hyangah** 2021-07-13 13:43 UTC
Labels: WillNotFix
