### ISSUE TITLE
Windows10 + WSL Error: "Error loading workspace folders (expected 1, got 0) failed to load view for: file:////wsl$/Ubuntu/wsl$/Ubuntu/home/<path to project folder>"

### ISSUE THREAD

**Issue by dsidirop** [golang/vscode-go#1574] opened 2021-06-17 07:55 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16.5 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
----------
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.6.11 h1:7S2k0xuVYc3secjy2uz0n+fGYxGJU6gXsLOmQ/r1HoI=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.5 h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.2 h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20210521203332-0cec03c779c1 h1:lCnv+lfrU9FRPGf8NeRuWAAPjNnema5WtBinMgs1fD8=    
    golang.org/x/tools@v0.1.1 h1:wGiQel/hW0NnEkJUk8lbzkX2gFJU6PFxf1v5OlCfuOs=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.1.3 h1:qTakTkI6ni6LFD5sBwwsdSO+AQqbSIxOauHTTQKZ/7o=
    mvdan.cc/gofumpt@v0.1.1 h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.57.0  b4c1bd0a9b03c749ea011b06c6d2676c8091a70c x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.25.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: C:\Users\Dominic\go
GOROOT: C:\Program Files\Go
PATH: C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Python39\Scripts\;C:\Python39\;C:\PROGRAM FILES\MICROSOFT MPI\BIN\;C:\PROGRAM FILES\GITLAB RUNNER\;C:\PYTHON27\SCRIPTS;C:\PYTHON38\SCRIPTS\;C:\PYTHON38\;C:\WINDOWS\SYSTEM32;C:\WINDOWS;C:\WINDOWS\SYSTEM32\WBEM;C:\WINDOWS\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\WINDOWS\SYSTEM32\OPENSSH\;C:\PROGRAM FILES (X86)\ATI TECHNOLOGIES\ATI.ACE\CORE-STATIC;C:\PROGRAM FILES\DOTNET\;C:\PROGRAM FILES\MICROSOFT SQL SERVER\130\TOOLS\BINN\;C:\PROGRAM FILES\MICROSOFT SQL SERVER\CLIENT SDK\ODBC\170\TOOLS\BINN\;C:\PROGRAM FILES\MICROSOFT VS CODE\BIN;C:\PROGRAMDATA\CHOCOLATEY\BIN;C:\PROGRAMDATA\CHOCOLATEY\LIB\MAVEN\APACHE-MAVEN-3.6.3\BIN;C:\PROGRAM FILES\OPENJDK\OPENJDK-8U242-B08\BIN;C:\PROGRAM FILES (X86)\AMD\ATI.ACE\CORE-STATIC;C:\PROGRAM FILES\GIT\CMD;C:\PROGRAM FILES (X86)\NVIDIA CORPORATION\PHYSX\COMMON;C:\PROGRAM FILES\NVIDIA CORPORATION\NVIDIA NVDLISR;C:\PROGRAM FILES (X86)\AMD APP SDK\3.0\BIN\X86_64;C:\PROGRAM FILES (X86)\AMD APP SDK\3.0\BIN\X86;C:\PROGRAM FILES\MICROSOFT SQL SERVER\CLIENT SDK\ODBC\130\TOOLS\BINN\;C:\PROGRAM FILES (X86)\OPENJDK\JDK-14.0.1\BIN;C:\PROGRAM FILES (X86)\OPENJDK\OPENJDK-8U252-B09\BIN;C:\PROGRAM FILES\DOCKER\DOCKER\RESOURCES\BIN;C:\PROGRAMDATA\DOCKERDESKTOP\VERSION-BIN;C:\PROGRAM FILES\VAULT\;C:\PROGRAM FILES\SEQ\;C:\PROGRAM FILES\SEQ\CLIENT\;C:\PROGRAM FILES (X86)\GOOGLE\CLOUD SDK\GOOGLE-CLOUD-SDK\BIN;C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\150\TOOLS\BINN\;C:\PROGRAM FILES\MICROSOFT SQL SERVER\150\TOOLS\BINN\;C:\PROGRAM FILES\MICROSOFT SQL SERVER\150\DTS\BINN\;C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\150\DTS\BINN\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Nuget;;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files (x86)\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Go\bin;C:\Program Files (x86)\GitExtensions\;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.1\bin;C:\Program Files\OpenJDK\jdk-16.0.1\bin;C:\Program Files\OpenJDK\openjdk-8u292-b10\bin;C:\Users\Dominic\AppData\Local\Microsoft\WindowsApps;C:\Users\Dominic\.dotnet\tools;C:\Users\Dominic\AppData\Local\Keybase\;C:\Users\Dominic\AppData\Roaming\npm;C:\Users\Dominic\AppData\Local\Yarn\bin;C:\Users\Dominic\AppData\Local\GitHubDesktop\bin;C:\Users\Dominic\go\bin;C:\Users\Dominic\AppData\Local\Markdown Monster;C:\Users\Dominic\.dotnet\tools;C:\Users\Dominic\go\bin

   gopkgs: C:\Users\Dominic\go\bin\gopkgs.exe installed
   go-outline: C:\Users\Dominic\go\bin\go-outline.exe installed
   gotests: C:\Users\Dominic\go\bin\gotests.exe installed
   gomodifytags: C:\Users\Dominic\go\bin\gomodifytags.exe installed
   impl: C:\Users\Dominic\go\bin\impl.exe installed
   goplay: C:\Users\Dominic\go\bin\goplay.exe installed
   dlv: C:\Users\Dominic\go\bin\dlv.exe installed
   dlv-dap: C:\Users\Dominic\go\bin\dlv-dap.exe installed
   staticcheck: C:\Users\Dominic\go\bin\staticcheck.exe installed
   gopls: C:\Users\Dominic\go\bin\gopls.exe installed

go env
Workspace Folder (magellan-streaming-broker): \\wsl$\Ubuntu\home\dominic\VS\laerdal\magellan-streaming-broker
	set GO111MODULE=
	set GOARCH=amd64
	set GOBIN=
	set GOCACHE=C:\Users\Dominic\AppData\Local\go-build
	set GOENV=C:\Users\Dominic\AppData\Roaming\go\env
	set GOEXE=.exe
	set GOFLAGS=
	set GOHOSTARCH=amd64
	set GOHOSTOS=windows
	set GOINSECURE=
	set GOMODCACHE=C:\Users\Dominic\go\pkg\mod
	set GONOPROXY=bitbucket.org/laerdalmedical
	set GONOSUMDB=bitbucket.org/laerdalmedical
	set GOOS=windows
	set GOPATH=C:\Users\Dominic\go
	set GOPRIVATE=bitbucket.org/laerdalmedical
	set GOPROXY=https://proxy.golang.org,direct
	set GOROOT=C:\Program Files\Go
	set GOSUMDB=sum.golang.org
	set GOTMPDIR=
	set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
	set GOVCS=
	set GOVERSION=go1.16.5
	set GCCGO=gccgo
	set AR=ar
	set CC=gcc
	set CXX=g++
	set CGO_ENABLED=1
	set GOMOD=\\wsl$\Ubuntu\home\dominic\VS\laerdal\magellan-streaming-broker\go.mod
	set CGO_CFLAGS=-g -O2
	set CGO_CPPFLAGS=
	set CGO_CXXFLAGS=-g -O2
	set CGO_FFLAGS=-g -O2
	set CGO_LDFLAGS=-g -O2
	set PKG_CONFIG=pkg-config
	set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Dominic\AppData\Local\Temp\go-build3943144360=/tmp/go-build -gno-record-gcc-switches
	
### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

<nothing in my settings.json file prefixed with go*>

### Describe the bug

I'm using VSCode+Go extension in Windows 10 + WSL2 (all fully updated to their latest versions).

Regardless of whether I open a golang folder/project directly as a folder or via a workspace file hosted inside the WSL's filesystem (file:////wsl$/Ubuntu/wsl$/Ubuntu/home/...) I get the same error upon launching VSCode:

               Error loading workspace folders (expected 1, got 0) failed to load view for:

                file:////wsl$/Ubuntu/wsl$/Ubuntu/home/<path to project folder>

               failed to get workspace configuration from client

               file:////wsl$/Ubuntu/wsl$/Ubuntu/home/<path to project folder>

               Request workspace/configuration failed with message:

              [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")

The files are navigable inside the file-explorer in the sidebar but static code analysis + code helpers (go to implementation, find usages) doesn't work at all. This shouldn't happen. If I copy the exact same folder into the Windows NTFS filesystem (C:\foo\bar) then VSCode + Go-Extension opens the folder just fine with full static analysis + code-helpers working 100% as intended.

The strange thing about this is that I'm the only one in my team who is experiencing this kind of error. Colleagues of mine running the same setup don't have such issues. The only difference between our machines is that I'm running BitDefender antivirus. I doubt BitDefender plays any role though.

Things I've tried:

1. Deleted my .vscode-server folder under my WSL home folder.
2. Reloaded VSCode
3. Restarted go-language-server
4. Tried placing the project in a different directory inside WSL

### Steps to reproduce the behavior:
1. Checkout any golang project inside the WSL filesystem (make sure you have the latest version of Windows + WSL + VSCode + Go extension)
2. Open its root-folder with latest VSCode + Go extension
3. You should be seeing the error described above

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/7284501/122355270-6eed8c00-cf5a-11eb-8cdb-07af2c1ac45d.png)

**Comment by hyangah** [comment] 2021-06-17 11:50
I think this extension needs the [Visual Studio Code Remote - WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) for developing in WSL (like many other extensions). 

Please review VS Code's documentation about [Developing in WSL](https://code.visualstudio.com/docs/remote/wsl). 
The described setup (vscode server inside WSL) is desirable because, even if this extension and the language server could support the `wsl$` file paths, `go` and other go tools would still have [various issues](https://github.com/golang/vscode-go/issues/1485#issuecomment-834740277).

**Comment by dsidirop** [comment] 2021-06-17 16:41
> I think this extension needs the [Visual Studio Code Remote - WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) for developing in WSL (like many other extensions).
> 
> Please review VS Code's documentation about [Developing in WSL](https://code.visualstudio.com/docs/remote/wsl).
> The described setup (vscode server inside WSL) is desirable because, even if this extension and the language server could support the `wsl$` file paths, `go` and other go tools would still have [various issues](https://github.com/golang/vscode-go/issues/1485#issuecomment-834740277).

Thank you for the prompt reply.

I have reviewed said guides and followed them to the letter. I doublechecked that I'm using the latest and greatest version of associated extensions as you can see in the screenshot. Still the issue persists if and only if I place the git repository inside the WSL file system.

![image](https://user-images.githubusercontent.com/7284501/122439149-117e2d00-cfa4-11eb-9871-401dd62933d7.png)

**Comment by wtask** [comment] 2021-06-17 18:09
I think the problem may occur if windows git binary try to access git repo cloned inside wsl with Ubuntu git and wise versa.
If you only need to apply some useful tools to your repo under Windows from Ubuntu open wsl terminal for your workspace and run desired tools. Or you should install Go inside WSL and use Remote Development extension. Check where required binaries are located - under Windows or inside WSL.

**Comment by hyangah** [comment] 2021-06-17 18:50
Thank you @wtask for the tip, and @dsidirop for filing the issue.

Now I see more and more Go users using WSL. Working in WSL needs a specific setup to work, I think it deserves a section in docs/troubleshooting.md or a separate doc (docs/developing-in-wsl.md maybe?).

**Comment by dsidirop** [comment] 2021-06-18 14:17
> I think the problem may occur if windows git binary try to access git repo cloned inside wsl with Ubuntu git and wise versa.

I have copy-pasted the git-repo of my windows machine into WSL. I will try a fresh-clone and see if things improve. Thank you for the quick tip!

**Comment by wtask** [comment] 2021-06-18 16:16
@dsidirop 
> Update: Re-cloned the git repos afresh inside WSL using WSL's git but the issue persists. Was worth a try though.
But VSCode may use Windows git binary

**Comment by dsidirop** [comment] 2021-06-18 17:33
> @dsidirop
> 
> > Update: Re-cloned the git repos afresh inside WSL using WSL's git but the issue persists. Was worth a try though.
> 
> But VSCode may use Windows git binary

Quick clarification:

I cloned the repos using the vanilla bash-command terminal inside WSL (no VSCode involved).
I then opened the workspace using VSCode. 

Was there something better I could do? Please instruct.

**Comment by wtask** [comment] 2021-06-18 19:11
Your project setup depends on your targets. I don't know them.
My setup is for Windows, with deployment based on Linux containers. 
All repos of my project are cloned under Windows only. The Go installation lives inside Windows. I use some Linux tools like `make` and run them with WSL terminal. But I have cmd-file for run Linux-make under Windows, alhtough I can run it like `wsl make`.
I have no `go` binary inside WSL, but there is a shortcut to Windows go-binary inside WSL Ubuntu distro to run go-related tasks from WSL terminal. For example, `go mod` or `go generate` launches smoothly from Ubuntu, but runs under Windows. And finally I use VSCode for Windows and have no issues with WSL. The Remote Development extension is not necessary in my case.

**Comment by stamblerre** [comment] 2021-06-21 23:49
> Regardless of whether I open a golang folder/project directly as a folder or via a workspace file hosted inside the WSL's filesystem (file:////wsl$/Ubuntu/wsl$/Ubuntu/home/...) I get the same error upon launching VSCode:
> 
> ```
>            Error loading workspace folders (expected 1, got 0) failed to load view for:
> 
>             file:////wsl$/Ubuntu/wsl$/Ubuntu/home/<path to project folder>
> 
>            failed to get workspace configuration from client
> 
>            file:////wsl$/Ubuntu/wsl$/Ubuntu/home/<path to project folder>
> 
>            Request workspace/configuration failed with message:
> 
>           [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
> ```

@dsidirop: Can you please share your workspace file? The workspace URI should include 3 slashes after `file:`, not 4, and that's the problem being reported here.

**Comment by hyangah** [comment] 2021-06-22 20:27
@stamblerre The workspace file would look like this:

```
{
	"folders": [
		{
			"path": "\\\\wsl$\\Ubuntu\\home\\golang\\delve"
		},
		{
			"path": "\\\\wsl$\\Ubuntu\\home\\golang\\tools"
		}
	],
	"settings": {}
}
```

This `\\wsl$\` is the UNC path to locate wsl filesystem from windows, so I don't see anything wrong about this. I don't know if gopls wants to support UNC path (Opening code using the UNC path directly doesn't work and I'd question why gopls would want though)

@dsidirop I opened code from Ubuntu/WSL (installed code, git, go inside the container, and also cloned my repo inside the container). I used Remote - WSL (part of the MS Remote Development pack) and it worked without any issue. 
![Screen Shot 2021-06-22 at 4 21 35 PM](https://user-images.githubusercontent.com/4999471/122994002-f7fb2d80-d375-11eb-8275-58db8cc35d10.png)

If I attempt to open the folders directly from Windows, I encounter the same issue. 

ps. the workspace settings equivalent with the above workspace setting when using the remote dev extension pack would look like the following
```
{
	"folders": [
		{
			"uri": "vscode-remote://wsl+ubuntu/home/golang/delve"
		},
		{
			"uri": "vscode-remote://wsl+ubuntu/home/golang/tools"
		}
	],
	"remoteAuthority": "wsl+ubuntu",
	"settings": {}
}
```

**Comment by wtask** [comment] 2021-06-22 20:39
@hyangah Did you open code.exe or Ubuntu binary? Does WSL support Linux GUI already? I'm outdated now.

**Comment by hyangah** [comment] 2021-06-22 21:06
@wtask I am new to WSL2 and followed this tutorial (https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode). A year old but it still seems to work.

I had code installed on windows already. Today I followed this instruction https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode#from-the-command-line and just ran `code .` from the ubuntu distribution app. Then, everything just magically worked.

Disclaimer: I had to install `go`, `git`, `gcc`, `gopls` again though.

Once this is done, if I launch `code.exe` from Windows, Isee these `WSL` projects, that I opened from the distribution's command line, listed and can access it directly. TBH, I don't know what kind of magic happened behind the scene. 

![Screen Shot 2021-06-22 at 5 04 06 PM](https://user-images.githubusercontent.com/4999471/122999210-f92f5900-d37b-11eb-802f-40f8623205b8.png)

**Comment by wtask** [comment] 2021-06-22 21:33
Okay, WSL version doesn't important in that case. You work with easy accessible VM which is Linux from Windows. And you should understand what you do and why. Unfortunately, I do not fully understand the problem, namely, what the user wants to do. Write code entirely in Linux from under Windows?

**Comment by wtask** [comment] 2021-06-22 22:01
![image](https://user-images.githubusercontent.com/45894304/123005298-8dbaab00-d3be-11eb-97b2-5daf888c07c3.png)

I didn't know I should install anything to work with WSL under VSCode. I think it is worst case and source of the problem is VSCode itself and its strange Server installed under Ubuntu, but not go-extension.

**Comment by hyangah** [comment] 2021-06-22 22:06
@wtask https://code.visualstudio.com/docs/remote/wsl has the architecture. The Go extension needs to be installed on the server side too and VS Code lists extensions installed locally & remotely separately.

**Comment by wtask** [comment] 2021-06-22 22:07
If you have installed code already under Windows better to add executable script somewhere inside Ubuntu which will be available through Path with name `code`:
```
#!/bin/sh  
code.exe "$@"
```

**Comment by wtask** [comment] 2021-06-22 22:16
@hyangah Ok, may be you should not use local (Windows) filesystem to save workspace started from WSL?

**Comment by hyangah** [comment] 2021-06-24 17:44
@dsidirop is it possible to avoid use of `\\wsl$` path?

**Comment by dsidirop** [comment] 2021-06-25 19:17
> Okay, WSL version doesn't important in that case. You work with easy accessible VM which is Linux from Windows. And you should understand what you do and why. Unfortunately, I do not fully understand the problem, namely, what the user wants to do. Write code entirely in Linux from under Windows?

Write code stored in the Linux filesystem (WSL) using VSCode. Simple as that.

**Comment by dsidirop** [comment] 2021-06-25 19:19
> > Regardless of whether I open a golang folder/project directly as a folder or via a workspace file hosted inside the WSL's filesystem (file:////wsl$/Ubuntu/wsl$/Ubuntu/home/...) I get the same error upon launching VSCode:
> > ```
> >            Error loading workspace folders (expected 1, got 0) failed to load view for:
> > 
> >             file:////wsl$/Ubuntu/wsl$/Ubuntu/home/<path to project folder>
> > 
> >            failed to get workspace configuration from client
> > 
> >            file:////wsl$/Ubuntu/wsl$/Ubuntu/home/<path to project folder>
> > 
> >            Request workspace/configuration failed with message:
> > 
> >           [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
> > ```
> 
> @dsidirop: Can you please share your workspace file? The workspace URI should include 3 slashes after `file:`, not 4, and that's the problem being reported here.

This is how my workspace file looks like:

    $ cat *MAG*
    {
            "folders": [
                    {
                            "path": "../../../foo-repo"
                    },
                    {
                            "path": "../../../bar-repo"
                    }
            ],
            "settings": {
            "makefile.makeDirectory": "..",
            "workbench.colorCustomizations": {
                    "activityBar.activeBackground": "#21aa16",
                    "activityBar.activeBorder": "#3946e5",
                    "activityBar.background": "#21aa16",
                    "activityBar.foreground": "#e7e7e7",
                    "activityBar.inactiveForeground": "#e7e7e799",
                    "activityBarBadge.background": "#3946e5",
                    "activityBarBadge.foreground": "#e7e7e7",
                    "statusBar.background": "#187d10",
                    "statusBar.foreground": "#e7e7e7",
                    "statusBarItem.hoverBackground": "#21aa16",
                    "titleBar.activeBackground": "#187d10",
                    "titleBar.activeForeground": "#e7e7e7",
                    "titleBar.inactiveBackground": "#187d1099",
                    "titleBar.inactiveForeground": "#e7e7e799"
            },
            "peacock.color": "#187d10"
            }
    }

Can you make a similar workspace file and try to reproduce the issue?

**Comment by hyangah** [comment] 2021-07-12 21:58
@dsidirop The Remote-WSL extension needs to be explicitly activated if you want to open the workspace. 


Here is the step I followed.

* From Command Palette, "Remote-WSL: Open Folder in WSL..."
![Screen Shot 2021-07-12 at 5 48 38 PM](https://user-images.githubusercontent.com/4999471/125360226-8fcab680-e339-11eb-8120-39eb556baa9f.png)

* Open the folder where your *.code-workspace file is and open the *.code-workspace file.

* Click the "Open Workspace" button in the editor
![Screen Shot 2021-07-12 at 5 49 42 PM](https://user-images.githubusercontent.com/4999471/125360398-cd2f4400-e339-11eb-8749-5fee6891b6f7.png)

Or, if you run `code work.code-workspace` from the terminal of a window with WSL extension activated (i.e. click "open a remote window" on the  left bottom status bar -> New WSL Window), this will open the workspace without an issue. 

There could be a simpler way to access a workspace for WSL but I don't know.
If you think the UX needs improvement, please file an issue in https://github.com/Microsoft/vscode-remote-release 

I am not sure what else this extension can do here.

**Comment by hyangah** [comment] 2021-09-22 22:51
Closing since we don't find any actionables here.

**Closed by hyangah** 2021-09-22 22:51 UTC
Labels: WaitingForInfo
