### ISSUE TITLE
testify test suite test cases cannot be debuged for single test

### ISSUE THREAD

**Issue by ip75** [golang/vscode-go#3015] opened 2023-10-18 16:08 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.21.3 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
----------
golang.org/x/tools/gopls v0.13.2
    golang.org/x/tools/gopls@v0.13.2 h1:Pyvx6MKvatbX3zzZmdGiFRfQZl0ohPlt2sFxO/5j6Ro=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e h1:+WEEuIdZHnUeJJmEUjyYC2gfUMj69yZXw17EnHg/otA=
    golang.org/x/exp/typeparams@v0.0.0-20221212164502-fae10dda9338 h1:2O2DON6y3XMJiQRAS1UWU+54aec2uopH3x7MAiqGW6Y=
    golang.org/x/mod@v0.12.0 h1:rmsUpXtvNzj340zd98LZ4KntptpfRHwpFOHG188oHXc=
    golang.org/x/sync@v0.3.0 h1:ftCYgMx6zT/asHUrPw8BLLscYtGznsLAnjq5RH9P66E=
    golang.org/x/sys@v0.10.0 h1:SqMFp9UcQJZa+pmYuAKjd9xq1f0j5rLcDIk0mj4qAsA=
    golang.org/x/text@v0.11.0 h1:LAntKIrcmeSKERyiOh0XMV39LXS8IE9UL2yP7+f5ij4=
    golang.org/x/tools@v0.11.2-0.20230810185051-cc6b5804b8cf h1:Oush7UwPamr2/iNeNFBuNFj89YyHn0YY69EKDdvANnk=
    golang.org/x/vuln@v0.0.0-20230110180137-6ad3e3d07815 h1:A9kONVi4+AnuOr1dopsibH6hLi1Huy54cbeJxnq4vmU=
    honnef.co/go/tools@v0.4.2 h1:6qXr+R5w+ktL5UkwEbPp+fEvfyoMPche6GkOpGHZcLc=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.21.0

* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.83.1
f1b07bd25dfad64b0167beb15359ae573aecd2cc
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.39.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/ip/go
GOROOT: /usr/local/go
PATH: /home/ip/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/SafeNet/Authentication/SAC/x64:/mnt/c/Program Files/SafeNet/Authentication/SAC/x32:/mnt/c/potrable/git/bin:/Docker/host/bin:/mnt/c/Users/polovykhin/AppData/Local/Microsoft/WindowsApps:/usr/local/go/bin/:/home/ip/go/bin

	go:	/usr/local/go/bin/go: go version go1.21.3 linux/amd64

	gotests:	/home/ip/go/bin/gotests	(version: v1.6.0 built with go: go1.21.3)
	gomodifytags:	/home/ip/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.21.3)
	impl:	not installed
	goplay:	not installed
	dlv:	/home/ip/go/bin/dlv	(version: v1.21.0 built with go: go1.21.0)
	staticcheck:	/home/ip/go/bin/staticcheck	(version: v0.4.5 built with go: go1.21.0)
	gopls:	/home/ip/go/bin/gopls	(version: v0.13.2 built with go: go1.21.0)

go env
Workspace Folder (test): /home/ip/iam/test1
Workspace Folder (test): /home/ip/iam/test2

Workspace Folder (test): /home/ip/iam/test
	GO111MODULE=''
	GOARCH='amd64'
	GOBIN=''
	GOCACHE='/home/ip/.cache/go-build'
	GOENV='/home/ip/.config/go/env'
	GOEXE=''
	GOEXPERIMENT=''
	GOFLAGS=''
	GOHOSTARCH='amd64'
	GOHOSTOS='linux'
	GOINSECURE='gitlab.cldx.io/*'
	GOMODCACHE='/home/ip/go/pkg/mod'
	GONOPROXY='gitlab.cldx.io'
	GONOSUMDB='gitlab.cldx.io'
	GOOS='linux'
	GOPATH='/home/ip/go'
	GOPRIVATE='gitlab.cldx.io'
	GOPROXY='http://prx-1.int.ops.cldx.ru:3000'
	GOROOT='/usr/local/go'
	GOSUMDB='sum.golang.org'
	GOTMPDIR=''
	GOTOOLCHAIN='auto'
	GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
	GOVCS=''
	GOVERSION='go1.21.3'
	GCCGO='gccgo'
	GOAMD64='v1'
	AR='ar'
	CC='gcc'
	CXX='g++'
	CGO_ENABLED='0'
	GOMOD='/home/ip/iam/test/go.mod'
	GOWORK='/home/ip/iam/go.work'
	CGO_CFLAGS='-O2 -g'
	CGO_CPPFLAGS=''
	CGO_CXXFLAGS='-O2 -g'
	CGO_FFLAGS='-O2 -g'
	CGO_LDFLAGS='-O2 -g'
	PKG_CONFIG='pkg-config'
	GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1530108490=/tmp/go-build -gno-record-gcc-switches'
</details>

### Describe the bug
testify test suite test cases cannot be debuged for single test

### Steps to reproduce the behavior:
the same issue like this #2189

**Comment by findleyr** [comment] 2023-10-26 19:51
The underlying issue https://github.com/golang/vscode-go/issues/2414 is still open. Is that what you are experiencing?

**Comment by ip75** [comment] 2023-10-26 19:56
> The underlying issue #2414 is still open. Is that what you are experiencing?

yes. Exactly.

**Comment by hyangah** [comment] 2023-10-26 20:17
Duplicate of #2414

**Closed by hyangah** 2023-10-26 20:17 UTC
Labels: Debug, WaitingForInfo
