### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Alfahan** [golang/vscode-go#3279] opened 2024-03-25 14:57 UTC
gopls version: v0.15.2/go1.19.1
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Mon, 25 Mar 2024 14:57:16 GMT
restart history:
Mon, 25 Mar 2024 14:56:37 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.21.1" (should be something like "go1.12")

goroutine 6007 [running]:
go/types.NewChecker(0x0%3F, 0xc002a41b40, 0xc005f966e0, 0x0%3F)
	  check.go:240  0x24e
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc0020d6f20, {0xc005182648, 0x1, 0x1})
	  analysis.go:1028  0x72c
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc0020d6f20, {0x1c6c760, 0xc006c787b0})
	  analysis.go:810  0xd9
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc0020d6f20, {0x1c6c760%3F, 0xc006c787b0})
	  analysis.go:672  0x145
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xda
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 241,
    "TestdataFiles": 0,
    "GoFiles": 134,
    "ModFiles": 1,
    "Dirs": 72
  },
  "GOARCH": "amd64",
  "GOOS": "windows",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.19.1",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "11.9615668s",
  "MemStats": {
    "HeapAlloc": 40423264,
    "HeapInUse": 56918016,
    "TotalAlloc": 156894496
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2785,
      "Largest": 945502,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.21.4",
        "AllPackages": {
          "Packages": 527,
          "LargestPackage": 134,
          "CompiledGoFiles": 2784,
          "Modules": 97
        },
        "WorkspacePackages": {
          "Packages": 39,
          "LargestPackage": 18,
          "CompiledGoFiles": 137,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment] 2024-03-25 21:11
Duplicate of #3276

**Closed by suzmue** 2024-03-25 21:11 UTC

**Comment by Alfahan** [comment] 2024-03-26 00:09
Okey thanks!
