### ISSUE TITLE
Installing this extension results in huge lag spikes.

### ISSUE THREAD

**Issue by syrull** [golang/vscode-go#2369] opened 2022-07-24 13:45 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
go version go1.18.3 windows/amd64

### Share the Go related settings you have added/edited
None, default install

### Describe the bug
After the installation of this extension, I cannot work with vscode at all it lags my whole computer, first I thought it was something wrong with vscode and I was going to report in the vscode's issue tracker, but after I deleted every extension and freshly installed vscode It was fine, I noticed that after the installation of this extension (only) I basically cannot go into vscode because of lag. Even my mouse lags..

### Steps to reproduce the behavior:
1. Install fresh VSCode
2. Install the extension

### Screenshots or recordings
In the recording I thought the bug comes from VSCode and I recorded it with some extensions enabled, same happens on a fresh install as well. You can see how my mouse skips and I cannot click the boxes because of lag.
https://imgur.com/a/rbabGxL 

I assume that won't be enough information, so please tell me which other things I should put here.

**Comment by hyangah** [comment] 2022-07-25 13:46
Troubleshooting instruction is https://github.com/golang/vscode-go/wiki/troubleshooting
Please share https://github.com/golang/vscode-go/wiki/troubleshooting#collect-gopls-information 

Also, check whether the workspace is configured in a way the extension can work reasonably.
https://github.com/golang/vscode-go#setting-up-your-workspace

**Comment by lenuse** [comment] 2022-07-28 03:33
I have a similar problem, I use go version go1.18.3 darwin/arm64, vs code version 1.69. When the golang project is opened, the CPU usage is very high, and it will take about 10 minutes to return to normal.
Screenshots：
![1658979113090](https://user-images.githubusercontent.com/12166648/181414550-0e45661e-10e2-4d86-854f-658b95b5ce86.jpg)
![1658979124092](https://user-images.githubusercontent.com/12166648/181414556-7f906ab8-b7dd-4700-9d8f-f91e9fd76011.jpg)

**Comment by hyangah** [comment] 2022-07-28 12:06
@lenuse  Can you share the info necessary for investigation?
We saw users experience a similar issue when working with a large code base or
adjust their workspace (https://github.com/golang/vscode-go#setting-up-your-workspace)
to limit scanning of the space. Or, it can be an issue in slow filesystem.

* Your project structure
* How you opened the directory
* Gopls log: instruction https://github.com/golang/vscode-go/wiki/troubleshooting#collect-extension-logs

**Comment by lenuse** [comment] 2022-07-28 12:29
> @lenuse Can you share the info necessary for investigation? We saw users experience a similar issue when working with a large code base or adjust their workspace (https://github.com/golang/vscode-go#setting-up-your-workspace) to limit scanning of the space. Or, it can be an issue in slow filesystem.
> 
> * Your project structure
> * How you opened the directory
> * Gopls log: instruction https://github.com/golang/vscode-go/wiki/troubleshooting#collect-extension-logs

Your project structure：github.com/panjf2000/ants
How you opened the directory：Open any go file and use command + s，At this point, it starts to take up a lot of cpu resources
Gopls log：The following is the log from command +s to the recovery of cpu occupancy
[log.txt](https://github.com/golang/vscode-go/files/9209498/log.txt)
。

**Comment by syrull** [comment] 2022-07-28 16:17
I don't even have a structure, its just a empty folder with a go file in it, however restarting the `gopls` solved the problem for now.

**Comment by lenuse** [comment] 2022-07-29 02:57
> I don't even have a structure, its just a empty folder with a go file in it, however restarting the `gopls` solved the problem for now.

I have tried restarting the computer, but the problem still occurs.

**Comment by syrull** [comment] 2022-07-29 04:42
> > I don't even have a structure, its just a empty folder with a go file in it, however restarting the `gopls` solved the problem for now.
> 
> I have tried restarting the computer, but the problem still occurs.

Try restarting the `gopls` itself, CTRL+SHIFT+P > Go: Restart Language Server

**Comment by lenuse** [comment] 2022-07-29 07:49
@syrull @hyangah Sorry, this problem is not caused by the go extension. Sorry again for wasting everyone's time. The source is go-group-imports-vscode.

**Comment by hyangah** [comment] 2022-07-29 11:08
@lenuse Good to hear that you figured out the issue. And for grouping imports into three groups, you may be interested in `"gopls": {  "formatting.local": "..."}`  setting. https://github.com/golang/vscode-go/wiki/settings#formattinglocal

@syrull Try to define `go.mod` for main module (https://go.dev/doc/tutorial/getting-started) - restarting gopls may seem to resolve an issue but I am not sure how much gopls supports a single file, adhoc package mode (that's beyond what's described in https://github.com/golang/vscode-go#setting-up-your-workspace and https://github.com/golang/tools/blob/master/gopls/doc/workspace.md) In worst case, the gopls and go commands will try to scan your file system looking for relevant `go.mod` file.

Closing.

**Closed by hyangah** 2022-07-29 11:08 UTC
Labels: WaitingForInfo
