### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by rifleridolfi** [golang/vscode-go#3314] opened 2024-04-04 10:25 UTC
gopls version: v0.15.2/go1.20.6
gopls flags: 
update flags: proxy
extension version: 2024.3.1416
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Thu, 04 Apr 2024 10:24:49 GMT
restart history:
Thu, 04 Apr 2024 10:24:37 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.21.1" (should be something like "go1.12")

goroutine 7660 [running]:
go/types.NewChecker(0x1400085c5c0%3F, 0x14005ba3040, 0x140090755e0, 0x0%3F)
	  check.go:237  0x1e8
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0x14003935b80, {0x14008706708, 0x1, 0x1})
	  analysis.go:1028  0x5fc
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0x14003935b80, {0x1031a69b8%3F, 0x140039583c0})
	  analysis.go:810  0x1d4
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0x14003935b80, {0x1031a69b8%3F, 0x140039583c0})
	  analysis.go:672  0x104
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xa4
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa0
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 42956,
    "TestdataFiles": 0,
    "GoFiles": 34401,
    "ModFiles": 39,
    "Dirs": 9800
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.20.6",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "73.019375ms",
  "MemStats": {
    "HeapAlloc": 2743976,
    "HeapInUse": 5275648,
    "TotalAlloc": 12998048
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 0,
      "Largest": 0,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.2",
        "AllPackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "WorkspacePackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by timothy-king** [comment] 2024-04-04 20:56
Duplicate of https://github.com/golang/go/issues/66636. Fix is expected to be in gopls@v0.15.3. Workaround is to reinstall gopls with go1.21+.

**Closed by timothy-king** 2024-04-04 20:56 UTC
