### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by lgxcentury** [golang/vscode-go#1928] opened 2021-12-04 14:22 UTC
gopls version: v0.7.3
gopls flags: 
update flags: proxy
extension version: 0.29.0
go version: 1.17.3
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Sat, 04 Dec 2021 14:21:44 GMT
restart history:
Sat, 04 Dec 2021 08:15:50 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2021-12-06 16:53
Closing, as the issue is empty.
Please reopen if you can share the stack trace of the gopls crash (found by navigating to View -> Output -> Tasks -> gopls (server)).

**Closed by findleyr** 2021-12-06 16:53 UTC
