### ISSUE TITLE
 gopls client: couldn't create connection to server

### ISSUE THREAD

**Issue by Mirko-Tebaldi** [golang/vscode-go#2578] opened 2022-12-17 17:07 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.19.4 windows/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- I got an `access denied` message on prompt
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.74.1
        - 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
        - x64
* Check your installed extensions to get the version of the VS Code Go extension
	- 8.417.742
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
      Checking configured tools....
      GOBIN: undefined
      toolsGopath: 
      gopath: C:\Users\mirko\go
      GOROOT: C:\Program Files\Go
      PATH: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python\Python310\;C:\Python\Python310\Scripts\;C:\Python\Python310;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\dotnet\;C:\Windows\System32\OpenSSH\;C:\Users\mirko\AppData\Local\Android\Sdk\platform-tools;C:\Users\mirko\AppData\Local\Android\Sdk\emulator;C:\Users\mirko\AppData\Local\Microsoft\Windows;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs;C:\Users\mirko\AppData\Local\Yarn\bin;C:\Users\mirko\AppData\Roaming\npm;C:\Users\mirko\AppData\Local\Programs\Fiddler;C:\Users\mirko\adb;C:\adb;C:\flutter\bin;C:\Users\mirko\AppData\Local\Android\Sdk\tools;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\;C:\Program Files (x86)\Common Files\Acronis\FileProtector\;C:\Program Files (x86)\Common Files\Acronis\FileProtector64\;C:\Users\mirko\.windows-build-tools\python27;C:\Program Files\Microsoft VS Code\bin;C:\Progetti\flutter\bin;C:\Users\mirko\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\mirko\AppData\Local\now-cli;C:\Users\mirko\AppData\Local\Microsoft\WindowsApps;C:\Users\mirko\.dotnet\tools;C:\Gradle\bin;C:\Program Files\JetBrains\PhpStorm 2019.3.3\bin;C:\Users\mirko\AppData\Roaming\Composer\vendor\bin;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\apache-ant-1.10.9\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Java\jdk1.8.0_202;C:\Program Files\Java\jdk1.8.0_202\bin;C:\Program Files\heroku\bin;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Go\bin;C:\laragon\bin;C:\laragon\bin\apache\httpd-2.4.35-win64-VC15\bin;C:\laragon\bin\composer;C:\laragon\bin\git\bin;C:\laragon\bin\git\cmd;C:\laragon\bin\git\mingw64\bin;C:\laragon\bin\git\usr\bin;C:\laragon\bin\laragon\utils;C:\laragon\bin\mongodb\mongodb-win32-x86_64-2012plus-4.2.13\bin;C:\laragon\bin\mysql\mysql-5.7.24-winx64\bin;C:\laragon\bin\nginx\nginx-1.16.0;C:\laragon\bin\ngrok;C:\laragon\bin\nodejs\node-v14.16.0-win-x64;C:\laragon\bin\notepad++;C:\laragon\bin\php\php-5.6.9-Win32-VC11-x64;C:\laragon\bin\postgresql\postgresql-13.1\bin;C:\laragon\bin\putty;C:\laragon\bin\redis\redis-x64-3.2.100;C:\laragon\bin\telnet;C:\laragon\usr\bin;C:\Users\mirko\AppData\Local\Yarn\config\global\node_modules\.bin;C:\Users\mirko\AppData\Roaming\Composer\vendor\bin;C:\Users\mirko\AppData\Roaming\npm;C:\Users\mirko\.cargo\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\mirko\.windows-build-tools\python27;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\Yarn\bin\;C:\Users\mirko\AppData\Local\Android\Sdk\platform-tools;C:\Users\mirko\AppData\Local\Android\Sdk\emulator;C:\Users\mirko\AppData\Local\Microsoft\Windows;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Users\mirko\adb;C:\Users\mirko\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\mirko\AppData\Local\now-cli;C:\Users\mirko\AppData\Local\Microsoft\WindowsApps;C:\Gradle\bin;C:\Program Files\JetBrains\PhpStorm 2020.3.2\bin;C:\Users\mirko\AppData\Local\Yarn\bin;C:\Users\mirko\AppData\Local\Microsoft\WindowsApps;C:\Users\mirko\go\bin
      
	      go:	C:\Program Files\Go\bin\go.exe: go version go1.19.4 windows/amd64
      
	      gotests:	not installed
	      gomodifytags:	not installed
	      impl:	not installed
	      goplay:	not installed
	      dlv:	C:\Users\mirko\go\bin\dlv.exe	(version: v1.20.1 built with go: go1.19.4)
	      staticcheck:	not installed
	      gopls:	C:\Users\mirko\go\bin\gopls.exe	(version: v0.11.0 built with go: go1.19.4)
      
      go env
      Workspace Folder (movieapp): c:\Progetti\go\movieapp
	      set GO111MODULE=
	      set GOARCH=amd64
	      set GOBIN=
	      set GOCACHE=C:\Users\mirko\AppData\Local\go-build
	      set GOENV=C:\Users\mirko\AppData\Roaming\go\env
	      set GOEXE=.exe
	      set GOEXPERIMENT=
	      set GOFLAGS=
	      set GOHOSTARCH=amd64
	      set GOHOSTOS=windows
	      set GOINSECURE=
	      set GOMODCACHE=C:\Users\mirko\go\pkg\mod
	      set GONOPROXY=
	      set GONOSUMDB=
	      set GOOS=windows
	      set GOPATH=C:\Users\mirko\go
	      set GOPRIVATE=
	      set GOPROXY=https://proxy.golang.org,direct
	      set GOROOT=C:\Program Files\Go
	      set GOSUMDB=sum.golang.org
	      set GOTMPDIR=
	      set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
	      set GOVCS=
	      set GOVERSION=go1.19.4
	      set GCCGO=gccgo
	      set GOAMD64=v1
	      set AR=ar
	      set CC=gcc
	      set CXX=g++
	      set CGO_ENABLED=1
	      set GOMOD=c:\Progetti\go\movieapp\go.mod
	      set GOWORK=
	      set CGO_CFLAGS=-g -O2
	      set CGO_CPPFLAGS=
	      set CGO_CXXFLAGS=-g -O2
	      set CGO_FFLAGS=-g -O2
	      set CGO_LDFLAGS=-g -O2
	      set PKG_CONFIG=pkg-config
	      set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\mirko\AppData\Local\Temp\go-build3234573528=/tmp/go-build -gno-record-gcc-switches

</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

	"[go]":  {
		"editor.insertSpaces": false,
		"editor.formatOnSave": true,
		"editor.codeActionsOnSave": {
				"source.organizeImports": true
		},
		"editor.suggest.snippetsPreventQuickSuggestions": false
	},
 
    
        "go.toolsManagement.autoUpdate": true

### Describe the bug
A clear and concise description of what the bug.

Opening a go file I got this error

![image](https://user-images.githubusercontent.com/114985433/208253207-2b76feb7-8c32-457b-8d21-455816420a22.png)

The full output i pasted in the previous section

### Steps to reproduce the behavior:

It happens to me simply opening a .go file

### Screenshots or recordings

Nothing to add with a video. Opening a .go file, this error popup !

**Comment by hyangah** [comment] 2022-12-19 15:59
>> Run gopls -v version to get version of Gopls from the VS Code integrated terminal.
> I got an access denied message on prompt

It looks like the gopls binary (C:\Users\mirko\go\bin\gopls.exe) wasn't able to run. Usual culprits are virus scanners (that misclassified the go binaries) or security settings. Please check permissions and make sure thee binaries listed in `Go: Locate Configured Go Tools` output can run.

**Comment by realtebo** [comment] 2022-12-19 16:14
Right !

Disabled Avast, fixed the problem. Sorry !

**Comment by hyangah** [comment] 2022-12-22 20:52
Glad that the problem is fixed. Closing.

**Closed by hyangah** 2022-12-22 20:52 UTC
Labels: WaitingForInfo
