### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by reynaldojosuatogatorop** [golang/vscode-go#3280] opened 2024-03-25 15:27 UTC
gopls version: v0.15.2/go1.20.3
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Mon, 25 Mar 2024 15:25:30 GMT
restart history:
Mon, 25 Mar 2024 10:57:28 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.1" (should be something like "go1.12")

goroutine 1203 [running]:
go/types.NewChecker(0x0%3F, 0xc00082bec0, 0xc00278b6d0, 0x0%3F)
	C:/Program   check.go:237  0x24e
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc0009efd90, {0xc001c40040, 0x2, 0x2})
	  analysis.go:1028  0x73d
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc0009efd90, {0x1599438%3F, 0xc001995c50})
	  analysis.go:810  0x218
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc0009efd90, {0x1599438%3F, 0xc001995c50})
	  analysis.go:672  0x145
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xda
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 63,
    "TestdataFiles": 0,
    "GoFiles": 12,
    "ModFiles": 1,
    "Dirs": 38
  },
  "GOARCH": "amd64",
  "GOOS": "windows",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.20.3",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "20.94878s",
  "MemStats": {
    "HeapAlloc": 9765336,
    "HeapInUse": 18792448,
    "TotalAlloc": 289281152
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 558,
      "Largest": 210104,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.1",
        "AllPackages": {
          "Packages": 80,
          "LargestPackage": 148,
          "CompiledGoFiles": 555,
          "Modules": 1
        },
        "WorkspacePackages": {
          "Packages": 9,
          "LargestPackage": 2,
          "CompiledGoFiles": 12,
          "Modules": 1
        },
        "Diagnostics": 23
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment] 2024-03-25 21:11
Duplicate of #3276

**Closed by suzmue** 2024-03-25 21:11 UTC
