### ISSUE TITLE
debug: breakpoints are missing filenames

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1212] opened 2021-02-08 14:24 UTC
dlv@master
vscode 1.53 & go extension Nightly 2021.2.516
Mac OS, go1.15.6

```
~$ go version -m ~/go/bin/dlv
/Users/hakim/go/bin/dlv: go1.15.6
        path    github.com/go-delve/delve/cmd/dlv
        mod     github.com/go-delve/delve       v1.6.1-0.20210205230555-74223baf9083    h1:Yzr7sRQS6itdVqxuH6rJU+3CZHbZ73WVoZBcAjDCnb4=
        ...
```

```
--- main.go ---
...

func main() {
	sum := 0 // <-- main.go:12: breakpoint
	for i := 0; i < 10; i++ {
		s := F()
		sum += s
	}
}
--- go.mod ---
module w

go 1.15
```
launch.json
```
        {
            "name": "Launch test package (dlv dap)",
            "type": "godlvdap",
            "request": "launch",
            "mode": "test",
            "program": "${fileDirname}",
            "logOutput": "dap",
            "showLog": true,
            "trace": "verbose"
        },
```

What I expected:

Like with the old debug adapter, the file name of the breakpoint is shown correctly.
![Screen Shot 2021-02-08 at 9 19 42 AM](https://user-images.githubusercontent.com/4999471/107231929-dc0e7500-69ee-11eb-9941-c5ddb49bd64a.png)

What I got instead:

File name was '/'. 

![image](https://user-images.githubusercontent.com/4999471/107232076-0102e800-69ef-11eb-9d3e-167461f8d59a.png)

<details>
<summary> dlv dap trace </summary>
2021-2-8, 14:10:14.516 UTC
[14:10:14.517 UTC] From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code - Insiders","adapterID":"godlvdap","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en","supportsProgressReporting":true,"supportsInvalidatedEvent":true})
[14:10:14.517 UTC] InitializeRequest
[14:10:14.517 UTC] To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true}}
[14:10:14.517 UTC] InitializeResponse
[14:10:14.517 UTC] From client: launch({"name":"Launch Package (dlv dap)","type":"godlvdap","request":"launch","mode":"debug","program":"/Users/hakim/projects/google/w","trace":"verbose","showLog":true,"logOutput":"dap","__configurationTarget":5,"packagePathToGoModPathMap":{"/Users/hakim/projects/google/w":"/Users/hakim/projects/google/w"},"apiVersion":2,"dlvLoadConfig":{"followPointers":true,"maxVariableRecurse":1,"maxStringLen":64,"maxArrayValues":64,"maxStructFields":-1},"showGlobalVariables":false,"dlvToolPath":"/Users/hakim/go/bin/dlv","env":{"ELECTRON_RUN_AS_NODE":"1","USER":"hakim","PATH":"/Users/hakim/.nvm/versions/node/v12.4.0/bin:/Users/hakim/google-cloud-sdk/bin:/Users/hakim/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/hakim/.npm-packages/bin","LOGNAME":"hakim","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.FgwU4b9tZD/Listeners","HOME":"/Users/hakim","SHELL":"/bin/bash","__CF_USER_TEXT_ENCODING":"0xDBC5:0x0:0x0","TMPDIR":"/var/folders/bw/6r6k9d113sv1_vvzk_1kfxbm001py5/T/","XPC_SERVICE_NAME":"com.microsoft.VSCodeInsiders.15536","XPC_FLAGS":"0x0","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","VSCODE_NLS_CONFIG":"{\"locale\":\"en\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_NODE_CACHED_DATA_DIR":"/Users/hakim/Library/Application Support/Code - Insiders/CachedData/8490d3dde47c57ba65ec40dd192d014fd2113496","VSCODE_IPC_HOOK":"/Users/hakim/Library/Application Support/Code - Insiders/1.53.0-insider-main.sock","VSCODE_PID":"37736","NVM_INC":"/Users/hakim/.nvm/versions/node/v12.4.0/include/node","MANPATH":"/Users/hakim/.nvm/versions/node/v12.4.0/share/man:/usr/local/git/current/share/man:/usr/local/share/man:/usr/share/man:/Users/hakim/.npm-packages/share/man:/Library/Apple/usr/share/man:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man:/Users/hakim/.npm-packages/share/man","NVM_CD_FLAGS":"","NVM_DIR":"/Users/hakim/.nvm","REMOTE_TSSERVER_HOSTNAME":"kalbi.nyc.corp.google.com","LD_LIBRARY_PATH":"/Users/hakim/homebrew/lib:","SK_SIGNING_PLUGIN":"gnubbyagent","PWD":"/","EDITOR":"vi","PS1":"\\w$ ","SHLVL":"1","NVM_BIN":"/Users/hakim/.nvm/versions/node/v12.4.0/bin","AUTH_HOST":"hakim3.nyc","_":"/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron","VSCODE_AMD_ENTRYPOINT":"vs/workbench/services/extensions/node/extensionHostProcess","VSCODE_PIPE_LOGGING":"true","VSCODE_VERBOSE_LOGGING":"true","VSCODE_LOG_NATIVE":"false","VSCODE_IPC_HOOK_EXTHOST":"/var/folders/bw/6r6k9d113sv1_vvzk_1kfxbm001py5/T/vscode-ipc-f576d6cf-d7a7-4dd8-8225-6b926479d6b3.sock","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","VSCODE_LOG_STACK":"true","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"true","GOPATH":"/Users/hakim/go","GOPROXY":"https://proxy.golang.org,direct","GOMODCACHE":"/Users/hakim/go/pkg/mod"},"__sessionId":"094e1d57-dd2f-4a2b-a31d-caa2c055b1c5"})
[14:10:14.517 UTC] launchRequest
[14:10:14.517 UTC] Running: /Users/hakim/go/bin/dlv dap --listen=127.0.0.1:42042 --log=true --log-output=dap
[14:10:14.949 UTC] dlv stdout: DAP server listening at: 127.0.0.1:42042

[14:10:14.950 UTC] dlv stderr: 2021-02-08T09:10:14-05:00 debug layer=dap DAP server pid = 91626

[14:10:15.161 UTC] dlv stderr: 2021-02-08T09:10:15-05:00 debug layer=dap [<- from client]{"seq":2,"type":"request","command":"launch","arguments":{"__configurationTarget":5,"__sessionId":"094e1d57-dd2f-4a2b-a31d-caa2c055b1c5","apiVersion":2,"dlvLoadConfig":{"followPointers":true,"maxArrayValues":64,"maxStringLen":64,"maxStructFields":-1,"maxVariableRecurse":1},"dlvToolPath":"/Users/hakim/go/bin/dlv","env":{"APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"true","AUTH_HOST":"hakim3.nyc","EDITOR":"vi","ELECTRON_RUN_AS_NODE":"1","GOMODCACHE":"/Users/hakim/go/pkg/mod","GOPATH":"/Users/hakim/go","GOPROXY":"https://proxy.golang.org,direct","HOME":"/Users/hakim","LD_LIBRARY_PATH":"/Users/hakim/homebrew/lib:","LOGNAME":"hakim","MANPATH":"/Users/hakim/.nvm/versions/node/v12.4.0/share/man:/usr/local/git/current/share/man:/usr/local/share/man:/usr/share/man:/Users/hakim/.npm-packages/share/man:/Library/Apple/usr/share/man:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man:/Users/hakim/.npm-packages/share/man","NVM_BIN":"/Users/hakim/.nvm/versions/node/v12.4.0/bin","NVM_CD_FLAGS":"","NVM_DIR":"/Users/hakim/.nvm","NVM_INC":"/Users/hakim/.nvm/versions/node/v12.4.0/include/node","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","PATH":"/Users/hakim/.nvm/versions/node/v12.4.0/bin:/Users/hakim/google-cloud-sdk/bin:/Users/hakim/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/hakim/.npm-packages/bin","PS1":"\\w$ ","PWD":"/","REMOTE_TSSERVER_HOSTNAME":"kalbi.nyc.corp.google.com","SHELL":"/bin/bash","SHLVL":"1","SK_SIGNING_PLUGIN":"gnubbyagent","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.FgwU4b9tZD/Listeners","TMPDIR":"/var/folders/bw/6r6k9d113sv1_vvzk_1kfxbm001py5/T/","USER":"hakim","VSCODE_AMD_ENTRYPOINT":"vs/workbench/services/extensions/node/extensionHostProcess","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","VSCODE_IPC_HOOK":"/Users/hakim/Library/Application Support/Code - Insiders/1.53.0-insider-main.sock","VSCODE_IPC_HOOK_EXTHOST":"/var/folders/bw/6r6k9d113sv1_vvzk_1kfxbm001py5/T/vscode-ipc-f576d6cf-d7a7-4dd8-8225-6b926479d6b3.sock","VSCODE_LOG_NATIVE":"false","VSCODE_LOG_STACK":"true","VSCODE_NLS_CONFIG":"{\"locale\":\"en\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_NODE_CACHED_DATA_DIR":"/Users/hakim/Library/Application Support/Code - Insiders/CachedData/8490d3dde47c57ba65ec40dd192d014fd2113496","VSCODE_PID":"37736","VSCODE_PIPE_LOGGING":"true","VSCODE_VERBOSE_LOGGING":"true","XPC_FLAGS":"0x0","XPC_SERVICE_NAME":"com.microsoft.VSCodeInsiders.15536","_":"/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron","__CF_USER_TEXT_ENCODING":"0xDBC5:0x0:0x0"},"host":"127.0.0.1","logOutput":"dap","mode":"debug","name":"Launch Package (dlv dap)","packagePathToGoModPathMap":{"/Users/hakim/projects/google/w":"/Users/hakim/projects/google/w"},"port":42042,"program":"/Users/hakim/projects/google/w","request":"launch","showGlobalVariables":false,"showLog":true,"trace":"verbose","type":"godlvdap"}}

[14:10:16.805 UTC] dlv stderr: 2021-02-08T09:10:16-05:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"initialized"}

[14:10:16.806 UTC] To client: {"seq":0,"type":"event","event":"initialized"}
[14:10:16.806 UTC] To client: {"seq":0,"type":"response","request_seq":2,"success":true,"command":"launch"}
[14:10:16.806 UTC] dlv stderr: 2021-02-08T09:10:16-05:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":2,"success":true,"command":"launch"}

[14:10:16.808 UTC] From client: setBreakpoints({"source":{"name":"main.go","path":"/Users/hakim/projects/google/w/main.go"},"lines":[12],"breakpoints":[{"line":12}],"sourceModified":false})
[14:10:16.809 UTC] dlv stderr: 2021-02-08T09:10:16-05:00 debug layer=dap [<- from client]{"seq":3,"type":"request","command":"setBreakpoints","arguments":{"source":{"name":"main.go","path":"/Users/hakim/projects/google/w/main.go"},"breakpoints":[{"line":12}],"lines":[12]}}

[14:10:16.809 UTC] dlv stderr: 2021-02-08T09:10:16-05:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":3,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"verified":true,"source":{},"line":12}]}}

[14:10:16.809 UTC] To client: {"seq":0,"type":"response","request_seq":3,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"verified":true,"source":{},"line":12}]}}
[14:10:16.824 UTC] From client: configurationDone(undefined)
[14:10:16.825 UTC] dlv stderr: 2021-02-08T09:10:16-05:00 debug layer=dap [<- from client]{"seq":4,"type":"request","command":"configurationDone","arguments":{}}
2021-02-08T09:10:16-05:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":4,"success":true,"command":"configurationDone"}

[14:10:16.825 UTC] To client: {"seq":0,"type":"response","request_seq":4,"success":true,"command":"configurationDone"}
[14:10:16.828 UTC] From client: threads(undefined)
[14:10:16.841 UTC] dlv stderr: 2021-02-08T09:10:16-05:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"stopped","body":{"reason":"breakpoint","threadId":1,"allThreadsStopped":true}}

[14:10:16.841 UTC] To client: {"seq":0,"type":"event","event":"stopped","body":{"reason":"breakpoint","threadId":1,"allThreadsStopped":true}}
[14:10:16.841 UTC] dlv stderr: 2021-02-08T09:10:16-05:00 debug layer=dap [<- from client]{"seq":5,"type":"request","command":"threads"}

[14:10:16.843 UTC] From client: threads(undefined)
[14:10:16.853 UTC] dlv stderr: 2021-02-08T09:10:16-05:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":5,"success":true,"command":"threads","body":{"threads":[{"id":1,"name":"* [Go 1] main.main (Thread 6067489)"},{"id":2,"name":"[Go 2] runtime.gopark"},{"id":3,"name":"[Go 3] runtime.gopark"},{"id":4,"name":"[Go 4] runtime.gopark"}]}}

[14:10:16.853 UTC] dlv stderr: 2021-02-08T09:10:16-05:00 debug layer=dap [<- from client]{"seq":6,"type":"request","command":"threads"}

[14:10:16.853 UTC] To client: {"seq":0,"type":"response","request_seq":5,"success":true,"command":"threads","body":{"threads":[{"id":1,"name":"* [Go 1] main.main (Thread 6067489)"},{"id":2,"name":"[Go 2] runtime.gopark"},{"id":3,"name":"[Go 3] runtime.gopark"},{"id":4,"name":"[Go 4] runtime.gopark"}]}}
[14:10:16.857 UTC] dlv stderr: 2021-02-08T09:10:16-05:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":6,"success":true,"command":"threads","body":{"threads":[{"id":1,"name":"* [Go 1] main.main (Thread 6067489)"},{"id":2,"name":"[Go 2] runtime.gopark"},{"id":3,"name":"[Go 3] runtime.gopark"},{"id":4,"name":"[Go 4] runtime.gopark"}]}}

[14:10:16.857 UTC] To client: {"seq":0,"type":"response","request_seq":6,"success":true,"command":"threads","body":{"threads":[{"id":1,"name":"* [Go 1] main.main (Thread 6067489)"},{"id":2,"name":"[Go 2] runtime.gopark"},{"id":3,"name":"[Go 3] runtime.gopark"},{"id":4,"name":"[Go 4] runtime.gopark"}]}}
[14:10:16.895 UTC] From client: stackTrace({"threadId":1,"startFrame":0,"levels":20})
[14:10:16.896 UTC] dlv stderr: 2021-02-08T09:10:16-05:00 debug layer=dap [<- from client]{"seq":7,"type":"request","command":"stackTrace","arguments":{"threadId":1,"levels":20,"format":{}}}

[14:10:16.898 UTC] dlv stderr: 2021-02-08T09:10:16-05:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":7,"success":true,"command":"stackTrace","body":{"stackFrames":[{"id":1000,"name":"main.main","source":{"name":"main.go","path":"/Users/hakim/projects/google/w/main.go"},"line":12,"column":0},{"id":1001,"name":"runtime.main","source":{"name":"proc.go","path":"/usr/local/go/src/runtime/proc.go"},"line":204,"column":0},{"id":1002,"name":"runtime.goexit","source":{"name":"asm_amd64.s","path":"/usr/local/go/src/runtime/asm_amd64.s"},"line":1374,"column":0}],"totalFrames":3}}

[14:10:16.899 UTC] To client: {"seq":0,"type":"response","request_seq":7,"success":true,"command":"stackTrace","body":{"stackFrames":[{"id":1000,"name":"main.main","source":{"name":"main.go","path":"/Users/hakim/projects/google/w/main.go"},"line":12,"column":0},{"id":1001,"name":"runtime.main","source":{"name":"proc.go","path":"/usr/local/go/src/runtime/proc.go"},"line":204,"column":0},{"id":1002,"name":"runtime.goexit","source":{"name":"asm_amd64.s","path":"/usr/local/go/src/runtime/asm_amd64.s"},"line":1374,"column":0}],"totalFrames":3}}
[14:10:17.323 UTC] From client: scopes({"frameId":1000})
[14:10:17.324 UTC] dlv stderr: 2021-02-08T09:10:17-05:00 debug layer=dap [<- from client]{"seq":8,"type":"request","command":"scopes","arguments":{"frameId":1000}}

[14:10:17.325 UTC] dlv stderr: 2021-02-08T09:10:17-05:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":8,"success":true,"command":"scopes","body":{"scopes":[{"name":"Arguments","variablesReference":1000,"expensive":false,"source":{}},{"name":"Locals","variablesReference":1001,"expensive":false,"source":{}}]}}

[14:10:17.325 UTC] To client: {"seq":0,"type":"response","request_seq":8,"success":true,"command":"scopes","body":{"scopes":[{"name":"Arguments","variablesReference":1000,"expensive":false,"source":{}},{"name":"Locals","variablesReference":1001,"expensive":false,"source":{}}]}}
[14:10:17.330 UTC] From client: variables({"variablesReference":1000})
[14:10:17.331 UTC] dlv stderr: 2021-02-08T09:10:17-05:00 debug layer=dap [<- from client]{"seq":9,"type":"request","command":"variables","arguments":{"variablesReference":1000,"format":{}}}

[14:10:17.331 UTC] dlv stderr: 2021-02-08T09:10:17-05:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":9,"success":true,"command":"variables","body":{"variables":[]}}

[14:10:17.331 UTC] To client: {"seq":0,"type":"response","request_seq":9,"success":true,"command":"variables","body":{"variables":[]}}
</details>

**Comment by hyangah** [comment] 2021-02-08 14:45
Related: adding additional breakpoints while the debug session is active (Delve DAP is running) is broken. Originally, I thought this is a separate issue. But I observed the breakpoint was actually set so `continue` stops at the new breakpoint. See the newly added breakpoints were shown with "/" as the file name in the breakpoints panel. I guess VS Code didn't add the newly added breakpoint to the editor due to the missing filename.

 ![breakpoint](https://user-images.githubusercontent.com/4999471/107234487-b898f980-69f1-11eb-8c64-af585be95d83.gif)

**Comment by polinasok** [comment] 2021-02-17 08:40
`"test"` in launch.json threw me off a bit, but I was able to reproduce this with
```
            "mode": "debug",
            "program": "${file}", 
```
Not sure what is going on yet. When comparing relevant log entries with the old and the new adapter, things look the same.

Old
```
[08:00:28.920 UTC] From client: setBreakpoints({"source":{"name":"main.go","path":"/Users/polina/go/src/issue1212/main.go"},"lines":[4],"breakpoints":[{"line":4}],"sourceModified":false})
```
New
```
2021-02-17T00:33:07-08:00 debug layer=dap [<- from client]{"seq":3,"type":"request","command":"setBreakpoints","arguments":{"source":{"name":"main.go","path":"/Users/polina/go/src/issue1212/main.go"},"breakpoints":[{"line":4}],"lines":[4]}}
```
Old
```
2021-02-17T00:00:30-08:00 info layer=debugger created breakpoint: &api.Breakpoint{ID:1, Name:"", Addr:0x105e88e, Addrs:[]uint64{0x105e88e}, File:"/Users/polina/go/src/issue1212/main.go", Line:4, FunctionName:"main.main", Cond:"", Tracepoint:false, TraceReturn:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(0xc0005460f0), LoadLocals:(*api.LoadConfig)(0xc000546120), HitCount:map[string]uint64{}, TotalHitCount:0x0}
```
New
```
2021-02-17T00:33:07-08:00 info layer=debugger created breakpoint: &api.Breakpoint{ID:1, Name:"", Addr:0x105e88e, Addrs:[]uint64{0x105e88e}, File:"/Users/polina/go/src/issue1212/main.go", Line:4, FunctionName:"main.main", Cond:"", Tracepoint:false, TraceReturn:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(0xc0001e9320), LoadLocals:(*api.LoadConfig)(0xc0001e9350), HitCount:map[string]uint64{}, TotalHitCount:0x0}
```
Old
```
[08:00:30.181 UTC] To client: {"seq":0,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":true,"line":4}]}}
```
New
```
2021-02-17T00:33:07-08:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":3,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"verified":true,"source":{},"line":4}]}}
```

**Comment by hyangah** [comment] 2021-02-17 15:08
Thanks for comparing and capturing the logs.
I suspect this party in the `setBreakpoints` response
`"breakpoints":[{"verified":true,"source":{},"line":4}]}}`

The old debug adapter didn't set `source` but depends on the deprecated `line` property (probably grandfathered?). From the spec, `source` replaces  `line` and is required. So let's try to populate the source property correctly and see how it goes.

**Comment by polinasok** [comment] 2021-02-17 20:38
Yup, I was looking into this myself already. Initially, I aimed to reproduce what the old debugger did (minus the obvious bugs) for a stable and consistent starting point. It is not clear why the same fields work for the old adapter, but not for the new one. In fact, you can even drop `line` in the response in the old adapter, and things would still work, probably because the editor already knows source as it already communicated it via the request.

That said, where do you see that `line` in the response is deprecated and that `source` is required? I don't see that in the spec for [setBreakpoints](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_SetBreakpoints) nor for [Breakpoint](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Breakpoint). They are not overlapping either - there is no line in [Source](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Source). I only see that `lines` is deprecated in the request (referenced [here](https://github.com/microsoft/vscode-debugadapter-node/blob/f82cafb41452753538c89424e84d70f05412d7d8/protocol/src/debugProtocol.ts#L656) and [here](https://github.com/microsoft/vscode-debugadapter-node/blob/f82cafb41452753538c89424e84d70f05412d7d8/protocol/src/debugProtocol.ts#L671)), but we don't rely on that anyway.

**Comment by hyangah** [comment] 2021-02-17 20:54
Ah, it's my mistake - I was looking at the request format. It looks like we can just drop the source property.
Everything is optional in Breakpoint, except the `verified` bit.

**Comment by polinasok** [comment] 2021-02-18 07:33
I have added optional information to Breakpoint in setBreakpoint response, and the UI is now working as intended - see snapshots in https://github.com/go-delve/delve/pull/2347. I still do not understand why the responses from the old adapter (where it is enough to only set `verified` field to have the UI do the right thing) and the new adapter are treated differently. 
/cc @weinand @isidorn

**Comment by weinand** [comment] 2021-02-18 09:00
@weinand I don't think that VS Code treats `setBreakpoints` responses differently for different adapters. @isidorn do you have an explanation?

**Comment by isidorn** [comment] 2021-02-18 14:29
We should not treat them differently.
My best suggestion is for @polinasok to set a breakpoint [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugSession.ts#L367) on the VS Code side and investigate further. Since that is the place where we handle the response of the `setBreakpoints` request.

**Comment by polinasok** [comment] 2021-02-24 08:57
Mystery has been solved! 

I followed the instructions [here](https://github.com/microsoft/vscode/wiki/How-to-Contribute) and [here](https://github.com/golang/vscode-go/blob/master/docs/contributing.md#sideload) to set up a debug session for this and hit the breakpoint as you recommended. I noticed this difference, which reminded me of us noticing `"source":{}` in the logs before:
![image](https://user-images.githubusercontent.com/51177946/108962538-c6738f00-762d-11eb-898a-67c8afc7f5ed.png)

![image](https://user-images.githubusercontent.com/51177946/108962661-ef941f80-762d-11eb-895e-56f47bbfc3a2.png)

And as a result after updating the `this.model`, the URI that used to be set to the path in the request, gets cleared and becomes empty, which is what is causes `\` to show up in the UI.

![image](https://user-images.githubusercontent.com/51177946/108965126-49e2af80-7631-11eb-999c-92882d594081.png)

When mapping DAP types to Go types, we defined `Source` as a struct. And in Go there is no such thing as an unset struct - such a struct just gets populated with all default values. And even though the [`Source` field has `omitempty`](https://github.com/google/go-dap/blob/e92a0d405e2d9f5623b71f64d4f5e781f6b0f9f9/schematypes.go#L1740), its empty version is still included as `"source":{}` by json marshaling in Go. Apparently I am not the only one who was surprised by this: there is  an open 5-year old and active proposal to fix this in `encoding/json` package (see https://github.com/golang/go/issues/11939). I guess, we could have also used a pointer to the struct to be able to unset it for real with `nil`. And perhaps we should revisit our entire schema in [go-dap](https://github.com/google/go-dap) with this in mind. But it might also make sense for vscode to address this as well - treating undefined `source.path` just like it treats undefined `source`.

**Comment by isidorn** [comment] 2021-02-24 09:01
@polinasok thanks for clarifying.
We are not handling `undefined` `source.path` and `source` the same beacuse a `source` can have a `sourceReference` for example and then we can use the `Source` properly.
Here's the code that handles it https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/common/debugSource.ts#L42

Though feel free to file a new issue in VS Code if you think we can improve this

**Comment by polinasok** [comment] 2021-02-24 09:31
Let's move vscode internals discussion to https://github.com/microsoft/vscode/issues/117554.
Closing this issue because we found a way to handle this in dlv-dap.

**Closed by polinasok** 2021-02-24 09:31 UTC
Labels: Debug, DlvDAP
