### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by kostromin59** [golang/vscode-go#3434] opened 2024-06-26 11:52 UTC
gopls version: v0.16.0/go1.22.4
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Wed, 26 Jun 2024 11:51:15 GMT
restart history:
Wed, 26 Jun 2024 11:25:22 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: slice bounds out of range [8:7]

goroutine 147 [running]:
golang.org/x/tools/gopls/internal/golang/completion.Selection.Suffix(...)
	  completion.go:367
golang.org/x/tools/gopls/internal/server.toProtocolCompletionItems({0x140002eeb08, 0x3, 0x140014586c0%3F}, 0x14000453f40, 0x140000f1688)
	  completion.go:114  0x778
golang.org/x/tools/gopls/internal/server.(*server).Completion(0x140000ce780, {0x101b76108, 0x14000359f50}, 0x1400039be00)
	  completion.go:76  0x4cc
golang.org/x/tools/gopls/internal/protocol.serverDispatch({0x101b76140, 0x1400040acd0}, {0x101b90050, 0x140000ce780}, 0x14000359a10, {0x101b76300, 0x14000414280})
	  tsserver.go:361  0x1f28
golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.ServerHandler.func3({0x101b76140, 0x1400040acd0}, 0x14000359a10, {0x101b76300, 0x14000414280})
	  protocol.go:160  0x74
golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.handshaker.func4({0x101b76140, 0x1400040acd0}, 0x14000359a10, {0x101b76300, 0x14000414280})
	  lsprpc.go:509  0x6e0
golang.org/x/tools/gopls/internal/protocol.Handlers.MustReplyHandler.func1({0x101b76140, 0x1400040acd0}, 0x14000243368, {0x101b76300, 0x14000414280})
	  handler.go:35  0xc0
golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2.2()
	  handler.go:103  0x90
created by golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2 in goroutine 133
	  handler.go:100  0x19c
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 68,
    "TestdataFiles": 0,
    "GoFiles": 7,
    "ModFiles": 1,
    "Dirs": 52
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.4",
  "GoplsVersion": "v0.16.0",
  "InitialWorkspaceLoadDuration": "258.992542ms",
  "MemStats": {
    "HeapAlloc": 13881816,
    "HeapInUse": 22388736,
    "TotalAlloc": 202745280
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 882,
      "Largest": 395026,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.4",
        "AllPackages": {
          "Packages": 139,
          "LargestPackage": 155,
          "CompiledGoFiles": 879,
          "Modules": 1
        },
        "WorkspacePackages": {
          "Packages": 3,
          "LargestPackage": 4,
          "CompiledGoFiles": 7,
          "Modules": 1
        },
        "Diagnostics": 6
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-06-26 14:41
Dupe of golang/go#68169, which will be fixed soon.

**Closed by findleyr** 2024-06-26 14:41 UTC
