### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by tkennon** [golang/vscode-go#1333] opened 2021-03-13 13:50 UTC
gopls version: v0.6.4
gopls flags: 
extension version: 0.23.2
environment: Visual Studio Code linux
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 0
total start count: 1

Started up VSCode, opened my workspace with Remote Containers, selected the default Go container (`1` - uses Go1.15.7), prompted to install the Go extension in this container, and when I did I see the error message below.

The same version of gopls and Go work fine when not working on the host as opposed to in the development container.

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 </pre>

**Comment by hyangah** [comment] 2021-03-13 15:14
Duplicate of #1300
In your cases,  the gopls in the remote container needs rebuilding. Sorry for the trouble. @tkennon

**Closed by hyangah** 2021-03-13 15:14 UTC

**Comment by tkennon** [comment] 2021-03-13 19:06
Thanks for the quick reply @hyangah, yep that's worked :+1:
