### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by aaron-dy-moon** [golang/vscode-go#1884] opened 2021-11-09 11:49 UTC
gopls version: v0.7.3
gopls flags: 
update flags: proxy
extension version: 0.29.0
go version: 1.16.5
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Tue, 09 Nov 2021 11:50:22 GMT
restart history:
Tue, 09 Nov 2021 11:50:04 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: assertion failed

goroutine 291 [running]:
go/types.(*Checker).handleBailout(0xc00113e000, 0xc001d23660)
	  check.go:245  0x9f
panic(0xd32420, 0x109a0d0)
	  panic.go:965  0x1b9
go/types.assert(...)
	  errors.go:20
go/types.(*Checker).shift(0xc00113e000, 0xc0028a0140, 0xc0028a0180, 0xc000a66fc0, 0x14)
	  expr.go:709  0xb6f
go/types.(*Checker).binary(0xc00113e000, 0xc0028a0140, 0xc000a66fc0, 0x10bcfe0, 0xc001726b60, 0x10bcfe0, 0xc001726b80, 0x14, 0xa4b61)
	  expr.go:821  0x155
go/types.(*Checker).exprInternal(0xc00113e000, 0xc0028a0140, 0x10bcc50, 0xc000a66fc0, 0x0, 0x0, 0xc00113e000)
	  expr.go:1553  0x1dc5
go/types.(*Checker).rawExpr(0xc00113e000, 0xc0028a0140, 0x10bcc50, 0xc000a66fc0, 0x0, 0x0, 0xc00113e000)
	  expr.go:1029  0x85
go/types.(*Checker).multiExpr(0xc00113e000, 0xc0028a0140, 0x10bcc50, 0xc000a66fc0)
	  expr.go:1652  0x58
go/types.(*Checker).expr(0xc00113e000, 0xc0028a0140, 0x10bcc50, 0xc000a66fc0)
	  expr.go:1646  0x49
go/types.(*Checker).call(0xc00113e000, 0xc0028a0140, 0xc000431280, 0x10bcfe0)
	  call.go:34  0xfa
go/types.(*Checker).exprInternal(0xc00113e000, 0xc0028a0140, 0x10bcce0, 0xc000431280, 0x0, 0x0, 0x203000)
	  expr.go:1519  0x1e2c
go/types.(*Checker).rawExpr(0xc00113e000, 0xc0028a0140, 0x10bcce0, 0xc000431280, 0x0, 0x0, 0x40)
	  expr.go:1029  0x85
go/types.(*Checker).multiExpr(0xc00113e000, 0xc0028a0140, 0x10bcce0, 0xc000431280)
	  expr.go:1652  0x58
go/types.(*Checker).expr(0xc00113e000, 0xc0028a0140, 0x10bcce0, 0xc000431280)
	  expr.go:1646  0x49
go/types.(*Checker).constDecl(0xc00113e000, 0xc0011cbb00, 0x10bcfe0, 0xc001726b20, 0x10bcce0, 0xc000431280, 0x0)
	  decl.go:499  0x1b4
go/types.(*Checker).objDecl(0xc00113e000, 0x10cfd70, 0xc0011cbb00, 0x0)
	  decl.go:186  0x765
go/types.(*Checker).packageObjects(0xc00113e000)
	  resolver.go:537  0x3a9
go/types.(*Checker).checkFiles(0xc00113e000, 0xc00112fb60, 0x4, 0x4, 0x0, 0x0)
	  check.go:265  0xb9
go/types.(*Checker).Files(...)
	  check.go:250
golang.org/x/tools/internal/lsp/cache.doTypeCheck(0x10beab8, 0xc000301f00, 0xc000626400, 0xc0002605a0, 0x2, 0xc0003dfd70, 0x0, 0x0, 0x0, 0x0)
	  check.go:536  0xd52
golang.org/x/tools/internal/lsp/cache.typeCheck(0x10beab8, 0xc000301f00, 0xc000626400, 0xc0002605a0, 0x2, 0xc0003dfd70, 0xc000e5a2a0, 0x0, 0x0)
	  check.go:313  0xa5
golang.org/x/tools/internal/lsp/cache.(*snapshot).buildPackageHandle.func1(0x10beab8, 0xc000301f00, 0x10ac7e0, 0xc000626400, 0xc0005cb7a0, 0x5e0936)
	  check.go:124  0x1bf
golang.org/x/tools/internal/memoize.(*Handle).run.func1(0xc000d0bb60, 0x10beab8, 0xc000301f00, 0xc000d117a0, 0x10ac7e0, 0xc000626400, 0xc000d17f80)
	  memoize.go:322  0xab
created by golang.org/x/tools/internal/memoize.(*Handle).run
	  memoize.go:315  0x185
[Error - 8:50:12 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2021-11-09 14:14
Thanks for the report @aaron-dy-moon 
The trace looks exactly like https://github.com/golang/go/issues/47472 which is marked as a duplicate of https://github.com/golang/go/issues/43765.

@aaron-dy-moon can you upgrade to 1.17.3 (and recompile gopls with go1.17.3) and see if the problem is reproducible? Thanks!

**Closed** 2021-11-12 21:23 UTC
Labels: WaitingForInfo, automatedReport
