### ISSUE TITLE
Failed to find go binary

### ISSUE THREAD

**Issue by weeco** [golang/vscode-go#1010] opened 2020-12-07 15:12 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
go version go1.15.6 linux/amd64

- Run `gopls -v version` to get version of Gopls if you are using [the language server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).
Not yet installed

- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
code -v
1.51.1
e5a624b788d92b8d34d1392e4c4d9789406efe8f
x64

- Check your installed extensions to get the version of the VS Code Go extension
v0.19.0

- Run `go env` to get the go development environment details
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/martin/.cache/go-build"
GOENV="/home/martin/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/martin/.gvm/pkgsets/go1.15.6/global/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/martin/.gvm/pkgsets/go1.15.6/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/martin/.gvm/gos/go1.15.6"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/martin/.gvm/gos/go1.15.6/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build441737748=/tmp/go-build -gno-record-gcc-switches"
```

### Describe the bug

After installing the go plugin it fails to find the go binary. The locate go binary command returns this:

```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: undefined
GOROOT: 
PATH: /home/martin/.gvm/bin:/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin

unable to locate "go" binary in GOROOT () or PATH (/home/martin/.gvm/bin:/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin)
```

It seems like it can't read the gopath. I tried reloading the VSCode windows several times but it hasn't worked once. In my ZSH console the GOROOT env variable is set:

```
echo $GOROOT
/home/martin/.gvm/gos/go1.15.6
```

### Steps to reproduce the behavior:

I'm not sure if it's reproducible but here's what I did (Ubuntu 20.04).

1. Install VSCode
2. Install Go plugin
3. Install latest Go version using gvm (Go version manager)
4. Reload window

**Comment by hyangah** [comment] 2020-12-07 17:19
@weeco thanks for reaching out.
The extension finds the go binary from one of the listed PATH (/home/martin/.gvm/bin:/sbin:/usr/bin:/usr/local/bin:/snap/bin in your case) inherited by the vscode main process. It looks like the vscode was launched through the UI app launcher that's not affected by the gvm, or outside of your workspace where gvm configures environment. 

If configuring the right PATH is tricky, one of the easiest workaround is to use

```
"go.goroot": "/home/martin/.gvm/gos/go1.15.6"
```

**Comment by hyangah** [comment] 2020-12-07 17:20
Duplicate of https://github.com/golang/vscode-go/issues/756

**Closed by hyangah** 2020-12-07 17:20 UTC
