### ISSUE TITLE
Multiline documentation in hover shown as single line

### ISSUE THREAD

**Issue by gudvinr** [golang/vscode-go#1248] opened 2021-02-25 15:33 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- go 1.16
- gopls 0.6.6
- code 1.53.2
- vscode-go 0.22.1

### Share the Go related settings you have added/edited
```json
    "go.lintOnSave": "workspace",
    "go.lintFlags": [ "-min_confidence=1.1" ],
    "go.toolsGopath": modified,
    "gopls": {
        "usePlaceholders": false,
        "analyses": {
            "composites": false,
            "shadow": true,
            "ST1000": false
        },
        "ui.diagnostic.staticcheck": true
    },
```

### Describe the bug

Documentation written with line breaks shown as continuous line without line breaks in hover string.  
Line breaks set to LF in my case.  
This applies to my packages, imported packages and stdlib.

### Screenshots or recordings
<img width="512" alt="2021-02-25 18 13 16" src="https://user-images.githubusercontent.com/1712806/109175770-32bdd200-7797-11eb-95b0-05e57c227a2b.png">

<img width="512" alt="2021-02-25 18 13 30" src="https://user-images.githubusercontent.com/1712806/109175800-394c4980-7797-11eb-9209-39d1d5ba7a70.png">

**Comment by stamblerre** [comment] 2021-02-25 19:21
I believe that this is working as intended, and this logic is documented in [ToHTML](https://golang.org/pkg/go/doc/#ToHTML) function used by `gopls`. It's possible that the VS Code UI could present this a little better, but that's not up to this extension.

**Comment by gudvinr** [comment] 2021-02-25 20:23
> I believe that this is working as intended

No, it's not. If you look into gopls logs with `-rpc.trace` you will see next line (irrelevant information marked as `skipped`):
```
[Trace - skipped] Received response 'textDocument/hover - (110)' in 1ms.
Result: {"contents":{"kind":"markdown","value":"```go\nfunc HelpDoc()\n```\n\n[`HelpDoc` on pkg.go.dev](skipped)\n\nHelpDoc document\nsecond line\nthird line\n"},"range":{skipped}}}
```

For snippet like this:
```go
// HelpDoc document
// second line
// third line
func HelpDoc() {
}
```
With `"kind":"markdown"` string `HelpDoc document\nsecond line\nthird line\n` clrearly is not a correct multiline string.  
Correct one should be `HelpDoc document  \nsecond line  \nthird line` with double spaces before line break and without final one.

**Comment by wtask** [comment] 2021-02-25 20:28
Line breaks will appear if you add extra LF to your doc-block. And something like MD is working, only very strange. I see syntax highlighting for some cases. For example:
```
// Method is ...
//
// Exceptions:
//
//{tab} - first ;
//{tab} - second ;
```
The '-' and ';' will be highlighted. Also there is double space between first and second lines. Strange behavior.

**Comment by gudvinr** [comment] 2021-02-25 20:48
I did a little digging and found out [an article from 2011](https://blog.golang.org/godoc) which says
> There are a few formatting rules that Godoc uses when converting comments to HTML:
> * _Subsequent lines of text are considered part of the same paragraph; you must leave a blank line to separate paragraphs._
> * Pre-formatted text must be indented relative to the surrounding comment text (see gob's doc.go for an example).
> * URLs will be converted to HTML links; no special markup is necessary.

So I guess this is indeed intentional behavior when it comes to rendering as HTML.  
Is it possible to add an option to show documentation in dense form then?

**Comment by hyangah** [comment] 2021-02-26 03:04
The bubble size changes depending on the window size. For small window size, I think the current behavior produces better form of documentation with line wrap. (for example, see the image included in  https://github.com/microsoft/vscode/issues/14165#issuecomment-299545783 if the line break is preserved and the tooltip is too narrow)  But in big window, I agree that the width seems too wide. https://github.com/microsoft/vscode/issues/14165 is a feature request for configurable tooltip size. Please upvote the issue.

**Comment by hyangah** [comment] 2021-02-26 03:07
@gopherbot add upstream-vscode and remove Documentation

**Comment by gudvinr** [comment] 2021-02-26 08:03
> width seems too wide

It's not about width mostly. Actually, I never said a word about tooltip being too wide. I am ok with its width. But documentation inside comments already written to be readable by person who looks at the code.  
It is structured in such way that is easily skimmable. At least in stdlib and most of my docs.

So while this upstream issue kind of related, I am not sure how it's possible to make hovers look good for everyone on every display.

**Comment by hyangah** [comment] 2021-02-26 15:28
Thanks for clarification, @gudvinr  
I meant documentation in hover looks better when the line wrap is done automatically based on the viewer's display size.

gopls follows the same style as the godoc and traditional go documentation in general. It's likely that your documentation is shown in the similar way in other official go documentation sites such as pkg.go.dev or godoc.org. For example compare this
source code https://go.googlesource.com/go/+/go1.16/src/net/http/pprof/pprof.go and how it's [presented in pkg.go.dev site](https://pkg.go.dev/net/http/pprof#section-sourcefiles). I think it's better to provide similar experience to users than inventing our own. If you do think preserving the style from the source is better for general go documentation, please file an issue in https://golang.org/issues for discussions.

I don't see any actionable in this extension. Can we close this issue?

**Comment by gudvinr** [comment] 2021-02-26 16:30
> Can we close this issue?

Yes, thanks for the help. I'll try to bring up that issue in gopls tracker then.  
It is indeed shown as you see it in godoc because of mimicking to HTML style. Although, for what it's worth there's at least a way to make formatted lists using `{space}- entry` notation as **wtask** mentioned.
This is how its done in [Go documentation](https://golang.org/pkg/encoding/json/) too but it's just a representation for any embedded source snippet.

**Closed** 2021-02-26 16:45 UTC
Labels: upstream-vscode
