### ISSUE TITLE
Ignoring certain files

### ISSUE THREAD

**Issue by kasvtv** [golang/vscode-go#1699] opened 2021-08-17 09:59 UTC
**Is your feature request related to a problem? Please describe.**
I'm working in a project with a decent amount of `protoc` generated code, which generates a bunch of warnings. As soon as the language server loads the project, my "Problems" pane is full of these warnings, which is very distracting. As this code is (re)generated automatically, and on regular basis, manually fixing these warnings is not feasible.

**Describe the solution you'd like**
I'd like to be able to ignore certain folders, especially in the case of warnings

**Describe alternatives you've considered**
Adding the files to `"files.exclude"` and enabling `"Hide Excluded Files"` in the Problems pane. I like the files still to be visible though.

**Comment by stamblerre** [comment] 2021-08-17 14:35
I believe this is a duplicate of https://github.com/golang/go/issues/41436. @kasvtv: Does that issue cover the concerns you've brought up here?

**Comment by stamblerre** [comment] 2021-08-17 19:16
Duplicate of golang/go#41436

**Closed by stamblerre** 2021-08-17 19:16 UTC
