### ISSUE TITLE
Godoc preview for current package

### ISSUE THREAD

**Issue by Southclaws** [golang/vscode-go#2513] opened 2022-10-29 12:33 UTC
**Is your feature request related to a problem? Please describe.**

I, like many open source authors, like to put effort into documenting our libraries. Now I can run `godoc` locally like this:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/1636971/198831523-30930e20-6207-4fb7-ac48-d8d1542d2c57.png">

but this is super outdated, it's not rendering my markdown like pkg.go.dev does. Now I've tried to run pkg.go.dev locally but it needs a ton of dependencies.

**Describe the solution you'd like**

As with a lot of languages, it would be really nice to be able to preview our documentation. This is especially important when it's quite extensive and includes code examples and many sections and headings.

**Describe alternatives you've considered**

godoc and pkgsite and also repeatedly pushing to the live pkg.go.dev every time I see an issue, this is extremely frustrating.

**Comment by findleyr** [comment] 2022-10-31 19:49
I think this is effectively a dupe of https://go.dev/issue/55861 -- if we were to support this it would likely be via gopls. There is some discussion there about how this could/should be approached.

**Closed by findleyr** 2022-10-31 19:49 UTC
