### ISSUE TITLE
Go: Install/Update Tools: "gocode: Failed to close gocode process"

### ISSUE THREAD

**Issue by joe-getcouragenow** [golang/vscode-go#362] opened 2020-07-16 14:27 UTC
I have had this now twice in the last week. First time i figured well thats handover issues, but 2nd time is not....

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
``` 
go version go1.14.4 darwin/amd64 
```

- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
```
code -v
1.47.1
485c41f9460bdb830c4da12c102daff275415b53
x64
```

- Check your installed extensions to get the version of the VS Code Go extension 
```
code --list-extensions --show-versions
Arjun.swagger-viewer@3.0.1
ban.spellright@3.0.50
bpruitt-goddard.mermaid-markdown-syntax-highlighting@1.0.3
bungcip.better-toml@0.3.2
Dart-Code.dart-code@3.12.2
Dart-Code.flutter@3.12.2
DavidAnson.vscode-markdownlint@0.36.1
dtsvet.vscode-wasm@1.3.1
golang.go@0.15.1
googlecloudtools.cloudcode@1.4.1
ms-azuretools.vscode-docker@1.3.1
ms-kubernetes-tools.vscode-kubernetes-tools@1.2.1
mtxr.sqltools@0.22.10
octref.vetur@0.24.0
redhat.vscode-yaml@0.9.1
rust-lang.rust@0.7.8
vstirbu.vscode-mermaid-preview@1.5.2
wholroyd.HCL@0.0.5
zxh404.vscode-proto3@0.4.2
```
- Run `go env` to get the go development environment details
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/apple/workspace/go/bin"
GOCACHE="/Users/apple/Library/Caches/go-build"
GOENV="/Users/apple/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build233778218=/tmp/go-build -gno-record-gcc-switches -fno-common"

```
### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```
 //-------- Golang configuration --------
    // From: https://github.com/golang/tools/blob/master/gopls/doc/vscode.md
    "go.useLanguageServer": true,
    "[go]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
        // Optional: Disable snippets, as they conflict with completion ranking.
        "editor.snippetSuggestions": "none",
    },
    "[go.mod]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
    },
    "gopls": {
        // Add parameter placeholders when completing a function.
        "usePlaceholders": true,

        // If true, enable additional analyses with staticcheck.
        // Warning: This will significantly increase memory usage.
        "staticcheck": false,
    },
```

### Describe the bug
WHen i run the golang tools install it ran but then failed:

```
Tools environment: GOPATH=/Users/apple/workspace/go, GOBIN=/Users/apple/workspace/go/bin
Installing 18 tools at the configured GOBIN: /Users/apple/workspace/go/bin in module mode.
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  gotests
  gomodifytags
  impl
  fillstruct
  goplay
  godoctor
  dlv
  gocode-gomod
  godef
  goreturns
  golint
  gopls

Installing github.com/uudashr/gopkgs/v2/cmd/gopkgs SUCCEEDED
Installing github.com/ramya-rao-a/go-outline SUCCEEDED
Installing github.com/acroca/go-symbols SUCCEEDED
Installing golang.org/x/tools/cmd/guru SUCCEEDED
Installing golang.org/x/tools/cmd/gorename SUCCEEDED
Installing github.com/cweill/gotests/... SUCCEEDED
Installing github.com/fatih/gomodifytags SUCCEEDED
Installing github.com/josharian/impl SUCCEEDED
Installing github.com/davidrjenni/reftools/cmd/fillstruct SUCCEEDED
Installing github.com/haya14busa/goplay/cmd/goplay SUCCEEDED
Installing github.com/godoctor/godoctor SUCCEEDED
Installing github.com/go-delve/delve/cmd/dlv SUCCEEDED
Installing github.com/stamblerre/gocode SUCCEEDED
Installing github.com/rogpeppe/godef SUCCEEDED
Installing github.com/sqs/goreturns SUCCEEDED
Installing golang.org/x/lint/golint SUCCEEDED
Installing golang.org/x/tools/gopls SUCCEEDED

1 tools failed to install.

gocode: Failed to close gocode process: Error: Command failed: /Users/apple/workspace/go/bin/gocode close
2020/07/16 16:08:52 dial unix /var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/gocode-daemon.apple: connect: no such file or directory
. 

```

```
For it to install all the tools ..
```

### Steps to reproduce the behavior:
1. Go to Command Pallet ... & Go: Install/Update Tools
2. Click on all the check boxes
3. See error above !

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

![Screenshot 2020-07-16 at 16 28 30](https://user-images.githubusercontent.com/59567750/87683467-69ebef80-c781-11ea-8025-55b8a2041037.png)

**Comment by joe-getcouragenow** [comment] 2020-07-16 14:39
It seems that gocode does NOT work with modules and is very old. Is there any point running this ?

**Comment by stamblerre** [comment] 2020-07-16 14:54
https://go-review.googlesource.com/c/vscode-go/+/242780 should have fixed this, but the fix has not yet been released. You can try the [Nightly build](https://github.com/golang/vscode-go/blob/master/docs/nightly.md) of the extension to confirm if the fix works for you.

**Comment by stamblerre** [comment] 2020-07-16 15:12
Oh, actually, I believe that the Nightly build has not yet been released.
In the meantime, you can install `gocode` by running `go get github.com/stamblerre/gocode`. This version of `gocode` does work with modules, but if you want a better development experience with modules, we recommend [`gopls`](https://github.com/golang/vscode-go/blob/master/docs/gopls.md) instead.

**Comment by hyangah** [comment] 2020-07-20 15:40
The new nightly version just published includes https://go-review.googlesource.com/c/vscode-go/+/242780 
@joe-getcouragenow and anyone who experienced this issue can try and check if it's fixed?
I will make a point release with this cl once bug fix is confirmed.

**Comment by sanket-bhalerao** [comment] 2020-07-20 19:12
for me, the tools do not install at all. it just stuck forever.
i tried to reinstall the extension (tried with the nightly and stable version as well)
restarting vscode does not help either.
with some luck, 1-2 tools got installed but not all.
I can not see any errors or any indication for error as well.

**Comment by hyangah** [comment] 2020-07-20 19:32
@sanket-bhalerao what is the nightly version?

**Comment by sanket-bhalerao** [comment] 2020-07-20 19:34
@hyangah 
![image](https://user-images.githubusercontent.com/9264813/87978468-0ef22980-caee-11ea-8519-b7ba8ce47f86.png)

**Comment by hyangah** [comment] 2020-07-20 19:37
@sanket-bhalerao Thanks. Can you manually install those tools? From a directory without go.mod file, run `GO111MODULE=on go get -x <path to the tool you are trying to install>`

**Comment by sanket-bhalerao** [comment] 2020-07-20 19:41
I can manually install it

**Comment by hyangah** [comment] 2020-07-20 19:43
@sanket-bhalerao glad to hear that you could manually install it. What tool was the problematic one when trying to install with the extension? 
We should add more logging definitely.

**Comment by sanket-bhalerao** [comment] 2020-07-20 19:49
i could not get any of the 17 tools that are listed.

**Comment by joe-getcouragenow** [comment] 2020-07-21 09:55
@hyangah @stamblerre

OK so it works fully for me just now.

VSCODE prompted to restart due to a new version of itself, detected that i had upgraded golang to 1.14.5, and prompted me to reinstall all the golang tools. Perfect workflow !! 


```


go version go1.14.5 darwin/amd64

Tools environment: GOPATH=/Users/apple/workspace/go, GOBIN=/Users/apple/workspace/go/bin
Installing 17 tools at the configured GOBIN: /Users/apple/workspace/go/bin in module mode.
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  gotests
  gomodifytags
  impl
  fillstruct
  goplay
  godoctor
  dlv
  gocode-gomod
  godef
  goreturns
  golint
  gopls

Installing github.com/uudashr/gopkgs/v2/cmd/gopkgs SUCCEEDED
Installing github.com/ramya-rao-a/go-outline SUCCEEDED
Installing github.com/acroca/go-symbols SUCCEEDED
Installing golang.org/x/tools/cmd/guru SUCCEEDED
Installing golang.org/x/tools/cmd/gorename SUCCEEDED
Installing github.com/cweill/gotests/... SUCCEEDED
Installing github.com/fatih/gomodifytags SUCCEEDED
Installing github.com/josharian/impl SUCCEEDED
Installing github.com/davidrjenni/reftools/cmd/fillstruct SUCCEEDED
Installing github.com/haya14busa/goplay/cmd/goplay SUCCEEDED
Installing github.com/godoctor/godoctor SUCCEEDED
Installing github.com/go-delve/delve/cmd/dlv SUCCEEDED
Installing github.com/stamblerre/gocode SUCCEEDED
Installing github.com/rogpeppe/godef SUCCEEDED
Installing github.com/sqs/goreturns SUCCEEDED
Installing golang.org/x/lint/golint SUCCEEDED
Installing golang.org/x/tools/gopls SUCCEEDED

All tools successfully installed. You are ready to Go :).
```


I think i can close this now ?

**Comment by hyangah** [comment] 2020-07-22 17:05
0.15.2 is released including the cl https://go-review.googlesource.com/c/vscode-go/+/242780 
CL https://golang.org/cl/243898 didn't make to 0.15.2, but is in the latest nightly. It will be in 0.16.0. 

I am not sure the cause of the problem @sanket-bhalerao is experiencing. (maybe try `gocode close` manually and see if it hangs). If you keep getting installation failures, please file a new issue. 

Thanks!

**Closed by hyangah** 2020-07-22 17:05 UTC
