### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by udaya2899** [golang/vscode-go#725] opened 2020-10-01 10:40 UTC
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

I shut down my laptop. Then, opened VS Code again. On Opening VS Code. The gopls server crashed.

Attached the stack trace

```
panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 104 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:58 +0x22e
golang.org/x/tools/internal/lsp/debug.section(0xed1100, 0xc00025bb00, 0x0, 0xd571db, 0x7, 0xc000256f18)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:69 +0x319
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xee50a0, 0xc00033b940, 0xed1100, 0xc00025bb00, 0x1, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:52 +0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc0001b5a40, 0xee50a0, 0xc00033b940, 0xc00023e000, 0x0, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/general.go:87 +0x58b
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc0001b5a40, 0xee50a0, 0xc00033b940, 0xc00023e000, 0xc00023e000, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/server_gen.go:108 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xee50a0, 0xc00033b940, 0xf00220, 0xc0001b5a40, 0xc000211b30, 0xee52e0, 0xc00033b8c0, 0x0, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/tsserver.go:235 +0x4bb
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xee50a0, 0xc00033b940, 0xc000211b30, 0xee52e0, 0xc00033b8c0, 0x0, 0xbfd58a31a0dd3ebb)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/protocol.go:63 +0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xee50a0, 0xc00033b940, 0xc000211b30, 0xee52e0, 0xc00033b8c0, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/lsprpc/lsprpc.go:557 +0x420
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xee50a0, 0xc00033b940, 0xc00032b720, 0xee52e0, 0xc00033b8c0, 0x40771f, 0xc00003e778)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:35 +0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00003ed80, 0xc00033f980, 0xc00032cdd0, 0xee50a0, 0xc00033b940, 0xc00032b720, 0xee52e0, 0xc00033b8c0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:100 +0x171
[Info  - 4:06:54 pm] Connection to server got closed. Server will restart.
panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 91 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:58 +0x22e
golang.org/x/tools/internal/lsp/debug.section(0xed1100, 0xc000348540, 0x0, 0xd571db, 0x7, 0xc000330f18)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:69 +0x319
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xee50a0, 0xc0001be880, 0xed1100, 0xc000348540, 0x1, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:52 +0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc000170c80, 0xee50a0, 0xc0001be880, 0xc000316000, 0x0, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/general.go:87 +0x58b
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc000170c80, 0xee50a0, 0xc0001be880, 0xc000316000, 0xc000316000, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/server_gen.go:108 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xee50a0, 0xc0001be880, 0xf00220, 0xc000170c80, 0xc00007e570, 0xee52e0, 0xc0001be800, 0x0, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/tsserver.go:235 +0x4bb
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xee50a0, 0xc0001be880, 0xc00007e570, 0xee52e0, 0xc0001be800, 0x0, 0xbfd58a31aea8bd08)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/protocol.go:63 +0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xee50a0, 0xc0001be880, 0xc00007e570, 0xee52e0, 0xc0001be800, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/lsprpc/lsprpc.go:557 +0x420
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xee50a0, 0xc0001be880, 0xc0001a7ae0, 0xee52e0, 0xc0001be800, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:35 +0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0000a6d20, 0xc0001bb9e0, 0xc000195f90, 0xee50a0, 0xc0001be880, 0xc0001a7ae0, 0xee52e0, 0xc0001be800)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:100 +0x171
[Info  - 4:06:54 pm] Connection to server got closed. Server will restart.
panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 79 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:58 +0x22e
golang.org/x/tools/internal/lsp/debug.section(0xed1100, 0xc0002efe30, 0x0, 0xd571db, 0x7, 0xc0002fef18)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:69 +0x319
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xee50a0, 0xc00033ff00, 0xed1100, 0xc0002efe30, 0x1, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:52 +0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc0001adea0, 0xee50a0, 0xc00033ff00, 0xc0002e4000, 0x0, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/general.go:87 +0x58b
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc0001adea0, 0xee50a0, 0xc00033ff00, 0xc0002e4000, 0xc0002e4000, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/server_gen.go:108 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xee50a0, 0xc00033ff00, 0xf00220, 0xc0001adea0, 0xc0002c9e60, 0xee52e0, 0xc00033fe80, 0x0, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/tsserver.go:235 +0x4bb
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xee50a0, 0xc00033ff00, 0xc0002c9e60, 0xee52e0, 0xc00033fe80, 0x0, 0xbfd58a31b06ea54b)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/protocol.go:63 +0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xee50a0, 0xc00033ff00, 0xc0002c9e60, 0xee52e0, 0xc00033fe80, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/lsprpc/lsprpc.go:557 +0x420
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xee50a0, 0xc00033ff00, 0xc000356320, 0xee52e0, 0xc00033fe80, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:35 +0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00003f080, 0xc00034e780, 0xc000337150, 0xee50a0, 0xc00033ff00, 0xc000356320, 0xee52e0, 0xc00033fe80)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:100 +0x171
[Info  - 4:06:54 pm] Connection to server got closed. Server will restart.
panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 92 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:58 +0x22e
golang.org/x/tools/internal/lsp/debug.section(0xed1100, 0xc0004ab170, 0x0, 0xd571db, 0x7, 0xc000498f18)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:69 +0x319
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xee50a0, 0xc0003f85c0, 0xed1100, 0xc0004ab170, 0x1, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:52 +0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc000385180, 0xee50a0, 0xc0003f85c0, 0xc0000fa000, 0x0, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/general.go:87 +0x58b
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc000385180, 0xee50a0, 0xc0003f85c0, 0xc0000fa000, 0xc0000fa000, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/server_gen.go:108 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xee50a0, 0xc0003f85c0, 0xf00220, 0xc000385180, 0xc0000e71a0, 0xee52e0, 0xc0003f8540, 0x0, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/tsserver.go:235 +0x4bb
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xee50a0, 0xc0003f85c0, 0xc0000e71a0, 0xee52e0, 0xc0003f8540, 0x0, 0xbfd58a31b2268aea)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/protocol.go:63 +0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xee50a0, 0xc0003f85c0, 0xc0000e71a0, 0xee52e0, 0xc0003f8540, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/lsprpc/lsprpc.go:557 +0x420
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xee50a0, 0xc0003f85c0, 0xc0003eece0, 0xee52e0, 0xc0003f8540, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:35 +0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0002171a0, 0xc0003f4f00, 0xc000381a10, 0xee50a0, 0xc0003f85c0, 0xc0003eece0, 0xee52e0, 0xc0003f8540)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:100 +0x171
[Info  - 4:06:54 pm] Connection to server got closed. Server will restart.
panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 121 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:58 +0x22e
golang.org/x/tools/internal/lsp/debug.section(0xed1100, 0xc0004805a0, 0x0, 0xd571db, 0x7, 0xc000368f18)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:69 +0x319
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xee50a0, 0xc00024efc0, 0xed1100, 0xc0004805a0, 0x1, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:52 +0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc00026a320, 0xee50a0, 0xc00024efc0, 0xc00035c000, 0x0, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/general.go:87 +0x58b
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc00026a320, 0xee50a0, 0xc00024efc0, 0xc00035c000, 0xc00035c000, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/server_gen.go:108 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xee50a0, 0xc00024efc0, 0xf00220, 0xc00026a320, 0xc0003525d0, 0xee52e0, 0xc00024ef40, 0x0, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/tsserver.go:235 +0x4bb
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xee50a0, 0xc00024efc0, 0xc0003525d0, 0xee52e0, 0xc00024ef40, 0x0, 0xbfd58a31b3d41b14)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/protocol.go:63 +0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xee50a0, 0xc00024efc0, 0xc0003525d0, 0xee52e0, 0xc00024ef40, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/lsprpc/lsprpc.go:557 +0x420
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xee50a0, 0xc00024efc0, 0xc00023f7a0, 0xee52e0, 0xc00024ef40, 0x0, 0x0)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:35 +0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00021eae0, 0xc000251bf0, 0xc000402000, 0xee50a0, 0xc00024efc0, 0xc00023f7a0, 0xee52e0, 0xc00024ef40)
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/home/hplapchn036/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:100 +0x171
[Error - 4:06:54 pm] Connection to server got closed. Server will not be restarted.
```

**Comment by udaya2899** [comment] 2020-10-01 11:03
This is my output on doing 

```echo $PATH```

```
/home/hplapchn036/bin:/usr/local/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by hyangah** [comment] 2020-10-01 13:07
@udaya2899  thanks for the report. This is a duplicate of https://github.com/golang/vscode-go/issues/713.

**Closed by hyangah** 2020-10-01 13:07 UTC
