### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by trend-ronghui-yang** [golang/vscode-go#3210] opened 2024-02-29 19:36 UTC
gopls version: v0.13.2/go1.22.0
gopls flags: 
update flags: proxy
extension version: 0.41.1
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Thu, 29 Feb 2024 19:36:11 GMT
restart history:
Thu, 29 Feb 2024 19:36:07 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: incomplete panic trace.

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after running for 622ms
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-02-29 19:57
Dupe of #3209.

**Closed by findleyr** 2024-02-29 19:57 UTC
