### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by ranggadablues** [golang/vscode-go#1623] opened 2021-07-14 10:24 UTC
gopls version: v0.7.0
gopls flags: 
update flags: proxy
extension version: 0.23.3
go version: 1.14.1
environment: Visual Studio Code linux
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: only file URIs are supported, got "untitled" from "untitled:Untitled-3"

goroutine 19930 [running]:
golang.org/x/tools/internal/span.URI.Filename(...)
	  uri.go:32
golang.org/x/tools/internal/lsp.(*Server).definition(0xc000134380, 0xe5c3e0, 0xc069be2400, 0xc069a10f80, 0x0, 0x0, 0x0, 0x0, 0x0)
	  definition.go:16  0x7a4
golang.org/x/tools/internal/lsp.(*Server).Definition(0xc000134380, 0xe5c3e0, 0xc069be2400, 0xc069a10f80, 0xc069a10f80, 0x0, 0x0, 0x0, 0x0)
	  server_gen.go:40  0x4d
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xe5c3e0, 0xc069be2400, 0xe772a0, 0xc000134380, 0xc068d40630, 0xe5c6a0, 0xc069be2380, 0x0, 0x0, 0xe4cd20)
	  tsserver.go:386  0x2642
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xe5c3e0, 0xc069be2400, 0xc068d40630, 0xe5c6a0, 0xc069be2380, 0x0, 0x0)
	  protocol.go:154  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xe5c3e0, 0xc069be2400, 0xc068d40630, 0xe5c6a0, 0xc069be2380, 0x0, 0x0)
	  lsprpc.go:684  0x43b
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xe5c3e0, 0xc069be2400, 0xc033f79b80, 0xe5c6a0, 0xc069be2380, 0xc05ff71600, 0x10000000043f566)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc068d1be60, 0xc068d3f1a0, 0xc0002e4ce0, 0xe5c3e0, 0xc069be2400, 0xc033f79b80, 0xe5c6a0, 0xc069be2380)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Error - 5:19:49 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2021-07-14 15:06
Duplicate of https://github.com/golang/vscode-go/issues/1559
Please update the Go extension (v0.26.0 is the latest).

**Closed by hyangah** 2021-07-14 15:06 UTC
