### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by quybuiptc** [golang/vscode-go#2334] opened 2022-07-12 15:31 UTC
gopls version: v0.9.0 (go1.18.2)
gopls flags: 
update flags: proxy
extension version: 0.34.1
go version: 1.18.2
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Tue, 12 Jul 2022 15:31:35 GMT
restart history:
Sat, 09 Jul 2022 17:29:19 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x11f7cf3]

goroutine 12650 [running]:
golang.org/x/tools/internal/xcontext.detachedContext.Value(...)
	  xcontext.go:23
golang.org/x/tools/internal/lsp/debug.GetInstance({0x1c73db0%3F, 0xc012bba270%3F})
	  serve.go:361  0x3e
golang.org/x/tools/internal/lsp/debug.makeGlobalExporter.func1({0x1c73db0, 0xc012bba270}, {{0xc0ab82d08a1688e8, 0x388250d2e, 0x21947c0}, {{{0x1c72ae0, 0xc0001ae0e0}, 0xa, {0x18c6680, 0x19fffeb}}, ...}, ...}, ...)
	  serve.go:571  0x7e
golang.org/x/tools/internal/event/core.deliver({0x1c73db0, 0xc012bba270}, 0xc0000a7e90, {{0xc0ab82d08a1688e8, 0x388250d2e, 0x21947c0}, {{{0x1c72ae0, 0xc0001ae0e0}, 0xa, {0x18c6680, ...}}, ...}, ...})
	  export.go:45  0xfd
golang.org/x/tools/internal/event/core.ExportPair({_, _}, {{0x0, 0x0, 0x0}, {{{0x1c72ae0, 0xc0001ae0e0}, 0xa, {0x18c6680, 0x19fffeb}}, ...}, ...}, ...)
	  export.go:68  0x128
golang.org/x/tools/internal/event.Start({0x1c73db0%3F, 0xc012bba270%3F}, {0x19fffeb%3F, 0xc011b15660%3F}, {0xc00bc74820%3F, 0x0%3F, 0x0%3F})
	  event.go:91  0x358
golang.org/x/tools/internal/jsonrpc2.(*conn).Notify(0x0%3F, {0x1c73db0, 0xc012bba270}, {0x19fffeb, 0xa}, {0x18a8e20%3F, 0xc011b15660%3F})
	  conn.go:85  0x35b
golang.org/x/tools/internal/lsp/protocol.clientConn.Notify(...)
	  protocol.go:60
golang.org/x/tools/internal/lsp/protocol.(*clientDispatcher).Progress(0x198ab40%3F, {0x1c73db0%3F, 0xc012bba270%3F}, 0x2321108%3F)
	  tsclient.go:168  0x42
golang.org/x/tools/internal/lsp/progress.(*WorkDone).Report(0xc00bc74000, {0x0%3F, 0x0%3F}, {0xc012ab7e60, 0x53}, 0x0)
	  progress.go:188  0x27e
golang.org/x/tools/internal/lsp/progress.(*WorkDoneWriter).Write(0xc00926c5a0%3F, {0xc00ff1c000%3F, 0x53, 0x104d552%3F})
	  progress.go:268  0x5c
io.(*multiWriter).Write(0xc00cd4e090%3F, {0xc00ff1c000, 0x53, 0x8000})
	  multi.go:60  0x86
io.copyBuffer({0x1c6d0e0, 0xc009ed7098}, {0x1c6d580, 0xc00cd4e090}, {0x0, 0x0, 0x0})
	  io.go:428  0x204
io.Copy(...)
	  io.go:385
os/exec.(*Cmd).writerDescriptor.func1()
	  exec.go:311  0x3a
os/exec.(*Cmd).Start.func1(0xc00a834420%3F)
	  exec.go:441  0x25
created by os/exec.(*Cmd).Start
	  exec.go:440  0x715
[Error - 10:31:14 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2022-07-12 21:37
This is a dupe of golang/go#53781. Apologies for the breakage: we'll release gopls@v0.9.1 this week with a fix.

**Closed by findleyr** 2022-07-12 21:37 UTC
