### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by mariaaloysiusa** [golang/vscode-go#2269] opened 2022-05-31 04:12 UTC
gopls version: v0.8.4 (go1.18.2)
gopls flags: go.useLanguageServer
update flags: proxy
extension version: 0.33.1
go version: 1.18.2
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Tue, 31 May 2022 04:12:29 GMT
restart history:
Tue, 31 May 2022 04:07:53 GMT: activation (enabled: true)
Tue, 31 May 2022 04:12:01 GMT: config change (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2022-05-31 13:49
Closing, as the issue is empty.
Please reopen if you can share the stack trace of the gopls crash (found by navigating to View -> Output -> Tasks -> gopls (server)).

**Closed by findleyr** 2022-05-31 13:49 UTC
