### ISSUE TITLE
gopls: automated issue report (crash) - SIGSEGV in lsp/cache.parseGoWork

### ISSUE THREAD

**Issue by qq51529210** [golang/vscode-go#2139] opened 2022-03-27 15:42 UTC
gopls version: v0.8.1 (go1.18)
gopls flags: 
update flags: proxy
extension version: 0.32.0
go version: 1.17.8
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Sun, 27 Mar 2022 15:42:14 GMT
restart history:
Sun, 27 Mar 2022 15:01:18 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1775772]

goroutine 59 [running]:
golang.org/x/tools/internal/lsp/cache.parseGoWork({0x1c01c18, 0xc000276180}, {0xc0004a9680, 0x33}, {0xc0004a9500%3F, 0xc0000ceec0%3F}, {0xc0003c8000, 0x0, 0x200}, {0x1bfb340, ...})
	  workspace.go:508  0x232
golang.org/x/tools/internal/lsp/cache.loadExplicitWorkspaceFile({0x1c01c18, 0xc000276180}, 0xc0005fed80, {0x1bfb340%3F, 0xc00011c080%3F})
	  workspace.go:152  0x1e6
golang.org/x/tools/internal/lsp/cache.newWorkspace({0x1c01c18, 0xc000276180}, {0xc0004a9680, 0x33}, {0x1bfb340, 0xc00011c080}, 0xc00009f890, 0x0, 0x0)
	  workspace.go:106  0xbb
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0xc00011c080, {0x1c01c18, 0xc000276180}, {0xc00042c7d0, 0x4}, {0xc0004a8580, 0x33}, 0xc0000d66c0, 0x0)
	  session.go:197  0x25d
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0xc00011c080, {0x1c01c18, 0xc000276180}, {0xc00042c7d0, 0x4}, {0xc0004a8580, 0x33}, 0xc00041e070%3F)
	  session.go:166  0x287
golang.org/x/tools/internal/lsp.(*Server).addView(0xc0000b8480, {0x1c01c18, 0xc000276180}, {0xc00042c7d0, 0x4}, {0xc0004a8580, 0x33})
	  workspace.go:42  0x1c7
golang.org/x/tools/internal/lsp.(*Server).addFolders(0xc0000b8480, {0x1c01c18%3F, 0xc000276180}, {0xc0000a2a40, 0x1, 0x1%3F})
	  general.go:234  0x6f5
golang.org/x/tools/internal/lsp.(*Server).initialized(0xc0000b8480, {0x1c01c18, 0xc000276180}, 0xc0005fe000%3F)
	  general.go:186  0x2fa
golang.org/x/tools/internal/lsp.(*Server).Initialized(0xc000521530%3F, {0x1c01c18%3F, 0xc000276180%3F}, 0x1859dc0%3F)
	  server_gen.go:156  0x25
golang.org/x/tools/internal/lsp/protocol.serverDispatch({0x1c01c18, 0xc000276180}, {0x1c0cd80, 0xc0000b8480}, 0xc0003ba000, {0x1c01e10, 0xc0002760c0})
	  tsserver.go:140  0x6d3
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1({0x1c01c18, 0xc000276180}, 0xc0003ba000, {0x1c01e10, 0xc0002760c0})
	  protocol.go:154  0x90
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1({0x1c01c18, 0xc000276180}, 0xc0003ba000, {0x1c01e10%3F, 0xc0002760c0%3F})
	  lsprpc.go:506  0xa43
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x1c01c18, 0xc000276180}, 0xc00000fad0, {0x1c01e10%3F, 0xc0002760c0%3F})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20a
[Error - 11:42:05 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2022-03-28 18:06
Thanks for the report - Duplicate of https://github.com/golang/go/issues/51844
The fix will be released soon (gopls v0.8.2)

Leaving this open until gopls/v0.8.2 is released.

**Comment by hyangah** [comment] 2022-03-31 23:14
[gopls/v0.8.2](https://github.com/golang/tools/releases/tag/gopls%2Fv0.8.2) is available now.

**Closed by hyangah** 2022-03-31 23:14 UTC
Labels: gopls
