### ISSUE TITLE
Intellisense doesn't work properly on vendor packages

### ISSUE THREAD

**Issue by dzpt** [golang/vscode-go#1075] opened 2021-01-01 13:03 UTC
- Run `go version` to get version of Go
`go version go1.15.5 darwin/amd64`

- Run `gopls -v version` to get version of Gopls if you are using [the language server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).
```
Build info
----------
golang.org/x/tools/gopls v0.5.4
    golang.org/x/tools/gopls@v0.5.4 h1:PkQWDfzw8CxoseHDQniF2GhzmndN8KnQL6gcG2gnF3Y=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.1 h1:JFrFEBb2xKufg6XkJsJr+WbKb4FQlURi5RUcBveYu9k=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
    golang.org/x/tools@v0.0.0-20201123203206-735e963e909b h1:U8XGResmZKfdo8rCjWPsuiB4cu7N0PJSpQwc9lZr9Rg=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.0.1-2020.1.6 h1:W18jzjh8mfPez+AwGLxmOImucz/IFjpNlrKVnaj2YVc=
    mvdan.cc/gofumpt@v0.0.0-20200927160801-5bfeb2e70dd6 h1:z+/YqapuV7VZPvBb3GYmuEJbA88M3PFUxaHilHYVCpQ=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
```
1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64
```

- Run `go env` to get the go development environment details
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/*/Library/Caches/go-build"
GOENV="/Users/*/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Volumes/*/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Volumes/*/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ks/6cl6kxl56tsbfbgg5gvmfmr40000gn/T/go-build091446728=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

It happens on vscode go 0.20.1:
Language Server = False:
Intellisense doesn't work on vendor packages in main.go file.
but it works on vendor packages files.

Language Server = True:
Intellisense doesn't work on vendor packages in package file.
but it works on the main file.

vscode go 0.19 extension doesn't have this issue

**Comment by hyangah** [comment] 2021-01-04 18:10
@dzpt Thanks for the report. Do you have a repro case to share?

**Comment by dzpt** [comment] 2021-01-05 03:14
@hyangah it won't work on any go code. not only with any specific repo.

**Comment by dzpt** [comment] 2021-01-05 22:14
@stamblerre It doesn't work.

**Comment by stamblerre** [comment] 2021-01-06 01:36
Ok, thanks for confirming. This sounds like golang/go#42527, so I think this can be closed in favor of that issue.
The language server will be on by default soon, so we will prioritize a fix with it enabled.

**Comment by stamblerre** [comment] 2021-01-06 01:36
Duplicate of golang/go#42527

**Closed by stamblerre** 2021-01-06 01:36 UTC
Labels: WaitingForInfo

**Comment by dzpt** [comment] 2021-05-25 19:30
@stamblerre It's May and it seems the issue still persists with latest gopls :(
