### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by VitorBaldacin** [golang/vscode-go#2826] opened 2023-06-20 12:28 UTC
gopls version: v0.12.2 (go1.20)
gopls flags: 
update flags: proxy
extension version: 0.39.0
go version: 1.20
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Tue, 20 Jun 2023 12:28:31 GMT
restart history:
Tue, 20 Jun 2023 12:28:14 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x729994]

goroutine 9500 [running]:
golang.org/x/tools/internal/gcimporter.iexportCommon.func1()
	  iexport.go:93  0x8a
panic({0xdc2b00, 0x16b8180})
	  panic.go:884  0x213
go/types.(*Package).Path(...)
	  package.go:31
golang.org/x/tools/internal/gcimporter.(*exportWriter).exportPath(...)
	  iexport.go:426
golang.org/x/tools/internal/gcimporter.(*exportWriter).pkg(0xc0051b7140, 0x0)
	  iexport.go:664  0x54
golang.org/x/tools/internal/gcimporter.(*exportWriter).setPkg(...)
	  iexport.go:832
golang.org/x/tools/internal/gcimporter.(*exportWriter).doTyp(0xc0051b7140, {0x1149df8%3F, 0xc008921380%3F}, 0x0)
	  iexport.go:776  0x514
golang.org/x/tools/internal/gcimporter.(*iexporter).typOff(0xc0001f0a50, {0x1149df8, 0xc008921380}, 0x0%3F)
	  iexport.go:694  0x92
golang.org/x/tools/internal/gcimporter.(*exportWriter).typ(0xc0051b7080, {0x1149df8%3F, 0xc008921380%3F}, 0x7293f7%3F)
	  iexport.go:677  0x2e
golang.org/x/tools/internal/gcimporter.(*exportWriter).typeList(0xc0051b7080, 0xc008747ba8, 0x0%3F)
	  iexport.go:849  0x7b
golang.org/x/tools/internal/gcimporter.(*exportWriter).doTyp(0xc0051b7080, {0x1149d58%3F, 0xc008745260%3F}, 0x0)
	  iexport.go:721  0xf3
golang.org/x/tools/internal/gcimporter.(*iexporter).typOff(0xc0001f0a50, {0x1149d58, 0xc008745260}, 0x4a8f0%3F)
	  iexport.go:694  0x92
golang.org/x/tools/internal/gcimporter.(*exportWriter).typ(0xc0051b6fc0, {0x1149d58%3F, 0xc008745260%3F}, 0xc005c33080%3F)
	  iexport.go:677  0x2e
golang.org/x/tools/internal/gcimporter.(*exportWriter).value(0xc0051b6fc0, {0x1149d58%3F, 0xc008745260}, {0x114d9f0, 0xc008921590})
	  iexport.go:911  0x45
golang.org/x/tools/internal/gcimporter.(*iexporter).doDecl(0xc0001f0a50, {0x1156518, 0xc004f8cfc0})
	  iexport.go:481  0x2ed
golang.org/x/tools/internal/gcimporter.iexportCommon({0x1145de0, 0xc00725d170}, 0xc004226a00, 0x0, 0x1, 0x2, {0xc000f57ca8, 0x1, 0xc00725d0e0%3F})
	  iexport.go:139  0x3a5
golang.org/x/tools/internal/gcimporter.IExportShallow(0xdbcfe0%3F, 0xc002c5fa90)
	  iexport.go:43  0x75
golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).checkPackage.func1()
	  check.go:646  0x2b1
created by golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).checkPackage
	  check.go:638  0x305
[Error - 09:28:27] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2023-06-20 15:16
Thank you for the report. Closing as a dupe of your other report, #2825.

**Closed by findleyr** 2023-06-20 15:16 UTC
