### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by JalalDA** [golang/vscode-go#3064] opened 2023-11-25 14:03 UTC
gopls version: v0.14.2 (go1.21.1)
gopls flags: true
update flags: proxy
extension version: 0.40.0
go version: 1.21.1
environment: Visual Studio Code darwin
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Sat, 25 Nov 2023 14:03:17 GMT
restart history:
Sat, 25 Nov 2023 14:01:08 GMT: activation (enabled: false)
Sat, 25 Nov 2023 14:03:09 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2023-11-27 14:45
Closing as dupe of #3064.

**Closed by findleyr** 2023-11-27 14:45 UTC

**Comment by JalalDA** [comment] 2023-11-28 01:48
kocak
