### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by unk1ndled** [golang/vscode-go#3416] opened 2024-05-31 00:44 UTC
gopls version: v0.15.3/go1.21.4
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Fri, 31 May 2024 00:43:46 GMT
restart history:
Thu, 30 May 2024 23:39:26 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: instantiated ident not found

goroutine 1753 [running]:
go/types.(*Checker).handleBailout(0xc002a583c0, 0xc0010b9860)
	C:/Program   check.go:336  0x88
panic({0x1035e20%3F, 0x1466310%3F})
	C:/Program   panic.go:914  0x21f
go/types.instantiatedIdent(...)
	C:/Program   check.go:594
go/types.(*Checker).recordInstance(0x1%3F, {0x146ebb0%3F, 0xc000674540%3F}, {0xc0001b8dd0%3F, 0xc0001b8dd0%3F, 0x1%3F}, {0x146ba88%3F, 0xc0007785c0%3F})
	C:/Program   check.go:570  0x1de
go/types.(*Checker).instantiateSignature(0xc002a583c0, 0x66a, {0x146ebb0, 0xc000674540}, 0xc000778540, {0xc0001b8dd0, 0x1, 0x1}, {0x0, 0x0, ...})
	C:/Program   call.go:153  0x2f9
go/types.(*Checker).arguments(0xc002a583c0, 0xc000674580, 0xc001683a40, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc0003913d8, ...}, ...)
	C:/Program   call.go:643  0x164a
go/types.(*Checker).callExpr(0xc002a583c0, 0xc000778200, 0xc000674580)
	C:/Program   call.go:302  0x86d
go/types.(*Checker).exprInternal(0xc002a583c0, {0x0, 0x0}, 0xc000778200, {0x146ebb0, 0xc000674580%3F}, {0x0%3F, 0x0%3F})
	C:/Program   expr.go:1359  0x1809
go/types.(*Checker).rawExpr(0xc002a583c0, {0x0, 0x0}, 0xc000778200, {0x146ebb0%3F, 0xc000674580%3F}, {0x0%3F, 0x0%3F}, 0x0)
	C:/Program   expr.go:965  0x1a5
go/types.(*Checker).stmt(0xc002a583c0, 0x0, {0x146ef70%3F, 0xc000204420%3F})
	C:/Program   stmt.go:397  0x19a
go/types.(*Checker).stmtList(0xc000608000%3F, 0x0, {0xc000d05040%3F, 0x1a785e0%3F, 0x1a785e0%3F})
	C:/Program   stmt.go:124  0x85
go/types.(*Checker).funcBody(0xc002a583c0, 0xc002e76b40, {0xc00088e5f8%3F, 0xc002b4d788%3F}, 0xc0006f1ec0, 0xc00180a4e0, {0x0, 0x0})
	C:/Program   stmt.go:44  0x345
go/types.(*Checker).funcDecl.func1()
	C:/Program   decl.go:826  0x39
go/types.(*Checker).processDelayed(0xc002a583c0, 0x0)
	C:/Program   check.go:439  0x15c
go/types.(*Checker).checkFiles(0xc002a583c0, {0xc000391320, 0x1, 0x1})
	C:/Program   check.go:383  0x245
go/types.(*Checker).Files(...)
	C:/Program   check.go:341
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).checkPackage(0xc002e76780, {0x1470588, 0xc00180b8f0}, 0xc0020730e0)
	  check.go:1532  0xb0e
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).handleSyntaxPackage(0xc002e76780, {0x1470588%3F, 0xc00180b8f0}, 0xc0029945a0%3F, {0xc0001f1f80, 0x3d})
	  check.go:563  0x609
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackageInternal.func2()
	  check.go:414  0x2b
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 150
	  errgroup.go:75  0x96
</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 1326 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2024-06-04 14:41
Thanks @unk1ndled 
Please see https://github.com/golang/vscode-go/issues/3417#issuecomment-2147708918 

Duplicate of golang/go#63933

**Closed by hyangah** 2024-06-04 14:41 UTC
