### ISSUE TITLE
gopls: null pointer panic

### ISSUE THREAD

**Issue by WinnieeBear** [golang/vscode-go#3364] opened 2024-04-25 03:10 UTC
gopls version: v0.15.3/go1.22.0
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Thu, 25 Apr 2024 03:09:39 GMT
restart history:
Thu, 25 Apr 2024 03:07:59 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 187,
    "TestdataFiles": 8,
    "GoFiles": 64,
    "ModFiles": 1,
    "Dirs": 100
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.0",
  "GoplsVersion": "v0.15.3",
  "InitialWorkspaceLoadDuration": "432.017698ms",
  "MemStats": {
    "HeapAlloc": 22192736,
    "HeapInUse": 39763968,
    "TotalAlloc": 296520640
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 1262,
      "Largest": 395026,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.0",
        "AllPackages": {
          "Packages": 202,
          "LargestPackage": 161,
          "CompiledGoFiles": 1292,
          "Modules": 6
        },
        "WorkspacePackages": {
          "Packages": 23,
          "LargestPackage": 38,
          "CompiledGoFiles": 98,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-04-25 14:58
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by findleyr** [comment] 2024-04-29 10:44
Thank you. This is a dupe of https://go.dev/issue/66923.

**Closed by findleyr** 2024-04-29 10:44 UTC
Labels: WaitingForInfo
