### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by softstone1** [golang/vscode-go#2158] opened 2022-04-03 14:37 UTC
gopls version: v0.8.2 (go1.18)
gopls flags: 
update flags: proxy
extension version: 0.32.0
go version: 1.18
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Sun, 03 Apr 2022 14:37:37 GMT
restart history:
Sun, 03 Apr 2022 14:37:20 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment] 2022-04-04 17:33
Closing as a duplicate of #2159

**Closed by suzmue** 2022-04-04 17:33 UTC
