### ISSUE TITLE
Inlay Hints

### ISSUE THREAD

**Issue by vidhanio** [golang/vscode-go#1992] opened 2022-01-04 23:48 UTC
**Describe the solution you'd like**
From the [Visual Studio Code docs](https://code.visualstudio.com/docs/languages/typescript#_inlay-hints), "Inlay hints add additional inline information to source code to help you understand what the code does." These would be useful for Go, and have been done in TypeScript and Rust for VS Code before. [Goland also already has these](https://www.jetbrains.com/help/go/inlay-hints.html), so their format might be helpful.

**Additional context**
Example in Goland with Go:
![Example in Goland](https://user-images.githubusercontent.com/41439633/148139184-57dfc6c6-0aa5-45ae-b556-30faf8da75eb.png)

Example in VS Code with Typescript:
![image](https://user-images.githubusercontent.com/41439633/148139207-f8921498-65d6-46a9-8523-f32b437e8bd3.png)

**Comment by hyangah** [comment] 2022-01-05 00:25
Duplicate of https://github.com/golang/vscode-go/issues/1631

It seems that [the upstream issue (LSP support)](https://github.com/microsoft/language-server-protocol/issues/956) is waiting for VS Code API for the inlayHints to be finalized (https://github.com/microsoft/vscode/issues/16221).

**Closed by hyangah** 2022-01-05 00:25 UTC

**Comment by vidhanio** [comment] 2022-01-05 00:28
Ah, I searched for "inlay hints" to see if any issues had been made, sorry!

**Comment by hyangah** [comment] 2022-01-05 01:31
Good point. Updated the issue title. :-)
