### ISSUE TITLE
 __debug_bin process can't exit   

### ISSUE THREAD

**Issue by zs2619** [golang/vscode-go#1606] opened 2021-07-05 03:59 UTC
docker image :golang:1.14-stretch
vscode version :1.57.1
vscode-go :v0.26.0
dlv version:
Delve Debugger
Version: 1.6.1
Build: $Id: 114218c22f3791287c4bc2f4ff35a846a1416ee9 $

I use Remote - Container extension  to  develop in container. 
When Stop debug , __debug_bin progress can't exit .
'ps -ef' still show __debug_bin 

output:
2021-07-05T03:52:17Z debug layer=debugger halting
2021-07-05T03:52:17Z warning layer=debugger reading debug_info: concrete subprogram without address range at 0x4f00

**Comment by hyangah** [comment] 2021-07-09 21:07
Thanks for the report @zs2619 
We need more information to triage the issue.

Do you mind sharing your launch configuration and share verbose logs around the debug session termination ?
To capture verbose logs, use these attributes in your launch.json setting (https://github.com/golang/vscode-go/blob/master/docs/debugging.md#enable-logging)

```
...
  "showLog": true,
  "trace": "verbose",
  "logOutput": "rpc,debugger"
```

**Comment by zs2619** [comment] 2021-07-13 06:46
> Thanks for the report @zs2619
> We need more information to triage the issue.
> 
> Do you mind sharing your launch configuration and share verbose logs around the debug session termination ?
> To capture verbose logs, use these attributes in your launch.json setting (https://github.com/golang/vscode-go/blob/master/docs/debugging.md#enable-logging)
> 
> ```
> ...
>   "showLog": true,
>   "trace": "verbose",
>   "logOutput": "rpc,debugger"
> ```

[d1.log](https://github.com/golang/vscode-go/files/6806482/d1.log)
Thanks @hyangah

**Comment by hyangah** [comment] 2021-07-13 16:34
Thanks @zs2619 for sharing the trace.
It looks like Delve is stuck and doesn't respond to the halt request (no `rpc2.CommandOut` in the trace).

```
2021-07-13T06:32:33Z debug layer=rpc (async 2) -> rpc2.StateOut{"State":{"Running":false,"Recording":false,"CoreDumping":false,"currentThread":{"id":21869,"pc":139990462184480,"file":"","line":0,"goroutineID":0,"ReturnValues":null,"CallReturn":false},"Threads":[{"id":21869,"pc":139990462184480,"file":"","line":0,"goroutineID":0,"ReturnValues":null,"CallReturn":false}],"NextInProgress":false,"exited":false,"exitStatus":0,"When":""}} error: ""
2021-07-13T06:32:33Z debug layer=rpc (async 3) <- RPCServer.Command(api.DebuggerCommand{"name":"continue","ReturnInfoLoadConfig":null})
2021-07-13T06:32:33Z debug layer=debugger continuing
2021-07-13T06:32:34Z debug layer=rpc (async 4) <- RPCServer.State(rpc2.StateIn{"NonBlocking":true})
2021-07-13T06:32:34Z debug layer=rpc (async 4) -> rpc2.StateOut{"State":{"Running":true,"Recording":false,"CoreDumping":false,"Threads":null,"NextInProgress":false,"exited":false,"exitStatus":0,"When":""}} error: ""
2021-07-13T06:32:53Z debug layer=rpc (async 5) <- RPCServer.Command(api.DebuggerCommand{"name":"halt","ReturnInfoLoadConfig":null})
2021-07-13T06:32:53Z debug layer=debugger halting
2021-07-13T06:32:53Z warning layer=debugger reading debug_info: concrete subprogram without address range at 0x4f00
2021-07-13T06:32:53Z warning layer=debugger reading debug_info: concrete subprogram without address range at 0x4f3a
2021-07-13T06:32:53Z warning layer=debugger reading debug_info: concrete subprogram without address range at 0x4fe5
....
```
 
 I don't know why this happens, and need delve experts' help to inspect further.  (cc @polinasok @suzmue)
 
 A good news is that it seems your launch configuration is one of the kinds the [new dlv-dap adapter](https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md) can support and IMO dlv-dap , so @zs2619 do you mind giving it a try? 
 
 Getting started: https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md#getting-started
 * It needs `dlv-dap` installed in the dev container.
 * I am not sure `"cwd": ".."` is going to work with dlv-dap currently. Try to pass the absolute directory path (you can use https://code.visualstudio.com/docs/editor/variables-reference e.g. `${workspaceFolder}/maxbet_slot_backend`)

**Comment by polinasok** [comment] 2021-07-13 17:55
+1 to trying with dlv-dap

Additional thoughts. Delve might not be stuck, but taking too long to halt, so the disconnect command times out and the session is forcefully closed, so no additional logging from the delve ever makes it to the Debug Console. You can try to launch delve manually from the command-line and connect to it from vscode. This way when vscode disconnect times out, dlv's log will continue showing up in the terminal window.

With the current set up, you will need to use:
```
$ dlv debug <program> <other flags> --headless --listen=:12345 --log-output=rpc,debugger
```
Change launch.json to this:
```
            "name": "Connect to server",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "port": 12345, // localhost implied
```

With dlv-dap, the switch (once you get it set up and get dlv-dap path from Go: Install/Update Tools) will be even easier:
```
$ dlv-dap dap --listen=:12345 --log --log-output=dap,debugger```
```
Change launch.json to this:
```
            ... existing configuration ...
            "port": 12345, // localhost implied
            "debugAdapter": "dlv-dap"
```

**Comment by polinasok** [comment] 2021-07-13 18:50
> I am not sure "cwd": ".." is going to work with dlv-dap currently. Try to pass the absolute directory path (you can use https://code.visualstudio.com/docs/editor/variables-reference e.g. ${workspaceFolder}/maxbet_slot_backend)

".." is a valid value that will be resolved by the extension into an absolute path before being sent to delve.

**Comment by hyangah** [comment] 2021-07-13 18:54
The problem is in the legacy adapter ".." was passed directly as "--wd". So, in this specific case, that's treated as the parent directory of the package directory. In the new debug adapter, it will be resolved as a relative to the workspace root - so there can be difference behavior-wise.

**Comment by polinasok** [comment] 2021-07-13 18:59
> The problem is in the legacy adapter ".." was passed directly as "--wd". So, in this specific case, that's treated as the parent directory of the package directory. In the new debug adapter, it will be resolved as a relative to the workspace root - so there can be difference behavior-wise.

That's true.

**Comment by zs2619** [comment] 2021-07-14 02:39
dlv-dap can resolves this issue

**Closed** 2021-07-14 15:07 UTC
Labels: Debug, WaitingForInfo
