### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by jayconrod** [golang/vscode-go#1732] opened 2021-08-30 17:29 UTC
gopls version: v0.7.1
gopls flags: 
update flags: proxy
extension version: 2021.8.3014
go version: devel go1.18-7b38dd8e25
environment: Visual Studio Code linux
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Crashed while editing code with generics in GOROOT at commit based on 7b38dd8e25.

I had just changed the type of a global variable:

```
// before
var downloadZipCache par.Cache

// after
var downloadZipCache par.Cache[module.Version, string]
```

When the crash happened, I was in the middle of changing this line:

```
// before
	type cached struct {
		zipfile string
		err     error
	}
	c := downloadZipCache.Do(mod, func() interface{} {

// after 
	return downloadZipCache.Do(mod, func() (string, er) {
```

<pre>panic: assertion failed

goroutine 6755 [running]:
go/types.(*Checker).handleBailout(0xc0002f8640, 0xc007391690)
	  check.go:244  0x8b
panic({0xc0cca0, 0xe6da40})
	  panic.go:814  0x214
go/types.assert(...)
	  errors.go:20
go/types.instantiatedHash(0x7f4cf419a368, {0xc007617700, 0x7f4d1e4e5e58, 0x30})
	  subst.go:262  0x165
go/types.(*Checker).instance(0xc0002f8640, 0xca3c10, {0xe841d8, 0xc00e3bc090}, {0xc007617700, 0xc01c370000, 0xc00730bca0})
	  instantiate.go:123  0x29a
go/types.(*Checker).instantiate(0xc0002f8640, 0xca3c10, {0xe841d8, 0xc00e3bc090}, {0xc007617700, 0xc0073910b8, 0xeabb38}, {0xc00730bca0, 0x2, 0x2})
	  instantiate.go:87  0x6d
go/types.(*Checker).instantiatedType(0xc0002f8640, {0xe867a0, 0xc01034aab0}, {0xc006eba160, 0x688e86, 0x2}, 0x0)
	  typexpr.go:436  0x229
go/types.(*Checker).typInternal(0xc0002f8640, {0xe866b0, 0xc00ebfa000}, 0x0)
	  typexpr.go:277  0x82c
go/types.(*Checker).definedType(0xc01c370000, {0xe866b0, 0xc00ebfa000}, 0xc0002f8640)
	  typexpr.go:180  0x45
go/types.(*Checker).varType(0xc007391368, {0xe866b0, 0xc00ebfa000})
	  typexpr.go:140  0x2f
go/types.(*Checker).varDecl(0xc3ebc0, 0xc012337630, {0x0, 0x0, 0x0}, {0xe866b0, 0xc00ebfa000}, {0x0, 0x0})
	  decl.go:515  0x99
go/types.(*Checker).objDecl(0xc0002f8640, {0xeabb38, 0xc012337630}, 0x682400)
	  decl.go:194  0x665
go/types.(*Checker).packageObjects(0xc0002f8640)
	  resolver.go:639  0x385
go/types.(*Checker).checkFiles(0xc0002f8640, {0xc005c7bd00, 0xc0028bc2d0, 0x2})
	  check.go:264  0xbf
go/types.(*Checker).Files(...)
	  check.go:249
golang.org/x/tools/internal/lsp/cache.doTypeCheck({0xe890d8, 0xc00eb0de40}, 0xc002131800, 0xc0016b05a0, 0x2, 0xc006102150, 0xc0000320c0)
	  check.go:544  0x893
golang.org/x/tools/internal/lsp/cache.typeCheck({0xe890d8, 0xc00eb0de40}, 0xc002131800, 0xc0016b05a0, 0x2, 0xc006102150)
	  check.go:321  0xe5
golang.org/x/tools/internal/lsp/cache.(*snapshot).buildPackageHandle.func1({0xe890d8, 0xc00eb0de40}, {0xe72060, 0xc002131800})
	  check.go:124  0x23e
golang.org/x/tools/internal/memoize.(*Handle).run.func1()
	  memoize.go:322  0xa9
created by golang.org/x/tools/internal/memoize.(*Handle).run
	  memoize.go:315  0x1c5
[Error - 10:22:12 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

Attached [gopls.log](https://github.com/golang/vscode-go/files/7078380/gopls.log)

**Comment by findleyr** [comment] 2021-08-30 19:03
I believe this is a dupe of https://golang.org/issue/47910, which should be fixed soon.

**Comment by findleyr** [comment] 2021-08-30 19:03
Thanks for the report. Moving this into 'on deck' status too see if it is reproducible once the go/types issue is fixed at tip.

**Closed** 2022-10-04 19:07 UTC
