### ISSUE TITLE
Support for Go text/html templates. 

### ISSUE THREAD

**Issue by oSethoum** [golang/vscode-go#2163] opened 2022-04-04 22:03 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
like Goland has support for go templates, and autocompletion for structs inside templates.

**Describe alternatives you've considered**
I considered using goland but it's full IDE huge and not free.

**Additional context**
From Goland.
[Add any other context or screenshots about the feature request here.](https://entgo.io/images/assets/template-autocomplete.gif)

**Comment by suzmue** [comment] 2022-04-05 13:19
The extension has some support for go templates already. Instructions for setting the language of your template files so that you get these features is available [here](https://github.com/golang/vscode-go/blob/master/docs/features.md#go-template-syntax-highlighting) and progress of the features can be tracked through issue #609.

Closing as a duplicate of #609

**Closed by suzmue** 2022-04-05 13:19 UTC
