### ISSUE TITLE
run test pass ldflags not work with --ldflags -r=/home/xxxx/go/src/program/clib

### ISSUE THREAD

**Issue by yiGmMk** [golang/vscode-go#3025] opened 2023-10-27 02:06 UTC
### What version of Go, VS Code & VS Code Go extension are you using?

go version go1.21.3 linux/amd64
golang.org/x/tools/gopls v0.13.2
    golang.org/x/tools/gopls@v0.13.2 h1:Pyvx6MKvatbX3zzZmdGiFRfQZl0ohPlt2sFxO/5j6Ro=

vscode 
```text
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
my project  needs a .so to work,it works with cmd like this in bash shell,however with button 'run test' above tests it doesn't 

```shell
go test -timeout 30s -tags linux -run ^TestGenCode$ program --ldflags -r=/home/xxxx/go/src/program/clib
```

err:

```shell
go test -timeout 30s -tags linux -run ^TestGenCode$ program --ldflags -r=/home/xxxx/go/src/program/clib

/tmp/go-build3735271922/b001/program.test: error while loading shared libraries: xxxxxx.so: cannot open shared object file: No such file or directory
FAIL	program   0.001s
FAIL
```

### Steps to reproduce the behavior:
1. click ''run test'

### Screenshots or recordings
![image](https://github.com/golang/vscode-go/assets/39377339/e001c08c-5a92-4816-8f32-aeafb54e049a)

**Comment by yiGmMk** [comment] 2023-10-27 02:09
run test doesn't work,however 'debug test' works also the same cmd works in bash shell,so i think it may a bug

**Comment by yiGmMk** [comment] 2023-10-27 02:29
may be caused by different param handle of  'debug test'  and 'run test'
  "go.buildFlags": [
        "--ldflags -r=${workspaceRoot}/clib"    // works for debug test but not run test
        // "-ldflags=-r ${workspaceRoot}/clib"  // works for run test but not debug test
    ],

**Comment by findleyr** [comment] 2023-11-02 18:03
Related: #1831.

@hyangah will know better, but I think we may soon be able to use "-ldflags=-r ${workspaceRoot}/clib" for both run test and debug test?

**Comment by findleyr** [comment] 2023-11-02 19:51
Can you also try `"--ldflags=-r=${workspaceRoot}/clib"`? Does that work for both?

**Comment by yiGmMk** [comment] 2023-11-03 13:52
> Can you also try `"--ldflags=-r=${workspaceRoot}/clib"`? Does that work for both?

works for both 'debug test' and 'run test'

**Comment by findleyr** [comment] 2023-11-03 13:56
Thanks. Then let's close this as a dupe of #1831

**Closed by findleyr** 2023-11-03 13:56 UTC

**Comment by Luranss** [comment] 2023-11-04 15:33
👍👍
