### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by cyy53589** [golang/vscode-go#3202] opened 2024-02-28 12:10 UTC
gopls version: v0.15.0/go1.20.4
gopls flags: 
update flags: proxy
extension version: 0.41.1
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Wed, 28 Feb 2024 12:08:17 GMT
restart history:
Wed, 28 Feb 2024 12:06:44 GMT: activation (enabled: true)
Wed, 28 Feb 2024 12:07:55 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

**It seems happening very time.**

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

```
[Info  - 8:08:15 PM] 2024/02/28 20:08:15 go/packages.Load #2: updating metadata for 395 packages

[Error - 8:08:16 PM] Request textDocument/semanticTokens/full failed.
  Message: semantictokens are disabled
  Code: 0 
[Error - 8:08:16 PM] Request textDocument/semanticTokens/full failed.
  Message: semantictokens are disabled
  Code: 0 
[Error - 8:08:17 PM] Request textDocument/semanticTokens/full failed.
  Message: semantictokens are disabled
  Code: 0 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb84830]

goroutine 7746 [running]:
golang.org/x/tools/gopls/internal/golang.highlightFuncControlFlow({0xc000778d00, 0x7, 0x9?}, 0xc00384a3f0)
	/root/go/pkg/mod/golang.org/x/tools/gopls@v0.15.0/internal/golang/highlight.go:241 +0x3f0
golang.org/x/tools/gopls/internal/golang.highlightPath({0xc000778d00, 0x7, 0x8}, 0xc001cc21e0?, 0xc0031107d0)
	/root/go/pkg/mod/golang.org/x/tools/gopls@v0.15.0/internal/golang/highlight.go:102 +0x2aa
golang.org/x/tools/gopls/internal/golang.Highlight({0x124e078?, 0xc002c7cd80?}, 0xc002f3fb60?, {0x124f1e0, 0xc002f3fb60}, {0x3cfb170?, 0xc0?})
	/root/go/pkg/mod/golang.org/x/tools/gopls@v0.15.0/internal/golang/highlight.go:53 +0x2e7
golang.org/x/tools/gopls/internal/server.(*server).DocumentHighlight(0xc003cfb170?, {0x124dfd0, 0xc0024639a0}, 0xc002c7cc90)
	/root/go/pkg/mod/golang.org/x/tools/gopls@v0.15.0/internal/server/highlight.go:32 +0x245
golang.org/x/tools/gopls/internal/protocol.serverDispatch({0x124dfd0, 0xc0024639a0}, {0x12608a0, 0xc00089c000}, 0xc002c7cc60, {0x124e2e0, 0xc000bd3b00})
	/root/go/pkg/mod/golang.org/x/tools/gopls@v0.15.0/internal/protocol/tsserver.go:376 +0x6a62
golang.org/x/tools/gopls/internal/protocol.ServerHandler.func1({0x124dfd0, 0xc0024639a0}, 0xc002c7cc60, {0x124e2e0, 0xc000bd3b00})
	/root/go/pkg/mod/golang.org/x/tools/gopls@v0.15.0/internal/protocol/protocol.go:160 +0x9a
golang.org/x/tools/gopls/internal/lsprpc.handshaker.func1({0x124dfd0, 0xc0024639a0}, 0xc002c7cc60, {0x124e2e0?, 0xc000bd3b00?})
	/root/go/pkg/mod/golang.org/x/tools/gopls@v0.15.0/internal/lsprpc/lsprpc.go:509 +0x9f9
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x124dfd0, 0xc0024639a0}, 0xc003b31c80, {0x124e2e0?, 0xc000bd3b00?})
	/root/go/pkg/mod/golang.org/x/tools@v0.18.1-0.20240221145400-a220b3b5ba60/internal/jsonrpc2/handler.go:35 +0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	/root/go/pkg/mod/golang.org/x/tools@v0.18.1-0.20240221145400-a220b3b5ba60/internal/jsonrpc2/handler.go:103 +0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/root/go/pkg/mod/golang.org/x/tools@v0.18.1-0.20240221145400-a220b3b5ba60/internal/jsonrpc2/handler.go:100 +0x20a
[Error - 8:08:17 PM] 
```

Failed to auto-collect gopls trace: incomplete panic trace.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 8479,
    "TestdataFiles": 0,
    "GoFiles": 0,
    "ModFiles": 0,
    "Dirs": 670
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.20.4",
  "GoplsVersion": "v0.15.0",
  "InitialWorkspaceLoadDuration": "45.516608ms",
  "MemStats": {
    "HeapAlloc": 3283944,
    "HeapInUse": 5758976,
    "TotalAlloc": 19641880
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 0,
      "Largest": 0,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.20.4",
        "AllPackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "WorkspacePackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-02-28 14:06
Thanks for the report. This is a duplicate of #3194, which will be fixed in a v0.15.1 release shortly.

**Closed by findleyr** 2024-02-28 14:06 UTC
