### ISSUE TITLE
增加依赖库显示

### ISSUE THREAD

**Issue by yupor5** [golang/vscode-go#2590] opened 2022-12-29 02:53 UTC
Type: <b>Feature Request</b>

增加依赖库显示

Extension version: 0.37.0
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: Yes

**Comment by suzmue** [comment] 2022-12-29 15:13
Closing as a duplicate of #2591

**Closed by suzmue** 2022-12-29 15:13 UTC
