### ISSUE TITLE
About quick run or debug a Go application like Dart???

### ISSUE THREAD

**Issue by billcoding** [golang/vscode-go#1704] opened 2021-08-19 03:21 UTC
![2021-08-19_111943](https://user-images.githubusercontent.com/21271780/130002431-d043d60b-fe01-4035-bf4b-b0b4c518bbc5.jpg)

**Comment by suzmue** [comment] 2021-08-19 22:47
Closing as a duplicate of golang/vscode-go#159

**Closed by suzmue** 2021-08-19 22:47 UTC
