### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by fabulias** [golang/vscode-go#1301] opened 2021-03-12 01:53 UTC
gopls version: v0.6.4
gopls flags: 
extension version: 0.23.1
environment: Visual Studio Code win32
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 0
total start count: 2

All plugins about Go are not working, I tried to update this plugin because visual studio alert me `Couldn't start gopls`

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

```[Error - 10:27:33 PM] Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 
gopls: failed reading header line: &{%!w(string=EOF)}
[Error - 10:38:40 PM] Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 
gopls: failed reading header line: &{%!w(string=EOF)}```

By policies company, I don't have access to work with PowerShell.

**Comment by hyangah** [comment] 2021-03-12 02:00
Thank you for the report, and sorry for the trouble. @fabulias 

This is a duplicate of https://github.com/golang/vscode-go/issues/1300
The latest gopls is v0.6.6. 

By the way, didn't the vscode pop up a notification to suggest updates before?
We need to find a better way to enforce updates. :-(

**Closed** 2021-03-12 02:35 UTC
Labels: WaitingForInfo
