### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by lastzidanemagaba** [golang/vscode-go#3461] opened 2024-07-19 10:25 UTC
gopls version: v0.16.1/go1.22.5
gopls flags: 
update flags: proxy
extension version: 0.42.0
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Fri, 19 Jul 2024 10:25:08 GMT
restart history:
Fri, 19 Jul 2024 08:17:00 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic:   stmt.go:932: assertion failed

goroutine 3378 [running]:
go/types.(*Checker).handleBailout(0xc004d28e00, 0xc004637898)
	  check.go:367  0x88
panic({0xe96ca0%3F, 0xc002a0dc50%3F})
	  panic.go:770  0x132
go/types.assert(0x0%3F)
	  errors.go:28  0x54
go/types.(*Checker).rangeStmt(0xc004d28e00, 0x3, 0xc00099ca20)
	  stmt.go:932  0xe70
go/types.(*Checker).stmt(0xc004d28e00, 0x0, {0x1313600, 0xc00099ca20})
	  stmt.go:827  0xab9
go/types.(*Checker).stmtList(0xc004d28e00, 0x0, {0xc0002d9400%3F, 0x0%3F, 0x4573be%3F})
	  stmt.go:121  0x85
go/types.(*Checker).funcBody(0xc004d28e00, 0x1310d08%3F, {0xc00278c5e0%3F, 0xc00014e380%3F}, 0xc0020fff00, 0xc0000ff860, {0x0%3F, 0x0%3F})
	  stmt.go:41  0x331
go/types.(*Checker).funcDecl.func1()
	  decl.go:852  0x3a
go/types.(*Checker).processDelayed(0xc004d28e00, 0x0)
	  check.go:467  0x162
go/types.(*Checker).checkFiles(0xc004d28e00, {0xc002c13d00, 0xa, 0x10})
	  check.go:411  0x1cc
go/types.(*Checker).Files(...)
	  check.go:372
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).checkPackage(0xc002d30840, {0x13149a8, 0xc000353f50}, 0xc002d479e0)
	  check.go:1543  0xa25
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).handleSyntaxPackage(0xc002d30840, {0x13149a8, 0xc000353f50}, 0x0, {0xc00085a2e0, 0x10})
	  check.go:568  0x5e5
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackageInternal.func2()
	  check.go:418  0x2b
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 186
	  errgroup.go:75  0x96
</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 707 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-07-27 17:16
Thanks for the report. Closing as a duplicate of golang/go#68334. This should be fixed by the 1.22.6 Go release.

**Closed by findleyr** 2024-07-27 17:16 UTC
