### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by llimao** [golang/vscode-go#2335] opened 2022-07-12 21:53 UTC
gopls version: v0.9.0 (go1.18)
gopls flags: 
update flags: proxy
extension version: 0.34.1
go version: 1.18
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Tue, 12 Jul 2022 21:53:34 GMT
restart history:
Tue, 12 Jul 2022 16:13:19 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x11f7773]

goroutine 80478 [running]:
golang.org/x/tools/internal/xcontext.detachedContext.Value(...)
	  xcontext.go:23
golang.org/x/tools/internal/lsp/debug.GetInstance({0x1c73510%3F, 0xc00b114020%3F})
	  serve.go:361  0x3e
golang.org/x/tools/internal/lsp/debug.makeGlobalExporter.func1({0x1c73510, 0xc00b114020}, {{0xc0ab993598465718, 0x33c17384dc9, 0x21907a0}, {{{0x1c72240, 0xc0000d60e0}, 0xa, {0x18c60c0, 0x19ff8fb}}, ...}, ...}, ...)
	  serve.go:571  0x7e
golang.org/x/tools/internal/event/core.deliver({0x1c73510, 0xc00b114020}, 0xc0000bd200, {{0xc0ab993598465718, 0x33c17384dc9, 0x21907a0}, {{{0x1c72240, 0xc0000d60e0}, 0xa, {0x18c60c0, ...}}, ...}, ...})
	  export.go:45  0xfd
golang.org/x/tools/internal/event/core.ExportPair({_, _}, {{0x0, 0x0, 0x0}, {{{0x1c72240, 0xc0000d60e0}, 0xa, {0x18c60c0, 0x19ff8fb}}, ...}, ...}, ...)
	  export.go:68  0x128
golang.org/x/tools/internal/event.Start({0x1c73510%3F, 0xc00b114020%3F}, {0x19ff8fb%3F, 0xc003c17900%3F}, {0xc00eb90050%3F, 0x0%3F, 0x0%3F})
	  event.go:91  0x358
golang.org/x/tools/internal/jsonrpc2.(*conn).Notify(0x0%3F, {0x1c73510, 0xc00b114020}, {0x19ff8fb, 0xa}, {0x18a88e0%3F, 0xc003c17900%3F})
	  conn.go:85  0x35b
golang.org/x/tools/internal/lsp/protocol.clientConn.Notify(...)
	  protocol.go:60
golang.org/x/tools/internal/lsp/protocol.(*clientDispatcher).Progress(0x198a480%3F, {0x1c73510%3F, 0xc00b114020%3F}, 0x23253c8%3F)
	  tsclient.go:168  0x42
golang.org/x/tools/internal/lsp/progress.(*WorkDone).Report(0xc00e85c050, {0x0%3F, 0x0%3F}, {0xc005176180, 0x5a}, 0x0)
	  progress.go:188  0x27e
golang.org/x/tools/internal/lsp/progress.(*WorkDoneWriter).Write(0xc00296e380%3F, {0xc00232a000%3F, 0x5a, 0x104d532%3F})
	  progress.go:268  0x5c
io.(*multiWriter).Write(0xc00d22e0e8%3F, {0xc00232a000, 0x5a, 0x8000})
	  multi.go:60  0x86
io.copyBuffer({0x1c6c8c0, 0xc0073e5170}, {0x1c6cd60, 0xc00d22e0e8}, {0x0, 0x0, 0x0})
	  io.go:428  0x204
io.Copy(...)
	  io.go:385
os/exec.(*Cmd).writerDescriptor.func1()
	  exec.go:311  0x3a
os/exec.(*Cmd).Start.func1(0xc000470fc0%3F)
	  exec.go:441  0x25
created by os/exec.(*Cmd).Start
	  exec.go:440  0x715
[Error - 6:53:26 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2022-07-12 22:02
Thank you for the report. This is a dupe of https://github.com/golang/go/issues/53781. Apologies for the breakage: we'll release gopls@v0.9.1 this week with a fix.

**Closed by findleyr** 2022-07-12 22:02 UTC
