### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by knekjitkax20** [golang/vscode-go#3357] opened 2024-04-23 06:57 UTC
gopls version: v0.15.3/go1.21.5
gopls flags: 
update flags: proxy
extension version: 0.41.3
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Tue, 23 Apr 2024 06:57:00 GMT
restart history:
Tue, 23 Apr 2024 06:56:46 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xa68b39]

goroutine 5941 [running]:
golang.org/x/tools/gopls/internal/cache.(*action).exec(0xc0011c7280)
	  analysis.go:1198  0xd9
golang.org/x/tools/gopls/internal/cache.execActions.func1.1()
	  analysis.go:1162  0x36
sync.(*Once).doSlow(0x0%3F, 0xc0047cae40%3F)
	  once.go:74  0xbf
sync.(*Once).Do(...)
	  once.go:65
golang.org/x/tools/gopls/internal/cache.execActions.func1()
	  analysis.go:1160  0x7a
created by golang.org/x/tools/gopls/internal/cache.execActions in goroutine 5616
	  analysis.go:1158  0x3e
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 99,
    "TestdataFiles": 0,
    "GoFiles": 57,
    "ModFiles": 1,
    "Dirs": 46
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.21.5",
  "GoplsVersion": "v0.15.3",
  "InitialWorkspaceLoadDuration": "1.636742604s",
  "MemStats": {
    "HeapAlloc": 70251160,
    "HeapInUse": 104816640,
    "TotalAlloc": 932113832
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 3358,
      "Largest": 917969,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.21.5",
        "AllPackages": {
          "Packages": 669,
          "LargestPackage": 147,
          "CompiledGoFiles": 3354,
          "Modules": 115
        },
        "WorkspacePackages": {
          "Packages": 22,
          "LargestPackage": 5,
          "CompiledGoFiles": 49,
          "Modules": 1
        },
        "Diagnostics": 1
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-04-25 19:30
Dupe of golang/go#66788

**Closed by findleyr** 2024-04-25 19:30 UTC
