### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Kami-don** [golang/vscode-go#3297] opened 2024-04-01 00:51 UTC
gopls version: v0.15.2/go1.18.1
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Mon, 01 Apr 2024 00:50:37 GMT
restart history:
Mon, 01 Apr 2024 00:47:35 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.1" (should be something like "go1.12")

goroutine 978 [running]:
go/types.NewChecker(0x0%3F, 0xc000d2ea00, 0xc000d34f50, 0x0%3F)
	  check.go:240  0x279
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc000d1ae70, {0xc0008b11f8, 0x1, 0x1})
	  analysis.go:1028  0x6f1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc000d1ae70, {0x1031b58, 0xc000ebaf30})
	  analysis.go:810  0xd9
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc000d1ae70, {0x1031b58%3F, 0xc000ebaf30})
	  analysis.go:672  0x145
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xda
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 2,
    "TestdataFiles": 0,
    "GoFiles": 1,
    "ModFiles": 1,
    "Dirs": 2
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.18.1",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "240.518386ms",
  "MemStats": {
    "HeapAlloc": 7370296,
    "HeapInUse": 12263424,
    "TotalAlloc": 78267648
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 484,
      "Largest": 210104,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.1",
        "AllPackages": {
          "Packages": 46,
          "LargestPackage": 161,
          "CompiledGoFiles": 481,
          "Modules": 1
        },
        "WorkspacePackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-04-01 15:35
Duplicate of golang/go#66636, which we will fix for gopls@v0.15.3.

**Closed by findleyr** 2024-04-01 15:35 UTC
