### ISSUE TITLE
`main` method could have a "run | debug" like go tests?

### ISSUE THREAD

**Issue by JonathanLoscalzo** [golang/vscode-go#3350] opened 2024-04-19 17:11 UTC
**Is your feature request related to a problem? Please describe.**
It could be useful to have a "run|debug" configuration directly in the main functions like we have in tests
<img width="286" alt="image" src="https://github.com/golang/vscode-go/assets/6944598/7bf0e2cd-2525-4e4d-84cb-2a09224ec92f">

**Describe the solution you'd like**
<img width="199" alt="image" src="https://github.com/golang/vscode-go/assets/6944598/d51dec59-aef0-4f05-b1d8-e924fb88363b">

**Additional context**
go version 1.22
machine macos M2

**Comment by hyangah** [comment] 2024-04-25 19:47
Thanks.
Duplicate of #159

**Closed by hyangah** 2024-04-25 19:47 UTC
