### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by mikeliddell-outreach** [golang/vscode-go#2000] opened 2022-01-07 02:38 UTC
gopls version: v0.7.4
gopls flags: 
update flags: proxy
extension version: 0.30.0
go version: 1.17.1
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Fri, 07 Jan 2022 02:36:51 GMT
restart history:
Fri, 07 Jan 2022 02:14:47 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

while trying to learn about module-versioning, I added two lines to go.mod. each is just a reference to a local fake module.

example.com/mliddell/gfx v0.0.0-00010101000000-000000000000 // indirect
example.com/mliddell/gfx v2.0.0+incompatible // indirect

<pre>panic: SetRequire called with conflicting versions for path example.com/mliddell/gfx (v0.0.0-00010101000000-000000000000 and v2.0.0 incompatible)

goroutine 949 [running]:
golang.org/x/mod/modfile.(*File).SetRequire(0xc00135a700, {0xc00348ce40, 0x8, 0xba})
	  rule.go:927  0x4da
golang.org/x/tools/internal/lsp/cache.switchDirectness(0xc0001df680, 0xc0001df2f0, 0xe924d8)
	  mod_tidy.go:442  0x2f3
golang.org/x/tools/internal/lsp/cache.directnessDiagnostic(0xc0001df2f0, 0xc0001df680, 0xc001d9ef78)
	  mod_tidy.go:369  0x19c
golang.org/x/tools/internal/lsp/cache.modTidyDiagnostics({0xf836c0, 0xc002937290}, {0xfacdc0, 0xc000326800}, 0xc000b87e40, 0xc00135a280, {0xc0019d2400, 0xd, 0xd38317})
	  mod_tidy.go:213  0x4fc
golang.org/x/tools/internal/lsp/cache.(*snapshot).ModTidy.func1({0xf83618, 0xc00348c700}, {0xf6c940, 0xc000326800})
	  mod_tidy.go:135  0x825
golang.org/x/tools/internal/memoize.(*Handle).run.func1()
	  memoize.go:327  0xa9
created by golang.org/x/tools/internal/memoize.(*Handle).run
	  memoize.go:320  0x1b0
[Error - 6:36:43 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2022-01-07 16:38
Thanks a lot for describing what caused this issue, @mikeliddell-outreach 
That's super helpful!

It looks like a duplicate of https://github.com/golang/go/issues/50425 
Gopls should avoid panicking.

**Comment by hyangah** [comment] 2022-01-07 19:18
Closing in favor of golang/go#50425. Thanks!
cc @findleyr

**Closed by hyangah** 2022-01-07 19:18 UTC
Labels: gopls, Duplicate
