### ISSUE TITLE
provide a references codelens

### ISSUE THREAD

**Issue by airtonix** [golang/vscode-go#3028] opened 2023-10-31 21:37 UTC
**Is your feature request related to a problem? Please describe.**

please return this feature: https://github.com/golang/vscode-go/issues/2509

**Describe the solution you'd like**

this for golang:

- https://code.visualstudio.com/docs/editor/editingevolved#_reference-information 

**Describe alternatives you've considered**

becoming a farmer of sheep instead of a software developer.

**Additional context**

it's useful.

**Comment by hyangah** [comment] 2023-10-31 23:31
Duplicate of https://github.com/golang/go/issues/40862

**Comment by findleyr** [comment] 2023-11-01 19:13
(closing as a dupe)

**Closed by findleyr** 2023-11-01 19:13 UTC
