### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by mossailem** [golang/vscode-go#3278] opened 2024-03-25 02:55 UTC
gopls version: v0.15.2/go1.18.1
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Mon, 25 Mar 2024 02:54:13 GMT
restart history:
Mon, 25 Mar 2024 02:53:59 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.1" (should be something like "go1.12")

goroutine 1823 [running]:
go/types.NewChecker(0x0%3F, 0xc0009a4640, 0xc00146abe0, 0x0%3F)
	  check.go:240  0x279
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc0003ddef0, {0xc00154f1a8, 0x1, 0x1})
	  analysis.go:1028  0x6f1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc0003ddef0, {0x1031b58, 0xc0014d18f0})
	  analysis.go:810  0xd9
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc0003ddef0, {0x1031b58%3F, 0xc0014d18f0})
	  analysis.go:672  0x145
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xda
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 6,
    "TestdataFiles": 0,
    "GoFiles": 3,
    "ModFiles": 1,
    "Dirs": 4
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.18.1",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "1.489877734s",
  "MemStats": {
    "HeapAlloc": 14093632,
    "HeapInUse": 20766720,
    "TotalAlloc": 188284416
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 885,
      "Largest": 395026,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.1",
        "AllPackages": {
          "Packages": 135,
          "LargestPackage": 161,
          "CompiledGoFiles": 882,
          "Modules": 1
        },
        "WorkspacePackages": {
          "Packages": 2,
          "LargestPackage": 2,
          "CompiledGoFiles": 3,
          "Modules": 1
        },
        "Diagnostics": 2
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment] 2024-03-25 21:10
Duplicate of #3276

**Closed by suzmue** 2024-03-25 21:10 UTC
Labels: Duplicate
