### ISSUE TITLE
Ubuntu 20.04 cannot use vscode-go 

### ISSUE THREAD

**Issue by fastopencn** [golang/vscode-go#1587] opened 2021-06-24 08:11 UTC
error:
Failed to run '/snap/bin/go env' (cwd: /home/cb/go/src/goim): Error: Command failed: /snap/bin/go env -json GOPATH GOROOT GOPROXY GOBIN GOMODCACHE

**Comment by rrrooommmaaa** [comment] 2021-06-24 11:07
Something to do with snap privileges.
I have used `snap_workaround` call from her and it helped me...
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1849753/comments/22

**Comment by hyangah** [comment] 2021-06-24 12:22
Duplicate of #166
Indeed `snap_workaround` was suggested here https://github.com/golang/vscode-go/issues/166#issuecomment-860002050

**Closed by hyangah** 2021-06-24 12:22 UTC

**Comment by TulyOpt** [comment] 2021-09-09 13:21
Hi, I have the same problem . Other workaround : remove snap version of go and reinstall go directly.

**Comment by rrrooommmaaa** [comment] 2021-09-09 18:09
> Hi, I have the same problem . Other workaround : remove snap version of go and reinstall go directly.

Me too, eventually. If it is possible to start debugging use snap's go, there may be insufficient privileges further down the road.
And I installed `vscode` directly too.
