### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by rustatian** [golang/vscode-go#2140] opened 2022-03-27 17:04 UTC
gopls version: v0.8.1 (go1.18)
gopls flags: 
update flags: proxy
extension version: 0.32.0
go version: 1.18
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Sun, 27 Mar 2022 17:03:48 GMT
restart history:
Sun, 27 Mar 2022 17:03:37 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb76272]

goroutine 108 [running]:
golang.org/x/tools/internal/lsp/cache.parseGoWork({0x1001cc8, 0xc000253aa0}, {0xc000162780, 0x42}, {0xc000162370%3F, 0xc00085aec0%3F}, {0xc0004b6e00, 0x0, 0x200}, {0xffb500, ...})
	  workspace.go:508  0x232
golang.org/x/tools/internal/lsp/cache.loadExplicitWorkspaceFile({0x1001cc8, 0xc000253aa0}, 0xc0000f3440, {0xffb500%3F, 0xc000752000%3F})
	  workspace.go:152  0x1e6
golang.org/x/tools/internal/lsp/cache.newWorkspace({0x1001cc8, 0xc000253aa0}, {0xc000162780, 0x42}, {0xffb500, 0xc000752000}, 0xc0002685a0, 0x0, 0x0)
	  workspace.go:106  0xbb
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0xc000752000, {0x1001cc8, 0xc000253aa0}, {0xc0004b5fcc, 0x4}, {0xc000044910, 0x42}, 0xc00055c240, 0x0)
	  session.go:197  0x25d
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0xc000752000, {0x1001cc8, 0xc000253aa0}, {0xc0004b5fcc, 0x4}, {0xc000044910, 0x42}, 0xc00009c8d0%3F)
	  session.go:166  0x287
golang.org/x/tools/internal/lsp.(*Server).addView(0xc000254360, {0x1001cc8, 0xc000253aa0}, {0xc0004b5fcc, 0x4}, {0xc000044910, 0x42})
	  workspace.go:42  0x1c7
golang.org/x/tools/internal/lsp.(*Server).addFolders(0xc000254360, {0x1001cc8%3F, 0xc000253aa0}, {0xc000247700, 0x1, 0x1%3F})
	  general.go:234  0x6f5
golang.org/x/tools/internal/lsp.(*Server).initialized(0xc000254360, {0x1001cc8, 0xc000253aa0}, 0xc000843b00%3F)
	  general.go:186  0x2fa
golang.org/x/tools/internal/lsp.(*Server).Initialized(0xc00073f430%3F, {0x1001cc8%3F, 0xc000253aa0%3F}, 0xc5af00%3F)
	  server_gen.go:156  0x25
golang.org/x/tools/internal/lsp/protocol.serverDispatch({0x1001cc8, 0xc000253aa0}, {0x100cdc0, 0xc000254360}, 0xc0002140c0, {0x1001ec0, 0xc0002539e0})
	  tsserver.go:140  0x6d3
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1({0x1001cc8, 0xc000253aa0}, 0xc0002140c0, {0x1001ec0, 0xc0002539e0})
	  protocol.go:154  0x90
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1({0x1001cc8, 0xc000253aa0}, 0xc0002140c0, {0x1001ec0%3F, 0xc0002539e0%3F})
	  lsprpc.go:506  0xa43
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x1001cc8, 0xc000253aa0}, 0xc00000e5a0, {0x1001ec0%3F, 0xc0002539e0%3F})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20a
[Error - 7:03:42 PM] </pre>

**Comment by hyangah** [comment] 2022-03-28 18:06
Thanks for the report - Duplicate of https://github.com/golang/vscode-go/issues/2121 and https://github.com/golang/go/issues/51844
The fix will be released soon (gopls v0.8.2)

**Closed by hyangah** 2022-03-28 18:06 UTC
