### ISSUE TITLE
debug: debug adapter got stuck during initialization

### ISSUE THREAD

**Issue by PucklaMotzer09** [golang/vscode-go#777] opened 2020-10-13 08:26 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.15.2 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.50.0 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3 x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.17.2
- Run `go env` to get the go development environment details
```
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\jonaspucher\AppData\Local\go-build
set GOENV=C:\Users\jonaspucher\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\jonaspucher\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\jonaspucher\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\jonaspucher\go\src\fyne.io\fyne\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\JONASP~1\AppData\Local\Temp\go-build131841526=/tmp/go-build -gno-record-gcc-switches
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```json
{
   "go.useLanguageServer": true,
   "go.formatTool": "gofmt"
}
```

### Describe the bug
When I start debugging either by pressing **F5** or clicking on the play button of the debugging panel, basically nothing happens. There is just the bar for pausing the debugging process. This is especially bad when trying to debug a test. It hardly works. Sometimes it works just fine, but on the next day nothing is working.

### Steps to reproduce the behavior:
1. Create any Go launch configuration
2. Start debugging
3. See that nothing happens

### Screenshots or recordings
trace log
```
InitializeRequest
InitializeResponse
LaunchRequest
Using GOPATH: C:\Users\jonaspucher\go
Using GOROOT: c:\go
Using PATH: undefined
Current working directory: C:\Users\jonaspucher\go\src\fyne.io\fyne/cmd/fyne_demo
Running: C:\Users\jonaspucher\go\bin\dlv.exe debug fyne.io\fyne/cmd/fyne_demo --headless=true --listen=127.0.0.1:23459 --api-version=2
DisconnectRequest
HaltRequest
Killing debug process manually as we could not halt delve in time
killing debugee (pid: 30028)...
Process exiting with code: 1
```

The killing of the debugging process was initiated by me.

**Comment by hyangah** [comment] 2020-10-13 14:36
@PucklaMotzer09 thanks for the report. Can you share your `launch.json` ? The following lines in the log look suspicious.

```
Current working directory: C:\Users\jonaspucher\go\src\fyne.io\fyne/cmd/fyne_demo
Running: C:\Users\jonaspucher\go\bin\dlv.exe debug fyne.io\fyne/cmd/fyne_demo 
```

What happens if you run the command `C:\Users\jonaspucher\go\bin\dlv.exe debug fyne.io\fyne/cmd/fyne_demo` from the directory (`C:\Users\jonaspucher\go\src\fyne.io\fyne/cmd/fyne_demo`)?

**Comment by PucklaMotzer09** [comment] 2020-10-14 06:11
launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Fyne Demo",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceFolder}/cmd/fyne_demo",
            "env": {},
            "args": [],
            "trace": "log"
        }
    ]
}
```

> What happens if you run the command C:\Users\jonaspucher\go\bin\dlv.exe debug fyne.io\fyne/cmd/fyne_demo from the directory (C:\Users\jonaspucher\go\src\fyne.io\fyne/cmd/fyne_demo)?

This is what happens
```
C:\Users\jonaspucher\go\src\fyne.io\fyne\cmd\fyne_demo>C:\Users\jonaspucher\go\bin\dlv.exe debug fyne.io\fyne/cmd/fyne_demo
Type 'help' for list of commands.
(dlv) 
```

**Comment by hyangah** [comment] 2020-10-14 13:53
@PucklaMotzer09 Thanks! 

Can you set a breakpoint in the main function of `cmd/fyne_demo/main.go` (maybe the very first line of the function) and try it? 
Unlike the commandline delve, the debugging session will start running the program immediately. When the program is in running state, vscode can't show variables or call stacks. 

If you are still seeing an issue, that may be a windows specific issue for which we need more detailed traces. Setting the following additional attributes will show more info on what delve is doing.

```
    ...
            "trace": "log",
            "showLog": true,
            "logOutput": "rpc"
```

cc @polinasok @suzmue I observed that when running the program without any breakpoint, I can't issue 'pause' (see the attached image - 'pause' button is deactivated). I could still set breakpoints unlike in #759, since I am using the stable version of the extension. I don't know this is an intended behavior or another bug we need to investigate. 
![Screen Shot 2020-10-14 at 9 50 54 AM](https://user-images.githubusercontent.com/4999471/95998374-cb643e80-0e02-11eb-9755-818961898f3c.png)

**Comment by PucklaMotzer09** [comment] 2020-10-14 14:41
I did as you said and added a breakpoint at the first line. I also added the additional attributes to the launch configuration.
Now it works.
This is the output when it stops at the breakpoint.
[output.txt](https://github.com/golang/vscode-go/files/5378925/output.txt)

I can even debug tests right now. This hasn't been working for over a week.

**Comment by hyangah** [comment] 2020-10-14 16:15
@PucklaMotzer09 glad to hear that it addresses the issue. No variables/callstacks when program is active is working as intended. 

@suzmue gave me a hint that the missing pause button issue is no longer reproducible with the latest vscode release (1.50). I was using 1.49. After upgrading to 1.50, the pause button issue I mentioned disappeared. :-)

So, I am closing this issue. Happy coding!

**Comment by polinasok** [comment] 2020-10-14 20:25
@PucklaMotzer09 I am glad that the workaround from @hyangah is working for you. As @hyangah said if you rely on the default on-entry behavior, the debug session will just run your program. You should be able to pause and set breakpoints while the program is running. (And if that is not the case, please file an issue.) However, if your program is a fast-running test, it might exit before you have a chance to do so.

By comparison, using dlv on the command-line, stops the program on entry and gives you a chance to set the breakpoints and then continue. You can achieve the same behavior in vscode using `"stopOnEntry": true` in `launch.json`. The program will stop before executing main. There is not much to display at that point in the CALL STACK, but you will see "paused on entry" there and Continue button will be enabled.

Your original log still looks concerning to me. According to that log, the initialization sequence never progressed after launching dlv. I do not see InitializeEvent, ConfigurationDoneRequest, and the default ContinueRequest, which is what makes your program just run and the variables/stacks not captured. I also do not see "API Listening" message from delve in that log, which is something you should *always* see with or without logging enabled if dlv debugger is working. Did you copy everything in that log? Did you by any chance click disconnect too soon before all the initialization was complete? Can you still reproduce the original problem? More logging would be helpful with 
```
            "trace":"verbose"
            "showLog": true,
            "logOutput": "rpc"
```

**Comment by PucklaMotzer09** [comment] 2020-10-15 06:31
It doesn't really address the issue. Currently it also works without setting a breakpoint. Tests and launch configurations. And it isn't really about not seeing any info. There really was nothing happening. The program didn't even start. But it is difficult to say what's really happening.

**Comment by hyangah** [comment] 2020-10-15 14:11
I am reopening this issue

@PucklaMotzer09 Can you reproduce the problem **if you _turn off_ the verbose logging**? 

Looking into the *original* trace, I don't see the `API server listening at: ...` message which should appear in normal case even without any logging. My current wild guess is that the debug adapter and the dlv headless server were racing, failed to establish connection, so got stuck. By adding the additional verbose logging, it's possible that we made the debug adapter and allowed more time for dlv to finish setting up environment (e.g. compile, launch process, attach, bringing up the server, etc).

**Comment by PucklaMotzer09** [comment] 2020-10-15 15:08
When removing all verbose logging it worked as well. It wrote ```API server listening at: ...``` into the log. Everything worked as expected. I will write again if I encounter the issue again. Thank you for your help.

**Closed** 2021-03-08 22:29 UTC
Labels: Debug, WaitingForInfo
