### ISSUE TITLE
gopls client: couldn't create connection to server.

### ISSUE THREAD

**Issue by demo007x** [golang/vscode-go#2921] opened 2023-08-05 13:40 UTC
I update the vscode latest:, but the gopls client: couldn't create connection to server.

vscode version info:

Version: 1.81.0 (Universal)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:40:02.782Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 23.0.0

<img width="966" alt="image" src="https://github.com/golang/vscode-go/assets/6418340/acbcbac2-2781-4253-9bd2-67210f5f9a38">

**Comment by findleyr** [comment] 2023-08-08 13:41
Hi, this may be related to golang/go#61190. Are you using xcode 15, by any chance?

**Comment by findleyr** [comment] 2023-08-10 15:59
Thanks for confirming. Closing this as a dupe of golang/go#61190

**Closed by findleyr** 2023-08-10 15:59 UTC
