### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by dpanic** [golang/vscode-go#2523] opened 2022-11-01 15:16 UTC
gopls version: v0.10.0 (go1.19.2)
gopls flags: 
update flags: proxy
extension version: 0.35.2
go version: 1.19.2
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Tue, 01 Nov 2022 15:12:55 GMT
restart history:
Tue, 01 Nov 2022 15:07:27 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc6109b]

goroutine 147 [running]:
go/types.(*Package).Path(...)
	  package.go:31
golang.org/x/tools/gopls/internal/lsp/source/completion.isStarTestingDotF({0x112f778%3F, 0xc008dfc0e0%3F})
	  completion.go:1283  0x7b
golang.org/x/tools/gopls/internal/lsp/source/completion.(*completer).methodsAndFields(0xc005676280, {0x112f778%3F, 0xc008dfc0e0}, 0x1, 0x0, 0xc0037a8f00)
	  completion.go:1246  0x211
golang.org/x/tools/gopls/internal/lsp/source/completion.(*completer).deepSearch(0xc005676280, {0x1133828%3F, 0xc0034332c0%3F})
	  deep_completion.go:229  0xabd
golang.org/x/tools/gopls/internal/lsp/source/completion.Completion({0x11337b8%3F, 0xc0003dd680%3F}, {0x113fd60%3F, 0xc0058f2000}, {0x1133ac8%3F, 0xc0002c3960}, {0x7976bf18%3F, 0x7fa8%3F}, {0x1, {0x0, ...}})
	  completion.go:571  0x1288
golang.org/x/tools/gopls/internal/lsp.(*Server).completion(0xd39580%3F, {0x11337b8, 0xc0003dd680}, 0xc0052e7450)
	  completion.go:32  0x1c5
golang.org/x/tools/gopls/internal/lsp.(*Server).Completion(0xc000332300%3F, {0x11337b8%3F, 0xc0003dd680%3F}, 0xd39580%3F)
	  server_gen.go:28  0x25
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch({0x11337b8, 0xc0003dd680}, {0x1143880, 0xc000132900}, 0xc005cdc630, {0x1133ba8, 0xc0003dd280})
	  tsserver.go:269  0x20c2
golang.org/x/tools/gopls/internal/lsp/protocol.ServerHandler.func1({0x11337b8, 0xc0003dd680}, 0xc005cdc630, {0x1133ba8, 0xc0003dd280})
	  protocol.go:157  0x90
golang.org/x/tools/gopls/internal/lsp/lsprpc.handshaker.func1({0x11337b8, 0xc0003dd680}, 0xc005cdc630, {0x1133ba8%3F, 0xc0003dd280%3F})
	  lsprpc.go:515  0xa43
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x11337b8, 0xc0003dd680}, 0xc0003cb428, {0x1133ba8%3F, 0xc0003dd280%3F})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20a
[Error - 4:12:38 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2022-11-01 16:18
Thank you for reporting! This is a dupe of golang/go#56505, which will be fixed (and released) soon.

**Closed by findleyr** 2022-11-01 16:18 UTC
