### ISSUE TITLE
Editor help prompts, code navigation doesn't work, when I open some files

### ISSUE THREAD

**Issue by xilu0** [golang/vscode-go#2407] opened 2022-08-13 14:04 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- <Paste go version here>
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <Paste gopls version here>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- <Paste VS Code version here>
* Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>
vscode version: 1.70.0
language and extension: go 1.7.0

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
**developer tools console error:**
```
workbench.desktop.main.js:sourcemap:2279 [[object Object]]Header must provide a Content-Length property.
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:2279
workbench.desktop.main.js:sourcemap:2279 Error: Header must provide a Content-Length property.
at StreamMessageReader.onData (/root/.vscode-server/extensions/golang.go-0.35.1/dist/goMain.js:3762:21)
at Socket. (/root/.vscode-server/extensions/golang.go-0.35.1/dist/goMain.js:3746:16)
at Socket.emit (node:events:390:28)
at addChunk (node:internal/streams/readable:315:12)
at readableAddChunk (node:internal/streams/readable:289:9)
at Socket.Readable.push (node:internal/streams/readable:228:10)
at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```
like：https://github.com/microsoft/vscode/issues/157886

**Comment by findleyr** [comment] 2022-08-13 15:34
Hi, this is almost certainly a dupe of #2406, which is a corruption of the jsonrpc2 stream. Thank you for reporting.

It is likely that you have the bad time format string "2006-02-01" somewhere in your project, and the stray print statement in the new "timeformat" analyzer is causing hanging.

Sorry for this unfortunate breakage - we only discovered it midday on Friday, and so will not be able to release a fix until Monday.

In the meantime you can do *any one* of the following fixes
1. Remove that bad format string
2. Disable the "timeformat" analyses
3. Downgrade to gopls@v0.9.1 (`go install golang.org/x/tools/gopls@v0.9.1`)
4. Upgrade to the next version of gopls that will be released on Monday (`go install/golang.org/x/tools/gopls@gopls-release-branch.0.9`).

**Comment by findleyr** [comment] 2022-08-14 12:30
Closing as a dupe.

**Closed by findleyr** 2022-08-14 12:30 UTC
