### ISSUE TITLE
No autocomplete

### ISSUE THREAD

**Issue by X-n3t** [golang/vscode-go#2611] opened 2023-01-16 01:39 UTC
![imagen](https://user-images.githubusercontent.com/52056830/212580903-3f8e66c7-5505-4d76-85f9-541d830c5e2c.png)

what's is wrong?, I reinstalled and I have the same problem.

**Comment by X-n3t** [comment] 2023-01-16 01:52
![imagen](https://user-images.githubusercontent.com/52056830/212582135-55f4209d-af1b-472c-96d9-f19960d549fa.png)

**Comment by pjweinb** [comment] 2023-01-16 12:02
It's looking for a declaration at that point. Does the same thing happen if
fmt.P is inside a function?

**Comment by X-n3t** [comment] 2023-01-16 12:22
I had a problem with autocomplete.. I think is in dependency instalation...
![imagen](https://user-images.githubusercontent.com/52056830/212677040-c0bf6795-4935-4349-8867-8ea29316cb56.png)
I resolved with this commands:
go clean -modcache
go install -v golang.org/x/tools/gopls@latest

**Comment by dle8** [comment] 2023-01-18 20:12
Thanks. Since the problem is resolved, I'll close this issue. If you have further issues, you can refer to this wiki doc here: https://github.com/golang/vscode-go/wiki/troubleshooting

**Closed by dle8** 2023-01-18 20:12 UTC
