### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by zgjin** [golang/vscode-go#2257] opened 2022-05-25 03:56 UTC
gopls version: v0.8.4 (go1.15.15)
gopls flags: 
update flags: proxy
extension version: 0.33.1
go version: 1.15.15
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Wed, 25 May 2022 03:49:16 GMT
restart history:
Wed, 25 May 2022 03:49:05 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

vscode-go extention can't start when vscode is openned. leading to vscode extention-host can't start.

<pre>panic: runtime error: index out of range [1] with length 1

goroutine 70 [running]:
golang.org/x/tools/internal/gocommand.cmdDebugStr(0xc00014a6e0, 0x26915fb, 0x2009ce0)
	  invoke.go:267  0x874
golang.org/x/tools/internal/gocommand.(*Invocation).run.func5(0x1ac5d18, 0xc00014a6e0, 0xc09b87ac80763d88, 0x26915fb, 0x2009ce0)
	  invoke.go:230  0x5d
golang.org/x/tools/internal/gocommand.(*Invocation).run(0xc00032a898, 0x1b9e7c0, 0xc00015bcb0, 0x1b8d200, 0xc00031f860, 0x1b8d200, 0xc00031f890, 0x1b8dea0, 0xc00000e080)
	  invoke.go:232  0x418
golang.org/x/tools/internal/gocommand.(*Invocation).runWithFriendlyError(0xc00032a898, 0x1b9e7c0, 0xc00015bcb0, 0x1b8d200, 0xc00031f860, 0x1b8d200, 0xc00031f890, 0x1856400, 0x1, 0xc0002aa3c0, ...)
	  invoke.go:154  0x8e
golang.org/x/tools/internal/gocommand.(*Runner).runConcurrent(0xc00016e020, 0x1b9e7c0, 0xc00015bcb0, 0x1992d38, 0x4, 0xc000298460, 0x5, 0x5, 0x0, 0x0, ...)
	  invoke.go:98  0x1cd
golang.org/x/tools/internal/gocommand.(*Runner).RunRaw(0xc00016e020, 0x1b9e7c0, 0xc00015bcb0, 0x1992d38, 0x4, 0xc000298460, 0x5, 0x5, 0x0, 0x0, ...)
	  invoke.go:73  0x9d
golang.org/x/tools/internal/gocommand.(*Runner).Run(...)
	  invoke.go:55
golang.org/x/tools/internal/gocommand.GoVersion(0x1b9e7c0, 0xc00015bcb0, 0x1992d38, 0x4, 0xc000298460, 0x5, 0x5, 0x0, 0x0, 0x0, ...)
	  version.go:33  0x3b8
golang.org/x/tools/internal/lsp/cache.(*Session).getWorkspaceInformation(0xc000172300, 0x1b9e7c0, 0xc00015bcb0, 0xc00036c680, 0x7f, 0xc00032e000, 0x0, 0x0, 0x0)
	  view.go:738  0x285
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0xc000172300, 0x1b9e7c0, 0xc00015bcb0, 0xc000491f90, 0xb, 0xc00036c680, 0x7f, 0xc00032e000, 0x0, 0xc00015bcb0, ...)
	  session.go:183  0xb3
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0xc000172300, 0x1b9e7c0, 0xc00015bcb0, 0xc000491f90, 0xb, 0xc00036c680, 0x7f, 0xc00032e000, 0x0, 0x0, ...)
	  session.go:165  0x27c
golang.org/x/tools/internal/lsp.(*Server).addView(0xc00013c000, 0x1b9e7c0, 0xc00015bcb0, 0xc000491f90, 0xb, 0xc00036c680, 0x7f, 0x185d280, 0xc000612b40, 0x0, ...)
	  workspace.go:40  0x1c8
golang.org/x/tools/internal/lsp.(*Server).addFolders(0xc00013c000, 0x1b9e7c0, 0xc00015bcb0, 0xc0004b59c0, 0x1, 0x1, 0x0, 0x0)
	  general.go:233  0x766
golang.org/x/tools/internal/lsp.(*Server).initialized(0xc00013c000, 0x1b9e7c0, 0xc00015bcb0, 0x203abe0, 0x0, 0x0)
	  general.go:185  0x1d9
golang.org/x/tools/internal/lsp.(*Server).Initialized(0xc00013c000, 0x1b9e7c0, 0xc00015bcb0, 0x203abe0, 0x203abe0, 0x0)
	  server_gen.go:160  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1b9e7c0, 0xc00015bcb0, 0x1bb33c0, 0xc00013c000, 0xc0002751d0, 0x1b9ea00, 0xc00015bbf0, 0x1b8e6e0, 0xc0001dcb00, 0x1b9e7c0)
	  tsserver.go:144  0xa22
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1b9e7c0, 0xc00015bcb0, 0xc0002751d0, 0x1b9ea00, 0xc00015bbf0, 0xc09b87ac805528c8, 0x248025d)
	  protocol.go:157  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1b9e7c0, 0xc00015bcb0, 0xc0002751d0, 0x1b9ea00, 0xc00015bbf0, 0x0, 0x0)
	  lsprpc.go:511  0x472
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1b9e7c0, 0xc00015bcb0, 0xc00016ec20, 0x1b9ea00, 0xc00015bbf0, 0x0, 0x0)
	  handler.go:35  0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc000126180, 0xc0001578c0, 0xc00049e1e0, 0x1b9e7c0, 0xc00015bcb0, 0xc00016ec20, 0x1b9ea00, 0xc00015bbf0)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 11:49:06 AM] </pre>

**Comment by hyangah** [comment] 2022-05-25 19:41
Duplicate of #2260

**Closed by hyangah** 2022-05-25 19:41 UTC

**Comment by hyangah** [comment] 2022-05-25 19:42
Can you check if you have any env var that is not in the form of "KEY=VALUE" format? If so, I think fixing the env var will help.
