### ISSUE TITLE
gopls: time.Format with the bad format "2006-02-01" causes gopls to hang (new analyzer) 

### ISSUE THREAD

**Issue by Phadin** [golang/vscode-go#2406] opened 2022-08-12 15:36 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.19 darwin/amd64
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.70.1 (Universal)
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.35.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- 	
	go:	/usr/local/bin/go: go version go1.19 darwin/amd64
	gotests:	not installed
	gomodifytags:	not installed
	impl:	not installed
	goplay:	not installed
	dlv:	/Users/mbarri202/go/bin/dlv	(version: v1.9.0 built with go: go1.19)
	staticcheck:	/Users/mbarri202/go/bin/staticcheck	(version: v0.3.3 built with go: go1.19)
	gopls:	/Users/mbarri202/go/bin/gopls	(version: v0.9.3 built with go: go1.19)

</details>

### Describe the bug
Intellisense/gopls dies when using custom time format with time.Format.  Go: Restart Language Server will work to restore functionality only if the offending code is removed or there are code errors preventing it from being run through.  When the error occurs, hovering over text is stuck with a 'loading...' box, saving will hang on trying to access go formatting, and autocomplete will not function.

### Steps to reproduce the behavior:
Go code that will cause the error:

now := time.Now()
nowFormatted := now.Format("2006-02-01")
fmt.Printf("Time: %v", nowFormatted)

Note that no error occurs with other time.Format functions such as `now.Format(time.RFC822)`.  It seemed to only occur with this custom format.

**Comment by findleyr** [comment] 2022-08-12 15:54
Hi, thank you for reporting.  I was not able to reproduce following your instructions. Can you please attach the panicking stack? (you can find this via `output -> gopls (server)`).

**Comment by findleyr** [comment] 2022-08-12 16:18
Wait, I do believe I can reproduce: I don't get a crash, but rather a hanging process.

I am investigating.

**Comment by findleyr** [comment] 2022-08-12 16:25
Well, yes it is reliably reproducible, and only with that format.

Almost certainly this is related to https://go.dev/cl/354010. Note that the format "2006-02-01" is likely wrong, per the discussion in https://go.dev/issue/48801. But of course it should not make gopls hang.

CC @timothy-king (Tim: no action required from you, just keeping you informed that there may be a bug in this analyzer).

Amazing that this was caught so soon. Thank you very much for filing an issue!

**Comment by findleyr** [comment] 2022-08-12 16:39
The root cause is a debug print statement left in the analyzer, which breaks gopls' communication over stdin/stdout.

**Comment by eqinox76** [comment] 2022-08-12 16:51
Hit the same issue with `time.Format("2006-02-01 15:04:05")`.
Kudos for adding this check even if the print statement is unfortunate.

**Comment by findleyr** [comment] 2022-08-12 17:42
Reopening and pinning until this is released.

Since it is Friday, we likely won't cut a new release until Monday.

**Comment by findleyr** [comment] 2022-08-13 15:36
The fix for this issue will be released on Monday (we don't do releases late in the day on Friday, I'm afraid).

In the meantime, anyone encountering this bug can take any **one** of the following mitigating steps:

- Remove the bad format string
- Disable the "timeformat" analyzer (see [documentation](https://github.com/golang/tools/blob/master/gopls/doc/analyzers.md))
- Downgrade to gopls@v0.9.1 (go install golang.org/x/tools/gopls@v0.9.1), which doesn't contain this regression.
- Upgrade to the patched version of gopls that will be released on Monday (go install golang.org/x/tools/gopls@gopls-release-branch.0.9).

**Comment by Phadin** [comment] 2022-08-15 12:19
Thank you for the quick verification and work on releasing a fix.

**Comment by findleyr** [comment] 2022-08-15 17:23
This fix has been release in gopls@v0.9.4.

**Closed by findleyr** 2022-08-15 17:23 UTC
