### ISSUE TITLE
Error: Setup Team Chat to work for your account.

### ISSUE THREAD

**Issue by huhugiter** [golang/vscode-go#472] opened 2020-08-05 02:16 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
  - go version go1.14.6 windows/amd64
  - it also crashed on linux.
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
  - 1.47.3
  - 91899dcef7b8110878ea59626991a18c8a6a1b3e
  - x64
- Check your installed extensions to get the version of the VS Code Go extension 
  - 0.16.0
- Run `go env` to get the go development environment details

```txt
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\huhu\AppData\Local\go-build
set GOENV=C:\Users\huhu\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\huhu\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Library\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Library\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\huhu\AppData\Local\Temp\go-build914854702=/tmp/go-build -gno-record-gcc-switches
```

### Describe the bug

After starting vscode, the extension crashes unexpectedly if is a go project.
When I switch to version 0.15.0, everything works fine.

```txt
c:\Users\huhu\.vscode\extensions\golang.go-0.16.0\dist\goMain.js:26315
    throw err;
    ^

[Error: Setup Team Chat to work for your account.
	at c:\Users\huhu\.vscode\extensions\karigari.chat-0.35.0\out\extension.js:151:179152
	at Timeout._onTimeout (c:\Users\huhu\.vscode\extensions\karigari.chat-0.35.0\out\extension.js:151:179182)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)] {
  vslsStack: [ CallSite {}, CallSite {}, CallSite {}, CallSite {} ]
}
```

### Steps to reproduce the behavior:

1. Open VSCode
2. Open a Golang project
3. Wait a while, it crashes

### Screenshots or recordings

![image](https://user-images.githubusercontent.com/26333129/89364222-ffd5c300-d70c-11ea-95c8-40133481f3c1.png)

**Comment by hyangah** [comment] 2020-08-05 03:39
@huhugiter thanks for the report. 
this is a duplicate of https://github.com/golang/vscode-go/issues/469. 
We accidentally installed a process-wide unhandled exception handler :-(

**Closed** 2020-08-05 03:40 UTC

**Comment by hyangah** [comment] 2020-08-05 04:02
BTW - thanks for this bug report. I could reproduce the problem based on this report.
