### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by ihsankhwaritsmi** [golang/vscode-go#3197] opened 2024-02-28 04:03 UTC
gopls version: v0.15.0/go1.22.0
gopls flags: 
update flags: proxy
extension version: 0.41.1
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Wed, 28 Feb 2024 04:02:30 GMT
restart history:
Wed, 28 Feb 2024 03:47:44 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 13,
    "TestdataFiles": 0,
    "GoFiles": 4,
    "ModFiles": 1,
    "Dirs": 4
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.0",
  "GoplsVersion": "v0.15.0",
  "InitialWorkspaceLoadDuration": "546.771723ms",
  "MemStats": {
    "HeapAlloc": 13191616,
    "HeapInUse": 20865024,
    "TotalAlloc": 149096744
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 818,
      "Largest": 210104,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.0",
        "AllPackages": {
          "Packages": 118,
          "LargestPackage": 161,
          "CompiledGoFiles": 814,
          "Modules": 2
        },
        "WorkspacePackages": {
          "Packages": 2,
          "LargestPackage": 3,
          "CompiledGoFiles": 4,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-02-28 14:27
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

This may be a duplicate of #3194, which will be fixed shortly.

**Closed** 2024-03-13 19:44 UTC
Labels: WaitingForInfo
