### ISSUE TITLE
Parameter Hints for Function Calls

### ISSUE THREAD

**Issue by Suraj-Yadav** [golang/vscode-go#1795] opened 2021-09-22 07:00 UTC
**Is your feature request related to a problem? Please describe.**
For function calls, sometimes it becomes quite difficult to tell what a argument actually does. Usually it happens when the arguments passed are boolean/integer. We can hover over the call and it would show the signature, but it would be helpful if we can tell this directly at a glance.
```go
func log(message string, appendTime bool) {
	if appendTime {
		fmt.Print(message, "at", time.Now())
	} else {
		fmt.Print(message)
	}
}

log("Process Started", true)

log("Still Running", false)

``` 

**Describe the solution you'd like**
We can have something like [Parameter hints](https://www.jetbrains.com/help/webstorm/viewing-method-parameter-information.html) in Webstorm.

**Describe alternatives you've considered**
The only alternative I see is hover.

**Additional context**
Image from Webstorm
![Image from Webstorm](https://resources.jetbrains.com/help/img/idea/2021.2/ws_javascript_parameter_hints.png)

**Comment by suzmue** [comment] 2021-09-22 17:01
You can enable placeholders to view the function signature inline using:
```
    "gopls": {
        "ui.completion.usePlaceholders": true
    }
```

Signature help with usePlaceholders=false:
<img width="521" alt="Screen Shot 2021-09-22 at 10 59 45 AM" src="https://user-images.githubusercontent.com/6634754/134388605-8a3dfcec-c82b-431a-82ef-e90cf097cb90.png">
Signature help with usePlaceholders=true:
<img width="593" alt="Screen Shot 2021-09-22 at 11 00 12 AM" src="https://user-images.githubusercontent.com/6634754/134388610-7077f36f-f6dc-492b-8678-84a50da56870.png">

**Comment by hyangah** [comment] 2021-09-22 23:21
Isn't it a duplicate of https://github.com/golang/vscode-go/issues/1631?

**Comment by suzmue** [comment] 2021-09-23 01:13
@hyangah Yes it looks like it.

Closing as a duplicate of #1631

**Closed by suzmue** 2021-09-23 01:13 UTC
