### ISSUE TITLE
multiline/block comment identifier conflicts with file globs inside strings

### ISSUE THREAD

**Issue by lirtistan** [golang/vscode-go#3634] opened 2024-12-22 02:12 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.23.4 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.16.2
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.96.2 29b115fb6fb418b80e93102cb177e06803e7b907 x64
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.42.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- see output below
```md
# Tools Configuration


## Environment

GOBIN: undefined
toolsGopath: 
gopath: /home/enrico/.go
GOROOT: /home/enrico/.asdf/installs/golang/1.23.4/go
PATH: /home/enrico/.asdf/installs/golang/1.23.4/go/bin:/home/enrico/.local/bin:/home/enrico/.asdf/installs/rust/stable/bin:/home/enrico/.asdf/shims:/home/enrico/.asdf/bin:/home/enrico/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/enrico/.local/share/JetBrains/Toolbox/scripts:/home/enrico/.local/share/JetBrains/Toolbox/scripts:/home/enrico/.local/bin:/home/enrico/.local/share/JetBrains/Toolbox/scripts
PATH (vscode launched with): /home/enrico/.local/bin:/home/enrico/.asdf/installs/rust/stable/bin:/home/enrico/.asdf/shims:/home/enrico/.asdf/bin:/home/enrico/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/enrico/.local/share/JetBrains/Toolbox/scripts:/home/enrico/.local/share/JetBrains/Toolbox/scripts:/home/enrico/.local/bin:/home/enrico/.local/share/JetBrains/Toolbox/scripts

## Tools

	go:	/home/enrico/.asdf/installs/golang/1.23.4/go/bin/go: go version go1.23.4 linux/amd64

	gopls:	/home/enrico/.go/bin/gopls	(version: v0.17.1 built with go: go1.23.4)
	gotests:	/home/enrico/.asdf/shims/gotests	(version: unknown - )
	gomodifytags:	/home/enrico/.asdf/shims/gomodifytags	(version: unknown - )
	impl:	/home/enrico/.asdf/shims/impl	(version: unknown - )
	goplay:	/home/enrico/.asdf/shims/goplay	(version: unknown - )
	dlv:	/home/enrico/.asdf/shims/dlv	(version: unknown - )
	staticcheck:	/home/enrico/.asdf/shims/staticcheck	(version: unknown - )

## Go env

Workspace Folder (web): /home/enrico/Projects/golang/active/web

	GO111MODULE=''
	GOARCH='amd64'
	GOBIN=''
	GOCACHE='/home/enrico/.cache/go-build'
	GOENV='/home/enrico/.config/go/env'
	GOEXE=''
	GOEXPERIMENT=''
	GOFLAGS=''
	GOHOSTARCH='amd64'
	GOHOSTOS='linux'
	GOINSECURE='ebony.local'
	GOMODCACHE='/home/enrico/.go/pkg/mod'
	GONOPROXY='ebony.local'
	GONOSUMDB='ebony.local'
	GOOS='linux'
	GOPATH='/home/enrico/.go'
	GOPRIVATE='ebony.local'
	GOPROXY='https://proxy.golang.org,direct'
	GOROOT='/home/enrico/.asdf/installs/golang/1.23.4/go'
	GOSUMDB='sum.golang.org'
	GOTMPDIR=''
	GOTOOLCHAIN='auto'
	GOTOOLDIR='/home/enrico/.asdf/installs/golang/1.23.4/go/pkg/tool/linux_amd64'
	GOVCS=''
	GOVERSION='go1.23.4'
	GODEBUG=''
	GOTELEMETRY='off'
	GOTELEMETRYDIR='/home/enrico/.config/go/telemetry'
	GCCGO='gccgo'
	GOAMD64='v1'
	AR='ar'
	CC='gcc'
	CXX='g++'
	CGO_ENABLED='0'
	GOMOD='/dev/null'
	GOWORK='/home/enrico/Projects/golang/active/web/go.work'
	CGO_CFLAGS='-O2 -g'
	CGO_CPPFLAGS=''
	CGO_CXXFLAGS='-O2 -g'
	CGO_FFLAGS='-O2 -g'
	CGO_LDFLAGS='-O2 -g'
	PKG_CONFIG='pkg-config'
	GOGCCFLAGS='-fPIC -m64 -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1658662752=/tmp/go-build -gno-record-gcc-switches'
```
</details>

### Share the Go related settings you have added/edited

```json
{
    "gopls": {
        "ui.semanticTokens": true,
    },
    "go.toolsManagement.autoUpdate": true,
    "go.buildTags": "debug",
    "go.inlayHints.constantValues": true,
    "[go]": {
        "breadcrumbs.showArrays": true,
            "editor.insertSpaces": false,
            "editor.formatOnSave": true,
            "editor.codeActionsOnSave": {
                "source.organizeImports": "always"
            }
    },
   "go.coverOnTestPackage": false,
    "go.editorContextMenuCommands": {
        "testCoverage": false,
        "debugTestAtCursor": false
    },
    "go.testFlags": [
        "-v"
    ],
}
```

### Describe the bug

The multiline comment identifier conflicts with file globs inside strings. Impossible to comment a block of code.

I expect that a multiline comment or (block comment) ignores occurences of opening/closing identifier inside strings variations.
So speaking, everything inside backticks or quotes should be skipped.

### Steps to reproduce the behavior:

1. Create a .go file
2. Call fs.Glob() or a similar function with a pattern like `"path/**/*.ext"`
3. Start a multiline/block comment above that glob  

For a better description, just have a look at the screen recording below.

### Screenshots or recordings

[2024-12-22 02-34-22.webm](https://github.com/user-attachments/assets/c76a699e-541c-4598-9259-590fecd4c141)

**Comment by h9jiang** [comment] 2024-12-27 20:04
Hi lirtistan, 

based on the [golang spec](https://go.dev/ref/spec#Comments) comment section:

```
General comments start with the character sequence /* and stop with the first subsequent character sequence */.
```

The comment start when encounter "/*" and stop when encounter "*/". Could you use `//` instead? If you are using vscode, `Command + /` can comment out the selected lines.

**Comment by lirtistan** [comment] 2024-12-27 20:23
Hi @h9jiang,

iam aware of the block comment shortcut in vscode, i use it to comment blocks of unused code (frequently). 

But golang also understands `/* general comments */` as you mentioned already, so they should work too, don't you think!?

Iam not inside the vscode code base, but  such general comment tokens can just happen outside of a string or as part or a string, so if the lexer/scanner runs over the document it should be aware of such occurences.

But this is a bug in both vscode and golang, a simple program like this...

```go main.go
package main

import (
	"fmt"
)

func main() {
	/*
	fmt.Println("*/")
	*/
}
```

...won't compile.

**Comment by findleyr** [comment] 2024-12-27 21:25
@lirtistan as you say, that is not valid Go code. The spec is clear about how "general comments" work:
https://go.dev/ref/spec#Comments

Why do you think this is a bug?  This is also how block comments behave in other languages with C-style syntax.

Closing as this is working as intended.

**Closed by findleyr** 2024-12-27 21:25 UTC
Labels: WaitingForInfo

**Comment by firelizzard18** [comment] 2024-12-27 21:38
When the parser encounters `/*` outside of a string it enters "block comment mode"; not literally, but close enough for this discussion. As long as it's in "block comment mode", it ignores any and all characters it encounters until it sees `*/`. You are asking for the compiler to interpret Go code or at the least quoted strings within a block comment and to ignore `*/` found within a quoted string. But block comments are allowed to contain _anything_ (except `*/`) so detecting and handling quoted strings is a rather problematic proposal.

**Comment by findleyr** [comment] 2024-12-27 21:44
As @firelizzard18 said, it would be rather complicated to even propose such a change to the Go spec.

But regardless, this is not the forum to propose changes to the language, and even if it *were*, this aspect of the language is set in stone.

**Comment by lirtistan** [comment] 2024-12-27 21:47
As i started this issue (days ago), it looked like an vscode extension issue, i wasn't aware of how golang(s) is handling block comments (iam new to golang).

However, sorry for the trouble i caused.

**Comment by findleyr** [comment] 2024-12-27 21:51
> However, sorry for the trouble i caused.

No problem at all.
