### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by marwan-at-work** [golang/vscode-go#768] opened 2020-10-10 14:16 UTC
gopls version: (devel)
commit: 
```
marwansulaiman@Marwans-MBP-2 tools % git log -1
commit fcf82128ed91fc9924ee9daba0d9816af1936ff9 (HEAD -> master, origin/master, origin/HEAD)
Author: Rebecca Stambler <rstambler@golang.org>
Date:   Thu Oct 8 20:50:07 2020 -0400

    internal/lsp/source: handle a possible nil pointer in call hierarchy
```
gopls flags: 

```
"usePlaceholders": true,
"experimentalWorkspaceModule": true
```

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

This happens when I open go.mod and go.sum 

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17d3ff1]

goroutine 164 [running]:
golang.org/x/tools/internal/lsp.(*Server).semanticTokensRange(0xc0000fcb00, 0x1af8e00, 0xc00024a880, 0xc0009c0050, 0x0, 0x0, 0xc000fbf550)
	  semantic.go:44  0x191
golang.org/x/tools/internal/lsp.(*Server).SemanticTokensRange(0xc0000fcb00, 0x1af8e00, 0xc00024a880, 0xc0009c0050, 0xc0009c0050, 0x0, 0x0)
	  server_gen.go:176  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1af8e00, 0xc00024a880, 0x1b0cd20, 0xc0000fcb00, 0xc001506de0, 0x1af9040, 0xc00024a7c0, 0x0, 0x1ae6240, 0xc000fbf340)
	  tsserver.go:253  0x5f92
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1af8e00, 0xc00024a880, 0xc001506de0, 0x1af9040, 0xc00024a7c0, 0x2a2257dc, 0x1f5ab40)
	  protocol.go:63  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1af8e00, 0xc00024a880, 0xc001506de0, 0x1af9040, 0xc00024a7c0, 0x0, 0x0)
	  lsprpc.go:557  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1af8e00, 0xc00024a880, 0xc000349c20, 0x1af9040, 0xc00024a7c0, 0x1f5b00001f5b, 0x1f5d00001f5d)
	  handler.go:35  0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc000292420, 0xc000276600, 0xc000a022d0, 0x1af8e00, 0xc00024a880, 0xc000349c20, 0x1af9040, 0xc00024a7c0)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 10:12:41 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

```
goroutine 3873 [running]:
golang.org/x/tools/internal/lsp.(*Server).semanticTokensFull(0xc00015cbb0, 0x1af8e00, 0xc00272c240, 0xc002cf0bd0, 0x0, 0x0, 0xc00395b4a0)
	/Users/marwansulaiman/marwan/tools/internal/lsp/semantic.go:28 +0x2d7
golang.org/x/tools/internal/lsp.(*Server).SemanticTokensFull(0xc00015cbb0, 0x1af8e00, 0xc00272c240, 0xc002cf0bd0, 0xc002cf0bd0, 0x0, 0x0)
	/Users/marwansulaiman/marwan/tools/internal/lsp/server_gen.go:168 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1af8e00, 0xc00272c240, 0x1b0cd20, 0xc00015cbb0, 0xc002cf0ba0, 0x1af9040, 0xc002271f80, 0x0, 0x1ae6240, 0xc00395b340)
	/Users/marwansulaiman/marwan/tools/internal/lsp/protocol/tsserver.go:239 +0x4d13
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1af8e00, 0xc00272c240, 0xc002cf0ba0, 0x1af9040, 0xc002271f80, 0x94ed65eb, 0x1f5ab40)
	/Users/marwansulaiman/marwan/tools/internal/lsp/protocol/protocol.go:63 +0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1af8e00, 0xc00272c240, 0xc002cf0ba0, 0x1af9040, 0xc002271f80, 0x0, 0x0)
	/Users/marwansulaiman/marwan/tools/internal/lsp/lsprpc/lsprpc.go:557 +0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1af8e00, 0xc00272c240, 0xc006bca8c0, 0x1af9040, 0xc002271f80, 0xc00628f720, 0x2)
	/Users/marwansulaiman/marwan/tools/internal/jsonrpc2/handler.go:35 +0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc005279860, 0xc0056caa20, 0xc0008b02d0, 0x1af8e00, 0xc00272c240, 0xc006bca8c0, 0x1af9040, 0xc002271f80)
	/Users/marwansulaiman/marwan/tools/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/Users/marwansulaiman/marwan/tools/internal/jsonrpc2/handler.go:100 +0x173
[Info  - 10:14:52 AM] Connection to server got closed. Server will restart.
[Error - 10:14:52 AM] Request textDocument/semanticTokens/full failed.
```

```
[Info  - 10:14:52 AM] Connection to server got closed. Server will restart.
[Error - 10:14:52 AM] Request textDocument/semanticTokens/full failed.
Error: Connection got disposed.
	at Object.dispose (/Users/marwansulaiman/.vscode/extensions/golang.go-nightly-2020.10.812/dist/goMain.js:74022:27)
	at Object.dispose (/Users/marwansulaiman/.vscode/extensions/golang.go-nightly-2020.10.812/dist/goMain.js:10691:35)
	at LanguageClient.handleConnectionClosed (/Users/marwansulaiman/.vscode/extensions/golang.go-nightly-2020.10.812/dist/goMain.js:12932:42)
	at LanguageClient.handleConnectionClosed (/Users/marwansulaiman/.vscode/extensions/golang.go-nightly-2020.10.812/dist/goMain.js:48371:15)
	at closeHandler (/Users/marwansulaiman/.vscode/extensions/golang.go-nightly-2020.10.812/dist/goMain.js:12919:18)
	at CallbackList.invoke (/Users/marwansulaiman/.vscode/extensions/golang.go-nightly-2020.10.812/dist/goMain.js:22271:39)
	at Emitter.fire (/Users/marwansulaiman/.vscode/extensions/golang.go-nightly-2020.10.812/dist/goMain.js:22333:36)
	at closeHandler (/Users/marwansulaiman/.vscode/extensions/golang.go-nightly-2020.10.812/dist/goMain.js:73268:26)
	at CallbackList.invoke (/Users/marwansulaiman/.vscode/extensions/golang.go-nightly-2020.10.812/dist/goMain.js:22271:39)
	at Emitter.fire (/Users/marwansulaiman/.vscode/extensions/golang.go-nightly-2020.10.812/dist/goMain.js:22333:36)
	at StreamMessageWriter.fireClose (/Users/marwansulaiman/.vscode/extensions/golang.go-nightly-2020.10.812/dist/goMain.js:72861:27)
	at Socket.<anonymous> (/Users/marwansulaiman/.vscode/extensions/golang.go-nightly-2020.10.812/dist/goMain.js:72894:42)
	at Socket.emit (events.js:223:5)
	at Socket.EventEmitter.emit (domain.js:475:20)
	at Pipe.<anonymous> (net.js:664:12)
```

**Comment by stamblerre** [comment] 2020-10-10 16:09
Duplicate of #41873

**Closed by stamblerre** 2020-10-10 16:10 UTC
