### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by tcagan** [golang/vscode-go#726] opened 2020-10-01 11:24 UTC
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Trying to install go tools as per popup suggested. The installation progressed but eventually crushed. I will note that I clicked "Install all tools" and then install for the gopls (two popup windows)

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 42 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x22e
golang.org/x/tools/internal/lsp/debug.section(0xed2840, 0xc0004a5830, 0x0, 0xd5849b, 0x7, 0xc0004a0f18)
	  info.go:69  0x319
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xee6840, 0xc000240e80, 0xed2840, 0xc0004a5830, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc000252320, 0xee6840, 0xc000240e80, 0xc000176c00, 0x0, 0x0, 0x0)
	  general.go:87  0x58b
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc000252320, 0xee6840, 0xc000240e80, 0xc000176c00, 0xc000176c00, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xee6840, 0xc000240e80, 0xf019c0, 0xc000252320, 0xc000489860, 0xee6a80, 0xc000240e00, 0x0, 0x0, 0x0)
	  tsserver.go:235  0x4bb
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xee6840, 0xc000240e80, 0xc000489860, 0xee6a80, 0xc000240e00, 0x0, 0xbfd58cd1f0fa05f7)
	  protocol.go:63  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xee6840, 0xc000240e80, 0xc000489860, 0xee6a80, 0xc000240e00, 0x0, 0x0)
	  lsprpc.go:557  0x420
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xee6840, 0xc000240e80, 0xc000201a80, 0xee6a80, 0xc000240e00, 0x40771f, 0xc0002a84d8)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00020e540, 0xc00024ea20, 0xc000206fe0, 0xee6840, 0xc000240e80, 0xc000201a80, 0xee6a80, 0xc000240e00)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Error - 7:21:43 AM] </pre>

**Comment by hyangah** [comment] 2020-10-01 13:07
@tcagan thanks for the report. This is a duplicate of https://github.com/golang/vscode-go/issues/713.

**Closed by hyangah** 2020-10-01 13:07 UTC
