### ISSUE TITLE
Automatic conversion of positional struct initialization to named

### ISSUE THREAD

**Issue by harriblex** [golang/vscode-go#2274] opened 2022-06-03 17:55 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice to have an option to automatically convert positional initialization of a struct to named arguments initialization. 

**Describe the solution you'd like**
Have an option to perform the automatic conversion, selectable from the right click refactor options.

**Describe alternatives you've considered**
-N/A

**Additional context**
Automatic conversion of the "example" struct initialization style to the "example2" style shown in the screenshot.
![example](https://user-images.githubusercontent.com/106833687/171919663-00faaa69-a542-45b6-8496-874c52171bdc.png)

**Comment by findleyr** [comment] 2022-06-09 16:55
This looks like a dupe of https://github.com/golang/go/issues/53062. Closing in favor of the gopls issue.

**Closed by findleyr** 2022-06-09 16:55 UTC
Labels: FeatureRequest
