### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by qiuyuzhou** [golang/vscode-go#2329] opened 2022-07-10 16:10 UTC
gopls version: v0.9.0 (go1.18.1)
gopls flags: 
update flags: proxy
extension version: 0.34.0
go version: 1.18.1
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Sun, 10 Jul 2022 16:09:52 GMT
restart history:
Sat, 25 Jun 2022 09:01:16 GMT: activation (enabled: true)
Thu, 07 Jul 2022 09:11:33 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x10444a818]

goroutine 23211 [running]:
golang.org/x/tools/internal/xcontext.detachedContext.Value(...)
	  xcontext.go:23
golang.org/x/tools/internal/lsp/debug.GetInstance({0x104e18e40%3F, 0x14027caaa70%3F})
	  serve.go:361  0x44
golang.org/x/tools/internal/lsp/debug.makeGlobalExporter.func1({0x104e18e40, 0x14027caaa70}, {{0xc0aadc4f1d94e810, 0x2bbe233c8, 0x105321780}, {{{0x104e17b70, 0x140001340e0}, 0xa, {0x104ce1720, 0x104a046b5}}, ...}, ...}, ...)
	  serve.go:571  0x58
golang.org/x/tools/internal/event/core.deliver({0x104e18e40, 0x14027caaa70}, 0x140005249c0, {{0xc0aadc4f1d94e810, 0x2bbe233c8, 0x105321780}, {{{0x104e17b70, 0x140001340e0}, 0xa, {0x104ce1720, ...}}, ...}, ...})
	  export.go:45  0xac
golang.org/x/tools/internal/event/core.ExportPair({_, _}, {{0x0, 0x0, 0x0}, {{{0x104e17b70, 0x140001340e0}, 0xa, {0x104ce1720, 0x104a046b5}}, ...}, ...}, ...)
	  export.go:68  0xc4
golang.org/x/tools/internal/event.Start({0x104e18e40%3F, 0x14027caaa70%3F}, {0x104a046b5%3F, 0x1401db523a0%3F}, {0x14028638e60%3F, 0x0%3F, 0x0%3F})
	  event.go:91  0x1e8
golang.org/x/tools/internal/jsonrpc2.(*conn).Notify(0x1401db523a0%3F, {0x104e18e40, 0x14027caaa70}, {0x104a046b5, 0xa}, {0x104cc4000%3F, 0x1401db523a0%3F})
	  conn.go:85  0x258
golang.org/x/tools/internal/lsp/protocol.clientConn.Notify(...)
	  protocol.go:60
golang.org/x/tools/internal/lsp/protocol.(*clientDispatcher).Progress(0x104da5980%3F, {0x104e18e40%3F, 0x14027caaa70%3F}, 0x140266ee900%3F)
	  tsclient.go:168  0x4c
golang.org/x/tools/internal/lsp/progress.(*WorkDone).Report(0x14028638960, {0x0%3F, 0x0%3F}, {0x1402819b100, 0x31}, 0x0)
	  progress.go:188  0x2b8
golang.org/x/tools/internal/lsp/progress.(*WorkDoneWriter).Write(0x1401ddaa3e0%3F, {0x140281cc000%3F, 0x31, 0x31%3F})
	  progress.go:268  0x60
io.(*multiWriter).Write(0x14027ee8d48%3F, {0x140281cc000, 0x31, 0x8000})
	  multi.go:60  0x90
io.copyBuffer({0x104e12418, 0x14027c9e8d0}, {0x104e128b8, 0x14027ee8d48}, {0x0, 0x0, 0x0})
	  io.go:428  0x1a8
io.Copy(...)
	  io.go:385
os/exec.(*Cmd).writerDescriptor.func1()
	  exec.go:311  0x48
os/exec.(*Cmd).Start.func1(0x14026978360%3F)
	  exec.go:441  0x30
created by os/exec.(*Cmd).Start
	  exec.go:440  0x5bc
[Error - 00:09:32] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2022-07-11 14:41
Thank you. This looks like a dupe of #2325. Closing in favor of the earlier report.

**Closed by findleyr** 2022-07-11 14:41 UTC
