### ISSUE TITLE
More helpful error message when trying to debug with wrong GOOS and GOARCH

### ISSUE THREAD

**Issue by Cookie04DE** [golang/vscode-go#1090] opened 2021-01-09 10:45 UTC
**Is your feature request related to a problem? Please describe.**
If you set the GOOS to `js` and the GOARCH to `wasm` in settings.json under `"go.toolsEnvVars"` and you try to debug your go application you get this cryptic error: `could not launch process: not an executable file
Process exiting with code: 1`
I tried to google this, but found nothing helpful.
**Describe the solution you'd like**
It would be nice if a more helpful error would be displayed. The current one  doesn't explain that you have the wrong GOOS and GOARCH, so it can't debug.

**Comment by hyangah** [comment] 2021-01-12 18:12
@Cookie04DE Thanks for the report. This is a duplicate of https://github.com/golang/vscode-go/issues/114 - let's follow up there.

**Closed by hyangah** 2021-01-12 18:12 UTC
