### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Mupia** [golang/vscode-go#3313] opened 2024-04-04 07:11 UTC
gopls version: v0.15.2/go1.20.4
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Thu, 04 Apr 2024 07:08:20 GMT
restart history:
Thu, 04 Apr 2024 07:08:13 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.0" (should be something like "go1.12")

goroutine 3845 [running]:
go/types.NewChecker(0x140007bd1d0%3F, 0x14002a37680, 0x14004d11e50, 0x0%3F)
	  check.go:237  0x1e8
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0x14001f12c60, {0x140041cdd38, 0x1, 0x1})
	  analysis.go:1028  0x5fc
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0x14001f12c60, {0x10147e998%3F, 0x140045a2360})
	  analysis.go:810  0x1d4
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0x14001f12c60, {0x10147e998%3F, 0x140045a2360})
	  analysis.go:672  0x104
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xa4
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa0
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 1881,
    "TestdataFiles": 1,
    "GoFiles": 53,
    "ModFiles": 1,
    "Dirs": 268
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.20.4",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "761.051542ms",
  "MemStats": {
    "HeapAlloc": 36603544,
    "HeapInUse": 59318272,
    "TotalAlloc": 444415120
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2109,
      "Largest": 596167,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.2",
        "AllPackages": {
          "Packages": 380,
          "LargestPackage": 155,
          "CompiledGoFiles": 2132,
          "Modules": 72
        },
        "WorkspacePackages": {
          "Packages": 17,
          "LargestPackage": 17,
          "CompiledGoFiles": 79,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by timothy-king** [comment] 2024-04-04 20:56
Duplicate of https://github.com/golang/go/issues/66636. Fix is expected to be in gopls@v0.15.3. Workaround is to reinstall gopls with go1.21+.

**Closed by timothy-king** 2024-04-04 20:56 UTC
