### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by supernomad** [golang/vscode-go#709] opened 2020-09-30 12:37 UTC
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 104 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x233
golang.org/x/tools/internal/lsp/debug.section(0xec5e40, 0xc000533980, 0x0, 0xd98f28, 0x7, 0xc00052ef28)
	  info.go:69  0x322
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xed9d60, 0xc0004ee540, 0xec5e40, 0xc000533980, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc0004f2280, 0xed9d60, 0xc0004ee540, 0xc000520000, 0x0, 0x0, 0x0)
	  general.go:87  0x585
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc0004f2280, 0xed9d60, 0xc0004ee540, 0xc000520000, 0xc000520000, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xed9d60, 0xc0004ee540, 0xeed8e0, 0xc0004f2280, 0xc0005139b0, 0xed9fa0, 0xc0004ee4c0, 0x0, 0xec7680, 0xc000516000)
	  tsserver.go:235  0x4d2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xed9d60, 0xc0004ee540, 0xc0005139b0, 0xed9fa0, 0xc0004ee4c0, 0xb17ead, 0x132dce0)
	  protocol.go:63  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xed9d60, 0xc0004ee540, 0xc0005139b0, 0xed9fa0, 0xc0004ee4c0, 0x0, 0x0)
	  lsprpc.go:557  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xed9d60, 0xc0004ee540, 0xc0004c98c0, 0xed9fa0, 0xc0004ee4c0, 0x407fc5, 0xc000390238)
	  handler.go:35  0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0002a6d80, 0xc000598210, 0xc0004ec140, 0xed9d60, 0xc0004ee540, 0xc0004c98c0, 0xed9fa0, 0xc0004ee4c0)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 8:35:57 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by supernomad** [comment] 2020-09-30 12:37
so go is absolutely in my path

**Comment by hyangah** [comment] 2020-09-30 12:40
@supernomad thanks for the report. Can you please share the result of the 
`Go: Locate Go Tools` vscode command  (from Command Palette)?

**Comment by hyangah** [comment] 2020-09-30 13:40
I think this is a duplicate of https://github.com/golang/vscode-go/issues/707#issuecomment-701393791. 

Please follow the workaround instruction for now.

**Closed by hyangah** 2020-09-30 13:40 UTC
Labels: WaitingForInfo
