### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by tomisetsu** [golang/vscode-go#3568] opened 2024-10-17 11:36 UTC
gopls version: v0.16.2/go1.22.1
gopls flags: 
update flags: proxy
extension version: 0.42.1
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Thu, 17 Oct 2024 11:36:02 GMT
restart history:
Thu, 17 Oct 2024 08:40:47 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1029f84e0]

goroutine 5258 [running]:
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0x1400515e0d0, {0x140044f2408, 0x77, 0x77})
	  analysis.go:1088  0x890
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0x1400515e0d0, {0x1030923c8, 0x14005ddd920})
	  analysis.go:835  0x174
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0x1400515e0d0, {0x1030923c8, 0x14005ddd920})
	  analysis.go:694  0x100
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:402  0xa4
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 5255
	  errgroup.go:75  0x98
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 1924,
    "TestdataFiles": 178,
    "GoFiles": 1258,
    "ModFiles": 1,
    "Dirs": 325
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.1",
  "GoplsVersion": "v0.16.2",
  "InitialWorkspaceLoadDuration": "1.563789791s",
  "MemStats": {
    "HeapAlloc": 156123096,
    "HeapInUse": 218783744,
    "TotalAlloc": 1631681736
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 3170,
      "Largest": 5961550,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.1",
        "AllPackages": {
          "Packages": 626,
          "LargestPackage": 155,
          "CompiledGoFiles": 4390,
          "Modules": 65
        },
        "WorkspacePackages": {
          "Packages": 243,
          "LargestPackage": 129,
          "CompiledGoFiles": 2017,
          "Modules": 1
        },
        "Diagnostics": 2067
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-10-24 18:34
Hi, this is a dupe of golang/go#64227.

Are you using bazel, by any chance?

**Closed by findleyr** 2024-10-24 18:34 UTC
Labels: FrozenDueToAge
