### ISSUE TITLE
Support doc links for documentation previews as defined in https://go.dev/doc/comment

### ISSUE THREAD

**Issue by Splizard** [golang/vscode-go#3230] opened 2024-03-07 02:03 UTC
Go documentation comments recently added support for Doc Links, which refer to exported identifiers from either within the same package or an imported package.

When highlighting a Go identifier, these Doc Links should be displayed as clickable links that jump to the referenced identifier. They should also be highlightable within the comment themselves, so that the referenced identifier can be jumped to.

```go
package main

type MyString string

// DoSomething prints "Hello World" as a [MyString]
//                                        ^ this should be highlightable
func DoSomething() {
    fmt.Println(MyString("Hello World"))
}
```

**Comment by adonovan** [comment] 2024-03-07 21:47
We agree! This is essentially a duplicate of https://github.com/golang/go/issues/64648, of which the first part (semantic token support) was merged today, and the second part (hover and definition support) is currently in review.

**Closed by adonovan** 2024-03-07 21:47 UTC
Labels: Documentation
