### ISSUE TITLE
Cannot install, cached Go version ({"binaryPath":"/snap/bin/go","version":""}) is invalid, recomputing

### ISSUE THREAD

**Issue by JoseFMP** [golang/vscode-go#627] opened 2020-09-10 10:58 UTC
In VS Code, when trying to install the extension (v0.16.2) the OUTPUT promps this: 
```
cached Go version ({"binaryPath":"/snap/bin/go","version":""}) is invalid, recomputing
```

And keeps printing the same line eternally.
![image](https://user-images.githubusercontent.com/24405049/92720696-2a134400-f38f-11ea-8dac-659db901cf88.png)

**Comment by hyangah** [comment] 2020-09-10 12:37
@JoseFMP Thanks for the report.

This is a duplicate of https://github.com/golang/vscode-go/issues/166.
@gildas and @dim shared a workaround https://github.com/golang/vscode-go/issues/166#issuecomment-688000742

**Closed by hyangah** 2020-09-10 12:37 UTC
