### ISSUE TITLE
Unable to click/navigate to failed test location on the test error output

### ISSUE THREAD

**Issue by uudashr** [golang/vscode-go#2511] opened 2022-10-28 01:36 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.19.2 darwin/arm64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- v0.9.5
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.72.2 d045a5eda657f4d7b676dedbfa7aab8207f8a075
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.35.2
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.

Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/nuruddin.ashr/go
GOROOT: /opt/homebrew/Cellar/go/1.19.2/libexec
PATH: /Users/nuruddin.ashr/.yarn/bin:/Users/nuruddin.ashr/.config/yarn/global/node_modules/.bin:/Users/nuruddin.ashr/.nvm/versions/node/v18.10.0/bin:/opt/homebrew/lib/ruby/gems/3.1.0/bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/nuruddin.ashr/.cargo/bin:/Users/nuruddin.ashr/Applications/flutter/bin:/Users/nuruddin.ashr/go/bin

	go:	/opt/homebrew/bin/go: go version go1.19.2 darwin/arm64

	gotests:	/Users/nuruddin.ashr/go/bin/gotests	(version: v1.6.0 built with go: go1.19.2)
	gomodifytags:	/Users/nuruddin.ashr/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.19.2)
	impl:	/Users/nuruddin.ashr/go/bin/impl	(version: v1.1.0 built with go: go1.19.2)
	goplay:	/Users/nuruddin.ashr/go/bin/goplay	(version: v1.0.0 built with go: go1.19.2)
	dlv:	/Users/nuruddin.ashr/go/bin/dlv	(version: v1.9.1 built with go: go1.19.2)
	staticcheck:	/Users/nuruddin.ashr/go/bin/staticcheck	(version: v0.3.3 built with go: go1.19.1)
	gopls:	/Users/nuruddin.ashr/go/bin/gopls	(version: v0.10.0 built with go: go1.19.2)

go env
Workspace Folder (hello): /Users/nuruddin.ashr/temp/hello
	GO111MODULE=""
	GOARCH="arm64"
	GOBIN=""
	GOCACHE="/Users/nuruddin.ashr/Library/Caches/go-build"
	GOENV="/Users/nuruddin.ashr/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="arm64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/nuruddin.ashr/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/nuruddin.ashr/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/opt/homebrew/Cellar/go/1.19.2/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.2/libexec/pkg/tool/darwin_arm64"
	GOVCS=""
	GOVERSION="go1.19.2"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/nuruddin.ashr/temp/hello/go.mod"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jb/7d_d4kn14pd26s66z0f7ds6w0000gr/T/go-build4257192567=/tmp/go-build -gno-record-gcc-switches -fno-common"
	
	

</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```json
{
    "go.useLanguageServer": true,
    "go.toolsManagement.autoUpdate": true,
    "gopls": {
        "ui.semanticTokens": true
    },
}
```

### Describe the bug
The failed test file path and the line number shown on the test output, but it can't be clicked. Doesn't work with cmd+click either.
I remember it we should be able to click the file path so we can easily navigate to the location of the failed test.

### Steps to reproduce the behavior:
1. Use this below code
```go
package hello_test

import "testing"

func TestHello(t *testing.T) {
	t.Error("Opps")
}

```
3. Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Test package` command.
4. See output
```
Running tool: /opt/homebrew/bin/go test -timeout 30s -coverprofile=/var/folders/jb/7d_d4kn14pd26s66z0f7ds6w0000gr/T/vscode-goK6TihG/go-code-cover github.com/uudashr/hello

--- FAIL: TestHello (0.00s)
    /Users/nuruddin.ashr/temp/hello/hello_test.go:6: Opps
FAIL
coverage: [no statements]
FAIL	github.com/uudashr/hello	0.231s
FAIL

```

### Screenshots or recordings
As we can see, the file path is not clickable

https://user-images.githubusercontent.com/166053/198441014-bf98b17a-a26d-4cbf-b717-71a2c7092ee9.mov

**Comment by findleyr** [comment] 2022-10-31 19:59
Hmm, this doesn't reproduce on my (Linux) machine:
![image](https://user-images.githubusercontent.com/57144380/199099370-5fb2a2f9-2832-4986-8a23-c3f9e7fd3ddb.png)

@hyangah @suzmue any idea what could lead to this behavior?

**Comment by suzmue** [comment] 2022-10-31 20:24
The links are coming VS Code not the Go extension. I see that the path for the test file is outside of the workspace folder in a directory labeled temp. 

@uudashr Is the full path of the file that you have open in VS Code /Users/nuruddin.ashr/temp/hello/hello_test.go? or is it in your workspace folder (for example /Users/nuruddin.ashr/Projects/ddd/numongo/hello/hello_test.go)

**Comment by uudashr** [comment] 2022-11-01 05:53
I've edited the details. But the result is the same, I still cannot click the filepath.

VSCode change its implementation so the filepath is not clickable anymore? Is there anything that we can do?

**Comment by hyangah** [comment] 2022-11-01 14:32
I cannot reproduce this either.
As @suzmue pointed out, the original report involved two different paths. Is there any chance symlinks are involved? 

https://github.com/microsoft/vscode/issues/163778 seems related.

**Comment by uudashr** [comment] 2022-11-01 23:01
I already update the info based on @suzmue findings, and reproduce the problem.
@hyangah when you said you can't reproduce it means in your case the filepath shown on test error output is clickable?

**Comment by hyangah** [comment] 2022-11-02 03:12
Yes, same as @findleyr shared, i could click the file path (cmd+click on mac, ctrl+click on linux). Do you mean you want the links to be clickable without needing to press ctrl or cmd key? I dont know if that ever worked. If you believe that was changed, please open an issue in the vscode issue tracker, mentioning go extension maintainers sent you there.

**Comment by uudashr** [comment] 2022-11-03 11:35
FUI I found that [React Native Tools extension](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native) not working well with Go extension

**Comment by findleyr** [comment] 2022-11-03 16:38
Thanks for investigating. I don't think there's anything we can do to work around this on our end; please file an issue with that extension and let us know if you discover anything we can do to work around this.

Closing for now.

**Closed by findleyr** 2022-11-03 16:38 UTC
Labels: NeedsInvestigation, WaitingForInfo, go-test

**Comment by uudashr** [comment] 2022-11-05 12:32
FYI I report the the issue here https://github.com/microsoft/vscode-react-native/issues/1854
