### ISSUE TITLE
Spaces at start of line are eaten, even in literals

### ISSUE THREAD

**Issue by Rufflewind** [golang/vscode-go#2989] opened 2023-09-24 05:40 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.21.1 windows/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- (not installed)
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.80.0
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.39.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- (skipped)
</details>

### Share the Go related settings you have added/edited

(Default settings)

### Describe the bug

Spaces get eaten if you try to paste them at the beginning of the line, even in the middle of a string literal.

### Steps to reproduce the behavior:

 1. Open a Go file.

 2. Create a multiline string literal like:

    ```go
    var s = `
    quick  brown
    fox
    `
    ```

 3. Select the double space between `quick` and `brown` and copy it using Ctrl+C.

 4. Move the cursor to the beginning of the `fox` and paste using Ctrl+V.

### Expected result

```go
var s = `
quick  brown
  fox
`
```

### Actual result

(nothing happens)

```go
var s = `
quick  brown
fox
`
```

### Screenshots or recordings

N/A

**Comment by findleyr** [comment] 2023-09-25 16:24
Wow, I can reproduce and that's odd.  One observation: if you undo (ctrl-z) immediately following the paste, you can under the auto-formatting, and get the expected result.

Notably, I tried setting `"editor.formatOnPaste": false`, and that didn't fix it.

I can't find logic in the extension that would do this, so I think it may be a VS Code bug.  @hyangah or @suzmue may know better.

**Comment by hyangah** [comment] 2023-09-25 16:52
Looks like I can reproduce the issue when I disable the go extension. This looks like a vscode issue

**Comment by findleyr** [comment] 2023-09-25 19:56
Thanks @hyangah. Then I'll close this as this is unfortunately not fixable on our end. @Rufflewind I suggest opening a VS Code issue.

**Closed by findleyr** 2023-09-25 19:56 UTC

**Comment by Rufflewind** [comment] 2023-09-26 03:48
Created https://github.com/microsoft/vscode/issues/194085
