### ISSUE TITLE
installation: unable to install gopls/v0.5.0

### ISSUE THREAD

**Issue by jorschac** [golang/vscode-go#694] opened 2020-09-27 13:35 UTC
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

I m opening my old go codes on my new laptop, while a warning popped out saying that gopls cant initialize.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

--------------
Message: unsupported URI scheme:  (gopls only supports file URIs)
------------------

when I run GO: install/Update Tools, installing failed, and the err message says that:
---------------------
Tools environment: GOPATH=/Users/han/go
Installing 1 tool at /Users/han/go/bin in module mode.
  gopls@0.5.0

Installing golang.org/x/tools/gopls@v0.5.0@0.5.0 FAILED

1 tools failed to install.

gopls: failed to install gopls(golang.org/x/tools/gopls@v0.5.0@0.5.0): Error: Command failed: /usr/local/go/bin/go get -v golang.org/x/tools/gopls@v0.5.0
go: finding golang.org/x v0.5.0
go: finding golang.org v0.5.0
go: finding golang.org/x/tools v0.5.0
go: finding golang.org/x/tools/gopls v0.5.0
go get golang.org/x/tools/gopls@v0.5.0: golang.org/x/tools/gopls@v0.5.0: Get https://proxy.golang.org/golang.org/x/tools/gopls/@v/v0.5.0.info: dial tcp 34.64.4.81:443: i/o timeout
 undefined
-------------------------

I reset my gopath from "go env" in VScode settings and try everything again but the issues are still there

BY THE WAY: I checked http request to GET https://proxy.golang.org/golang.org/x/tools/gopls/@v/v0.5.0.info. The err code is 410, which means the resources it want to fetch is removed somehow

**Comment by stamblerre** [comment] 2020-09-27 15:56
Closing, as the issue is empty.

@jorschac: Can you please check your `gopls` version (`gopls version`)? It should be `v0.5.0`--if it's not, you can update by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools". Also, the latest version of this extension is 0.17.0, so please update if you are not using that version.

Please reopen if you can share the stack trace of the gopls crash (found by navigating to View -> Output -> Tasks -> gopls (server)).

**Comment by jorschac** [comment] 2020-09-29 19:29
> Closing, as the issue is empty.
> 
> @jorschac: Can you please check your `gopls` version (`gopls version`)? It should be `v0.5.0`--if it's not, you can update by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools". Also, the latest version of this extension is 0.17.0, so please update if you are not using that version.
> 
> Please reopen if you can share the stack trace of the gopls crash (found by navigating to View -> Output -> Tasks -> gopls (server)).
 
I updated all information, please reopen it

**Comment by stamblerre** [comment] 2020-09-29 20:07
Can you please share the output of `go env`?

**Comment by jorschac** [comment] 2020-09-29 20:11
> Can you please share the output of `go env`?

here it is:

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/han/Library/Caches/go-build"
GOENV="/Users/han/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/han/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="/usr/bin/clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lp/g5m3gzsn529by64s58d5wms00000gn/T/go-build111952491=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by stamblerre** [comment] 2020-09-29 20:15
It looks like you may be unable to access proxy.golang.org (for example, https://proxy.golang.org is unavailable in China). Please try configuring your `GOPROXY` to point to a different proxy.

**Comment by jorschac** [comment] 2020-09-29 20:23
> It looks like you may be unable to access proxy.golang.org (for example, https://proxy.golang.org is unavailable in China). Please try configuring your `GOPROXY` to point to a different proxy.

fixed thank you

**Closed** 2020-09-29 20:24 UTC
