### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by paulosimao-dc** [golang/vscode-go#2082] opened 2022-02-24 11:30 UTC
gopls version: v0.7.5
gopls flags: 
update flags: proxy
extension version: 0.31.1
go version: 1.18rc1
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Thu, 24 Feb 2022 11:30:29 GMT
restart history:
Thu, 24 Feb 2022 11:13:12 GMT: activation (enabled: true)
Thu, 24 Feb 2022 11:22:25 GMT: manual (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Crash

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100ab1b54]

goroutine 121 [running]:
golang.org/x/tools/internal/lsp/cache.parseGoWork({0x100f23058, 0x1400029c810}, {0x14000732140, 0x4e}, {0x140002083c0%3F, 0x14000732147%3F}, {0x1400072ae00, 0x0, 0x200}, {0x100f1cae8, ...})
	  workspace.go:503  0x1d4
golang.org/x/tools/internal/lsp/cache.parseExplicitWorkspaceFile({0x100f23058, 0x1400029c810}, {0x14000732140, 0x4e}, {0x100f1cae8%3F, 0x1400057d980%3F}, 0x14000498720)
	  workspace.go:150  0x15c
golang.org/x/tools/internal/lsp/cache.newWorkspace({0x100f23058, 0x1400029c810}, {0x14000732140, 0x4e}, {0x100f1cae8, 0x1400057d980}, 0x14000498720, 0x0, 0x0)
	  workspace.go:93  0x44
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0x1400057d980, {0x100f23058%3F, 0x1400029c810}, {0x1400035cbb0, 0xc}, {0x14000156730, 0x4e}, {0x14000042360, 0x51}, 0x140000c3d40, ...)
	  session.go:197  0x228
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0x1400057d980, {0x100f23058, 0x1400029c810}, {0x1400035cbb0, 0xc}, {0x14000156730, 0x4e}, {0x14000042360, 0x51}, 0x0%3F)
	  session.go:166  0x1c0
golang.org/x/tools/internal/lsp.(*Server).addView(0x140001d4d80, {0x100f23058, 0x1400029c810}, {0x1400035cbb0, 0xc}, {0x14000156730, 0x4e})
	  workspace.go:59  0x304
golang.org/x/tools/internal/lsp.(*Server).addFolders(0x140001d4d80, {0x100f23058%3F, 0x1400029c810}, {0x140002b2d00, 0x8, 0x8%3F})
	  general.go:234  0x4e8
golang.org/x/tools/internal/lsp.(*Server).initialized(0x140001d4d80, {0x100f23058, 0x1400029c810}, 0x140005b01b0%3F)
	  general.go:186  0x2d4
golang.org/x/tools/internal/lsp.(*Server).Initialized(0x140000397d0%3F, {0x100f23058%3F, 0x1400029c810%3F}, 0x100de7220%3F)
	  server_gen.go:144  0x28
golang.org/x/tools/internal/lsp/protocol.serverDispatch({0x100f23058, 0x1400029c810}, {0x100f2caa8, 0x140001d4d80}, 0x140005b3ad0, {0x100f23250, 0x1400029c750})
	  tsserver.go:137  0x5c8
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1({0x100f23058, 0x1400029c810}, 0x140005b3ad0, {0x100f23250, 0x1400029c750})
	  protocol.go:154  0x70
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1({0x100f23058, 0x1400029c810}, 0x140005b3ad0, {0x100f23250%3F, 0x1400029c750%3F})
	  lsprpc.go:506  0x788
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x100f23058, 0x1400029c810}, 0x14000219068, {0x100f23250%3F, 0x1400029c750%3F})
	  handler.go:35  0xf4
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0x90
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x1dc
[Error - 8:30:21 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2022-02-25 16:24
Thanks for the report. @paulosimao-dc Do you experience the same issue when using `gopls` v0.8.0-pre.2?

 ```
 go1.18rc1 install golang.org/x/tools/gopls@v0.8.0-pre.2
 ```
 
As part of https://github.com/golang/go/issues/44696, the go.work parsing logic has changed a lot since v0.7.5.

**Comment by findleyr** [comment] 2022-03-04 18:53
CC @matloob

**Comment by findleyr** [comment] 2022-03-04 18:54
BTW: the latest version of gopls (v0.8.0) contains a new go.work parser. Can you please try it?

**Comment by paulosimao-dc** [comment] 2022-03-04 19:00
Sure
Sds,



*Paulo Simão*
+55 (31) 99868-3138
***@***.***
*digitalcircle.com.br* <https://digitalcircle.com.br>

**Comment by findleyr** [comment] 2022-03-07 19:46
I think this should be resolved in the latest version of gopls, so am tentatively closing. Please reopen if you discover that it reproduces.

**Closed by findleyr** 2022-03-07 19:46 UTC
Labels: WaitingForInfo
