### ISSUE TITLE
add multiple tags to "add tags to struct"

### ISSUE THREAD

**Issue by OneOfOne** [golang/vscode-go#1158] opened 2021-01-31 21:07 UTC
Sometimes you need different tags for the same field, for example `json:"x,omitempty" bigquery:"x"`, it'd be nice if the "add tags to struct" option was a menu that allowed multiple options.

I could to work on an implementation if the idea sounds acceptable.

**Comment by hyangah** [comment] 2021-02-01 16:12
@OneOfOne Thanks for volunteering! Is it a duplicate of https://github.com/golang/vscode-go/issues/905?

**Comment by OneOfOne** [comment] 2021-02-01 17:12
@hyangah I didn't see that before but yeah I guess it could work that way.

**Comment by hyangah** [comment] 2021-02-03 03:35
Thanks! I will close this issue in favor of the old issue. AFAIK, nobody is currently working on this. 😉

**Closed by hyangah** 2021-02-03 03:35 UTC
Labels: WaitingForInfo
