### ISSUE TITLE
"Error: TypeError: Cannot read property 'get' of undefined" after upgrading to 0.21.0 from 0.20.2

### ISSUE THREAD

**Issue by virtumonde** [golang/vscode-go#1108] opened 2021-01-21 13:17 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.15.6 darwin/amd64
- Run `gopls -v version` to get version of Gopls if you are using [the language server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).
	- zsh: command not found: gopls (not using gopls)
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- Version: 1.52.1
        Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
        Date: 2020-12-16T16:30:02.420Z
        Electron: 9.3.5
        Chrome: 83.0.4103.122
        Node.js: 12.14.1
        V8: 8.3.110.13-electron.0
        OS: Darwin x64 19.6.0
- Check your installed extensions to get the version of the VS Code Go extension
        - 0.21.0
- Run `go env` to get the go development environment details
          - GO111MODULE=""
          GOARCH="amd64"
          GOBIN=""
          GOCACHE="/Users/virtumonde/Library/Caches/go-build"
          GOENV="/Users/virtumonde/Library/Application Support/go/env"
          GOEXE=""
          GOFLAGS=""
          GOHOSTARCH="amd64"
          GOHOSTOS="darwin"
          GOINSECURE=""
          GOMODCACHE="/Users/virtumonde/go/pkg/mod"
          GONOPROXY=""
          GONOSUMDB=""
          GOOS="darwin"
          GOPATH="/Users/virtumonde/go"
          GOPRIVATE=""
          GOPROXY="https://proxy.golang.org,direct"
          GOROOT="/usr/local/Cellar/go/1.15.6/libexec"
          GOSUMDB="sum.golang.org"
          GOTMPDIR=""
          GOTOOLDIR="/usr/local/Cellar/go/1.15.6/libexec/pkg/tool/darwin_amd64"
          GCCGO="gccgo"
          AR="ar"
          CC="clang"
          CXX="clang++"
          CGO_ENABLED="1"
          GOMOD="/Users/virtumonde/project/project-backend/go.mod"
          CGO_CFLAGS="-g -O2"
          CGO_CPPFLAGS=""
          CGO_CXXFLAGS="-g -O2"
          CGO_FFLAGS="-g -O2"
          CGO_LDFLAGS="-g -O2"
          PKG_CONFIG="pkg-config"
          GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3s/8wr36j7s6_zglc_lrkklgmbh0000gn/T/go-build237076511=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Share the Go related settings you have added/edited

Nothing has been edited. Rolling back to 0.20.2 removes the error.

### Steps to reproduce the behavior:
1. Upgrade to 0.21.0 from 0.20.2
2. See error after saving a file (the extension doesn't work)

### Screenshots or recordings
![alt text](https://i.imgur.com/RVnceB0.png)

**Comment by hyangah** [comment] 2021-01-21 15:41
Sorry for the trouble. This is a duplicate of #1104

**Closed by hyangah** 2021-01-21 15:41 UTC
