### ISSUE TITLE
Autocompletion does not consider partially entered identifier 

### ISSUE THREAD

**Issue by wtask** [golang/vscode-go#390] opened 2020-07-22 14:15 UTC
```
Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Go extension 0.15.1
```
Start typing something able to complete with help of Go-extension. Press Ctrl+Space or wait when auto-completion drop-down will be opened. Press Enter or Tab to use suggested string. As result we got partially entered identifier concatenated with the whole identifier obtained with auto-completion. In other words, if auto-completion target is `MyIdentifier` and I typed `MyId` the final result is `MyIdMyIndentifier`. I really do not understand the vscode-go logic to use auto-completion.

**Comment by wtask** [comment] 2020-07-22 15:24
@hyangah Looks like https://github.com/golang/go/issues/38600
Yes, I use gopls

**Comment by hyangah** [comment] 2020-07-22 16:54
Thanks for checking and verifying it @wtask 
Since this is the upstream gopls bug, let's close this and follow up in the upstream bug.

Duplicate of golang/go#38600.

**Closed by hyangah** 2020-07-22 16:54 UTC
Labels: upstream-tools
