### ISSUE TITLE
can't get hints for xxx_test.go

### ISSUE THREAD

**Issue by leoyox** [golang/vscode-go#2365] opened 2022-07-21 08:44 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- 1.16
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- 0.9.1
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.69.2
* Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Share the Go related settings you have added/edited

```json
"gopls": {
    "ui.semanticTokens": true,
    "build.experimentalWorkspaceModule": false,
    "ui.completion.usePlaceholders": true
  }
```

### Describe the bug
can't get hints when editing xxxx_test.go, except that everything is fine.

**Comment by findleyr** [comment] 2022-07-21 23:17
Hi, when you say "hints", do you mean completion results? Or are you talking about inlay hints?

**Comment by leopox** [comment] 2022-07-22 01:28
> Hi, when you say "hints", do you mean completion results? Or are you talking about inlay hints?

sorry for my poor english. i mean code completion actually.

**Comment by findleyr** [comment] 2022-07-22 01:30
Thanks. Can you reduce to a minimal repro? I do not reproduce this problem with the x_test packages I am looking at.

Are you able to try reinstalling with a more recent version of Go? Go 1.18+, ideally?

**Comment by leopox** [comment] 2022-07-27 02:49
> Thanks. Can you reduce to a minimal repro? I do not reproduce this problem with the x_test packages I am looking at.
> 
> Are you able to try reinstalling with a more recent version of Go? Go 1.18+, ideally?

so strange, it works right now. maybe indexing?

**Comment by findleyr** [comment] 2022-07-27 13:01
> so strange, it works right now. maybe indexing?

Gopls does not currently persist any state to disk. If it worked upon a restart, you may have gotten gopls into a broken state due to buggy invalidation.

We're fixing a lot of invalidation bugs for the next gopls release. So hopefully this will cease to be an issue.

**Comment by hyangah** [comment] 2022-07-29 11:13
It sounds like the problem was self resolved. Closing.

When you have any issues related to the inlay hints or other intellisense , please capture & share the language server trace following the instruction in https://github.com/golang/vscode-go/wiki/troubleshooting#collect-gopls-information. We are happy to help and investigate together.

Thanks.

**Closed by hyangah** 2022-07-29 11:13 UTC
Labels: WaitingForInfo
