### ISSUE TITLE
can't turn off annoying message about go-outline

### ISSUE THREAD

**Issue by pjweinb** [golang/vscode-go#2141] opened 2022-03-27 22:28 UTC
I am running go 1.18 and the latest gopls and v0.32.0 of vscode-go.

I do not have a copy of go-outline, and don't want one, but the box that pops up only gives me the choice to Install or Install All.
1. Is there some way of telling vscode-go not to ask about go-outline?
2. The popup does not say what Install All means.

**Comment by hyangah** [comment] 2022-03-28 18:15
`go-outline` is still a required tool for codelens, test explorer, and other historic features.
So, for now it needs to be installed.

Duplicate of https://github.com/golang/vscode-go/issues/1020

**Closed by hyangah** 2022-03-28 18:15 UTC
