### ISSUE TITLE
"Run without debugging" causes "Process exiting with code: -4058 signal: false"

### ISSUE THREAD

**Issue by grehkil** [golang/vscode-go#1013] opened 2020-12-08 21:36 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.15.6 windows/amd64

- Run `gopls -v version` to get version of Gopls if you are using [the language server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).
	- golang.org/x/tools/gopls v0.5.5
	-    golang.org/x/tools/gopls@v0.5.5 h1:YBLs2WCwxx6mBF98Y6/mDIpKhP4Dt4Dz2q6LnMRBpDw=
	-    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
	-    github.com/google/go-cmp@v0.5.1 h1:JFrFEBb2xKufg6XkJsJr+WbKb4FQlURi5RUcBveYu9k=
	-    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
	-    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
	-    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
	-    golang.org/x/tools@v0.0.0-20201204180437-c46b611624b3 h1:uxH+MECLNmX/vsPe4txyeQ1LCmhdUxf7p4hjkHexg+c=
	-    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
	-    honnef.co/go/tools@v0.0.1-2020.1.6 h1:W18jzjh8mfPez+AwGLxmOImucz/IFjpNlrKVnaj2YVc=
	-    mvdan.cc/gofumpt@v0.0.0-20200927160801-5bfeb2e70dd6 h1:z+/YqapuV7VZPvBb3GYmuEJbA88M3PFUxaHilHYVCpQ=
	-    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.51.1
	- e5a624b788d92b8d34d1392e4c4d9789406efe8f
	- x64

- Check your installed extensions to get the version of the VS Code Go extension
	- 0.19.0

- Run `go env` to get the go development environment details
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\thoma\AppData\Local\go-build
set GOENV=C:\Users\thoma\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\thoma\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\thoma\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\thoma\AppData\Local\Temp\go-build778672914=/tmp/go-build -gno-record-gcc-switches

- OS informations:
	- Windows 10 x64.

### Share the Go related settings you have added/edited

Nothing added/edited. Fresh install of VS Code / Golang extension / etc.

### Describe the bug
Using a source code as simple as :
```
package main

func main() {
  println("hello world")
}
```

"`Start Debugging (F5)`" works perfectly and correctly launches the program in debug mode.

But using "`Run without Debugging (Ctrl+F5)`" results in an immediate exit, apparently without executing the program, with the following message in the Debug Console : "`Process exiting with code: -4058 signal: false`".

### Steps to reproduce the behavior:
1. Copy the simple Hello world program above
2. In the "`Run`" menu, select "`Run without debugging`"

### Screenshots or recordings
Not necessary.

**Comment by hyangah** [comment] 2020-12-09 00:59
Duplicate of #999

**Closed** 2020-12-09 01:00 UTC
