### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by lijiuxing1** [golang/vscode-go#3344] opened 2024-04-18 01:41 UTC
gopls version: v0.15.3/go1.22.2
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Thu, 18 Apr 2024 01:32:17 GMT
restart history:
Wed, 17 Apr 2024 10:05:07 GMT: activation (enabled: true)
Thu, 18 Apr 2024 01:29:11 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: slice bounds out of range [:-1]

goroutine 59965 [running]:
golang.org/x/tools/gopls/internal/protocol.(*Mapper).LineCol8Position(0xc001f1f0e0, 0x1, 0x0)
	  mapper.go:151  0x1ad
golang.org/x/tools/gopls/internal/cache.goPackagesErrorDiagnostics.func1({{0x0, 0x0}, {0xc005be6990, 0x8b}, 0x1}, 0x8b%3F, {0x1240060, 0xc0004af9e0}, {0x12483a0, 0xc034545900})
	  errors.go:58  0x145
golang.org/x/tools/gopls/internal/cache.goPackagesErrorDiagnostics({0x12483a0, 0xc034545900}, {{0x0, 0x0}, {0xc005be6990, 0x8b}, 0x1}, 0xc009e05a00, {0x1240060, 0xc0004af9e0})
	  errors.go:69  0xf5
golang.org/x/tools/gopls/internal/cache.computeLoadDiagnostics({0x12483a0, 0xc034545900}, 0xc0004af9e0, 0xc009e05a00)
	  load.go:541  0x185
golang.org/x/tools/gopls/internal/cache.(*packageHandleBuilder).buildPackageHandle(0xc022484840, {0x12483a0, 0xc034545900}, 0xc03435eeb0)
	  check.go:1129  0x2b7
golang.org/x/tools/gopls/internal/cache.(*Snapshot).getPackageHandles.func2.1()
	  check.go:932  0xce
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 59708
	  errgroup.go:75  0x96
</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 27340 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment] 2024-04-18 18:39
Thanks for the report @lijiuxing1 
Looks like this is a duplicate of https://github.com/golang/go/issues/66875
Let's discuss the problem there.

**Comment by hyangah** [comment] 2024-04-18 18:40
Duplicate of golang/go#66875

**Closed by hyangah** 2024-04-18 18:40 UTC
