### ISSUE TITLE
Highlight for chan

### ISSUE THREAD

**Issue by gianttt97** [golang/vscode-go#2146] opened 2022-03-29 03:28 UTC
```go
var a chan <- chan int 
```
the second `chan` is not highlighting in vscode.

```go
var c <-chan <-chan int
```
the first `chan` is not highlighting in vscode.

![Pasted image 20220329112725](https://user-images.githubusercontent.com/18088066/160527275-193de74b-ed70-4c8e-bcf4-cbdf00b98fa5.png)

**Comment by hyangah** [comment] 2022-03-29 14:06
@gianttt97  The default syntax highlighting is offered by the vscode (that vendors https://github.com/jeff-hykin/better-go-syntax), not this extension.

Instead, you can try the semantic-token based syntax highlighting this extension offers by using gopls. 
 
```
    "gopls": {
        "ui.semanticTokens": true
    }
```

I verify that the semantic-token based syntax highlighting doesn't have the problem.
![Screen Shot 2022-03-29 at 10 02 38 AM](https://user-images.githubusercontent.com/4999471/160629096-26649266-ecc1-4bfd-b888-ed9fd9b7beee.png)

@pjweinb It looks like arrows (`<-`) don't get semantic token info, so only textmate scopes are applied. (see the screenshot - I enabled the semantic token feature) Am I misinterpreting this?

![Screen Shot 2022-03-29 at 10 04 38 AM](https://user-images.githubusercontent.com/4999471/160629564-e3f81213-0352-42f0-8041-0667df447aea.png)

**Comment by pjweinb** [comment] 2022-03-29 22:09
some arrows do get semantic tokens (in send statements) but maybe some
don't. Please file an issue and assign it to me.

**Comment by li1234yun** [comment] 2022-03-30 00:27
Can you think to improve the golang theme? The issue is vscode's developer answer. 

[Improve golang default light+/dark+ theme](https://github.com/microsoft/vscode/issues/146128)

**Comment by hyangah** [comment] 2022-03-30 00:54
@li1234yun As the vscode dev explained, the coloring was done by the color theme. Color themes are not the scope of this extension. https://code.visualstudio.com/docs/getstarted/themes have more info about extensions that offer color themes. For the grammar, please see my previous comment. https://github.com/golang/vscode-go/issues/2146#issuecomment-1081916769 - 1) file an issue or contribute to  https://github.com/jeff-hykin/better-go-syntax or 2) use semantic tokens this extension & gopls offer.

@pjweinb Opened a gopls issue.

**Closed by hyangah** 2022-03-30 00:54 UTC
Labels: Question

**Comment by li1234yun** [comment] 2022-04-01 01:06
@hyangah Hello,

Does the Go team consider implementing the grammer itself？You maybe more professional. :-)

**Comment by li1234yun** [comment] 2022-04-08 02:14
Thank you! @hyangah 
```
    "gopls": {
        "ui.semanticTokens": true
    }
```
It helps me!
